"""Add ritual-style axe ribbons and the worms-pattern sprite set to the Valtan four-slash Full Restore docs.

The two installed documents keep every existing element (the baked AnimationTrail
elements and their edge histories are untouched). New elements are appended:

* one CascadeRibbon per source Trails notify, anchored to the weapon socket
  StartControl / b_wp_r_01 and generated by distance (SpawnPerUnit, spawn rate 0),
  exactly like the Kouku ritual staff-tip ribbon; the ribbon keeps its own source
  material (native 2410).
* the nine sprite emitters of FX_MN_RPBF_00_N.Par_N_RPBF_Cast_Exp_01 (worms pattern,
  originally on the left hand) re-anchored to the same weapon socket, spawning one
  particle per fixed step and revolving around the socket on a 40 cm circle.

Candidates are written under out/; --install replaces the live documents after a
hash check with backups and an atomic swap.
"""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import math
import os
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
AUTHORED = ROOT / 'Data/Effects/Authored'
EVIDENCE = ROOT / 'out/StaggerBallValtan20260917/valtan'

STAGE009 = 'effect.valtan.action.420609.stage009.full.restore'
STAGE008 = 'effect.valtan.action.420609.stage008.full.restore'
WORMS = 'effect.valtan.action.420612.stage004.full.restore'
RIBBON_TEMPLATE = 'valtan.action.d271afd619472e5658d89d72'   # stage009 notify-012 emitter_21 (ribbon)
SPAWN_PER_UNIT_DONOR = 'valtan.action.952e5cd5c79d117907b0d318'  # stage009 emitter_20 (SpawnPerUnit 50 cm)
WORMS_NOTIFY_START = 1.2048189640045166
FIXED_STEP = 1.0 / 60.0
ORBIT_RADIUS_UE_CM = 40.0
ORBIT_TURNS_PER_SECOND = 1.5
CONTINUOUS_SPAWN_RATE = 60.0

# source Trails notifies (seconds) and the baked edge spans they own
WINDOWS = {
    STAGE009: dict(clipSeconds=3.167, windows=[(1.6400439739227295, 0.5333328247070312)]),
    STAGE008: dict(clipSeconds=3.5, windows=[(1.666545033454895, 0.2666664123535156),
                                             (2.2210700511932373, 0.19999980926513672),
                                             (3.0076498985290527, 0.19999980926513672)]),
}


def read(path):
    return json.loads(path.read_text(encoding='utf-8-sig'))


def write(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    # Authored documents are LF without BOM; never let the platform newline leak in.
    path.write_bytes((json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + '\n').encode('utf-8'))


def sha(data):
    return hashlib.sha256(data).hexdigest()


def stable(prefix, *parts):
    return prefix + hashlib.sha256('|'.join(parts).encode('utf8')).hexdigest()[:24]


def module(element, class_name):
    found = [m for m in element['sourceRecipe']['modules'] if m['className'] == class_name]
    assert len(found) == 1, (element['id'], class_name, len(found))
    return found[0]


def set_literal(mod, path, value, kind='number'):
    for literal in mod['literals']:
        if literal['propertyPath'] == path:
            literal['value'] = value
            return
    mod['literals'].append(dict(propertyPath=path, kind=kind, value=value))


def set_constant(mod, path, value):
    for dist in mod['distributions']:
        if dist['propertyPath'] == path:
            dist['lookupTable'] = [value] * 4
            dist['lookupTableChunkSize'] = 1
            dist['lookupTableNumElements'] = 1
            dist['componentCount'] = 1
            dist['operation'] = 1
            dist['keys'] = []
            return
    raise KeyError((mod['stableId'], path))


def key(time, value):
    return dict(timeSeconds=time, value=list(value), arriveTangent=[0, 0, 0], leaveTangent=[0, 0, 0],
                interpolation='linear')


TRACK_KEY_STEP = 1.0 / 30.0   # 12 degrees per key at 1.5 turns/s; playback interpolates linearly


def orbit_track(element_id, start, life):
    keys = []
    steps = int(math.ceil(life / TRACK_KEY_STEP))
    for i in range(steps + 1):
        t = min(life, i * TRACK_KEY_STEP)
        angle = 2.0 * math.pi * ORBIT_TURNS_PER_SECOND * t
        keys.append(key(start + t, [ORBIT_RADIUS_UE_CM * math.cos(angle), ORBIT_RADIUS_UE_CM * math.sin(angle), 0.0]))
    # Omit alphaScaleKeys: an explicitly empty curve evaluates to zero, whereas
    # no alpha track preserves the source particle's own alpha over life.
    return dict(sourceOccurrenceId=element_id, sourceTimeOriginSeconds=0, previewOriginUE3Cm=[0, 0, 0],
                nodes=[dict(sourceObjectPath=element_id + '/axe-orbit', frame='WORLD', initialPositionUE3Cm=[0.0, 0.0, 0.0],
                            initialEulerDegrees=[0, 0, 0], scaleUE3=[1, 1, 1], positionKeys=keys, eulerKeys=[])])


def ribbon_element(asset, template, spawn_per_unit, ordinal, start, span, clip_seconds):
    element = copy.deepcopy(template)
    element['id'] = stable('valtan.ribbon.', asset, template['id'], 'ritual-spu50', str(ordinal))
    element['displayName'] = f'axe ribbon {ordinal + 1} | ritual spu50 (2410)'
    element['groupId'] = asset
    element['sourceNode'] = template['sourceNode'] + '|ritual'
    element['visible'] = True
    point_life = element['detail']['trail']['pointLifeTimeSeconds']
    life = min(span + point_life, clip_seconds - start)
    assert life > span, (asset, ordinal, life, span)
    point_life = life - span
    element['detail']['trail']['pointLifeTimeSeconds'] = point_life
    element['detail']['particle']['lifeTimeSeconds'] = [point_life, point_life]
    element['detail']['particle']['spawnRatePerSecond'] = 0.0
    element['detail']['particle']['localSpace'] = False
    element['detail']['timing']['startDelaySeconds'] = start
    element['detail']['timing']['lifeTimeSeconds'] = life
    recipe = element['sourceRecipe']
    recipe['emitterDelaySeconds'] = 0.0
    recipe['emitterDurationSeconds'] = span
    recipe['emitterLoopCount'] = 1
    recipe['bursts'] = []
    set_literal(module(element, 'particlemodulerequired'), 'emitterduration', span)
    set_literal(module(element, 'particlemodulerequired'), 'emitterloops', 1.0)
    set_constant(module(element, 'particlemodulelifetime'), 'lifetime', point_life)
    set_constant(module(element, 'particlemodulespawn'), 'rate', 0.0)
    set_literal(module(element, 'particlemoduletypedataribbon'), 'bspawninitialparticle', True, 'boolean')
    assert not [m for m in recipe['modules'] if m['className'] == 'particlemodulespawnperunit']
    donor = copy.deepcopy(spawn_per_unit)
    recipe['modules'].insert(len(recipe['modules']) - 2, donor)
    element['sourcePresentation']['sourceTimeSeconds'] = start
    element['runtimeCarrier'] = copy.deepcopy(template['runtimeCarrier'])
    return element


def worm_element(asset, source, attachment, ordinal, window_index, start, span, clip_seconds):
    element = copy.deepcopy(source)
    element.pop('runtimeCarrier', None)
    element['id'] = stable('valtan.worms.', asset, source['id'], 'startcontrol', str(window_index), str(ordinal))
    emitter = source['sourceNode'].rsplit('.', 1)[-1]
    element['displayName'] = f'axe worms w{window_index + 1}.{ordinal + 1} | {emitter}'[:60]
    element['groupId'] = asset
    element['sourceNode'] = (source['sourceNode'] + '|startcontrol')[:256]
    element['visible'] = True
    element['actionCueAttachment'] = copy.deepcopy(attachment)
    particle = element['detail']['particle']
    particle_life = max(particle['lifeTimeSeconds'])
    life = min(span + particle_life, clip_seconds - start)
    assert life > 0.0, (asset, ordinal, start)
    element['detail']['timing']['startDelaySeconds'] = start
    element['detail']['timing']['lifeTimeSeconds'] = life
    particle['spawnRatePerSecond'] = CONTINUOUS_SPAWN_RATE
    particle['localSpace'] = False
    recipe = element['sourceRecipe']
    recipe['emitterDelaySeconds'] = 0.0
    recipe['emitterDurationSeconds'] = span
    recipe['emitterLoopCount'] = 1
    set_literal(module(element, 'particlemodulerequired'), 'emitterduration', span)
    set_literal(module(element, 'particlemodulerequired'), 'emitterloops', 1.0)
    set_constant(module(element, 'particlemodulespawn'), 'rate', CONTINUOUS_SPAWN_RATE)
    presentation = element.get('sourcePresentation')
    if isinstance(presentation, dict) and 'sourceTimeSeconds' in presentation:
        presentation['sourceTimeSeconds'] = start
    element['sourceTransformTrack'] = orbit_track(element['id'], start, life)
    return element


def worm_sources(worms):
    rows = [e for e in worms['elements']
            if e['kind'] == 'particle' and e['sourceRecipe']['rendererShape'] == 'sprite'
            and abs(e['detail']['timing']['startDelaySeconds'] - WORMS_NOTIFY_START) < 1e-6]
    assert len(rows) == 9, len(rows)
    return rows


def build(asset, stage009, worms):
    document = read(AUTHORED / f'{asset}.effect.json')
    assert document['version'] == 15 and document['effectAssetId'] == asset
    template = next(e for e in stage009['elements'] if e['id'] == RIBBON_TEMPLATE)
    assert template['kind'] == 'trail' and template['runtimeCarrier']['kind'] == 'cascadeRibbonV1'
    donor = next(e for e in stage009['elements'] if e['id'] == SPAWN_PER_UNIT_DONOR)
    spawn_per_unit = module(donor, 'particlemodulespawnperunit')
    assert [l['value'] for l in spawn_per_unit['literals'] if l['propertyPath'] == 'unitscalar'] == [50.0]
    attachment = copy.deepcopy(template['actionCueAttachment'])
    assert attachment['runtimeAnchorSlotId'] == 'StartControl' and attachment['runtimeBoneName'] == 'b_wp_r_01'
    plan = WINDOWS[asset]
    added = []
    for index, (start, span) in enumerate(plan['windows']):
        added.append(ribbon_element(asset, template, spawn_per_unit, index, start, span, plan['clipSeconds']))
        for ordinal, source in enumerate(worm_sources(worms)):
            added.append(worm_element(asset, source, attachment, ordinal, index, start, span, plan['clipSeconds']))
    # Re-runs replace the elements this builder owns (stable ids) and never touch the rest.
    owned = {e['id']: e for e in added}
    document['elements'] = [owned.pop(e['id']) if e['id'] in owned else e for e in document['elements']]
    for element in added:
        assert len(element['displayName'].encode('utf8')) <= 64
        if element['id'] in owned:
            document['elements'].append(owned.pop(element['id']))
    assert not owned
    return document, added


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--install', action='store_true')
    args = parser.parse_args()
    stage009 = read(AUTHORED / f'{STAGE009}.effect.json')
    worms = read(AUTHORED / f'{WORMS}.effect.json')
    inputs = {name: sha((AUTHORED / f'{name}.effect.json').read_bytes()) for name in (STAGE009, STAGE008, WORMS)}
    candidates, summary = {}, {}
    for asset in (STAGE009, STAGE008):
        document, added = build(asset, stage009, worms)
        path = EVIDENCE / 'candidate' / f'{asset}.effect.json'
        write(path, document)
        candidates[asset] = path
        summary[asset] = dict(elementsBefore=len(document['elements']) - len(added), added=len(added),
                              addedIds=[e['id'] for e in added],
                              ribbons=[dict(id=e['id'], start=e['detail']['timing']['startDelaySeconds'],
                                            life=e['detail']['timing']['lifeTimeSeconds'],
                                            pointLife=e['detail']['trail']['pointLifeTimeSeconds'])
                                       for e in added if e['kind'] == 'trail'])
    write(EVIDENCE / 'fixtures.json', [dict(name=asset, passExpected=True, path=str(candidates[asset]), values={})
                                       for asset in candidates])
    receipt = dict(inputs=inputs, installed=False, summary=summary,
                   candidates={asset: str(path.relative_to(ROOT)) for asset, path in candidates.items()})
    if args.install:
        for asset, path in candidates.items():
            target = AUTHORED / f'{asset}.effect.json'
            before = target.read_bytes()
            assert sha(before) == inputs[asset], f'{asset} changed since the candidate was built'
            backup = EVIDENCE / 'before' / f'{asset}.effect.json'
            backup.parent.mkdir(parents=True, exist_ok=True)
            backup.write_bytes(before)
            temp = target.with_name(target.name + f'.claude-{os.getpid()}-{uuid.uuid4().hex[:8]}.tmp')
            with open(temp, 'xb') as handle:
                handle.write(path.read_bytes())
            assert sha(target.read_bytes()) == inputs[asset]
            os.replace(temp, target)
            summary[asset]['installedSha256'] = sha(target.read_bytes())
        receipt['installed'] = True
    write(EVIDENCE / 'receipt.json', receipt)
    print(json.dumps({asset: {k: v for k, v in row.items() if k != 'addedIds'} for asset, row in summary.items()},
                     ensure_ascii=False, indent=1))


if __name__ == '__main__':
    main()
