param(
    [string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
    [string]$ProjectPath = 'Client\Default\Client.vcxproj',
    [string]$FiltersPath = 'Client\Default\Client.vcxproj.filters',
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
$utf8Bom = [Text.UTF8Encoding]::new($true)
$newline = "`r`n"
$generatedComment = 'Generated by Tools/EffectPipeline/Sync-EffectDataProject.ps1.'

function Resolve-RepositoryPath([string]$RelativePath) {
    return [IO.Path]::GetFullPath((Join-Path $RepositoryRoot $RelativePath))
}

function Read-Utf8Text([string]$Path) {
    return [IO.File]::ReadAllText($Path, [Text.Encoding]::UTF8)
}

function Escape-Xml([string]$Value) {
    return [Security.SecurityElement]::Escape($Value)
}

function Sort-OrdinalUnique([string[]]$Values) {
    $set = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
    foreach ($value in $Values) {
        $null = $set.Add($value)
    }
    $result = [string[]]@($set)
    [Array]::Sort($result, [StringComparer]::Ordinal)
    return $result
}

function Get-StableFilterGuid([string]$FilterName) {
    $bytes = [Text.Encoding]::UTF8.GetBytes("LostArk.Client.Filter:`n$FilterName")
    $sha256 = [Security.Cryptography.SHA256]::Create()
    try {
        $hash = $sha256.ComputeHash($bytes)
    }
    finally {
        $sha256.Dispose()
    }
    $guidBytes = [byte[]]::new(16)
    [Array]::Copy($hash, $guidBytes, 16)
    $guidBytes[7] = ($guidBytes[7] -band 0x0f) -bor 0x50
    $guidBytes[8] = ($guidBytes[8] -band 0x3f) -bor 0x80
    return ([Guid]::new($guidBytes)).ToString('D')
}

function Get-EffectFilter([string]$GitPath) {
    $directory = [IO.Path]::GetDirectoryName($GitPath.Replace('/', '\'))
    $relativeDirectory = $directory.Substring('Data\Effects'.Length).TrimStart('\')
    if ([string]::IsNullOrWhiteSpace($relativeDirectory)) {
        return '96.DataFiles\Effects'
    }
    return '96.DataFiles\Effects\' + $relativeDirectory
}

function Remove-GeneratedGroup(
    [string]$Text,
    [string]$Label
) {
    $escapedComment = [regex]::Escape("  <!-- $generatedComment -->")
    $escapedLabel = [regex]::Escape($Label)
    $pattern = "(?ms)^$escapedComment\r?\n  <ItemGroup Label=`"$escapedLabel`">.*?^  </ItemGroup>\r?\n"
    return [regex]::Replace($Text, $pattern, '')
}

function Insert-BeforeUniqueAnchor(
    [string]$Text,
    [string]$Anchor,
    [string]$Insertion,
    [string]$Description
) {
    $count = ([regex]::Matches($Text, [regex]::Escape($Anchor))).Count
    if ($count -ne 1) {
        throw "Expected exactly one $Description anchor, found $count."
    }
    return $Text.Replace($Anchor, $Insertion + $Anchor)
}

$projectFullPath = Resolve-RepositoryPath $ProjectPath
$filtersFullPath = Resolve-RepositoryPath $FiltersPath
foreach ($path in @($projectFullPath, $filtersFullPath)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required project file is missing: $path"
    }
}

Push-Location $RepositoryRoot
try {
    $effectFiles = @(& git ls-files --cached --others --exclude-standard -- Data/Effects)
    if ($LASTEXITCODE -ne 0) {
        throw 'git ls-files failed while enumerating Data/Effects.'
    }
    $effectFiles = @($effectFiles |
        Where-Object { $_ -notmatch '(?i)\.tmp(?:\.|$)' } |
        Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
        ForEach-Object { $_.Replace('\', '/') })
    $effectFiles = @(Sort-OrdinalUnique $effectFiles)
}
finally {
    Pop-Location
}

if ($effectFiles.Count -eq 0) {
    throw 'No Git-managed Data/Effects files were found.'
}

$projectText = Read-Utf8Text $projectFullPath
$filtersText = Read-Utf8Text $filtersFullPath
[xml]$filtersXml = $filtersText
$filterManager = [Xml.XmlNamespaceManager]::new($filtersXml.NameTable)
$filterManager.AddNamespace('m', 'http://schemas.microsoft.com/developer/msbuild/2003')
$existingFilterGuids = @{}
foreach ($node in $filtersXml.SelectNodes('//m:Filter[@Include]', $filterManager)) {
    $filterName = [string]$node.Include
    if ($filterName.StartsWith('96.DataFiles\Effects', [StringComparison]::Ordinal)) {
        $identifier = [string]$node.UniqueIdentifier
        if (-not [string]::IsNullOrWhiteSpace($identifier)) {
            $existingFilterGuids[$filterName] = $identifier.Trim('{}')
        }
    }
}

$projectText = Remove-GeneratedGroup $projectText 'GeneratedEffectDataFiles'
$filtersText = Remove-GeneratedGroup $filtersText 'GeneratedEffectDataFilters'
$filtersText = Remove-GeneratedGroup $filtersText 'GeneratedEffectDataFilterItems'

# Remove only Effect data registrations. All other project entries and formatting remain untouched.
$projectEffectItem = '(?m)^[ \t]*<None Include="\.\.\\\.\.\\Data\\Effects\\[^"]+"\s*/>\r?\n'
$projectText = [regex]::Replace($projectText, $projectEffectItem, '')
$filterEffectItem = '(?ms)^[ \t]*<None Include="\.\.\\\.\.\\Data\\Effects\\[^"]+"\s*>\s*<Filter>[^<]+</Filter>\s*</None>\r?\n'
$filtersText = [regex]::Replace($filtersText, $filterEffectItem, '')
$effectFilterDefinition = '(?ms)^[ \t]*<Filter Include="96\.DataFiles\\Effects(?:\\[^"]*)?"\s*>\s*<UniqueIdentifier>\{[^<]+\}</UniqueIdentifier>\s*</Filter>\r?\n'
$filtersText = [regex]::Replace($filtersText, $effectFilterDefinition, '')

$filterNames = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
$null = $filterNames.Add('96.DataFiles\Effects')
foreach ($effectFile in $effectFiles) {
    $filterName = Get-EffectFilter $effectFile
    while ($filterName.StartsWith('96.DataFiles\Effects', [StringComparison]::Ordinal)) {
        $null = $filterNames.Add($filterName)
        $separator = $filterName.LastIndexOf('\')
        if ($separator -lt '96.DataFiles\Effects'.Length) {
            break
        }
        $filterName = $filterName.Substring(0, $separator)
    }
}
$sortedFilterNames = @(Sort-OrdinalUnique ([string[]]@($filterNames)))

$projectLines = [Collections.Generic.List[string]]::new()
$projectLines.Add("  <!-- $generatedComment -->")
$projectLines.Add('  <ItemGroup Label="GeneratedEffectDataFiles">')
foreach ($effectFile in $effectFiles) {
    $include = '..\..\' + $effectFile.Replace('/', '\')
    $projectLines.Add("    <None Include=`"$(Escape-Xml $include)`" />")
}
$projectLines.Add('  </ItemGroup>')
$projectBlock = ($projectLines -join $newline) + $newline

$filterDefinitionLines = [Collections.Generic.List[string]]::new()
$filterDefinitionLines.Add("  <!-- $generatedComment -->")
$filterDefinitionLines.Add('  <ItemGroup Label="GeneratedEffectDataFilters">')
foreach ($filterName in $sortedFilterNames) {
    $guid = if ($existingFilterGuids.ContainsKey($filterName)) {
        $existingFilterGuids[$filterName]
    }
    else {
        Get-StableFilterGuid $filterName
    }
    $filterDefinitionLines.Add("    <Filter Include=`"$(Escape-Xml $filterName)`">")
    $filterDefinitionLines.Add("      <UniqueIdentifier>{$guid}</UniqueIdentifier>")
    $filterDefinitionLines.Add('    </Filter>')
}
$filterDefinitionLines.Add('  </ItemGroup>')
$filterDefinitionBlock = ($filterDefinitionLines -join $newline) + $newline

$filterItemLines = [Collections.Generic.List[string]]::new()
$filterItemLines.Add("  <!-- $generatedComment -->")
$filterItemLines.Add('  <ItemGroup Label="GeneratedEffectDataFilterItems">')
foreach ($effectFile in $effectFiles) {
    $include = '..\..\' + $effectFile.Replace('/', '\')
    $filterName = Get-EffectFilter $effectFile
    $filterItemLines.Add("    <None Include=`"$(Escape-Xml $include)`">")
    $filterItemLines.Add("      <Filter>$(Escape-Xml $filterName)</Filter>")
    $filterItemLines.Add('    </None>')
}
$filterItemLines.Add('  </ItemGroup>')
$filterItemBlock = ($filterItemLines -join $newline) + $newline

$projectAnchor = '  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />' + $newline
$expectedProjectText = Insert-BeforeUniqueAnchor $projectText $projectAnchor $projectBlock 'Client project import'
$filtersAnchor = '</Project>' + $newline
$expectedFiltersText = Insert-BeforeUniqueAnchor $filtersText $filtersAnchor ($filterDefinitionBlock + $filterItemBlock) 'Client filters closing tag'

# Parse the fully materialized documents before comparing or committing them.
[xml]$null = $expectedProjectText
[xml]$null = $expectedFiltersText

if ($Check) {
    $differences = [Collections.Generic.List[string]]::new()
    if ($expectedProjectText -cne (Read-Utf8Text $projectFullPath)) {
        $differences.Add($ProjectPath)
    }
    if ($expectedFiltersText -cne (Read-Utf8Text $filtersFullPath)) {
        $differences.Add($FiltersPath)
    }
    if ($differences.Count -ne 0) {
        throw "Effect data project registration is stale: $($differences -join ', '). Run this script without -Check."
    }
    Write-Host "Effect data project registration PASS: files=$($effectFiles.Count) filters=$($sortedFilterNames.Count)"
    exit 0
}

[IO.File]::WriteAllText($projectFullPath, $expectedProjectText, $utf8Bom)
[IO.File]::WriteAllText($filtersFullPath, $expectedFiltersText, $utf8Bom)
Write-Host "Effect data project registration updated: files=$($effectFiles.Count) filters=$($sortedFilterNames.Count)"
