#!/usr/bin/env python3
"""Prove a translated family HLSL reproduces its cooked DXBC numerically.

A translation that compiles is not a translation that is correct.  This
harness closes that gap the only way it can be closed without the original
renderer: it runs the cooked pixel shader and the compiled translation on the
same WARP device, with the same constant buffers, the same textures, the same
samplers and the same carrier vertex shader, and compares every render target
the program writes.

The fixture values are synthetic and deterministic.  They are chosen to
exercise the arithmetic program, not to reproduce a material instance.  The
current texture fixtures are uniform 1x1 resources, so a pass does not prove
UV, LOD, address-mode, or TextureCube sampling semantics.  It means only that
the exercised translation computes what the cooked program computes; sampler
state, vertex factory, render state and visual fidelity remain separate gates.
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
LEVEL_TOOLS = REPOSITORY_ROOT / "Tools" / "LevelPlacementExtractor"
for extra in (str(Path(__file__).resolve().parent), str(LEVEL_TOOLS)):
    if extra not in sys.path:
        sys.path.insert(0, extra)

from extract_artist_31470_main_ref_shader_cache import (  # noqa: E402
    DEFAULT_D3DCOMPILER,
    D3DDisassembler,
)
from replay_ue3_material_pixel_shaders import (  # noqa: E402
    CarrierCompiler,
    GenericWarpReplay,
    _component_width,
    _hlsl_scalar,
    build_carrier_source,
    dxbc_chunks,
    parse_signature,
)
from translate_ue3_dxbc_to_hlsl import (  # noqa: E402
    COVERAGE_INPUT,
    COVERAGE_OUTPUT,
    TranslationError,
    parse_declarations,
    translate_body,
    _SAMPLE_SEQUENCE,
)

COMPONENTS = "xyzw"

# The translator reads immediates from the disassembly text, which prints a
# float with six decimals.  An immediate such as 1/255 therefore arrives as
# 0.003922 rather than 0.00392156862, and the residual shows up in the output
# at around 1e-5.  That floor belongs to the printed form, not to the
# translation, so it is reported as its own grade instead of being folded into
# either "exact" or "wrong".
EXACT_TOLERANCE = 0.0
PRINT_PRECISION_TOLERANCE = 1e-4
TOLERANCE = PRINT_PRECISION_TOLERANCE

# The translation is instruction-for-instruction, so the comparison is only
# meaningful if the compiler is not allowed to reassociate it back into a
# different program.  Skipping optimization and asking for IEEE strictness is
# what keeps `dp3`/`rsq`/`mad` chains in the order the cooked program used.
D3DCOMPILE_SKIP_OPTIMIZATION = 1 << 2
D3DCOMPILE_IEEE_STRICTNESS = 1 << 13
TRANSLATION_COMPILE_FLAGS = (
    D3DCOMPILE_SKIP_OPTIMIZATION | D3DCOMPILE_IEEE_STRICTNESS)


class VerificationError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise VerificationError(message)


def compile_pixel_shader(compiler: CarrierCompiler, source: bytes,
                         label: str) -> bytes:
    """`CarrierCompiler` is hard-wired to vs_5_0; borrow only its DLL entry."""
    import ctypes

    code = ctypes.c_void_p()
    errors = ctypes.c_void_p()
    backing = ctypes.create_string_buffer(source)
    result = compiler.function(
        backing, len(source), label.encode("ascii"), None, None,
        b"main", b"ps_5_0", TRANSLATION_COMPILE_FLAGS, 0,
        ctypes.byref(code), ctypes.byref(errors))
    from replay_ue3_material_pixel_shaders import blob_bytes, release

    text = (blob_bytes(errors).decode("utf-8", "replace")
            if errors.value else "")
    if not (result >= 0 and code.value):
        release(errors)
        release(code)
        raise VerificationError(
            f"translated HLSL failed to compile: "
            f"0x{result & 0xFFFFFFFF:08X} {text}")
    bytecode = blob_bytes(code)
    release(errors)
    release(code)
    return bytecode


def build_standalone_source(
    disassembly: dict[str, Any],
    input_signature: list[dict[str, Any]],
    output_signature: list[dict[str, Any]],
) -> str:
    """Re-emit the translation with the cooked program's own linkage."""
    declarations = parse_declarations(disassembly["declarations"])
    lines: list[str] = ["// generated by verify_ue3_dxbc_hlsl_translation.py"]

    for name, size in sorted(declarations["constantBuffers"].items()):
        register = int(name[2:])
        lines.append(f"cbuffer Constants{register} : register(b{register})")
        lines.append("{")
        lines.append(f"    float4 {name}[{size}];")
        lines.append("};")
    for sampler in declarations["samplers"]:
        lines.append(
            f"SamplerState {sampler} : register(s{sampler[1:]});")
    for texture in declarations["textures"]:
        lines.append(f"{declarations['textureTypes'][texture]} {texture} "
                     f": register(t{texture[1:]});")
    lines.append("")

    lines.append("struct STAGE_INPUT")
    lines.append("{")
    carrier_rows = []
    front_face_rows = []
    for index, row in enumerate(input_signature):
        # The rasterizer, not the carrier vertex shader, supplies
        # SV_IsFrontFace, and HLSL types it as bool rather than as the mask
        # the cooked program reads from its input register.
        if row["semanticName"].casefold() == "sv_isfrontface":
            lines.append(f"    bool f{index} : SV_IsFrontFace;")
            front_face_rows.append((index, row))
            continue
        if row["systemValueType"] == 9:
            continue
        width = _component_width(row["mask"])
        scalar = _hlsl_scalar(row["componentType"])
        type_name = scalar if width == 1 else f"{scalar}{width}"
        semantic = f"{row['semanticName']}{row['semanticIndex']}"
        lines.append(f"    {type_name} f{index} : {semantic};")
        carrier_rows.append((index, row, width))
    if declarations["coverageInput"]:
        lines.append("    uint coverage : SV_Coverage;")
    lines.append("};")
    lines.append("")

    # SV_Coverage and SV_Depth appear in the output signature with no render
    # target index; only the indexed targets belong in the struct.
    targets = sorted({
        row["register"] for row in output_signature
        if row["register"] < 8
    })
    lines.append("struct STAGE_OUTPUT")
    lines.append("{")
    for register in targets:
        lines.append(f"    float4 o{register} : SV_Target{register};")
    if declarations["coverageMask"]:
        lines.append(f"    uint {COVERAGE_OUTPUT} : SV_Coverage;")
    lines.append("};")
    lines.append("")

    lines.append("STAGE_OUTPUT main(STAGE_INPUT stage)")
    lines.append("{")
    registers = sorted(
        {row["register"] for _, row, _ in carrier_rows}
        | {row["register"] for _, row in front_face_rows})
    for register in registers:
        lines.append(f"    float4 v{register} = (float4)0;")
    for index, row in front_face_rows:
        lines.append(
            f"    v{row['register']}.x = stage.f{index} ? "
            f"asfloat(0xffffffffu) : 0.0f;")
    for index, row, width in carrier_rows:
        target = f"v{row['register']}"
        if width == 1:
            lines.append(f"    {target}.x = stage.f{index};")
        else:
            lines.append(
                f"    {target}.{COMPONENTS[:width]} = stage.f{index};")
    for index in range(declarations["temporaryCount"]):
        lines.append(f"    float4 r{index} = (float4)0;")
    for register in targets:
        lines.append(f"    float4 o{register} = (float4)0;")
    if declarations["coverageMask"]:
        lines.append(f"    uint {COVERAGE_OUTPUT} = 0xffffffffu;")
    if declarations["coverageInput"]:
        lines.append(f"    uint4 {COVERAGE_INPUT} = stage.coverage;")
    lines.append("")

    _SAMPLE_SEQUENCE["value"] = 0
    lines.extend(translate_body(disassembly["instructions"], "    "))
    lines.append("")
    lines.append("    STAGE_OUTPUT result;")
    for register in targets:
        lines.append(f"    result.o{register} = o{register};")
    if declarations["coverageMask"]:
        lines.append(f"    result.{COVERAGE_OUTPUT} = {COVERAGE_OUTPUT};")
    lines.append("    return result;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def pattern(seed: int, row: int, lane: int) -> float:
    table = (0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0, -0.25, -0.5, 0.125)
    return table[(seed * 13 + row * 7 + lane * 3) % len(table)]


def make_fixture(declarations: dict[str, Any], carrier_row_count: int,
                 seed: int) -> dict[str, Any]:
    cbuffers: dict[str, list[list[float]]] = {}
    for name, count in declarations["constantBuffers"].items():
        register = str(int(name[2:]))
        cbuffers[register] = [
            [pattern(seed, index + int(register) * 31, lane)
             for lane in range(4)]
            for index in range(count)
        ]
    carrier = [
        [pattern(seed + 5, index, lane) for lane in range(4)]
        for index in range(carrier_row_count)
    ]
    textures = {
        str(int(name[1:])): [
            0.5 + 0.1 * ((seed + int(name[1:]) + lane) % 4)
            for lane in range(4)
        ]
        for name in declarations["textures"]
    }
    return {
        "seed": seed,
        "constantBuffers": cbuffers,
        "carrierRows": carrier,
        "textures": textures,
    }


def replay_declarations(declarations: dict[str, Any]) -> dict[str, Any]:
    return {
        "constantBufferFloat4Counts": {
            str(int(name[2:])): count
            for name, count in declarations["constantBuffers"].items()
        },
        "textureRegisters": sorted(
            int(name[1:]) for name in declarations["textures"]),
        "samplerRegisters": sorted(
            int(name[1:]) for name in declarations["samplers"]),
    }


def compare(original: list[list[float]], translated: list[list[float]]
            ) -> dict[str, Any]:
    require(len(original) == len(translated),
            "render-target count differs between original and translation")
    worst = 0.0
    mismatches = []
    for index, (left, right) in enumerate(zip(original, translated)):
        for lane, (a, b) in enumerate(zip(left, right)):
            if math.isnan(a) and math.isnan(b):
                continue
            if not math.isfinite(a) or not math.isfinite(b):
                # NaN comparisons and inf/inf division both produce NaN.  If
                # they fall through to the relative-delta path below, Python's
                # comparisons treat that delta as neither greater nor smaller
                # and a one-sided non-finite result is silently accepted.
                same_infinity = (
                    math.isinf(a) and math.isinf(b) and a == b)
                if same_infinity:
                    continue
                worst = max(worst, 1.0)
                mismatches.append({
                    "renderTarget": index,
                    "component": COMPONENTS[lane],
                    "original": printable_float(a),
                    "translated": printable_float(b),
                    "reason": "NON_FINITE_MISMATCH",
                })
                continue
            delta = abs(a - b)
            scale = max(1.0, abs(a), abs(b))
            relative = delta / scale
            worst = max(worst, relative)
            if relative > TOLERANCE:
                mismatches.append({
                    "renderTarget": index,
                    "component": COMPONENTS[lane],
                    "original": a,
                    "translated": b,
                })
    return {"worstRelativeDelta": worst, "mismatches": mismatches}


def printable_float(value: float) -> float | str:
    """Keep mismatch reports strict JSON even when the GPU returns NaN/Inf."""

    if math.isnan(value):
        return "NaN"
    if value == float("inf"):
        return "+Infinity"
    if value == float("-inf"):
        return "-Infinity"
    return value


def verify(path: Path, d3dcompiler: Path, seeds: list[int],
           emit_source: Path | None) -> dict[str, Any]:
    bytecode = path.read_bytes()
    disassembler = D3DDisassembler(d3dcompiler)
    disassembly = disassembler.disassemble(bytecode)
    chunks = dxbc_chunks(bytecode)
    require("ISGN" in chunks, "cooked shader has no input signature")
    require("OSGN" in chunks, "cooked shader has no output signature")
    input_signature = parse_signature(chunks["ISGN"])
    output_signature = parse_signature(chunks["OSGN"])

    source = build_standalone_source(
        disassembly, input_signature, output_signature)
    if emit_source is not None:
        emit_source.parent.mkdir(parents=True, exist_ok=True)
        emit_source.write_text(source, encoding="utf-8")

    compiler = CarrierCompiler(d3dcompiler)
    translated_dxbc = compile_pixel_shader(
        compiler, source.encode("utf-8"), path.stem)
    carrier_source, carrier_rows = build_carrier_source(input_signature)
    carrier_dxbc, _ = compiler.compile(carrier_source, "carrier")

    declarations = parse_declarations(disassembly["declarations"])
    replay_decl = replay_declarations(declarations)
    render_targets = max(
        (row["register"] for row in output_signature
         if row["register"] < 8), default=0) + 1

    replay = GenericWarpReplay()
    results = []
    for seed in seeds:
        fixture = make_fixture(declarations, carrier_rows, seed)
        original = replay.run(
            bytecode, carrier_dxbc, fixture, replay_decl, render_targets)
        produced = replay.run(
            translated_dxbc, carrier_dxbc, fixture, replay_decl,
            render_targets)
        comparison = compare(original, produced)
        results.append({
            "seed": seed,
            "worstRelativeDelta": comparison["worstRelativeDelta"],
            "mismatchCount": len(comparison["mismatches"]),
            "mismatches": comparison["mismatches"][:8],
        })

    worst = max(row["worstRelativeDelta"] for row in results)
    passed = all(row["mismatchCount"] == 0 for row in results)
    if not passed:
        grade = "NUMERIC_MISMATCH"
    elif worst <= EXACT_TOLERANCE:
        grade = "NUMERIC_EXACT"
    else:
        grade = "NUMERIC_WITHIN_PRINT_PRECISION"
    return {
        "dxbc": path.name,
        "profile": disassembly["profile"],
        "instructionCount": disassembly["instructionCount"],
        "renderTargetCount": render_targets,
        "worstRelativeDelta": worst,
        "seeds": results,
        "result": grade,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dxbc", type=Path, nargs="+")
    parser.add_argument("--d3dcompiler", type=Path,
                        default=DEFAULT_D3DCOMPILER)
    parser.add_argument("--seeds", type=int, nargs="+",
                        default=[1, 2, 3, 4, 5])
    parser.add_argument("--emit-directory", type=Path, default=None)
    parser.add_argument("--report", type=Path, default=None)
    arguments = parser.parse_args(argv)

    rows = []
    failures = 0
    for path in arguments.dxbc:
        emit = (arguments.emit_directory / f"{path.stem}.hlsl"
                if arguments.emit_directory else None)
        try:
            row = verify(path, arguments.d3dcompiler, arguments.seeds, emit)
        except (VerificationError, TranslationError) as error:
            failures += 1
            row = {"dxbc": path.name, "result": "FAILED", "error": str(error)}
            print(f"FAIL {path.name}: {error}", file=sys.stderr)
        else:
            if row["result"] == "NUMERIC_MISMATCH":
                failures += 1
            worst = row["worstRelativeDelta"]
            print(f"{row['result']} {path.name} "
                  f"instructions={row['instructionCount']} "
                  f"rt={row['renderTargetCount']} worstDelta={worst:.3e}")
        rows.append(row)

    if arguments.report is not None:
        arguments.report.parent.mkdir(parents=True, exist_ok=True)
        arguments.report.write_text(
            json.dumps(rows, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8")
    print(f"RESULT: matched={len(rows) - failures} failed={failures}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
