"""Generates the KoukuSaton arena hidden-placement header.

The pop-up book cutscene reveals the tent arena, so the arena must not already
be standing when the level opens. The arena sits around the roulette floor at
(-0.3, 737.5); the circus plaza it must not touch is 800m away at z -70..-110,
so a radius test separates them without ambiguity.

Run after editing map placements:
    python Tools/KakulSaydonPipeline/build_arena_hidden_ids.py
"""

import io
import os
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

REPOSITORY_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
AREA_ID = "LV_LUT_MIDNIGHTC_ED"
# Roulette floor placement 40 owns the arena centre.
ARENA_CENTER_XZ = (-0.3, 737.5)
ARENA_RADIUS_M = 80.0
PLACEMENT_FIELD_COUNT = 16
VISIBLE_FIELD_INDEX = 15
HEADER_RELATIVE_PATH = "Client/Public/KakulArenaHiddenPlacements.h"


def read_arena_placement_ids(placement_path):
    ids = []
    with open(placement_path, encoding="utf-8") as handle:
        lines = handle.read().splitlines()
    if not lines or not lines[0].startswith("LOSTARK_MAP_PLACEMENTS"):
        raise SystemExit(f"Not a map placement document: {placement_path}")
    for line in lines[1:]:
        fields = line.split()
        if len(fields) != PLACEMENT_FIELD_COUNT:
            continue
        # Field 15 is MAP_PLACEMENT_RECORD::visible. Culling boxes, the
        # roulette wheel and other conditional props are authored invisible;
        # hiding and restoring them would make the cutscene reveal geometry the
        # Area never shows.
        if fields[VISIBLE_FIELD_INDEX] != "1":
            continue
        x = float(fields[5])
        z = float(fields[7])
        dx = x - ARENA_CENTER_XZ[0]
        dz = z - ARENA_CENTER_XZ[1]
        if dx * dx + dz * dz <= ARENA_RADIUS_M * ARENA_RADIUS_M:
            ids.append(int(fields[0]))
    ids.sort()
    return ids


def write_header(header_path, ids):
    with open(header_path, "w", encoding="utf-8", newline="\r\n") as handle:
        handle.write("#pragma once\n")
        handle.write("\n")
        handle.write("/* Generated by Tools/KakulSaydonPipeline/"
                     "build_arena_hidden_ids.py. Do not edit by hand.\n")
        handle.write(f"   Map placements within {ARENA_RADIUS_M:.0f}m of the "
                     f"roulette floor at ({ARENA_CENTER_XZ[0]}, "
                     f"{ARENA_CENTER_XZ[1]}).\n")
        handle.write("   The cutscene raises these, so the level suppresses "
                     "them before the first frame. */\n")
        handle.write("\n")
        handle.write("#include <array>\n")
        handle.write("#include <cstdint>\n")
        handle.write("\n")
        handle.write("namespace Client\n")
        handle.write("{\n")
        handle.write(f"\tinline constexpr std::array<uint64_t, {len(ids)}> "
                     "KAKUL_ARENA_HIDDEN_PLACEMENT_IDS = {{\n")
        for index in range(0, len(ids), 4):
            row = " ".join(f"{value}ull," for value in ids[index:index + 4])
            handle.write(f"\t\t{row}\n")
        handle.write("\t}};\n")
        handle.write("}\n")


def main():
    placement_path = os.path.join(
        REPOSITORY_ROOT, "Data", "Maps", "Authoring", AREA_ID,
        f"{AREA_ID}.mapplacements")
    if not os.path.isfile(placement_path):
        raise SystemExit(f"Map placement document is missing: {placement_path}")
    ids = read_arena_placement_ids(placement_path)
    if not ids:
        raise SystemExit("No arena placement matched the radius test.")
    header_path = os.path.join(REPOSITORY_ROOT, HEADER_RELATIVE_PATH)
    write_header(header_path, ids)
    print(f"Arena placements: {len(ids)}")
    print(f"Header: {header_path}")


if __name__ == "__main__":
    main()
