// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

float4 cb0[3];
SamplerState s0;
SamplerState s1;
Texture2D t0;
Texture2D t1;

struct Shade_Ue3_fx_a_pa_firework_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_a_pa_firework_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_a_pa_firework_01_ad_OUTPUT Shade_Ue3_fx_a_pa_firework_01_ad(Shade_Ue3_fx_a_pa_firework_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;

    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, v2.xyxx, t1.xyzw, s1, l(0.000000)
    float4 fetch1 = t1.SampleBias(s1, v2.xy, 0.0f);
    r0.x = fetch1.x;
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // lt r0.x, |r0.x|, l(0.000001)
    r0.x = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, v4.x
    r0.y = r0.y * v4.x;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // add r0.x, r0.x, r0.x
    r0.x = r0.x + r0.x;
    // min r0.x, r0.x, l(1.000000)
    r0.x = min(r0.x, 1.0f);
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyzw, v2.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch2 = t0.SampleBias(s0, v2.xy, 0.0f);
    r1.x = fetch2.x;
    r1.y = fetch2.y;
    r1.z = fetch2.z;
    r1.w = fetch2.w;
    // mul r0.y, r1.w, l(3.000000)
    r0.y = r1.w * 3.0f;
    // mad r1.xyz, cb0[2].xyzx, r1.xyzx, r1.xxxx
    float stage3_x = cb0[2].x * r1.x + r1.x;
    float stage3_y = cb0[2].y * r1.y + r1.x;
    float stage3_z = cb0[2].z * r1.z + r1.x;
    r1.x = stage3_x;
    r1.y = stage3_y;
    r1.z = stage3_z;
    // mad r1.xyz, v3.xyzx, r1.xyzx, cb0[1].xyzx
    float stage4_x = v3.x * r1.x + cb0[1].x;
    float stage4_y = v3.y * r1.y + cb0[1].y;
    float stage4_z = v3.z * r1.z + cb0[1].z;
    r1.x = stage4_x;
    r1.y = stage4_y;
    r1.z = stage4_z;
    // mul r1.xyz, r1.xyzx, v5.wwww
    float stage5_x = r1.x * v5.w;
    float stage5_y = r1.y * v5.w;
    float stage5_z = r1.z * v5.w;
    r1.x = stage5_x;
    r1.y = stage5_y;
    r1.z = stage5_z;
    // mul r0.x, r0.x, r0.y
    r0.x = r0.x * r0.y;
    // mul r0.x, r0.x, cb0[0].x
    r0.x = r0.x * cb0[0].x;
    // mul o0.xyz, r0.xxxx, r1.xyzx
    float stage6_x = r0.x * r1.x;
    float stage6_y = r0.x * r1.y;
    float stage6_z = r0.x * r1.z;
    o0.x = stage6_x;
    o0.y = stage6_y;
    o0.z = stage6_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_a_pa_firework_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
