// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

float4 cb0[23];
float4 cb2[4];
SamplerState s0;
SamplerState s1;
SamplerState s2;
SamplerState s3;
SamplerState s4;
Texture2D t0;
Texture2D t1;
Texture2D t2;
Texture2D t3;
Texture2D t4;

struct Shade_Ue3_fx_d_pa_dissolve_01_ma_INPUT
{
    float4 v0;
    float4 v1;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_d_pa_dissolve_01_ma_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
    uint oMask;
};

Shade_Ue3_fx_d_pa_dissolve_01_ma_OUTPUT Shade_Ue3_fx_d_pa_dissolve_01_ma(Shade_Ue3_fx_d_pa_dissolve_01_ma_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;
    uint oMask = 0xffffffffu;

    // add r0.xy, v4.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v4.x + -0.5f;
    float stage1_y = v4.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // dp2 r1.y, cb0[15].xyxx, r0.xyxx
    r1.y = dot(cb0[15].xy, r0.xy);
    // dp2 r1.x, cb0[14].xyxx, r0.xyxx
    r1.x = dot(cb0[14].xy, r0.xy);
    // add r2.xyzw, r1.xyxy, l(0.500000, 0.000000, -0.500000, 0.000000)
    float stage2_x = r1.x + 0.5f;
    float stage2_y = r1.y + 0.0f;
    float stage2_z = r1.x + -0.5f;
    float stage2_w = r1.y + 0.0f;
    r2.x = stage2_x;
    r2.y = stage2_y;
    r2.z = stage2_z;
    r2.w = stage2_w;
    // mul_sat r0.z, r1.x, l(1000.000000)
    r0.z = saturate(r1.x * 1000.0f);
    // dp2 r0.w, r2.zwzz, r2.zwzz
    r0.w = dot(r2.zw, r2.zw);
    // dp2 r1.x, r2.xyxx, r2.xyxx
    r1.x = dot(r2.xy, r2.xy);
    // sqrt r1.x, r1.x
    r1.x = sqrt(r1.x);
    // mad_sat r1.x, -r1.x, cb0[21].w, l(1.000000)
    r1.x = saturate(-r1.x * cb0[21].w + 1.0f);
    // sqrt r0.w, r0.w
    r0.w = sqrt(r0.w);
    // mad_sat r0.w, -r0.w, cb0[21].w, l(1.000000)
    r0.w = saturate(-r0.w * cb0[21].w + 1.0f);
    // add r0.w, -r1.x, r0.w
    r0.w = -r1.x + r0.w;
    // mad_sat r0.z, r0.z, r0.w, r1.x
    r0.z = saturate(r0.z * r0.w + r1.x);
    // dp2 r1.x, cb0[3].xyxx, r0.xyxx
    r1.x = dot(cb0[3].xy, r0.xy);
    // dp2 r1.y, cb0[4].xyxx, r0.xyxx
    r1.y = dot(cb0[4].xy, r0.xy);
    // add r0.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage3_x = r1.x + 0.5f;
    float stage3_y = r1.y + 0.5f;
    r0.x = stage3_x;
    r0.y = stage3_y;
    // mul r0.w, r0.x, cb0[19].w
    r0.w = r0.x * cb0[19].w;
    // mad r1.x, cb0[19].z, cb0[19].y, r0.w
    r1.x = cb0[19].z * cb0[19].y + r0.w;
    // mul r0.w, r0.y, cb0[20].x
    r0.w = r0.y * cb0[20].x;
    // add r0.xy, r0.xyxx, cb0[5].xyxx
    float stage4_x = r0.x + cb0[5].x;
    float stage4_y = r0.y + cb0[5].y;
    r0.x = stage4_x;
    r0.y = stage4_y;
    // mul r0.xy, r0.xyxx, cb0[6].xyxx
    float stage5_x = r0.x * cb0[6].x;
    float stage5_y = r0.y * cb0[6].y;
    r0.x = stage5_x;
    r0.y = stage5_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t1.xyzw, s0, l(0.000000)
    float4 fetch6 = t1.SampleBias(s0, r0.xy, 0.0f);
    r0.x = fetch6.x;
    // mad r1.y, cb0[19].z, cb0[20].y, r0.w
    r1.y = cb0[19].z * cb0[20].y + r0.w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r1.xyxx, t0.yxzw, s4, l(0.000000)
    float4 fetch7 = t0.SampleBias(s4, r1.xy, 0.0f);
    r0.y = fetch7.x;
    // mad r0.y, r0.y, cb0[20].z, r0.z
    r0.y = r0.y * cb0[20].z + r0.z;
    // add r0.y, r0.y, l(0.100000)
    r0.y = r0.y + 0.1f;
    // max r0.z, cb0[2].x, l(-0.250000)
    r0.z = max(cb0[2].x, -0.25f);
    // min r0.z, r0.z, l(1.000000)
    r0.z = min(r0.z, 1.0f);
    // add r0.z, -r0.z, l(1.000000)
    r0.z = -r0.z + 1.0f;
    // add r0.y, -r0.z, r0.y
    r0.y = -r0.z + r0.y;
    // add_sat r0.y, r0.y, cb0[22].x
    r0.y = saturate(r0.y + cb0[22].x);
    // mul_sat r0.y, r0.y, cb0[0].w
    r0.y = saturate(r0.y * cb0[0].w);
    // add r0.y, r0.y, l(-0.333300)
    r0.y = r0.y + -0.3333f;
    // lt r0.y, r0.y, l(0.000000)
    r0.y = asfloat((r0.y < 0.0f) ? 0xffffffffu : 0u);
    // discard_nz r0.y
    if (asuint(r0.y) != 0u) discard;
    // mov oMask, vCoverage.x
    oMask = asuint(vCoverage.x);
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // lt r0.x, |r0.x|, l(0.000001)
    r0.x = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[16].z
    r0.y = r0.y * cb0[16].z;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul r0.y, r0.y, cb0[16].w
    r0.y = r0.y * cb0[16].w;
    // mul r0.y, r0.y, cb0[2].w
    r0.y = r0.y * cb0[2].w;
    // mul r1.xyz, cb0[7].xyzx, cb0[7].wwww
    float stage8_x = cb0[7].x * cb0[7].w;
    float stage8_y = cb0[7].y * cb0[7].w;
    float stage8_z = cb0[7].z * cb0[7].w;
    r1.x = stage8_x;
    r1.y = stage8_y;
    r1.z = stage8_z;
    // mul r0.yzw, r0.yyyy, r1.xxyz
    float stage9_y = r0.y * r1.x;
    float stage9_z = r0.y * r1.y;
    float stage9_w = r0.y * r1.z;
    r0.y = stage9_y;
    r0.z = stage9_z;
    r0.w = stage9_w;
    // movc r0.xyz, r0.xxxx, l(0,0,0,0), r0.yzwy
    float stage10_x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    float stage10_y = asuint(r0.x) != 0u ? asfloat(0u) : r0.z;
    float stage10_z = asuint(r0.x) != 0u ? asfloat(0u) : r0.w;
    r0.x = stage10_x;
    r0.y = stage10_y;
    r0.z = stage10_z;
    // mul r1.xy, v4.xyxx, cb0[11].xyxx
    float stage11_x = v4.x * cb0[11].x;
    float stage11_y = v4.y * cb0[11].y;
    r1.x = stage11_x;
    r1.y = stage11_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t4.xyzw, s3, l(0.000000)
    float4 fetch12 = t4.SampleBias(s3, r1.xy, 0.0f);
    r1.x = fetch12.x;
    r1.y = fetch12.y;
    r1.z = fetch12.z;
    // dp3 r0.w, r1.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.w = dot(r1.xyz, float3(0.3f, 0.59f, 0.11f));
    // add r2.xyz, -r1.xyzx, r0.wwww
    float stage13_x = -r1.x + r0.w;
    float stage13_y = -r1.y + r0.w;
    float stage13_z = -r1.z + r0.w;
    r2.x = stage13_x;
    r2.y = stage13_y;
    r2.z = stage13_z;
    // mad r1.xyz, cb0[18].yyyy, r2.xyzx, r1.xyzx
    float stage14_x = cb0[18].y * r2.x + r1.x;
    float stage14_y = cb0[18].y * r2.y + r1.y;
    float stage14_z = cb0[18].y * r2.z + r1.z;
    r1.x = stage14_x;
    r1.y = stage14_y;
    r1.z = stage14_z;
    // max r1.xyz, |r1.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage15_x = max(abs(r1.x), 1e-06f);
    float stage15_y = max(abs(r1.y), 1e-06f);
    float stage15_z = max(abs(r1.z), 1e-06f);
    r1.x = stage15_x;
    r1.y = stage15_y;
    r1.z = stage15_z;
    // log r1.xyz, r1.xyzx
    float stage16_x = log2(r1.x);
    float stage16_y = log2(r1.y);
    float stage16_z = log2(r1.z);
    r1.x = stage16_x;
    r1.y = stage16_y;
    r1.z = stage16_z;
    // mul r1.xyz, r1.xyzx, cb0[18].zzzz
    float stage17_x = r1.x * cb0[18].z;
    float stage17_y = r1.y * cb0[18].z;
    float stage17_z = r1.z * cb0[18].z;
    r1.x = stage17_x;
    r1.y = stage17_y;
    r1.z = stage17_z;
    // exp r1.xyz, r1.xyzx
    float stage18_x = exp2(r1.x);
    float stage18_y = exp2(r1.y);
    float stage18_z = exp2(r1.z);
    r1.x = stage18_x;
    r1.y = stage18_y;
    r1.z = stage18_z;
    // mul r2.xyz, cb0[12].xyzx, cb0[12].wwww
    float stage19_x = cb0[12].x * cb0[12].w;
    float stage19_y = cb0[12].y * cb0[12].w;
    float stage19_z = cb0[12].z * cb0[12].w;
    r2.x = stage19_x;
    r2.y = stage19_y;
    r2.z = stage19_z;
    // mul r1.xyz, r1.xyzx, r2.xyzx
    float stage20_x = r1.x * r2.x;
    float stage20_y = r1.y * r2.y;
    float stage20_z = r1.z * r2.z;
    r1.x = stage20_x;
    r1.y = stage20_y;
    r1.z = stage20_z;
    // dp3 r0.w, v5.xyzx, v5.xyzx
    r0.w = dot(v5.xyz, v5.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r2.xy, r0.wwww, v5.xyxx
    float stage21_x = r0.w * v5.x;
    float stage21_y = r0.w * v5.y;
    r2.x = stage21_x;
    r2.y = stage21_y;
    // mul r2.zw, v4.xxxy, cb0[9].xxxy
    float stage22_z = v4.x * cb0[9].x;
    float stage22_w = v4.y * cb0[9].y;
    r2.z = stage22_z;
    r2.w = stage22_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.zw, r2.zwzz, t2.zwxy, s1, l(0.000000)
    float4 fetch23 = t2.SampleBias(s1, r2.zw, 0.0f);
    r2.z = fetch23.x;
    r2.w = fetch23.y;
    // mad r3.xy, r2.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
    float stage24_x = r2.z * 2.0f + -1.0f;
    float stage24_y = r2.w * 2.0f + -1.0f;
    r3.x = stage24_x;
    r3.y = stage24_y;
    // mul r2.zw, r3.xxxy, cb0[17].xxxx
    float stage25_z = r3.x * cb0[17].x;
    float stage25_w = r3.y * cb0[17].x;
    r2.z = stage25_z;
    r2.w = stage25_w;
    // mad r2.xy, -r2.xyxx, cb0[8].xyxx, r2.zwzz
    float stage26_x = -r2.x * cb0[8].x + r2.z;
    float stage26_y = -r2.y * cb0[8].y + r2.w;
    r2.x = stage26_x;
    r2.y = stage26_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xyxx, t3.xyzw, s2, l(0.000000)
    float4 fetch27 = t3.SampleBias(s2, r2.xy, 0.0f);
    r2.x = fetch27.x;
    r2.y = fetch27.y;
    r2.z = fetch27.z;
    // dp3 r0.w, r2.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.w = dot(r2.xyz, float3(0.3f, 0.59f, 0.11f));
    // add r4.xyz, -r2.xyzx, r0.wwww
    float stage28_x = -r2.x + r0.w;
    float stage28_y = -r2.y + r0.w;
    float stage28_z = -r2.z + r0.w;
    r4.x = stage28_x;
    r4.y = stage28_y;
    r4.z = stage28_z;
    // mad r2.xyz, cb0[17].yyyy, r4.xyzx, r2.xyzx
    float stage29_x = cb0[17].y * r4.x + r2.x;
    float stage29_y = cb0[17].y * r4.y + r2.y;
    float stage29_z = cb0[17].y * r4.z + r2.z;
    r2.x = stage29_x;
    r2.y = stage29_y;
    r2.z = stage29_z;
    // max r2.xyz, |r2.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage30_x = max(abs(r2.x), 1e-06f);
    float stage30_y = max(abs(r2.y), 1e-06f);
    float stage30_z = max(abs(r2.z), 1e-06f);
    r2.x = stage30_x;
    r2.y = stage30_y;
    r2.z = stage30_z;
    // log r2.xyz, r2.xyzx
    float stage31_x = log2(r2.x);
    float stage31_y = log2(r2.y);
    float stage31_z = log2(r2.z);
    r2.x = stage31_x;
    r2.y = stage31_y;
    r2.z = stage31_z;
    // mul r2.xyz, r2.xyzx, cb0[17].zzzz
    float stage32_x = r2.x * cb0[17].z;
    float stage32_y = r2.y * cb0[17].z;
    float stage32_z = r2.z * cb0[17].z;
    r2.x = stage32_x;
    r2.y = stage32_y;
    r2.z = stage32_z;
    // exp r2.xyz, r2.xyzx
    float stage33_x = exp2(r2.x);
    float stage33_y = exp2(r2.y);
    float stage33_z = exp2(r2.z);
    r2.x = stage33_x;
    r2.y = stage33_y;
    r2.z = stage33_z;
    // mul r4.xyz, cb0[10].xyzx, cb0[10].wwww
    float stage34_x = cb0[10].x * cb0[10].w;
    float stage34_y = cb0[10].y * cb0[10].w;
    float stage34_z = cb0[10].z * cb0[10].w;
    r4.x = stage34_x;
    r4.y = stage34_y;
    r4.z = stage34_z;
    // mad r1.xyz, r2.xyzx, r4.xyzx, r1.xyzx
    float stage35_x = r2.x * r4.x + r1.x;
    float stage35_y = r2.y * r4.y + r1.y;
    float stage35_z = r2.z * r4.z + r1.z;
    r1.x = stage35_x;
    r1.y = stage35_y;
    r1.z = stage35_z;
    // mul r2.xyz, cb0[13].xyzx, cb0[13].wwww
    float stage36_x = cb0[13].x * cb0[13].w;
    float stage36_y = cb0[13].y * cb0[13].w;
    float stage36_z = cb0[13].z * cb0[13].w;
    r2.x = stage36_x;
    r2.y = stage36_y;
    r2.z = stage36_z;
    // mul r4.xyz, r1.xyzx, r2.xyzx
    float stage37_x = r1.x * r2.x;
    float stage37_y = r1.y * r2.y;
    float stage37_z = r1.z * r2.z;
    r4.x = stage37_x;
    r4.y = stage37_y;
    r4.z = stage37_z;
    // mad r1.xyz, -r1.xyzx, r2.xyzx, r1.xyzx
    float stage38_x = -r1.x * r2.x + r1.x;
    float stage38_y = -r1.y * r2.y + r1.y;
    float stage38_z = -r1.z * r2.z + r1.z;
    r1.x = stage38_x;
    r1.y = stage38_y;
    r1.z = stage38_z;
    // dp2 r0.w, r3.xyxx, r3.xyxx
    r0.w = dot(r3.xy, r3.xy);
    // add r0.w, -r0.w, l(1.000000)
    r0.w = -r0.w + 1.0f;
    // max r0.w, r0.w, l(0.000000)
    r0.w = max(r0.w, 0.0f);
    // sqrt r0.w, r0.w
    r0.w = sqrt(r0.w);
    // add r3.z, r0.w, l(0.000010)
    r3.z = r0.w + 1e-05f;
    // mad r2.xyz, cb0[17].xxxx, r3.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
    float stage39_x = cb0[17].x * r3.x + 0.0f;
    float stage39_y = cb0[17].x * r3.y + 0.0f;
    float stage39_z = cb0[17].x * r3.z + 1.0f;
    r2.x = stage39_x;
    r2.y = stage39_y;
    r2.z = stage39_z;
    // dp3 r0.w, v1.xyzx, v1.xyzx
    r0.w = dot(v1.xyz, v1.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r3.xyz, r0.wwww, v1.xyzx
    float stage40_x = r0.w * v1.x;
    float stage40_y = r0.w * v1.y;
    float stage40_z = r0.w * v1.z;
    r3.x = stage40_x;
    r3.y = stage40_y;
    r3.z = stage40_z;
    // dp3_sat r0.w, r3.xyzx, r2.xyzx
    r0.w = saturate(dot(r3.xyz, r2.xyz));
    // log r1.w, r0.w
    r1.w = log2(r0.w);
    // lt r0.w, r0.w, l(0.000001)
    r0.w = asfloat((r0.w < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.w, r1.w, cb0[18].w
    r1.w = r1.w * cb0[18].w;
    // exp r1.w, r1.w
    r1.w = exp2(r1.w);
    // mul_sat r1.w, r1.w, cb0[19].x
    r1.w = saturate(r1.w * cb0[19].x);
    // movc r0.w, r0.w, l(0), r1.w
    r0.w = asuint(r0.w) != 0u ? asfloat(0u) : r1.w;
    // mad r1.xyz, r0.wwww, r1.xyzx, r4.xyzx
    float stage41_x = r0.w * r1.x + r4.x;
    float stage41_y = r0.w * r1.y + r4.y;
    float stage41_z = r0.w * r1.z + r4.z;
    r1.x = stage41_x;
    r1.y = stage41_y;
    r1.z = stage41_z;
    // add r0.xyz, r0.xyzx, r1.xyzx
    float stage42_x = r0.x + r1.x;
    float stage42_y = r0.y + r1.y;
    float stage42_z = r0.z + r1.z;
    r0.x = stage42_x;
    r0.y = stage42_y;
    r0.z = stage42_z;
    // mad o0.xyz, r0.xyzx, cb0[0].xyzx, cb0[1].xyzx
    float stage43_x = r0.x * cb0[0].x + cb0[1].x;
    float stage43_y = r0.y * cb0[0].y + cb0[1].y;
    float stage43_z = r0.z * cb0[0].z + cb0[1].z;
    o0.x = stage43_x;
    o0.y = stage43_y;
    o0.z = stage43_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);
    // dp3 r0.x, v0.xyzx, v0.xyzx
    r0.x = dot(v0.xyz, v0.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v0.zxyz
    float stage44_x = r0.x * v0.z;
    float stage44_y = r0.x * v0.x;
    float stage44_z = r0.x * v0.y;
    r0.x = stage44_x;
    r0.y = stage44_y;
    r0.z = stage44_z;
    // mul r0.w, r0.y, r3.y
    r0.w = r0.y * r3.y;
    // mad r0.w, r3.x, r0.z, -r0.w
    r0.w = r3.x * r0.z + -r0.w;
    // mov r0.z, r3.z
    r0.z = r3.z;
    // mul r0.y, r0.w, v1.w
    r0.y = r0.w * v1.w;
    // dp3 r0.w, r0.xyzx, r0.xyzx
    r0.w = dot(r0.xyz, r0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r0.xyz, r0.wwww, r0.xyzx
    float stage45_x = r0.w * r0.x;
    float stage45_y = r0.w * r0.y;
    float stage45_z = r0.w * r0.z;
    r0.x = stage45_x;
    r0.y = stage45_y;
    r0.z = stage45_z;
    // ge r0.w, l(0.000000), r0.z
    r0.w = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // dp3 r0.z, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.z = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.zzzz
    float stage46_x = r0.x / r0.z;
    float stage46_y = r0.y / r0.z;
    r0.x = stage46_x;
    r0.y = stage46_y;
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage47_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage47_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage47_x;
    r1.y = stage47_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage48_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage48_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage48_x;
    r1.y = stage48_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage49_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage49_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage49_x;
    r1.y = stage49_y;
    // movc r0.xy, r0.wwww, r1.xyxx, r0.xyxx
    float stage50_x = asuint(r0.w) != 0u ? r1.x : r0.x;
    float stage50_y = asuint(r0.w) != 0u ? r1.y : r0.y;
    r0.x = stage50_x;
    r0.y = stage50_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage51_x = r0.x * 0.5f + 0.5f;
    float stage51_y = r0.y * 0.5f + 0.5f;
    o2.x = stage51_x;
    o2.y = stage51_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage52_z = 1.0f;
    float stage52_w = asfloat(0u);
    o2.z = stage52_z;
    o2.w = stage52_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage53_x = cb2[3].x;
    float stage53_y = cb2[3].y;
    float stage53_z = cb2[3].z;
    o3.x = stage53_x;
    o3.y = stage53_y;
    o3.z = stage53_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage54_x = asfloat(0u);
    float stage54_y = asfloat(0u);
    float stage54_z = asfloat(0u);
    float stage54_w = asfloat(0u);
    o4.x = stage54_x;
    o4.y = stage54_y;
    o4.z = stage54_z;
    o4.w = stage54_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage55_x = asfloat(0u);
    float stage55_y = asfloat(0u);
    float stage55_z = asfloat(0u);
    float stage55_w = asfloat(0u);
    o5.x = stage55_x;
    o5.y = stage55_y;
    o5.z = stage55_z;
    o5.w = stage55_w;

    Shade_Ue3_fx_d_pa_dissolve_01_ma_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    result.oMask = oMask;
    return result;
}
