constexpr std::array<std::string_view,0> DIMENSIONMASTER_SD_TEXTURES_320 = {{}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,10> DIMENSIONMASTER_SD_PARAMETERS_320 = {{
    {"selectioncolor", 3u, 0u, true},
    {"mask_color", 2u, 0u, true},
    {"cricle_rotation", 0u, 0u, false},
    {"uv_scale_x", 1u, 2u, false},
    {"uv_scale_y", 1u, 3u, false},
    {"uv_position_x", 1u, 0u, false},
    {"uv_position_y", 1u, 1u, false},
    {"mask_hardness", 0u, 1u, false},
    {"mask_power", 0u, 3u, false},
    {"mask_intensity", 0u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,1> DIMENSIONMASTER_SD_SWITCHES_320 = {{
    {"use_inverse", false},
}};

constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_321 = {{"maintex","uv_noise_tex","emissivetex02","dissolve_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,38> DIMENSIONMASTER_SD_PARAMETERS_321 = {{
    {"selectioncolor", 10u, 0u, true},
    {"uvnoise_move_x", 8u, 2u, false},
    {"uvnoise_move_y", 8u, 3u, false},
    {"maintex_move_x", 4u, 3u, false},
    {"maintex_move_y", 5u, 0u, false},
    {"maintex_rotator", 5u, 3u, false},
    {"dissolvetex_rotator", 1u, 3u, false},
    {"edge_color", 9u, 0u, true},
    {"maintex_panspeed_x", 5u, 1u, false},
    {"maintex_tile_x", 6u, 0u, false},
    {"maintex_tile_y", 6u, 1u, false},
    {"maintex_panspeed_y", 5u, 2u, false},
    {"maintex_dynamicpan_x_velue", 4u, 1u, false},
    {"maintex_dynamicpan_y_velue", 4u, 2u, false},
    {"uv_noisetex_pan_x", 7u, 2u, false},
    {"uv_noisetex_tile_x", 8u, 0u, false},
    {"uv_noisetex_tile_y", 8u, 1u, false},
    {"uv_noisetex_pan_y", 7u, 3u, false},
    {"uv_noise_velue", 7u, 1u, false},
    {"emissivetex02_panspeed_x", 3u, 0u, false},
    {"emissivetex02_tile_x", 3u, 2u, false},
    {"emissivetex02_tile_y", 3u, 3u, false},
    {"emissivetex02_panspeed_y", 3u, 1u, false},
    {"emissive_core_power", 2u, 2u, false},
    {"emissive_core_strength", 2u, 3u, false},
    {"emissive_base", 2u, 1u, false},
    {"disslovetex_01_panspeed_x", 0u, 0u, false},
    {"disslovetex_01_tile_x", 0u, 2u, false},
    {"disslovetex_01_tile_y", 0u, 3u, false},
    {"disslovetex_01_panspeed_y", 0u, 1u, false},
    {"dissolvetex_move_x", 1u, 1u, false},
    {"dissolvetex_move_y", 1u, 2u, false},
    {"dissolve_hardness", 1u, 0u, false},
    {"edge_thin", 2u, 0u, false},
    {"spheremask_strength", 6u, 2u, false},
    {"spheremask_strength_max", 6u, 3u, false},
    {"spheremask_strength_min", 7u, 0u, false},
    {"maintex_alpha_strength", 4u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,20> DIMENSIONMASTER_SD_SWITCHES_321 = {{
    {"use_dissolve", true},
    {"use_meshtype", false},
    {"use_uvnoise", true},
    {"achannel_use_uvnoisedynamicpan", false},
    {"use_uv_noise_02", false},
    {"use_uv_noisetex_02", true},
    {"uv_noisetype", true},
    {"maintex_type_polar", true},
    {"maintex_pan_xy", false},
    {"use_dynamic_spheryxy", false},
    {"uv_sphery_y", false},
    {"uv_sphery_x", false},
    {"use_alpha_fresnel", false},
    {"use_dissolvetex_02", false},
    {"use_dissolvetex_noise", false},
    {"use_dissolvetex_noise_type", true},
    {"use_dissolvetex_02_mixtype", true},
    {"use_sphere_alpha", true},
    {"dissloveoutline_multyply_alpha", false},
    {"use_emissivetex02", true},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_322 = {{"maintex","uv_noise_tex","dissolve_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,34> DIMENSIONMASTER_SD_PARAMETERS_322 = {{
    {"selectioncolor", 9u, 0u, true},
    {"uvnoise_move_x", 7u, 2u, false},
    {"uvnoise_move_y", 7u, 3u, false},
    {"maintex_move_x", 3u, 3u, false},
    {"maintex_move_y", 4u, 0u, false},
    {"maintex_rotator", 4u, 3u, false},
    {"dissolvetex_rotator", 1u, 3u, false},
    {"edge_color", 8u, 0u, true},
    {"maintex_panspeed_x", 4u, 1u, false},
    {"maintex_tile_x", 5u, 0u, false},
    {"maintex_tile_y", 5u, 1u, false},
    {"maintex_panspeed_y", 4u, 2u, false},
    {"maintex_dynamicpan_x_velue", 3u, 1u, false},
    {"maintex_dynamicpan_y_velue", 3u, 2u, false},
    {"uv_noisetex_pan_x", 6u, 2u, false},
    {"uv_noisetex_tile_x", 7u, 0u, false},
    {"uv_noisetex_tile_y", 7u, 1u, false},
    {"uv_noisetex_pan_y", 6u, 3u, false},
    {"uv_noise_velue", 6u, 1u, false},
    {"emissive_core_power", 2u, 2u, false},
    {"emissive_core_strength", 2u, 3u, false},
    {"emissive_base", 2u, 1u, false},
    {"disslovetex_01_panspeed_x", 0u, 0u, false},
    {"disslovetex_01_tile_x", 0u, 2u, false},
    {"disslovetex_01_tile_y", 0u, 3u, false},
    {"disslovetex_01_panspeed_y", 0u, 1u, false},
    {"dissolvetex_move_x", 1u, 1u, false},
    {"dissolvetex_move_y", 1u, 2u, false},
    {"dissolve_hardness", 1u, 0u, false},
    {"edge_thin", 2u, 0u, false},
    {"spheremask_strength", 5u, 2u, false},
    {"spheremask_strength_max", 5u, 3u, false},
    {"spheremask_strength_min", 6u, 0u, false},
    {"maintex_alpha_strength", 3u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,20> DIMENSIONMASTER_SD_SWITCHES_322 = {{
    {"use_dissolve", true},
    {"use_meshtype", false},
    {"use_uvnoise", true},
    {"achannel_use_uvnoisedynamicpan", false},
    {"use_uv_noise_02", false},
    {"use_uv_noisetex_02", true},
    {"uv_noisetype", true},
    {"maintex_type_polar", true},
    {"maintex_pan_xy", false},
    {"use_dynamic_spheryxy", false},
    {"uv_sphery_y", false},
    {"uv_sphery_x", false},
    {"use_alpha_fresnel", false},
    {"use_dissolvetex_02", false},
    {"use_dissolvetex_noise", false},
    {"use_dissolvetex_noise_type", true},
    {"use_dissolvetex_02_mixtype", true},
    {"use_sphere_alpha", true},
    {"dissloveoutline_multyply_alpha", false},
    {"use_emissivetex02", false},
}};

constexpr std::array<std::string_view,2> DIMENSIONMASTER_SD_TEXTURES_323 = {{"01.map_e","06.map_f"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,22> DIMENSIONMASTER_SD_PARAMETERS_323 = {{
    {"selectioncolor", 6u, 0u, true},
    {"16.emissiion_str", 5u, 0u, true},
    {"time", 4u, 3u, false},
    {"04.map_e_panning_x", 1u, 2u, false},
    {"02.map_e_uvscale_r", 1u, 0u, false},
    {"03.map_e_uvscale_g", 1u, 1u, false},
    {"01.amount", 0u, 0u, false},
    {"11.curvature", 3u, 1u, false},
    {"05.map_e_panning_y", 1u, 3u, false},
    {"09.map_f_panning_x", 2u, 2u, false},
    {"07.map_f_uvscale_r", 2u, 0u, false},
    {"08.map_f_uvscale_g", 2u, 1u, false},
    {"10.map_f_panning_y", 2u, 3u, false},
    {"12.desaturation", 3u, 3u, false},
    {"15.emissiion_power", 4u, 0u, false},
    {"21.noise_str", 4u, 1u, false},
    {"11.centermask_str", 3u, 0u, false},
    {"12.centermask_power", 3u, 2u, false},
    {"01.circle_radius", 0u, 1u, false},
    {"02.circle_hardness", 0u, 3u, false},
    {"22.noise_power", 4u, 2u, false},
    {"01.depthbiasdalpha_bias", 0u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,10> DIMENSIONMASTER_SD_SWITCHES_323 = {{
    {"00.usedistortion", false},
    {"01.usemesh", false},
    {"40.usefresnal", false},
    {"00.use_uvdistort", false},
    {"20.useaddnoise", true},
    {"00.usecentermask", true},
    {"00.use_uvdistort_alpha", false},
    {"20.usecolorvari", false},
    {"00.checkisdepthbiasalpha", true},
    {"00.uselight", false},
}};


constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_324 = {{"01.icemap","01.specmap","native_texture_2"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,15> DIMENSIONMASTER_SD_PARAMETERS_324 = {{
    {"selectioncolor", 6u, 0u, true},
    {"05.specmap_uvscale.x", 1u, 1u, false},
    {"06.specmap_uvscale.y", 1u, 2u, false},
    {"02.icemap_uv.x", 0u, 0u, false},
    {"03.icemap_uv.y", 0u, 2u, false},
    {"09.specmap_color", 4u, 0u, true},
    {"06.icemap_color", 3u, 0u, true},
    {"meshemitterdynamicparameter", 5u, 0u, true},
    {"02.specmap_str", 0u, 1u, false},
    {"07.desaturation", 1u, 3u, false},
    {"08.specmap_power", 2u, 0u, false},
    {"09.ice_deep", 2u, 1u, false},
    {"04.desaturation", 0u, 3u, false},
    {"05.icemap_power", 1u, 0u, false},
    {"51.fresnal_power", 2u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,6> DIMENSIONMASTER_SD_SWITCHES_324 = {{
    {"00.usedistortion", false},
    {"00.checkisdepthbiasalpha", false},
    {"10.usesnow", false},
    {"00.useshadow", false},
    {"--usespecullar", true},
    {"00.useemission", false},
}};


constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_325 = {{"06.map","02.map_e","01.map_a","21.map_c"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,25> DIMENSIONMASTER_SD_PARAMETERS_325 = {{
    {"selectioncolor", 8u, 0u, true},
    {"93.emissiion_color", 6u, 0u, true},
    {"meshemitterdynamicparameter", 7u, 0u, true},
    {"21.uvscale.x", 3u, 1u, false},
    {"22.uvscale.y", 3u, 2u, false},
    {"time", 5u, 1u, false},
    {"05.map_e_panning_x", 1u, 3u, false},
    {"03.map_e_uvscale_r", 0u, 2u, false},
    {"04.map_e_uvscale_g", 1u, 0u, false},
    {"09.map_d_panning_x", 2u, 3u, false},
    {"07.map_d_uvscale_r", 2u, 1u, false},
    {"08.map_d_uvscale_g", 2u, 2u, false},
    {"10.map_d_panning_y", 3u, 0u, false},
    {"05.distort_str", 1u, 1u, false},
    {"06.map_e_panning_y", 2u, 0u, false},
    {"91.desaturation", 4u, 3u, false},
    {"92.emissiion_power", 5u, 0u, false},
    {"04.map_a_panning_x", 0u, 3u, false},
    {"02.map_a_uvscale_r", 0u, 0u, false},
    {"03.map_a_uvscale_g", 0u, 1u, false},
    {"05.map_a_panning_y", 1u, 2u, false},
    {"29.cmap.direct", 3u, 3u, false},
    {"30.cmap.time(rotrate)", 4u, 0u, false},
    {"36.str", 4u, 1u, false},
    {"37.power", 4u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,26> DIMENSIONMASTER_SD_SWITCHES_325 = {{
    {"00.usedistortion", false},
    {"01.usemesh", true},
    {"31.mapch.r", true},
    {"32.mapch.g", true},
    {"20.use_clampmap", true},
    {"25.use_yclamp", false},
    {"00.use_uvdistort", true},
    {"10.use_mapb", false},
    {"00.use_mapa", true},
    {"30.usefresnal", false},
    {"00.checkisdepthbiasalpha", false},
    {"00.use_emission", true},
    {"50.usefresemission", false},
    {"01.use_emissionmap", true},
    {"10.use_mapf", false},
    {"11.map_e + map_f", false},
    {"00.usespecullar", false},
    {"20.usefresspec", false},
    {"40.use_clampmap", false},
    {"48.use_yclamp", false},
    {"41.map_e + map_f", false},
    {"60.twist", false},
    {"60.usedissolveemission", false},
    {"31.fresnal.invert", false},
    {"33.mapch.b", true},
    {"34.mapch.a", true},
}};


constexpr std::array<std::string_view,6> DIMENSIONMASTER_SD_TEXTURES_326 = {{"maintex","uv_noise_tex_02","uv_noise_tex","emissivetex02","noisedissolve_tex","dissolve_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,46> DIMENSIONMASTER_SD_PARAMETERS_326 = {{
    {"selectioncolor", 13u, 0u, true},
    {"meshemitterdynamicparameter", 12u, 0u, true},
    {"maintex_rotator", 6u, 1u, false},
    {"maintex_move_x", 5u, 1u, false},
    {"maintex_move_y", 5u, 2u, false},
    {"dissolvetex_rotator", 1u, 3u, false},
    {"edge_color", 11u, 0u, true},
    {"maintex_panspeed_x", 5u, 3u, false},
    {"maintex_tile_x", 6u, 2u, false},
    {"maintex_tile_y", 6u, 3u, false},
    {"maintex_dynamicpan_x_velue", 4u, 3u, false},
    {"maintex_dynamicpan_y_velue", 5u, 0u, false},
    {"maintex_panspeed_y", 6u, 0u, false},
    {"uv_noisetex_pan_x", 9u, 1u, false},
    {"uv_noisetex_tile_x", 10u, 1u, false},
    {"uv_noisetex_tile_y", 10u, 2u, false},
    {"uv_noisetex_pan_02_x", 8u, 3u, false},
    {"uv_noisetex_tile_02_x", 9u, 3u, false},
    {"uv_noisetex_tile_02_y", 10u, 0u, false},
    {"uv_noisetex_pan_02_y", 9u, 0u, false},
    {"uv_noise_02_strength", 8u, 1u, false},
    {"uv_noisetex_pan_y", 9u, 2u, false},
    {"dynamic_uvnoise_x", 2u, 0u, false},
    {"dynamic_uvnoise_y", 2u, 1u, false},
    {"uv_noise_velue", 8u, 2u, false},
    {"emissivetex02_panspeed_x", 3u, 2u, false},
    {"emissivetex02_tile_x", 4u, 0u, false},
    {"emissivetex02_tile_y", 4u, 1u, false},
    {"emissivetex02_panspeed_y", 3u, 3u, false},
    {"emissive_core_power", 3u, 0u, false},
    {"emissive_core_strength", 3u, 1u, false},
    {"emissive_base", 2u, 3u, false},
    {"disslovetex_01_panspeed_x", 0u, 0u, false},
    {"disslovetex_01_tile_x", 0u, 2u, false},
    {"disslovetex_01_tile_y", 0u, 3u, false},
    {"noisetodisslovetex_01_panspeed_x", 7u, 1u, false},
    {"noisetodisslovetex_01_tile_x", 7u, 3u, false},
    {"noisetodisslovetex_01_tile_y", 8u, 0u, false},
    {"noisetodisslovetex_01_panspeed_y", 7u, 2u, false},
    {"noisedissolvetex_strength", 7u, 0u, false},
    {"disslovetex_01_panspeed_y", 0u, 1u, false},
    {"dissolvetex_move_x", 1u, 1u, false},
    {"dissolvetex_move_y", 1u, 2u, false},
    {"dissolve_hardness", 1u, 0u, false},
    {"edge_thin", 2u, 2u, false},
    {"maintex_alpha_strength", 4u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,20> DIMENSIONMASTER_SD_SWITCHES_326 = {{
    {"use_dissolve", true},
    {"use_meshtype", true},
    {"use_uvnoise", true},
    {"achannel_use_uvnoisedynamicpan", true},
    {"use_uv_noise_02", true},
    {"use_uv_noisetex_02", true},
    {"uv_noisetype", true},
    {"maintex_type_polar", false},
    {"maintex_pan_xy", true},
    {"use_dynamic_spheryxy", false},
    {"uv_sphery_y", false},
    {"uv_sphery_x", false},
    {"use_alpha_fresnel", false},
    {"use_dissolvetex_02", false},
    {"use_dissolvetex_noise", true},
    {"use_dissolvetex_noise_type", true},
    {"use_dissolvetex_02_mixtype", true},
    {"use_sphere_alpha", false},
    {"dissloveoutline_multyply_alpha", true},
    {"use_emissivetex02", true},
}};


constexpr std::array<std::string_view,1> DIMENSIONMASTER_SD_TEXTURES_327 = {{"emissive_tex"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,8> DIMENSIONMASTER_SD_PARAMETERS_327 = {{
    {"selectioncolor", 3u, 0u, true},
    {"meshemitterdynamicparameter", 2u, 0u, true},
    {"uv_scale", 1u, 1u, false},
    {"dynamic_parameter_explanation", 0u, 0u, false},
    {"emissive_desaturation", 0u, 3u, false},
    {"edge_intensity", 0u, 1u, false},
    {"edge_power", 0u, 2u, false},
    {"emissive_power", 1u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,18> DIMENSIONMASTER_SD_SWITCHES_327 = {{
    {"use_mesh_world_normal", false},
    {"use_depth_alpha", false},
    {"use_distortion", false},
    {"use_distortion_floor", false},
    {"use_meshtype", true},
    {"use_subuv_tex", false},
    {"use_alpha_tex", false},
    {"use_uv_panning", false},
    {"use_uv_rotation", false},
    {"use_uv_noise_tex", false},
    {"use_fresnel_alpha", false},
    {"use_camera_alpha", false},
    {"use_edge_glow", true},
    {"non_alpha_chanel", false},
    {"use_axisy", true},
    {"use_dynparam_panning", false},
    {"use_uv_noise_tex_02", false},
    {"use_rotation_angle", false},
}};


constexpr std::array<std::string_view,5> DIMENSIONMASTER_SD_TEXTURES_328 = {{"06.map","02.map_e","12.map_f","01.map_a","21.map_c"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,31> DIMENSIONMASTER_SD_PARAMETERS_328 = {{
    {"selectioncolor", 9u, 0u, true},
    {"93.emissiion_color", 7u, 0u, true},
    {"meshemitterdynamicparameter", 8u, 0u, true},
    {"21.uvscale.x", 4u, 1u, false},
    {"22.uvscale.y", 4u, 2u, false},
    {"time", 6u, 3u, false},
    {"05.map_e_panning_x", 1u, 3u, false},
    {"03.map_e_uvscale_r", 0u, 2u, false},
    {"04.map_e_uvscale_g", 1u, 0u, false},
    {"09.map_d_panning_x", 2u, 3u, false},
    {"07.map_d_uvscale_r", 2u, 1u, false},
    {"08.map_d_uvscale_g", 2u, 2u, false},
    {"10.map_d_panning_y", 3u, 0u, false},
    {"05.distort_str", 1u, 1u, false},
    {"06.map_e_panning_y", 2u, 0u, false},
    {"15.map_f_panning_x", 3u, 3u, false},
    {"13.map_f_uvscale_r", 3u, 1u, false},
    {"14.map_f_uvscale_g", 3u, 2u, false},
    {"16.map_f_panning_y", 4u, 0u, false},
    {"91.desaturation", 6u, 1u, false},
    {"92.emissiion_power", 6u, 2u, false},
    {"04.map_a_panning_x", 0u, 3u, false},
    {"02.map_a_uvscale_r", 0u, 0u, false},
    {"03.map_a_uvscale_g", 0u, 1u, false},
    {"05.map_a_panning_y", 1u, 2u, false},
    {"29.cmap.direct", 4u, 3u, false},
    {"30.cmap.time(rotrate)", 5u, 0u, false},
    {"36.str", 5u, 3u, false},
    {"37.power", 6u, 0u, false},
    {"32.fresnal_power", 5u, 1u, false},
    {"33.fresnal_str", 5u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,26> DIMENSIONMASTER_SD_SWITCHES_328 = {{
    {"00.usedistortion", false},
    {"01.usemesh", true},
    {"31.mapch.r", true},
    {"32.mapch.g", true},
    {"20.use_clampmap", true},
    {"25.use_yclamp", false},
    {"00.use_uvdistort", true},
    {"10.use_mapb", false},
    {"00.use_mapa", true},
    {"30.usefresnal", true},
    {"00.checkisdepthbiasalpha", false},
    {"00.use_emission", true},
    {"50.usefresemission", false},
    {"01.use_emissionmap", true},
    {"10.use_mapf", true},
    {"11.map_e + map_f", true},
    {"00.usespecullar", false},
    {"20.usefresspec", false},
    {"40.use_clampmap", false},
    {"48.use_yclamp", false},
    {"41.map_e + map_f", false},
    {"60.twist", false},
    {"60.usedissolveemission", false},
    {"31.fresnal.invert", false},
    {"33.mapch.b", true},
    {"34.mapch.a", true},
}};


constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_329 = {{"06.map","01.map_e","06.map_f","11.edge_map"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,36> DIMENSIONMASTER_SD_PARAMETERS_329 = {{
    {"selectioncolor", 12u, 0u, true},
    {"18.edge_color", 8u, 0u, true},
    {"meshemitterdynamicparameter", 11u, 0u, true},
    {"00.rotateuv", 0u, 0u, false},
    {"19.emissiion_color", 9u, 0u, true},
    {"20.emissiion_color", 10u, 0u, true},
    {"00.rotateuv.", 0u, 1u, false},
    {"04.map_e_panning_x", 1u, 0u, false},
    {"02.map_e_uvscale_r", 0u, 2u, false},
    {"03.map_e_uvscale_g", 0u, 3u, false},
    {"09.map_d_panning_x", 3u, 2u, false},
    {"07.map_d_uvscale_r", 2u, 0u, false},
    {"08.map_d_uvscale_g", 2u, 2u, false},
    {"10.map_d_panning_y", 4u, 0u, false},
    {"05.distort_str", 1u, 1u, false},
    {"05.map_e_panning_y", 1u, 3u, false},
    {"09.map_f_panning_x", 3u, 3u, false},
    {"07.map_f_uvscale_r", 2u, 1u, false},
    {"08.map_f_uvscale_g", 2u, 3u, false},
    {"10.map_f_panning_y", 4u, 1u, false},
    {"14.map_dd_panning_x", 5u, 3u, false},
    {"12.map_dd_uvscale_r", 5u, 1u, false},
    {"13.map_dd_uvscale_g", 5u, 2u, false},
    {"15.map_dd_panning_y", 6u, 1u, false},
    {"08.phase_str", 3u, 0u, false},
    {"09.gap_hardness", 3u, 1u, false},
    {"10.power", 4u, 2u, false},
    {"16.str", 6u, 3u, false},
    {"17.power", 7u, 0u, false},
    {"12.desaturation", 5u, 0u, false},
    {"15.emissiion_power", 6u, 0u, false},
    {"16.emissiion_str", 6u, 2u, false},
    {"11.str", 4u, 3u, false},
    {"51.power", 7u, 1u, false},
    {"52.str", 7u, 2u, false},
    {"05.distortion_str", 1u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,20> DIMENSIONMASTER_SD_SWITCHES_329 = {{
    {"00.usedistortion", true},
    {"--use_outalphamap", true},
    {"01.bothsides_type", true},
    {"03.box_type", false},
    {"00.use_uvdistort", true},
    {"--use_dissolve", true},
    {"01.usemesh", true},
    {"01.liner_type", false},
    {"02.bothsides_type", true},
    {"03.cross_type", false},
    {"04.sweep_type", false},
    {"05.radialtype", true},
    {"06.invert", false},
    {"00.useboundry", false},
    {"02.liner_type", false},
    {"50.use_fresnal", true},
    {"10.useedgeemission", true},
    {"--use_gradient", true},
    {"--use_detailmap", true},
    {"00.checkisdepthbiasalpha", false},
}};


constexpr std::array<std::string_view,2> DIMENSIONMASTER_SD_TEXTURES_330 = {{"06.map","01.map_a"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,18> DIMENSIONMASTER_SD_PARAMETERS_330 = {{
    {"selectioncolor", 5u, 0u, true},
    {"01.rotateuv", 0u, 0u, false},
    {"meshemitterdynamicparameter", 4u, 0u, true},
    {"04.map_a_pantimescale", 1u, 1u, false},
    {"02.map_a_uv.x", 0u, 2u, false},
    {"03.map_a_uv.y", 1u, 0u, false},
    {"10.edgeemission_power", 2u, 2u, false},
    {"11.edgeemission_str", 3u, 0u, false},
    {"09.map_d_panning_x", 2u, 1u, false},
    {"07.map_d_uvscale_r", 1u, 3u, false},
    {"08.map_d_uvscale_g", 2u, 0u, false},
    {"10.map_d_panning_y", 2u, 3u, false},
    {"05.distort_str", 1u, 2u, false},
    {"01.wavecount", 0u, 1u, false},
    {"02.wavestr", 0u, 3u, false},
    {"11.width", 3u, 1u, false},
    {"31.fresnel_str", 3u, 2u, false},
    {"32.fresnel_power", 3u, 3u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_330 = {{
    {"30.usefresnel", true},
    {"50.useendfalloff", false},
    {"01.usemesh", true},
    {"00.use_uvdistort", true},
    {"00.use_wavetimebezier_in_dp", true},
}};


constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_331 = {{"maintex","emissivetex02","dissolve_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,30> DIMENSIONMASTER_SD_PARAMETERS_331 = {{
    {"selectioncolor", 9u, 0u, true},
    {"meshemitterdynamicparameter", 8u, 0u, true},
    {"maintex_rotator", 6u, 0u, false},
    {"maintex_move_x", 5u, 0u, false},
    {"maintex_move_y", 5u, 1u, false},
    {"dissolvetex_rotator", 1u, 3u, false},
    {"edge_color", 7u, 0u, true},
    {"maintex_panspeed_x", 5u, 2u, false},
    {"maintex_tile_x", 6u, 1u, false},
    {"maintex_tile_y", 6u, 2u, false},
    {"maintex_dynamicpan_x_velue", 4u, 2u, false},
    {"maintex_dynamicpan_y_velue", 4u, 3u, false},
    {"maintex_panspeed_y", 5u, 3u, false},
    {"emissivetex02_panspeed_x", 3u, 0u, false},
    {"emissivetex02_tile_x", 3u, 2u, false},
    {"emissivetex02_tile_y", 3u, 3u, false},
    {"emissivetex02_panspeed_y", 3u, 1u, false},
    {"emissive_core_power", 2u, 2u, false},
    {"emissive_core_strength", 2u, 3u, false},
    {"emissive_base", 2u, 1u, false},
    {"disslovetex_01_panspeed_x", 0u, 0u, false},
    {"disslovetex_01_tile_x", 0u, 2u, false},
    {"disslovetex_01_tile_y", 0u, 3u, false},
    {"disslovetex_01_panspeed_y", 0u, 1u, false},
    {"dissolvetex_move_x", 1u, 1u, false},
    {"dissolvetex_move_y", 1u, 2u, false},
    {"dissolve_hardness", 1u, 0u, false},
    {"edge_thin", 2u, 0u, false},
    {"fresnel_power", 4u, 0u, false},
    {"maintex_alpha_strength", 4u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,20> DIMENSIONMASTER_SD_SWITCHES_331 = {{
    {"use_dissolve", true},
    {"use_meshtype", true},
    {"use_uvnoise", false},
    {"achannel_use_uvnoisedynamicpan", false},
    {"use_uv_noise_02", false},
    {"use_uv_noisetex_02", true},
    {"uv_noisetype", true},
    {"maintex_type_polar", false},
    {"maintex_pan_xy", true},
    {"use_dynamic_spheryxy", false},
    {"uv_sphery_y", false},
    {"uv_sphery_x", false},
    {"use_alpha_fresnel", true},
    {"use_dissolvetex_02", false},
    {"use_dissolvetex_noise", false},
    {"use_dissolvetex_noise_type", true},
    {"use_dissolvetex_02_mixtype", true},
    {"use_sphere_alpha", false},
    {"dissloveoutline_multyply_alpha", false},
    {"use_emissivetex02", true},
}};


constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_332 = {{"maintex","uv_noise_tex","noisedissolve_tex","dissolve_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,42> DIMENSIONMASTER_SD_PARAMETERS_332 = {{
    {"selectioncolor", 12u, 0u, true},
    {"meshemitterdynamicparameter", 11u, 0u, true},
    {"maintex_rotator", 5u, 3u, false},
    {"maintex_move_x", 4u, 3u, false},
    {"maintex_move_y", 5u, 0u, false},
    {"dissolvetex_rotator", 2u, 0u, false},
    {"edge_color", 10u, 0u, true},
    {"maintex_panspeed_x", 5u, 1u, false},
    {"maintex_tile_x", 6u, 0u, false},
    {"maintex_tile_y", 6u, 1u, false},
    {"maintex_dynamicpan_x_velue", 4u, 1u, false},
    {"maintex_dynamicpan_y_velue", 4u, 2u, false},
    {"maintex_panspeed_y", 5u, 2u, false},
    {"uv_noisetex_pan_x", 8u, 3u, false},
    {"uv_noisetex_tile_x", 9u, 1u, false},
    {"uv_noisetex_tile_y", 9u, 2u, false},
    {"uv_noisetex_pan_y", 9u, 0u, false},
    {"dynamic_uvnoise_x", 2u, 1u, false},
    {"dynamic_uvnoise_y", 2u, 2u, false},
    {"uv_noise_velue", 8u, 2u, false},
    {"emissive_core_power", 3u, 1u, false},
    {"emissive_core_strength", 3u, 2u, false},
    {"emissive_base", 3u, 0u, false},
    {"disslovetex_01_panspeed_x", 0u, 0u, false},
    {"disslovetex_01_tile_x", 0u, 2u, false},
    {"disslovetex_01_tile_y", 0u, 3u, false},
    {"noisetodisslovetex_01_panspeed_x", 6u, 3u, false},
    {"noisetodisslovetex_01_tile_x", 7u, 1u, false},
    {"noisetodisslovetex_01_tile_y", 7u, 2u, false},
    {"noisetodisslovetex_01_panspeed_y", 7u, 0u, false},
    {"noisedissolvetex_strength", 6u, 2u, false},
    {"disslovetex_01_panspeed_y", 0u, 1u, false},
    {"dissolvetex_move_x", 1u, 1u, false},
    {"dissolvetex_move_y", 1u, 2u, false},
    {"dissolvetex_power", 1u, 3u, false},
    {"dissolve_hardness", 1u, 0u, false},
    {"edge_thin", 2u, 3u, false},
    {"fresnel_power", 3u, 3u, false},
    {"spheremask_strength", 7u, 3u, false},
    {"spheremask_strength_max", 8u, 0u, false},
    {"spheremask_strength_min", 8u, 1u, false},
    {"maintex_alpha_strength", 4u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,19> DIMENSIONMASTER_SD_SWITCHES_332 = {{
    {"use_alpha_fresnel", true},
    {"use_meshtype", true},
    {"use_dissolvetex_noise", true},
    {"use_dissolvetex_noise_type", true},
    {"achannel_use_uvnoisedynamicpan", true},
    {"use_uv_noise_02", false},
    {"use_uv_noisetex_02", true},
    {"uv_noisetype", true},
    {"maintex_type_polar", false},
    {"maintex_pan_xy", true},
    {"use_dynamic_spheryxy", false},
    {"uv_sphery_y", false},
    {"uv_sphery_x", false},
    {"use_sphere_alpha", true},
    {"use_emissivetex02", false},
    {"use_dissolve", true},
    {"dissloveoutline_multyply_alpha", true},
    {"texcoordpowertype_paramordynamic", true},
    {"use_uvnoise", true},
}};

constexpr std::array<std::string_view,5> DIMENSIONMASTER_SD_TEXTURES_341 = {{"uv_noise_texture","alpha_texture1_mask","alpha_texture2","emissive_tex_02","emissive_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,31> DIMENSIONMASTER_SD_PARAMETERS_341 = {{
    {"selectioncolor", 8u, 0u, true},
    {"mainalpha_move_u", 5u, 0u, false},
    {"mainalpha_move_v", 5u, 1u, false},
    {"mainalpha_rotator", 5u, 2u, false},
    {"emissive_tex_02_move_u", 3u, 2u, false},
    {"emissive_tex_02_move_v", 3u, 3u, false},
    {"emissive_tex_01_move_u", 2u, 0u, false},
    {"emissive_tex_01_move_v", 2u, 1u, false},
    {"mainalpha_tile_u", 5u, 3u, false},
    {"mainalpha_tile_v", 6u, 0u, false},
    {"uv_noise_panspeed_x", 6u, 1u, false},
    {"uv_noise_tile_u", 6u, 3u, false},
    {"uv_noise_tile_v", 7u, 0u, false},
    {"uv_noise_panspeed_y", 6u, 2u, false},
    {"uv_noise_velue", 7u, 1u, false},
    {"emissive_background_power", 0u, 1u, false},
    {"emissive_background_strength", 0u, 2u, false},
    {"emissive_tex_01_panspeed_x", 2u, 2u, false},
    {"emissive_tex_01_tile_u", 3u, 0u, false},
    {"emissive_tex_01_tile_v", 3u, 1u, false},
    {"emissive_tex_02_panspeed_x", 4u, 0u, false},
    {"emissive_tex_02_tile_u", 4u, 2u, false},
    {"emissive_tex_02_tile_v", 4u, 3u, false},
    {"emissive_tex_02_panspeed_y", 4u, 1u, false},
    {"emissive_noise_velue", 1u, 1u, false},
    {"emissive_tex_01_panspeed_y", 2u, 3u, false},
    {"emissive_power", 1u, 2u, false},
    {"emissive_core_power", 0u, 3u, false},
    {"emissive_core_strength", 1u, 0u, false},
    {"emissive_strength", 1u, 3u, false},
    {"alpha_tex_power", 0u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,6> DIMENSIONMASTER_SD_SWITCHES_341 = {{
    {"use_distortion", false},
    {"use_emissive_tex_02", true},
    {"emissive_tex_(01+02)/2", false},
    {"use_alphatex_type_pola", false},
    {"use_uv_noisetexture", true},
    {"use_emissive_tex02_to_emissive01_uvnoise", true},
}};

constexpr std::array<std::string_view,8> DIMENSIONMASTER_SD_TEXTURES_342 = {{"cracknormal_tex","native_texture_1","in_hole_texture","aura_texture","aura_colormap_tex","native_texture_5","native_texture_6","alpha_tex_02"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,30> DIMENSIONMASTER_SD_PARAMETERS_342 = {{
    {"selectioncolor", 9u, 0u, true},
    {"in_hole_panx", 3u, 2u, false},
    {"in_hole_pany", 3u, 3u, false},
    {"alpha_tile_x", 0u, 0u, false},
    {"alpha_tile_y", 0u, 1u, false},
    {"cracknormal_tile_x", 1u, 1u, false},
    {"cracknormal_tile_y", 1u, 2u, false},
    {"time", 5u, 2u, false},
    {"in_hole_color", 8u, 0u, true},
    {"aura_color", 7u, 0u, true},
    {"distortionpower", 2u, 0u, false},
    {"distortionscale", 2u, 1u, false},
    {"scale", 5u, 1u, false},
    {"cracknormal_str", 1u, 0u, false},
    {"in_hole_crackuv", 2u, 3u, false},
    {"in_hole_height", 3u, 1u, false},
    {"in_hole_pow", 4u, 0u, false},
    {"in_hole_str", 4u, 1u, false},
    {"in_hole_desaturation", 3u, 0u, false},
    {"main_ucoord", 4u, 3u, false},
    {"twist_str", 5u, 3u, false},
    {"main_tex_upanner", 4u, 2u, false},
    {"curve_power", 1u, 3u, false},
    {"main_v_panner", 5u, 0u, false},
    {"uvnoise_utile", 6u, 1u, false},
    {"uvnoise_vtile", 6u, 2u, false},
    {"uvnoise_pan", 6u, 0u, false},
    {"aura_pow", 0u, 2u, false},
    {"aura_str", 0u, 3u, false},
    {"edge_crack_desaturation", 2u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_342 = {{
    {"use_dynamic_vcoord", true},
    {"uvnoise_v_pannertime", true},
    {"main_v_pannertime", false},
    {"main_u_pannertime", false},
    {"use_mesh", false},
}};

constexpr std::array<std::string_view,8> DIMENSIONMASTER_SD_TEXTURES_343 = {{"cracknormal_tex","native_texture_1","in_hole_texture","aura_texture","aura_colormap_tex","native_texture_5","native_texture_6","alpha_tex_02"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,30> DIMENSIONMASTER_SD_PARAMETERS_343 = {{
    {"selectioncolor", 9u, 0u, true},
    {"in_hole_panx", 3u, 2u, false},
    {"in_hole_pany", 3u, 3u, false},
    {"alpha_tile_x", 0u, 0u, false},
    {"alpha_tile_y", 0u, 1u, false},
    {"cracknormal_tile_x", 1u, 1u, false},
    {"cracknormal_tile_y", 1u, 2u, false},
    {"time", 5u, 2u, false},
    {"in_hole_color", 8u, 0u, true},
    {"aura_color", 7u, 0u, true},
    {"distortionpower", 2u, 0u, false},
    {"distortionscale", 2u, 1u, false},
    {"scale", 5u, 1u, false},
    {"cracknormal_str", 1u, 0u, false},
    {"in_hole_crackuv", 2u, 3u, false},
    {"in_hole_height", 3u, 1u, false},
    {"in_hole_pow", 4u, 0u, false},
    {"in_hole_str", 4u, 1u, false},
    {"in_hole_desaturation", 3u, 0u, false},
    {"main_ucoord", 4u, 3u, false},
    {"twist_str", 5u, 3u, false},
    {"main_tex_upanner", 4u, 2u, false},
    {"curve_power", 1u, 3u, false},
    {"main_v_panner", 5u, 0u, false},
    {"uvnoise_utile", 6u, 1u, false},
    {"uvnoise_vtile", 6u, 2u, false},
    {"uvnoise_pan", 6u, 0u, false},
    {"aura_pow", 0u, 2u, false},
    {"aura_str", 0u, 3u, false},
    {"edge_crack_desaturation", 2u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_343 = {{
    {"use_dynamic_vcoord", true},
    {"uvnoise_v_pannertime", true},
    {"main_v_pannertime", false},
    {"main_u_pannertime", false},
    {"use_mesh", false},
}};

constexpr std::array<std::string_view,6> DIMENSIONMASTER_SD_TEXTURES_344 = {{"01_color_tex","01_distort01_tex","01_distort02_tex","01_alpha01_tex","01_alpha02_tex","01_alpha03_tex"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,66> DIMENSIONMASTER_SD_PARAMETERS_344 = {{
    {"selectioncolor", 17u, 0u, true},
    {"03_color_vtile", 2u, 3u, false},
    {"11_color_vdynamicspeed", 13u, 3u, false},
    {"05_color_voffset", 6u, 1u, false},
    {"07_color_vspeed", 8u, 1u, false},
    {"08_color_utwist", 9u, 1u, false},
    {"06_color_uspeed", 7u, 0u, false},
    {"10_color_udynamicspeed", 12u, 1u, false},
    {"04_color_uoffset", 4u, 2u, false},
    {"02_color_utile", 1u, 0u, false},
    {"09_color_vtwist", 10u, 3u, false},
    {"03_distort01_vtile", 3u, 0u, false},
    {"11_distort01_vdynamicspeed", 14u, 0u, false},
    {"05_distort01_voffset", 6u, 2u, false},
    {"08_distort01_utwist", 9u, 2u, false},
    {"10_distort01_udynamicspeed", 12u, 2u, false},
    {"04_distort01_uoffset", 4u, 3u, false},
    {"02_distort01_utile", 1u, 1u, false},
    {"09_distort01_vtwist", 11u, 0u, false},
    {"99_distort01_scale", 15u, 3u, false},
    {"03_distort02_vtile", 3u, 1u, false},
    {"11_distort02_vdynamicspeed", 14u, 1u, false},
    {"05_distort02_voffset", 6u, 3u, false},
    {"08_distort02_utwist", 9u, 3u, false},
    {"10_distort02_udynamicspeed", 12u, 3u, false},
    {"04_distort02_uoffset", 5u, 0u, false},
    {"02_distort02_utile", 1u, 2u, false},
    {"09_distort02_vtwist", 11u, 1u, false},
    {"99_distort02_scale", 16u, 0u, false},
    {"12_color_distortscale", 15u, 1u, false},
    {"13_color_desaturation", 15u, 2u, false},
    {"02_color_power", 0u, 3u, false},
    {"03_color_multiply", 2u, 2u, false},
    {"03_alpha01_vtile", 1u, 3u, false},
    {"11_alpha01_vdynamicspeed", 13u, 0u, false},
    {"05_alpha01_voffset", 5u, 2u, false},
    {"07_a01_vspeed", 7u, 2u, false},
    {"08_alpha01_utwist", 8u, 2u, false},
    {"07_a01_uspeed", 7u, 1u, false},
    {"10_alpha01_udynamicspeed", 11u, 2u, false},
    {"04_alpha01_uoffset", 3u, 2u, false},
    {"02_alpha01_utile", 0u, 0u, false},
    {"09_alpha01_vtwist", 10u, 0u, false},
    {"12_alpha01_distortscale", 14u, 2u, false},
    {"03_alpha02_vtile", 2u, 0u, false},
    {"11_alpha02_vdynamicspeed", 13u, 1u, false},
    {"05_alpha02_voffset", 5u, 3u, false},
    {"07_a02_vspeed", 8u, 0u, false},
    {"08_alpha02_utwist", 8u, 3u, false},
    {"07_a02_uspeed", 7u, 3u, false},
    {"10_alpha02_udynamicspeed", 11u, 3u, false},
    {"04_alpha02_uoffset", 3u, 3u, false},
    {"02_alpha02_utile", 0u, 1u, false},
    {"09_alpha02_vtwist", 10u, 1u, false},
    {"12_alpha02_distortscale", 14u, 3u, false},
    {"03_alpha03_vtile", 2u, 1u, false},
    {"11_alpha03_vdynamicspeed", 13u, 2u, false},
    {"05_alpha03_voffset", 6u, 0u, false},
    {"08_alpha03_utwist", 9u, 0u, false},
    {"10_alpha03_udynamicspeed", 12u, 0u, false},
    {"04_alpha03_uoffset", 4u, 0u, false},
    {"02_alpha03_utile", 0u, 2u, false},
    {"09_alpha03_vtwist", 10u, 2u, false},
    {"12_alpha03_distortscale", 15u, 0u, false},
    {"04_alpha_power", 4u, 1u, false},
    {"05_alpha01_multiply", 5u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,14> DIMENSIONMASTER_SD_SWITCHES_344 = {{
    {"99_use_meshtype", false},
    {"00_usedistort02", true},
    {"usealpha03", true},
    {"alphablend_multiply", true},
    {"00_alphatocolor_multiply", false},
    {"01_usedepth", false},
    {"00_color_usepolaruv", true},
    {"00_alpha01_usepolaruv", true},
    {"00_alpha02_usepolaruv", true},
    {"00_alpha03_usepolaruv", true},
    {"00_distort02_usepolaruv", true},
    {"00_distort01_usepolaruv", true},
    {"00_usefresnel", false},
    {"01_invert", false},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_345 = {{"uv_noise_01_tex","emissive_tex","transition texture"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,16> DIMENSIONMASTER_SD_PARAMETERS_345 = {{
    {"selectioncolor", 4u, 0u, true},
    {"total_scale", 1u, 1u, false},
    {"uv_noise_01_panning_x", 3u, 0u, false},
    {"uv_noise_01_tiling", 3u, 2u, false},
    {"uv_noise_01_panning_y", 3u, 1u, false},
    {"uv_noise_01_intensity", 2u, 3u, false},
    {"emissive_uv_scale_x", 0u, 3u, false},
    {"emissive_uv_scale_y", 1u, 0u, false},
    {"emissive_desaturation", 0u, 0u, false},
    {"emissive_intensity", 0u, 1u, false},
    {"transition_panning_x", 2u, 0u, false},
    {"transition_tiling", 2u, 2u, false},
    {"transition_panning_y", 2u, 1u, false},
    {"transition line thickness", 1u, 2u, false},
    {"emissive_line_intensity", 0u, 2u, false},
    {"transition thickness", 1u, 3u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,6> DIMENSIONMASTER_SD_SWITCHES_345 = {{
    {"non_alpha_chanel", true},
    {"use_distortion", false},
    {"use_fresnel_alpha", false},
    {"use_meshtype", false},
    {"use_polarcoordinate", true},
    {"use_uv_noise_02", false},
}};

constexpr std::array<std::string_view,6> DIMENSIONMASTER_SD_TEXTURES_347 = {{"native_texture_0","cracknormal_tex","colormaptex","native_texture_3","native_texture_4","native_texture_5"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,8> DIMENSIONMASTER_SD_PARAMETERS_347 = {{
    {"selectioncolor", 2u, 0u, true},
    {"alpha_tile_x", 0u, 0u, false},
    {"alpha_tile_y", 0u, 1u, false},
    {"cracknormal_tile_x", 0u, 3u, false},
    {"cracknormal_tile_y", 1u, 0u, false},
    {"time", 1u, 2u, false},
    {"cracknormal_str", 0u, 2u, false},
    {"desaturation", 1u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,0> DIMENSIONMASTER_SD_SWITCHES_347 = {{
}};

constexpr std::array<std::string_view,6> DIMENSIONMASTER_SD_TEXTURES_348 = {{"01.map_f","21.map_bump","06.map","05.map_a","01.groundmap","01.noisemap"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,32> DIMENSIONMASTER_SD_PARAMETERS_348 = {{
    {"selectioncolor", 10u, 0u, true},
    {"19.emissiion_color", 9u, 0u, true},
    {"01.color", 7u, 0u, true},
    {"02.gmap.uv.x", 0u, 1u, false},
    {"03.gmap.uv.y", 1u, 0u, false},
    {"07.specmap_color.", 8u, 0u, true},
    {"09.map_d_panning_x", 4u, 1u, false},
    {"07.map_d_uvscale_r", 3u, 3u, false},
    {"08.map_d_uvscale_g", 4u, 0u, false},
    {"27.map_e_panning_x", 6u, 2u, false},
    {"25.map_e_uvscale_r", 6u, 0u, false},
    {"26.map_e_uvscale_g", 6u, 1u, false},
    {"28.map_e_panning_y", 6u, 3u, false},
    {"23.bumpheight", 5u, 3u, false},
    {"01.depth", 0u, 0u, false},
    {"10.map_d_panning_y", 4u, 3u, false},
    {"05.distort_str", 2u, 2u, false},
    {"04.map_e_panning_x", 1u, 2u, false},
    {"02.map_e_uvscale_r", 0u, 2u, false},
    {"03.map_e_uvscale_g", 1u, 1u, false},
    {"05.map_e_panning_y", 2u, 3u, false},
    {"12.desaturation", 5u, 1u, false},
    {"15.emissiion_power", 5u, 2u, false},
    {"04.str", 1u, 3u, false},
    {"05.power", 3u, 0u, false},
    {"05.desaturation.", 2u, 1u, false},
    {"06.specmap_power.", 3u, 2u, false},
    {"02.nmap.uvscale", 0u, 3u, false},
    {"05.d.power", 2u, 0u, false},
    {"06.d.str", 3u, 1u, false},
    {"09.str", 4u, 2u, false},
    {"10.power", 5u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,7> DIMENSIONMASTER_SD_SWITCHES_348 = {{
    {"06.mapch.r", true},
    {"07.mapch.g", true},
    {"08.mapch.b", true},
    {"01.usemesh", false},
    {"20.use_bumo", true},
    {"00.use_uvdistort", true},
    {"--usespecullar", false},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_349 = {{"02.map_e","06.map","22.map_a"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,24> DIMENSIONMASTER_SD_PARAMETERS_349 = {{
    {"selectioncolor", 7u, 0u, true},
    {"93.emissiion_color", 6u, 0u, true},
    {"22.map_a_uvscale_r", 3u, 2u, false},
    {"23.map_a_uvscale_g", 3u, 3u, false},
    {"time", 5u, 1u, false},
    {"05.map_e_panning_x", 1u, 2u, false},
    {"03.map_e_uvscale_r", 0u, 3u, false},
    {"04.map_e_uvscale_g", 1u, 0u, false},
    {"11.uv.curvature", 3u, 1u, false},
    {"09.map_d_panning_x", 2u, 2u, false},
    {"07.map_d_uvscale_r", 2u, 0u, false},
    {"08.map_d_uvscale_g", 2u, 1u, false},
    {"10.map_d_panning_y", 3u, 0u, false},
    {"05.distort_str", 1u, 1u, false},
    {"06.map_e_panning_y", 1u, 3u, false},
    {"91.desaturation", 4u, 1u, false},
    {"92.emissiion_power", 4u, 2u, false},
    {"02.radius", 0u, 1u, false},
    {"03.hardness", 0u, 2u, false},
    {"09.power", 2u, 3u, false},
    {"24.map_a_panning_x", 4u, 0u, false},
    {"95.str", 4u, 3u, false},
    {"96.power", 5u, 0u, false},
    {"01.depthbiasdalpha_bias", 0u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,27> DIMENSIONMASTER_SD_SWITCHES_349 = {{
    {"00.usespecullar", false},
    {"11.mape+mapf", false},
    {"10.use_mapb", false},
    {"01.use_emissionmap", true},
    {"01.usemesh", false},
    {"05.useinvert", false},
    {"00.usedistortion", false},
    {"01.usesphmask", true},
    {"25.xinvert", false},
    {"20.usetwirl", false},
    {"01.usecoordinate_index1", false},
    {"94.sphmask+(texmap*phasemap)", false},
    {"01.effectonalphatex", false},
    {"11.useclamptexmap", false},
    {"91.mapch.r", true},
    {"92.mapch.g", true},
    {"00.checkisdepthbiasalpha", true},
    {"21.usephasetexmap", true},
    {"30.usefresnal", false},
    {"31.fresnal.invert", false},
    {"00.use_uvdistort", true},
    {"29.usedynamic_ypanning", true},
    {"23.usedynamicstr", false},
    {"93.mapch.b", true},
    {"10.fresnal", true},
    {"99.alphadissolve", false},
    {"94.mapch.a", true},
}};

constexpr std::array<std::string_view,5> DIMENSIONMASTER_SD_TEXTURES_351 = {{"01.map_uv","01.map_e","native_texture_2","01.map_a","11.map_b"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,14> DIMENSIONMASTER_SD_PARAMETERS_351 = {{
    {"selectioncolor", 4u, 0u, true},
    {"19.emissiion_color", 3u, 0u, true},
    {"04.map_e_panning_x", 0u, 3u, false},
    {"02.map_e_uvscale_r", 0u, 1u, false},
    {"03.map_e_uvscale_g", 0u, 2u, false},
    {"05.map_e_panning_y", 1u, 0u, false},
    {"12.desaturation", 1u, 3u, false},
    {"15.emissiion_power", 2u, 1u, false},
    {"09.str", 1u, 1u, false},
    {"10.power", 1u, 2u, false},
    {"12.map_b_uvscale", 2u, 0u, false},
    {"18.str", 2u, 2u, false},
    {"19.power", 2u, 3u, false},
    {"01.depthbiasdalpha_bias", 0u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,8> DIMENSIONMASTER_SD_SWITCHES_351 = {{
    {"00.checkisdepthbiasalpha", true},
    {"01.usemesh", false},
    {"06.mapch.r", true},
    {"07.mapch.g", true},
    {"08.mapch.b", true},
    {"00.useemissionmap", true},
    {"30.usefresnal", false},
    {"31.fresnal.invert", false},
}};

constexpr std::array<std::string_view,1> DIMENSIONMASTER_SD_TEXTURES_352 = {{"15.map_type"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,14> DIMENSIONMASTER_SD_PARAMETERS_352 = {{
    {"selectioncolor", 5u, 0u, true},
    {"01.color.a", 3u, 0u, true},
    {"02.color.b", 4u, 0u, true},
    {"07.map.rotation", 2u, 1u, false},
    {"08.map.rot.variton", 2u, 2u, false},
    {"06.noise_uvscale.x1", 2u, 0u, false},
    {"03.color_lerpstr", 0u, 3u, false},
    {"04.color_lerppow", 1u, 1u, false},
    {"03.low threshold", 1u, 0u, false},
    {"04.gain", 1u, 2u, false},
    {"05.bias", 1u, 3u, false},
    {"01.density", 0u, 0u, false},
    {"02.density_power", 0u, 2u, false},
    {"01.depthbiasdalpha_bias", 0u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,9> DIMENSIONMASTER_SD_SWITCHES_352 = {{
    {"10.usedistancealpha", false},
    {"00.use_depthbiasalpha", true},
    {"16.invert", false},
    {"20.usetimebezire", true},
    {"30.usephase by worldposition", false},
    {"01.self shadow", false},
    {"01.use explode", false},
    {"10.use detailmap", false},
    {"00.usevaricolor", true},
}};

constexpr std::array<std::string_view,2> DIMENSIONMASTER_SD_TEXTURES_360 = {{"uv_noise_tex","emissive_tex"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,10> DIMENSIONMASTER_SD_PARAMETERS_360 = {{
    {"selectioncolor", 3u, 0u, true},
    {"emissive_color&intensity", 2u, 0u, true},
    {"uv_noise_panning_x", 0u, 3u, false},
    {"uv_noise_panning_y", 1u, 0u, false},
    {"uv_panning_x", 1u, 2u, false},
    {"uv_panning_y", 1u, 3u, false},
    {"uv_noise_tilling", 1u, 1u, false},
    {"uv_noise_intensity", 0u, 2u, false},
    {"dynamic_parameter_explanation", 0u, 0u, false},
    {"emissive_tex_desturation", 0u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_360 = {{
    {"use_meshtype", false},
    {"use_subuv_tex", false},
    {"use_nonalpha_tex", false},
    {"use_emissive_vertcolor", false},
    {"use_nonuvnoise", false},
}};

constexpr std::array<std::string_view,5> DIMENSIONMASTER_SD_TEXTURES_361 = {{"uv_noise_texture","alpha_texture1_mask","alpha_texture2","emissive_tex_02","emissive_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,31> DIMENSIONMASTER_SD_PARAMETERS_361 = {{
    {"selectioncolor", 8u, 0u, true},
    {"mainalpha_move_u", 5u, 0u, false},
    {"mainalpha_move_v", 5u, 1u, false},
    {"mainalpha_rotator", 5u, 2u, false},
    {"emissive_tex_02_move_u", 3u, 2u, false},
    {"emissive_tex_02_move_v", 3u, 3u, false},
    {"emissive_tex_01_move_u", 2u, 0u, false},
    {"emissive_tex_01_move_v", 2u, 1u, false},
    {"mainalpha_tile_u", 5u, 3u, false},
    {"mainalpha_tile_v", 6u, 0u, false},
    {"uv_noise_panspeed_x", 6u, 1u, false},
    {"uv_noise_tile_u", 6u, 3u, false},
    {"uv_noise_tile_v", 7u, 0u, false},
    {"uv_noise_panspeed_y", 6u, 2u, false},
    {"uv_noise_velue", 7u, 1u, false},
    {"emissive_background_power", 0u, 1u, false},
    {"emissive_background_strength", 0u, 2u, false},
    {"emissive_tex_01_panspeed_x", 2u, 2u, false},
    {"emissive_tex_01_tile_u", 3u, 0u, false},
    {"emissive_tex_01_tile_v", 3u, 1u, false},
    {"emissive_tex_02_panspeed_x", 4u, 0u, false},
    {"emissive_tex_02_tile_u", 4u, 2u, false},
    {"emissive_tex_02_tile_v", 4u, 3u, false},
    {"emissive_tex_02_panspeed_y", 4u, 1u, false},
    {"emissive_noise_velue", 1u, 1u, false},
    {"emissive_tex_01_panspeed_y", 2u, 3u, false},
    {"emissive_power", 1u, 2u, false},
    {"emissive_core_power", 0u, 3u, false},
    {"emissive_core_strength", 1u, 0u, false},
    {"emissive_strength", 1u, 3u, false},
    {"alpha_tex_power", 0u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,6> DIMENSIONMASTER_SD_SWITCHES_361 = {{
    {"use_distortion", false},
    {"use_emissive_tex_02", true},
    {"emissive_tex_(01+02)/2", false},
    {"use_alphatex_type_pola", false},
    {"use_uv_noisetexture", true},
    {"use_emissive_tex02_to_emissive01_uvnoise", true},
}};

constexpr std::array<std::string_view,6> DIMENSIONMASTER_SD_TEXTURES_362 = {{"00.uvdistort.tex","native_texture_1","01.screentex","21.map_clamp","01.map_a","11.map_b"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,19> DIMENSIONMASTER_SD_PARAMETERS_362 = {{
    {"selectioncolor", 6u, 0u, true},
    {"51.color", 4u, 0u, true},
    {"52.color_gap", 5u, 0u, true},
    {"22.map_c_uvscale_r", 3u, 1u, false},
    {"23.map_c_uvscale_g", 3u, 2u, false},
    {"05.map_u_panning_x", 1u, 3u, false},
    {"03.map_u_uvscale_r", 0u, 3u, false},
    {"04.map_u_uvscale_g", 1u, 1u, false},
    {"06.map_u_panning_y", 2u, 0u, false},
    {"01.uvdistort.str", 0u, 0u, false},
    {"04.map_a_panning_x", 1u, 0u, false},
    {"02.map_a_uvscale_r", 0u, 1u, false},
    {"03.map_a_uvscale_g", 0u, 2u, false},
    {"05.map_a_panning_y", 1u, 2u, false},
    {"14.map_b_panning_x", 2u, 3u, false},
    {"12.map_b_uvscale_r", 2u, 1u, false},
    {"13.map_b_uvscale_g", 2u, 2u, false},
    {"15.map_b_panning_y", 3u, 0u, false},
    {"31.subtract", 3u, 3u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,0> DIMENSIONMASTER_SD_SWITCHES_362 = {{
}};

constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_363 = {{"noise_tex","diff_tex","native_texture_2","opacity_tex"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,26> DIMENSIONMASTER_SD_PARAMETERS_363 = {{
    {"selectioncolor", 9u, 0u, true},
    {"diff_high_color", 6u, 0u, true},
    {"diff_low_color", 7u, 0u, true},
    {"diff_u_tile", 1u, 1u, false},
    {"diff_v_tile", 1u, 2u, false},
    {"noise_u_tile", 2u, 2u, false},
    {"noise_v_tile", 3u, 0u, false},
    {"noise_u_pan", 2u, 1u, false},
    {"noise_v_pan", 2u, 3u, false},
    {"meshemitterdynamicparameter", 8u, 0u, true},
    {"wave_pan_speed", 4u, 3u, false},
    {"diff_rotation", 0u, 2u, false},
    {"opacity_u_tile", 4u, 0u, false},
    {"opacity_v_tile", 4u, 1u, false},
    {"opacity_rotation", 3u, 1u, false},
    {"noise_str", 2u, 0u, false},
    {"diff_u_center", 1u, 0u, false},
    {"wave_tile", 5u, 1u, false},
    {"wave_str", 5u, 0u, false},
    {"wave_noise_str", 4u, 2u, false},
    {"diff_desturation", 0u, 0u, false},
    {"diff_pow", 0u, 1u, false},
    {"diff_str", 0u, 3u, false},
    {"opacity_u_center", 3u, 3u, false},
    {"opacity_str", 3u, 2u, false},
    {"distortion_str", 1u, 3u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,1> DIMENSIONMASTER_SD_SWITCHES_363 = {{
    {"use_mesh", true},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_364 = {{"maintex","uv_noise_tex","dissolve_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,34> DIMENSIONMASTER_SD_PARAMETERS_364 = {{
    {"selectioncolor", 9u, 0u, true},
    {"maintex_rotator", 5u, 1u, false},
    {"maintex_move_x", 4u, 1u, false},
    {"maintex_move_y", 4u, 2u, false},
    {"dissolvetex_rotator", 1u, 3u, false},
    {"edge_color", 8u, 0u, true},
    {"maintex_panspeed_x", 4u, 3u, false},
    {"maintex_tile_x", 5u, 2u, false},
    {"maintex_tile_y", 5u, 3u, false},
    {"maintex_dynamicpan_x_velue", 3u, 3u, false},
    {"maintex_dynamicpan_y_velue", 4u, 0u, false},
    {"maintex_panspeed_y", 5u, 0u, false},
    {"uv_noisetex_pan_x", 7u, 0u, false},
    {"uv_noisetex_tile_x", 7u, 2u, false},
    {"uv_noisetex_tile_y", 7u, 3u, false},
    {"uv_noisetex_pan_y", 7u, 1u, false},
    {"dynamic_uvnoise_x", 2u, 0u, false},
    {"dynamic_uvnoise_y", 2u, 1u, false},
    {"uv_noise_velue", 6u, 3u, false},
    {"emissive_core_power", 3u, 0u, false},
    {"emissive_core_strength", 3u, 1u, false},
    {"emissive_base", 2u, 3u, false},
    {"disslovetex_01_panspeed_x", 0u, 0u, false},
    {"disslovetex_01_tile_x", 0u, 2u, false},
    {"disslovetex_01_tile_y", 0u, 3u, false},
    {"disslovetex_01_panspeed_y", 0u, 1u, false},
    {"dissolvetex_move_x", 1u, 1u, false},
    {"dissolvetex_move_y", 1u, 2u, false},
    {"dissolve_hardness", 1u, 0u, false},
    {"edge_thin", 2u, 2u, false},
    {"spheremask_strength", 6u, 0u, false},
    {"spheremask_strength_max", 6u, 1u, false},
    {"spheremask_strength_min", 6u, 2u, false},
    {"maintex_alpha_strength", 3u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,20> DIMENSIONMASTER_SD_SWITCHES_364 = {{
    {"use_dissolve", true},
    {"use_meshtype", false},
    {"use_uvnoise", true},
    {"achannel_use_uvnoisedynamicpan", true},
    {"use_uv_noise_02", false},
    {"use_uv_noisetex_02", true},
    {"uv_noisetype", true},
    {"maintex_type_polar", false},
    {"maintex_pan_xy", true},
    {"use_dynamic_spheryxy", false},
    {"uv_sphery_y", false},
    {"uv_sphery_x", false},
    {"use_alpha_fresnel", false},
    {"use_dissolvetex_02", false},
    {"use_dissolvetex_noise", false},
    {"use_dissolvetex_noise_type", true},
    {"use_dissolvetex_02_mixtype", true},
    {"use_sphere_alpha", true},
    {"dissloveoutline_multyply_alpha", false},
    {"use_emissivetex02", false},
}};

constexpr std::array<std::string_view,0> DIMENSIONMASTER_SD_TEXTURES_365 = {{}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,2> DIMENSIONMASTER_SD_PARAMETERS_365 = {{
    {"selectioncolor", 1u, 0u, true},
    {"meshemitterdynamicparameter", 0u, 0u, true},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,0> DIMENSIONMASTER_SD_SWITCHES_365 = {{
}};

constexpr std::array<std::string_view,2> DIMENSIONMASTER_SD_TEXTURES_366 = {{"01.map_a","21.map_c"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,16> DIMENSIONMASTER_SD_PARAMETERS_366 = {{
    {"selectioncolor", 5u, 0u, true},
    {"meshemitterdynamicparameter", 4u, 0u, true},
    {"21.uvscale.x", 1u, 1u, false},
    {"22.uvscale.y", 1u, 2u, false},
    {"time", 3u, 1u, false},
    {"04.map_a_panning_x", 0u, 2u, false},
    {"02.map_a_uvscale_r", 0u, 0u, false},
    {"03.map_a_uvscale_g", 0u, 1u, false},
    {"05.map_a_panning_y", 1u, 0u, false},
    {"29.cmap.direct", 1u, 3u, false},
    {"30.cmap.time(rotrate)", 2u, 0u, false},
    {"36.str", 2u, 3u, false},
    {"37.power", 3u, 0u, false},
    {"32.fresnal_power", 2u, 1u, false},
    {"33.fresnal_str", 2u, 2u, false},
    {"05.distortion_str", 0u, 3u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,26> DIMENSIONMASTER_SD_SWITCHES_366 = {{
    {"00.usedistortion", true},
    {"01.usemesh", true},
    {"31.mapch.r", false},
    {"32.mapch.g", false},
    {"20.use_clampmap", true},
    {"25.use_yclamp", true},
    {"00.use_uvdistort", false},
    {"10.use_mapb", false},
    {"00.use_mapa", true},
    {"30.usefresnal", true},
    {"00.checkisdepthbiasalpha", false},
    {"00.use_emission", false},
    {"50.usefresemission", false},
    {"01.use_emissionmap", true},
    {"10.use_mapf", false},
    {"11.map_e + map_f", false},
    {"00.usespecullar", false},
    {"20.usefresspec", false},
    {"40.use_clampmap", false},
    {"48.use_yclamp", false},
    {"41.map_e + map_f", false},
    {"60.twist", false},
    {"60.usedissolveemission", false},
    {"31.fresnal.invert", false},
    {"33.mapch.b", true},
    {"34.mapch.a", true},
}};

constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_367 = {{"02.map_e","01.map_a","11.map_b","21.map_c"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,25> DIMENSIONMASTER_SD_PARAMETERS_367 = {{
    {"selectioncolor", 8u, 0u, true},
    {"93.emissiion_color", 6u, 0u, true},
    {"meshemitterdynamicparameter", 7u, 0u, true},
    {"21.uvscale.x", 3u, 1u, false},
    {"22.uvscale.y", 3u, 2u, false},
    {"time", 5u, 1u, false},
    {"05.map_e_panning_x", 1u, 3u, false},
    {"03.map_e_uvscale_r", 0u, 3u, false},
    {"04.map_e_uvscale_g", 1u, 1u, false},
    {"06.map_e_panning_y", 2u, 0u, false},
    {"91.desaturation", 4u, 3u, false},
    {"92.emissiion_power", 5u, 0u, false},
    {"04.map_a_panning_x", 1u, 0u, false},
    {"02.map_a_uvscale_r", 0u, 1u, false},
    {"03.map_a_uvscale_g", 0u, 2u, false},
    {"05.map_a_panning_y", 1u, 2u, false},
    {"14.map_b_panning_x", 2u, 3u, false},
    {"12.map_b_uvscale_r", 2u, 1u, false},
    {"13.map_b_uvscale_g", 2u, 2u, false},
    {"15.map_b_panning_y", 3u, 0u, false},
    {"29.cmap.direct", 3u, 3u, false},
    {"30.cmap.time(rotrate)", 4u, 0u, false},
    {"36.str", 4u, 1u, false},
    {"37.power", 4u, 2u, false},
    {"01.depthbiasdalpha_bias", 0u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,26> DIMENSIONMASTER_SD_SWITCHES_367 = {{
    {"00.usedistortion", false},
    {"01.usemesh", true},
    {"31.mapch.r", true},
    {"32.mapch.g", true},
    {"20.use_clampmap", true},
    {"25.use_yclamp", false},
    {"00.use_uvdistort", false},
    {"10.use_mapb", true},
    {"00.use_mapa", true},
    {"30.usefresnal", false},
    {"00.checkisdepthbiasalpha", true},
    {"00.use_emission", true},
    {"50.usefresemission", false},
    {"01.use_emissionmap", true},
    {"10.use_mapf", false},
    {"11.map_e + map_f", false},
    {"00.usespecullar", false},
    {"20.usefresspec", false},
    {"40.use_clampmap", false},
    {"48.use_yclamp", false},
    {"41.map_e + map_f", false},
    {"60.twist", false},
    {"60.usedissolveemission", false},
    {"31.fresnal.invert", false},
    {"33.mapch.b", true},
    {"34.mapch.a", true},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_368 = {{"14.map_d","01.map_a","06.map_b"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,20> DIMENSIONMASTER_SD_PARAMETERS_368 = {{
    {"selectioncolor", 5u, 0u, true},
    {"power", 4u, 1u, false},
    {"str", 4u, 2u, false},
    {"04.map_a_panning_x", 1u, 2u, false},
    {"02.map_a_uvscale_r", 0u, 3u, false},
    {"03.map_a_uvscale_g", 1u, 1u, false},
    {"17.map_d_panning_x", 3u, 3u, false},
    {"15.map_d_uvscale_r", 3u, 1u, false},
    {"16.map_d_uvscale_g", 3u, 2u, false},
    {"18.map_d_panning_y", 4u, 0u, false},
    {"13.distortstr", 3u, 0u, false},
    {"05.map_a_panning_y", 1u, 3u, false},
    {"09.map_b_panning_x", 2u, 2u, false},
    {"07.map_b_uvscale_r", 2u, 0u, false},
    {"08.map_b_uvscale_g", 2u, 1u, false},
    {"10.map_b_panning_y", 2u, 3u, false},
    {"00.noisepower", 0u, 0u, false},
    {"00.noisestr", 0u, 1u, false},
    {"01.range", 0u, 2u, false},
    {"02.power", 1u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_368 = {{
    {"--usefakedepthbiasalpha", true},
    {"checkisdepthbiasalpha", false},
    {"00.checkisnoiseon", true},
    {"12.uvnoise", true},
    {"11.uvmirroring", false},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_369 = {{"maintex","uv_noise_tex","dissolve_tex_01"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,34> DIMENSIONMASTER_SD_PARAMETERS_369 = {{
    {"selectioncolor", 9u, 0u, true},
    {"maintex_rotator", 5u, 1u, false},
    {"maintex_move_x", 4u, 1u, false},
    {"maintex_move_y", 4u, 2u, false},
    {"dissolvetex_rotator", 1u, 3u, false},
    {"edge_color", 8u, 0u, true},
    {"maintex_panspeed_x", 4u, 3u, false},
    {"maintex_tile_x", 5u, 2u, false},
    {"maintex_tile_y", 5u, 3u, false},
    {"maintex_dynamicpan_x_velue", 3u, 3u, false},
    {"maintex_dynamicpan_y_velue", 4u, 0u, false},
    {"maintex_panspeed_y", 5u, 0u, false},
    {"uv_noisetex_pan_x", 7u, 0u, false},
    {"uv_noisetex_tile_x", 7u, 2u, false},
    {"uv_noisetex_tile_y", 7u, 3u, false},
    {"uv_noisetex_pan_y", 7u, 1u, false},
    {"dynamic_uvnoise_x", 2u, 0u, false},
    {"dynamic_uvnoise_y", 2u, 1u, false},
    {"uv_noise_velue", 6u, 3u, false},
    {"emissive_core_power", 3u, 0u, false},
    {"emissive_core_strength", 3u, 1u, false},
    {"emissive_base", 2u, 3u, false},
    {"disslovetex_01_panspeed_x", 0u, 0u, false},
    {"disslovetex_01_tile_x", 0u, 2u, false},
    {"disslovetex_01_tile_y", 0u, 3u, false},
    {"disslovetex_01_panspeed_y", 0u, 1u, false},
    {"dissolvetex_move_x", 1u, 1u, false},
    {"dissolvetex_move_y", 1u, 2u, false},
    {"dissolve_hardness", 1u, 0u, false},
    {"edge_thin", 2u, 2u, false},
    {"spheremask_strength", 6u, 0u, false},
    {"spheremask_strength_max", 6u, 1u, false},
    {"spheremask_strength_min", 6u, 2u, false},
    {"maintex_alpha_strength", 3u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,20> DIMENSIONMASTER_SD_SWITCHES_369 = {{
    {"use_dissolve", true},
    {"use_meshtype", false},
    {"use_uvnoise", true},
    {"achannel_use_uvnoisedynamicpan", true},
    {"use_uv_noise_02", false},
    {"use_uv_noisetex_02", true},
    {"uv_noisetype", true},
    {"maintex_type_polar", false},
    {"maintex_pan_xy", true},
    {"use_dynamic_spheryxy", false},
    {"uv_sphery_y", false},
    {"uv_sphery_x", false},
    {"use_alpha_fresnel", false},
    {"use_dissolvetex_02", false},
    {"use_dissolvetex_noise", false},
    {"use_dissolvetex_noise_type", true},
    {"use_dissolvetex_02_mixtype", true},
    {"use_sphere_alpha", true},
    {"dissloveoutline_multyply_alpha", false},
    {"use_emissivetex02", false},
}};

constexpr std::array<std::string_view,1> DIMENSIONMASTER_SD_TEXTURES_370 = {{"15.map_type"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,14> DIMENSIONMASTER_SD_PARAMETERS_370 = {{
    {"selectioncolor", 5u, 0u, true},
    {"01.color.a", 3u, 0u, true},
    {"02.color.b", 4u, 0u, true},
    {"07.map.rotation", 2u, 1u, false},
    {"08.map.rot.variton", 2u, 2u, false},
    {"06.noise_uvscale.x1", 2u, 0u, false},
    {"03.color_lerpstr", 0u, 3u, false},
    {"04.color_lerppow", 1u, 1u, false},
    {"03.low threshold", 1u, 0u, false},
    {"04.gain", 1u, 2u, false},
    {"05.bias", 1u, 3u, false},
    {"01.density", 0u, 0u, false},
    {"02.density_power", 0u, 2u, false},
    {"01.depthbiasdalpha_bias", 0u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,9> DIMENSIONMASTER_SD_SWITCHES_370 = {{
    {"10.usedistancealpha", false},
    {"00.use_depthbiasalpha", true},
    {"16.invert", true},
    {"20.usetimebezire", true},
    {"30.usephase by worldposition", false},
    {"01.self shadow", false},
    {"01.use explode", false},
    {"10.use detailmap", false},
    {"00.usevaricolor", true},
}};

constexpr std::array<std::string_view,0> DIMENSIONMASTER_SD_TEXTURES_371 = {{}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,6> DIMENSIONMASTER_SD_PARAMETERS_371 = {{
    {"selectioncolor", 2u, 0u, true},
    {"10.radius", 1u, 0u, false},
    {"04.ringthickness", 0u, 1u, false},
    {"05.shapehardness", 0u, 2u, false},
    {"07.power", 0u, 3u, false},
    {"01.depthbiasdalpha_bias", 0u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,8> DIMENSIONMASTER_SD_SWITCHES_371 = {{
    {"00.alphamap", false},
    {"20.usehemisphere", false},
    {"00.useemissioncolor", false},
    {"00.checkisdepthbiasalpha", true},
    {"01.usesoftshape", false},
    {"02.useouthardness", false},
    {"00.use_uvdistort", false},
    {"00.usedistortion", false},
}};

constexpr std::array<std::string_view,1> DIMENSIONMASTER_SD_TEXTURES_372 = {{"flow_texture"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,12> DIMENSIONMASTER_SD_PARAMETERS_372 = {{
    {"selectioncolor", 4u, 0u, true},
    {"flow_rot", 1u, 0u, false},
    {"edge_color", 3u, 0u, true},
    {"core_radius", 0u, 0u, false},
    {"flow_tile_u", 1u, 2u, false},
    {"flow_tile_v", 1u, 3u, false},
    {"flow_offset_x", 0u, 2u, false},
    {"flow_offset_y", 0u, 3u, false},
    {"flow_str", 1u, 1u, false},
    {"threshold", 2u, 1u, false},
    {"thickness", 2u, 0u, false},
    {"emissive_pow", 0u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_372 = {{
    {"pan_x_dyn", false},
    {"pan_x_use", false},
    {"pan_y_use", false},
    {"use_depth", false},
    {"use_radial", false},
}};

constexpr std::array<std::string_view,1> DIMENSIONMASTER_SD_TEXTURES_373 = {{"15.map_type"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,18> DIMENSIONMASTER_SD_PARAMETERS_373 = {{
    {"selectioncolor", 7u, 0u, true},
    {"07.map.rotation", 2u, 3u, false},
    {"21.timescale", 3u, 1u, false},
    {"08.map.rot.variton", 3u, 0u, false},
    {"04.color", 6u, 0u, true},
    {"01.color.a", 4u, 0u, true},
    {"02.color.b", 5u, 0u, true},
    {"06.noise_uvscale.x1", 2u, 2u, false},
    {"02.multiplier", 0u, 3u, false},
    {"03.falloff", 1u, 1u, false},
    {"03.color_lerpstr", 1u, 0u, false},
    {"04.color_lerppow", 1u, 3u, false},
    {"03.low threshold", 1u, 2u, false},
    {"04.gain", 2u, 0u, false},
    {"05.bias", 2u, 1u, false},
    {"01.density", 0u, 0u, false},
    {"02.density_power", 0u, 2u, false},
    {"01.depthbiasdalpha_bias", 0u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,9> DIMENSIONMASTER_SD_SWITCHES_373 = {{
    {"16.invert", true},
    {"20.usetimebezire", false},
    {"30.usephase by worldposition", false},
    {"01.self shadow", false},
    {"00.usevaricolor", true},
    {"01.use explode", true},
    {"10.use detailmap", false},
    {"00.use_depthbiasalpha", true},
    {"10.usedistancealpha", false},
}};

constexpr std::array<std::string_view,7> DIMENSIONMASTER_SD_TEXTURES_375 = {{"native_texture_0","noise02_texture","noise01_flow_texture","noise01_texture","diffuse_tex","native_texture_5","gradientmap"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,24> DIMENSIONMASTER_SD_PARAMETERS_375 = {{
    {"selectioncolor", 7u, 0u, true},
    {"holocolor", 6u, 0u, true},
    {"diffuse_tile_x", 1u, 0u, false},
    {"diffuse_tile_y", 1u, 1u, false},
    {"diffuse_offset_x", 0u, 1u, false},
    {"diffuse_offset_y", 0u, 2u, false},
    {"rot_speed", 4u, 1u, false},
    {"noise02_movetime_str", 3u, 3u, false},
    {"noise02_str", 4u, 0u, false},
    {"diffuse_texsize", 0u, 3u, false},
    {"noise01_movetime_str", 3u, 1u, false},
    {"noise01_str", 3u, 2u, false},
    {"rot_str", 4u, 2u, false},
    {"colorizealpha", 0u, 0u, false},
    {"timevariable", 4u, 3u, false},
    {"flickeringalpha", 1u, 2u, false},
    {"linevalue", 2u, 2u, false},
    {"x_speed", 5u, 0u, false},
    {"y_speed", 5u, 1u, false},
    {"highvalue", 2u, 1u, false},
    {"lowvalue", 3u, 0u, false},
    {"globalopacity", 1u, 3u, false},
    {"lowopacity", 2u, 3u, false},
    {"gra_pow", 2u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_375 = {{
    {"opa_clamp", false},
    {"use_diff_tex_alphachannel", false},
    {"use_mesh", false},
    {"use_meshsoftedge", false},
    {"use_texedgerot", true},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_389 = {{"14.map_d","01.map_a","06.map_b"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,19> DIMENSIONMASTER_SD_PARAMETERS_389 = {{
    {"selectioncolor", 6u, 0u, true},
    {"noisecolor", 5u, 0u, true},
    {"15.map_d_uvscale_r", 2u, 3u, false},
    {"16.map_d_uvscale_g", 3u, 0u, false},
    {"02.map_a_uvscale_r", 0u, 2u, false},
    {"03.map_a_uvscale_g", 1u, 0u, false},
    {"04.map_a_panning_x", 1u, 2u, false},
    {"05.map_a_panning_y", 2u, 0u, false},
    {"02.map_b_uvscale_r", 0u, 3u, false},
    {"03.map_b_uvscale_g", 1u, 1u, false},
    {"04.map_b_panning_x", 1u, 3u, false},
    {"05.map_b_panning_y", 2u, 1u, false},
    {"power", 3u, 3u, false},
    {"13.distortstr", 2u, 2u, false},
    {"00.noisepower", 0u, 0u, false},
    {"00.noisestr", 0u, 1u, false},
    {"biasvalue", 3u, 1u, false},
    {"str", 4u, 0u, false},
    {"depthbiasdalpha_bias", 3u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,6> DIMENSIONMASTER_SD_SWITCHES_389 = {{
    {"checkisdepthbiasalpha", true},
    {"00.checkisnoiseon", true},
    {"12.uvnoise", true},
    {"11.uvmirroring", false},
    {"use_meshtype", false},
    {"use_multyply_noisecolor", false},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_390 = {{"14.map_d","01.map_a","06.map_b"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,24> DIMENSIONMASTER_SD_PARAMETERS_390 = {{
    {"selectioncolor", 7u, 0u, true},
    {"02.color_a", 6u, 0u, true},
    {"11.direct", 2u, 2u, false},
    {"04.map_a_panning_x", 1u, 0u, false},
    {"02.map_a_uvscale_r", 0u, 2u, false},
    {"03.map_a_uvscale_g", 0u, 3u, false},
    {"17.map_d_panning_x", 4u, 2u, false},
    {"15.map_d_uvscale_r", 4u, 0u, false},
    {"16.map_d_uvscale_g", 4u, 1u, false},
    {"18.map_d_panning_y", 4u, 3u, false},
    {"13.distortstr", 3u, 3u, false},
    {"05.map_a_panning_y", 1u, 1u, false},
    {"09.map_b_panning_x", 2u, 0u, false},
    {"07.map_b_uvscale_r", 1u, 2u, false},
    {"08.map_b_uvscale_g", 1u, 3u, false},
    {"10.map_b_panning_y", 2u, 1u, false},
    {"31.noisepower", 5u, 0u, false},
    {"32.noisestr", 5u, 1u, false},
    {"11.width.power", 3u, 0u, false},
    {"12.width.strength", 3u, 2u, false},
    {"01.height.power", 0u, 0u, false},
    {"02.height.strength", 0u, 1u, false},
    {"11.range", 2u, 3u, false},
    {"12.power", 3u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,12> DIMENSIONMASTER_SD_SWITCHES_390 = {{
    {"01.useconeuv", false},
    {"01.usemesh", false},
    {"00.blendingadd", false},
    {"30.usefresnal", false},
    {"00.usenoise", true},
    {"30.use((map_a+map_b)*0.5)", true},
    {"00.usecolor", true},
    {"00z.usemapcolor", false},
    {"01.usenoise", false},
    {"00.checkisdepthbiasalpha", false},
    {"10.usefakedepthbiasalpha", true},
    {"00.useuvnoise", true},
}};

constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_391 = {{"flowtex","diff_tex1","diff_tex2","opacity_tex"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,27> DIMENSIONMASTER_SD_PARAMETERS_391 = {{
    {"selectioncolor", 8u, 0u, true},
    {"diff_backcolor", 6u, 0u, true},
    {"flow_tile_u", 3u, 3u, false},
    {"flow_tile_v", 4u, 0u, false},
    {"flow_pan_u", 3u, 1u, false},
    {"flow_pan_v", 3u, 2u, false},
    {"meshemitterdynamicparameter", 7u, 0u, true},
    {"diff1_pan_u", 0u, 1u, false},
    {"diff1_pan_v", 0u, 2u, false},
    {"diff2_pan_u", 1u, 1u, false},
    {"diff2_pan_v", 1u, 2u, false},
    {"opacity_tile_u", 5u, 2u, false},
    {"opacity_tile_v", 5u, 3u, false},
    {"opacity_rot", 5u, 0u, false},
    {"diff1_tile_v", 1u, 0u, false},
    {"diff1_tile_u", 0u, 3u, false},
    {"flow_bias", 3u, 0u, false},
    {"diff2_tile_v", 2u, 0u, false},
    {"diff2_tile_u", 1u, 3u, false},
    {"diff_des", 2u, 1u, false},
    {"diff_pow", 2u, 2u, false},
    {"diff_str", 2u, 3u, false},
    {"cameravec_pow", 0u, 0u, false},
    {"opacity_distort_str", 4u, 2u, false},
    {"gra_pow", 4u, 1u, false},
    {"opacity_pow", 4u, 3u, false},
    {"opacity_str", 5u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_391 = {{
    {"use_gra_r_channel", false},
    {"use_colormap", false},
    {"diff_pan_use_u", false},
    {"use_cam_vector", true},
    {"use_distortion", false},
}};

constexpr std::array<std::string_view,6> DIMENSIONMASTER_SD_TEXTURES_392 = {{"diff_tex","a_mask_tex","a_noise_01_tex","b_mask_tex","b_noise_01_tex","dissolve_tex"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,56> DIMENSIONMASTER_SD_PARAMETERS_392 = {{
    {"selectioncolor", 16u, 0u, true},
    {"meshemitterdynamicparameter", 15u, 0u, true},
    {"a_rotator", 3u, 1u, false},
    {"a_noise_01_tile_u", 2u, 1u, false},
    {"a_noise_01_tile_v", 2u, 2u, false},
    {"a_noise_01_pan_x", 1u, 2u, false},
    {"a_noise_01_offset_x", 1u, 0u, false},
    {"a_noise_01_pan_y", 1u, 3u, false},
    {"a_noise_01_offset_y", 1u, 1u, false},
    {"a_mask_color", 13u, 0u, true},
    {"b_rotator", 7u, 2u, false},
    {"b_noise_01_tile_u", 6u, 2u, false},
    {"b_noise_01_tile_v", 6u, 3u, false},
    {"b_noise_01_pan_x", 5u, 3u, false},
    {"b_noise_01_offset_x", 5u, 1u, false},
    {"b_noise_01_pan_y", 6u, 0u, false},
    {"b_noise_01_offset_y", 5u, 2u, false},
    {"b_mask_color", 14u, 0u, true},
    {"dissolve_rot", 10u, 2u, false},
    {"diff_tile_u", 9u, 1u, false},
    {"diff_tile_v", 9u, 2u, false},
    {"diff_tex_desaturation", 9u, 0u, false},
    {"a_sizecontrol", 3u, 2u, false},
    {"a_tile_u", 3u, 3u, false},
    {"a_tile_v", 4u, 0u, false},
    {"a_offset_x", 2u, 3u, false},
    {"a_offset_y", 3u, 0u, false},
    {"a_noise_01_str", 2u, 0u, false},
    {"b_mask_debug(0or1)", 4u, 1u, false},
    {"a_mask_str", 0u, 3u, false},
    {"a_mask_pow", 0u, 2u, false},
    {"a_mask_desaturation", 0u, 1u, false},
    {"b_sizecontrol", 7u, 3u, false},
    {"b_tile_u", 8u, 0u, false},
    {"b_tile_v", 8u, 1u, false},
    {"b_offset_x", 7u, 0u, false},
    {"b_offset_y", 7u, 1u, false},
    {"b_noise_01_str", 6u, 1u, false},
    {"a_mask_debug(0or1)", 0u, 0u, false},
    {"b_mask_str", 5u, 0u, false},
    {"b_mask_pow", 4u, 3u, false},
    {"b_mask_desaturation", 4u, 2u, false},
    {"diff_str", 8u, 3u, false},
    {"diff_pow", 8u, 2u, false},
    {"mask_linearalpha", 11u, 3u, false},
    {"opacity_pow", 12u, 2u, false},
    {"opacity_str", 12u, 3u, false},
    {"mask_radius", 12u, 0u, false},
    {"mask_density", 11u, 2u, false},
    {"dissolve_pan_x", 10u, 0u, false},
    {"dissolve_tile_x", 10u, 3u, false},
    {"dissolve_tile_y", 11u, 0u, false},
    {"dissolve_pan_y", 10u, 1u, false},
    {"dissolve_hardness", 9u, 3u, false},
    {"meshedgefade", 12u, 1u, false},
    {"distortion", 11u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,21> DIMENSIONMASTER_SD_SWITCHES_392 = {{
    {"meshtype_use", true},
    {"mesh_billboard_use", false},
    {"depthalpha_use", false},
    {"meshedge_soft_use", false},
    {"coresoft_use", false},
    {"width_height_use", false},
    {"mask_compose", false},
    {"b_sizecontrol_dyuse", false},
    {"nonpolar_mask_b", true},
    {"b_pan_y_use", false},
    {"b_pan_x_dynuse", false},
    {"b_pan_x_use", false},
    {"a_sizecontrol_dyuse", false},
    {"nonpolar_mask_a", true},
    {"a_pan_y_use", false},
    {"a_pan_x_dynuse", false},
    {"a_pan_x_use", false},
    {"diff_polar_use", false},
    {"diff_pan_y_use", false},
    {"diff_pan_x_use", false},
    {"dissolve_use", true},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_393 = {{"hade_tex","emit tex2","native_texture_2"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,10> DIMENSIONMASTER_SD_PARAMETERS_393 = {{
    {"selectioncolor", 3u, 0u, true},
    {"power", 1u, 2u, false},
    {"worldtex_u", 1u, 3u, false},
    {"worldtex_v", 2u, 0u, false},
    {"0_map_emit_str", 0u, 1u, false},
    {"emissive_str", 1u, 0u, false},
    {"0_map_emit_power", 0u, 0u, false},
    {"centerhole_power", 0u, 3u, false},
    {"mask_str", 1u, 1u, false},
    {"3_distort_str", 0u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,19> DIMENSIONMASTER_SD_SWITCHES_393 = {{
    {"0_checkisdistort", true},
    {"1_1checkiscamdistance", false},
    {"2_checkisdiststrbezier", false},
    {"4_checkisdistortmap", false},
    {"checkisfresnelmask", false},
    {"0_checkismaptomask", false},
    {"checkispolarcoor", true},
    {"checkiscenterhole", true},
    {"5_checkisuvdistort", false},
    {"00.useuvdistort", true},
    {"6_checkis_x_panner", false},
    {"7_checkisdisttimebezier", false},
    {"checkismeshemitvc", false},
    {"1_1checkisuv", false},
    {"1_2checkisuv", false},
    {"1_3checkisuv", false},
    {"checkisdepthbiasalpha", false},
    {"checkisemissionvariation", false},
    {"hade_powerdy", false},
}};

constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_394 = {{"flowtex","diff_tex1","diff_tex2","opacity_tex"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,27> DIMENSIONMASTER_SD_PARAMETERS_394 = {{
    {"selectioncolor", 8u, 0u, true},
    {"diff_backcolor", 6u, 0u, true},
    {"flow_tile_u", 3u, 3u, false},
    {"flow_tile_v", 4u, 0u, false},
    {"flow_pan_u", 3u, 1u, false},
    {"flow_pan_v", 3u, 2u, false},
    {"meshemitterdynamicparameter", 7u, 0u, true},
    {"diff1_pan_u", 0u, 1u, false},
    {"diff1_pan_v", 0u, 2u, false},
    {"diff2_pan_u", 1u, 1u, false},
    {"diff2_pan_v", 1u, 2u, false},
    {"opacity_tile_u", 5u, 2u, false},
    {"opacity_tile_v", 5u, 3u, false},
    {"opacity_rot", 5u, 0u, false},
    {"diff1_tile_v", 1u, 0u, false},
    {"diff1_tile_u", 0u, 3u, false},
    {"flow_bias", 3u, 0u, false},
    {"diff2_tile_v", 2u, 0u, false},
    {"diff2_tile_u", 1u, 3u, false},
    {"diff_des", 2u, 1u, false},
    {"diff_pow", 2u, 2u, false},
    {"diff_str", 2u, 3u, false},
    {"cameravec_pow", 0u, 0u, false},
    {"opacity_distort_str", 4u, 2u, false},
    {"gra_pow", 4u, 1u, false},
    {"opacity_pow", 4u, 3u, false},
    {"opacity_str", 5u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_394 = {{
    {"use_gra_r_channel", false},
    {"use_colormap", false},
    {"diff_pan_use_u", false},
    {"use_cam_vector", true},
    {"use_distortion", false},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_395 = {{"tex_uvnoise_01","tex_alpha_01","tex_alpha_02"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,16> DIMENSIONMASTER_SD_PARAMETERS_395 = {{
    {"selectioncolor", 4u, 0u, true},
    {"tex_alpha_move_u", 2u, 0u, false},
    {"tex_alpha_move_v", 2u, 1u, false},
    {"tex_alpha_01_rotator", 1u, 2u, false},
    {"tex_alpha_01_r_tile", 1u, 1u, false},
    {"tex_alpha_01_g_tile", 1u, 0u, false},
    {"tex_flow_r_tile", 3u, 1u, false},
    {"tex_flow_g_tile", 3u, 0u, false},
    {"tex_noise_velue", 3u, 2u, false},
    {"tex_alpha_power", 2u, 3u, false},
    {"tex_alpha_multiply", 2u, 2u, false},
    {"tex_alpha_backvelue", 1u, 3u, false},
    {"center_hole_size", 0u, 2u, false},
    {"center_hole_hardness", 0u, 0u, false},
    {"center_hole_power", 0u, 1u, false},
    {"disto_velue", 0u, 3u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,2> DIMENSIONMASTER_SD_SWITCHES_395 = {{
    {"use_alpha_02_tile", false},
    {"use_disto", true},
}};

constexpr std::array<std::string_view,3> DIMENSIONMASTER_SD_TEXTURES_396 = {{"tex_uvnoise_01","tex_alpha_01","tex_alpha_02"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,17> DIMENSIONMASTER_SD_PARAMETERS_396 = {{
    {"selectioncolor", 4u, 0u, true},
    {"tex_alpha_move_u", 2u, 1u, false},
    {"tex_alpha_move_v", 2u, 2u, false},
    {"tex_alpha_01_rotator", 1u, 1u, false},
    {"tex_alpha_01_r_tile", 1u, 0u, false},
    {"tex_alpha_01_g_tile", 0u, 3u, false},
    {"tex_flow_r_tile", 3u, 2u, false},
    {"tex_flow_g_tile", 3u, 1u, false},
    {"tex_noise_velue", 3u, 3u, false},
    {"tex_alpha_02_r_tile", 1u, 3u, false},
    {"tex_alpha_02_g_tile", 1u, 2u, false},
    {"tex_alpha_power", 3u, 0u, false},
    {"tex_alpha_multiply", 2u, 3u, false},
    {"tex_alpha_backvelue", 2u, 0u, false},
    {"center_hole_size", 0u, 2u, false},
    {"center_hole_hardness", 0u, 0u, false},
    {"center_hole_power", 0u, 1u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,2> DIMENSIONMASTER_SD_SWITCHES_396 = {{
    {"use_disto", false},
    {"use_alpha_02_tile", true},
}};

constexpr std::array<std::string_view,2> DIMENSIONMASTER_SD_TEXTURES_397 = {{"diff_texture","lighttexture"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,9> DIMENSIONMASTER_SD_PARAMETERS_397 = {{
    {"selectioncolor", 2u, 0u, true},
    {"diff_tilleing", 0u, 2u, false},
    {"desaturation", 0u, 1u, false},
    {"light_brightness", 1u, 0u, false},
    {"light_hardness", 1u, 1u, false},
    {"emissive_pow", 0u, 3u, false},
    {"opacity_radial", 1u, 2u, false},
    {"opacity_str", 1u, 3u, false},
    {"depth", 0u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,2> DIMENSIONMASTER_SD_SWITCHES_397 = {{
    {"use_light_1_vectorangle", false},
    {"use_light_2_vectorangle", true},
}};

constexpr std::array<std::string_view,4> DIMENSIONMASTER_SD_TEXTURES_399 = {{"diff_texture","flow_texture","flow_uvoffsettexture","main_texture"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,46> DIMENSIONMASTER_SD_PARAMETERS_399 = {{
    {"selectioncolor", 12u, 0u, true},
    {"flow_tile_x", 5u, 2u, false},
    {"flow_tile_y", 5u, 3u, false},
    {"flow_offset_x", 4u, 1u, false},
    {"flow_offset_y", 4u, 2u, false},
    {"flow_pan_x", 4u, 3u, false},
    {"flow_pan_y", 5u, 0u, false},
    {"flow_rot", 5u, 1u, false},
    {"uvoffset_tile_x", 10u, 2u, false},
    {"uvoffset_tile_y", 10u, 3u, false},
    {"uvoffset_offset_x", 9u, 0u, false},
    {"uvoffset_offset_y", 9u, 1u, false},
    {"uvoffset_pan_x", 9u, 2u, false},
    {"uvoffset_pan_y", 9u, 3u, false},
    {"uvoffset_rot", 10u, 0u, false},
    {"diff_tile_x", 3u, 2u, false},
    {"diff_tile_y", 3u, 3u, false},
    {"diff_rot", 3u, 0u, false},
    {"diff_color", 11u, 0u, true},
    {"main_tile_x", 7u, 2u, false},
    {"main_tile_y", 7u, 3u, false},
    {"main_rot", 7u, 1u, false},
    {"uvoffset_str", 10u, 1u, false},
    {"diff_flowstr", 2u, 0u, false},
    {"diff_dypan_x", 1u, 2u, false},
    {"diff_offset_x", 2u, 1u, false},
    {"diff_dypan_y", 1u, 3u, false},
    {"diff_offset_y", 2u, 2u, false},
    {"diff_pow", 2u, 3u, false},
    {"diff_str", 3u, 1u, false},
    {"diff_desaturation", 1u, 1u, false},
    {"flowstr", 6u, 0u, false},
    {"main_dypan_x", 6u, 1u, false},
    {"main_offset_x", 6u, 3u, false},
    {"main_dypan_y", 6u, 2u, false},
    {"main_offset_y", 7u, 0u, false},
    {"mask_pow", 8u, 0u, false},
    {"mask_str", 8u, 1u, false},
    {"spheremask_radius", 8u, 2u, false},
    {"spheremask_str", 8u, 3u, false},
    {"coreglow_radius", 0u, 0u, false},
    {"coreglow_str", 0u, 1u, false},
    {"coreopacity_radius", 0u, 3u, false},
    {"coreopacity_pow", 0u, 2u, false},
    {"coreopacity_str", 1u, 0u, false},
    {"distortion", 4u, 0u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,13> DIMENSIONMASTER_SD_SWITCHES_399 = {{
    {"use_diff_dypan", true},
    {"use_coreglow", true},
    {"use_widthmask", false},
    {"use_heightmask", false},
    {"use_spheremask", true},
    {"use_uvvolumesphere", false},
    {"use_adddiffuse", true},
    {"use_mesh", false},
    {"use_transition", false},
    {"use_transition_polar", false},
    {"use_mask_polar", true},
    {"use_coreopacity", true},
    {"use_depth", false},
}};

constexpr std::array<std::string_view,1> DIMENSIONMASTER_SD_TEXTURES_374 = {{"detail texture"}};
constexpr std::array<DIMENSIONMASTER_SD_PARAMETER_DESC,5> DIMENSIONMASTER_SD_PARAMETERS_374 = {{
    {"selectioncolor", 1u, 0u, true},
    {"wave amplitude", 0u, 3u, false},
    {"cyclenum01", 0u, 0u, false},
    {"cyclenum02", 0u, 1u, false},
    {"line thickness", 0u, 2u, false},
}};
constexpr std::array<DIMENSIONMASTER_SD_SWITCH_DESC,5> DIMENSIONMASTER_SD_SWITCHES_374 = {{
    {"use_centerdistortion", true},
    {"use_detaildistortion", true},
    {"use_texture", true},
    {"use_tworing", true},
    {"use_wavering", true},
}};

constexpr std::array<DIMENSIONMASTER_SD_PROGRAM_DESC,49> DIMENSIONMASTER_SD_PROGRAM_STORAGE = {{
    {320u,"effect.ue3.sd-320-native.v1","fx_m_mi_01.fx_mi.fx_e_pa_gl_10_1_tr","fx_mastermaterial.fx_mm.fx_mm_maskcontrol_01_tr","ue3.material.fx.mastermaterial.fx.mm.fx.mm.maskcontrol.01.tr.30a3b56d23fe",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_320,DIMENSIONMASTER_SD_PARAMETERS_320,DIMENSIONMASTER_SD_SWITCHES_320},
    {321u,"effect.ue3.sd-321-native.v1","fx_m_mi_r_00.fx_mi.fx_r_pa_spritewave_24_02_tr","fx_m_mi_m_00.fx_m.fx_m_pa_spritewave_01_tr","ue3.material.fx.m.mi.m.00.fx.m.fx.m.pa.spritewave.01.tr.21401ca3cd92",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_321,DIMENSIONMASTER_SD_PARAMETERS_321,DIMENSIONMASTER_SD_SWITCHES_321},
    {322u,"effect.ue3.sd-322-native.v1","fx_m_mi_r_00.fx_mi.fx_r_pa_spritewave_30_01_tr","fx_m_mi_m_00.fx_m.fx_m_pa_spritewave_01_tr","ue3.material.fx.m.mi.m.00.fx.m.fx.m.pa.spritewave.01.tr.21401ca3cd92",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_322,DIMENSIONMASTER_SD_PARAMETERS_322,DIMENSIONMASTER_SD_SWITCHES_322},
    {323u,"effect.ue3.sd-323-native.v1","fx_m_mi_r_00.fx_mi.fx_r_pa_twirl_03_09_ad","fx_m_mi_03.fx_m.fx_d_pa_twirl_05_ad","ue3.material.fx.m.mi.03.fx.m.fx.d.pa.twirl.05.ad.2b8e151c3da1",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_323,DIMENSIONMASTER_SD_PARAMETERS_323,DIMENSIONMASTER_SD_SWITCHES_323},
    {324u,"effect.ue3.sd-324-native.v1","fx_m_mi_00.fx_mi.fx_d_me_ice_01_02_tr","fx_m_mi_00.fx_m.fx_d_me_ice_01_tr","ue3.material.fx.m.mi.00.fx.m.fx.d.me.ice.01.tr.b5fca778c01f",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_324,DIMENSIONMASTER_SD_PARAMETERS_324,DIMENSIONMASTER_SD_SWITCHES_324},
    {325u,"effect.ue3.sd-325-native.v1","fx_m_mi_01.fx_mi.fx_k_me_floorstrm_08_ad","fx_m_mi_00.fx_m.fx_d_pa_master_01_ad","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.master.01.ad.2bf3a6febe9f",true,"mesh",false,false,false,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_325,DIMENSIONMASTER_SD_PARAMETERS_325,DIMENSIONMASTER_SD_SWITCHES_325},
    {326u,"effect.ue3.sd-326-native.v1","fx_m_mi_w_00.mi.fx_w_me_spritewave_01_77_tr","fx_m_mi_m_00.fx_m.fx_m_pa_spritewave_01_tr","ue3.material.fx.m.mi.m.00.fx.m.fx.m.pa.spritewave.01.tr.21401ca3cd92",true,"mesh",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_326,DIMENSIONMASTER_SD_PARAMETERS_326,DIMENSIONMASTER_SD_SWITCHES_326},
    {327u,"effect.ue3.sd-327-native.v1","fx_m_mi_m_00.fx_mi.fx_m_me_ap_07_6_ts_tr","fx_mastermaterial.fx_mm.fx_mm_basic_01_tr","ue3.material.fx.mastermaterial.fx.mm.fx.mm.basic.01.tr.ce17b96d1b77",true,"mesh",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_327,DIMENSIONMASTER_SD_PARAMETERS_327,DIMENSIONMASTER_SD_SWITCHES_327},
    {328u,"effect.ue3.sd-328-native.v1","fx_m_mi_m_00.fx_mi.fx_m_me_floorstrm_21_ad","fx_m_mi_00.fx_m.fx_d_pa_master_01_ad","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.master.01.ad.2bf3a6febe9f",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_328,DIMENSIONMASTER_SD_PARAMETERS_328,DIMENSIONMASTER_SD_SWITCHES_328},
    {329u,"effect.ue3.sd-329-native.v1","fx_m_mi_g_00.fx_mi.fx_g_me_field_01_1_tr","fx_m_mi_00.fx_m.fx_d_pa_field_02_tr","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.field.02.tr.5f5c790fded2",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_329,DIMENSIONMASTER_SD_PARAMETERS_329,DIMENSIONMASTER_SD_SWITCHES_329},
    {330u,"effect.ue3.sd-330-native.v1","fx_m_mi_00.fx_mi.fx_d_me_electric_03_13_ad","fx_m_mi_00.fx_m.fx_d_pa_electric_03_ad","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.electric.03.ad.781f15e7340d",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_330,DIMENSIONMASTER_SD_PARAMETERS_330,DIMENSIONMASTER_SD_SWITCHES_330},
    {331u,"effect.ue3.sd-331-native.v1","fx_m_mi_s_00.fx_mi.fx_s_me_spritewave_03_18_tr","fx_m_mi_m_00.fx_m.fx_m_pa_spritewave_01_tr","ue3.material.fx.m.mi.m.00.fx.m.fx.m.pa.spritewave.01.tr.21401ca3cd92",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_331,DIMENSIONMASTER_SD_PARAMETERS_331,DIMENSIONMASTER_SD_SWITCHES_331},
    {332u,"effect.ue3.sd-332-native.v1","fx_m_mi_m_00.fx_mi.fx_m_me_spritewave_01_8_ad","fx_m_mi_m_00.fx_m.fx_m_pa_spritewave_01_ad","ue3.material.fx.m.mi.m.00.fx.m.fx.m.pa.spritewave.01.ad.caabbddf8b55",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_332,DIMENSIONMASTER_SD_PARAMETERS_332,DIMENSIONMASTER_SD_SWITCHES_332},
    {341u,"effect.ue3.sd-341-native.v1","fx_m_mi_t_00.fx_mi.fx_t_pa_worldoffset_02_14_tr","fx_m_mi_03.fx_mi.fx_m_pa_worldoffset_02_tr","ue3.material.fx.m.mi.03.fx.mi.fx.m.pa.worldoffset.02.tr.6507c4b13a9b",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_341,DIMENSIONMASTER_SD_PARAMETERS_341,DIMENSIONMASTER_SD_SWITCHES_341},
    {342u,"effect.ue3.sd-342-native.v1","fx_m_mi_s_00.fx_mi.fx_s_pa_glasshole_01_01_tr","fx_m_mi_s_00.fx_m.fx_s_pa_glasshole_01_tr","ue3.material.fx.m.mi.s.00.fx.m.fx.s.pa.glasshole.01.tr.52a7be1f5d8b",false,"sprite",false,true,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_342,DIMENSIONMASTER_SD_PARAMETERS_342,DIMENSIONMASTER_SD_SWITCHES_342},
    {343u,"effect.ue3.sd-343-native.v1","fx_m_mi_s_00.fx_mi.fx_s_pa_glasshole_01_02_tr","fx_m_mi_s_00.fx_m.fx_s_pa_glasshole_01_tr","ue3.material.fx.m.mi.s.00.fx.m.fx.s.pa.glasshole.01.tr.52a7be1f5d8b",false,"sprite",false,true,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_343,DIMENSIONMASTER_SD_PARAMETERS_343,DIMENSIONMASTER_SD_SWITCHES_343},
    {344u,"effect.ue3.sd-344-native.v1","fx_m_mi_m_00.fx_mi.fx_m_phantomblade_finish_01_tr_inst","fx_m_mi_m_00.fx_m.fx_m_baseringmaster_01_ad","ue3.material.fx.m.mi.m.00.fx.m.fx.m.baseringmaster.01.ad.79781ff74bea",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_344,DIMENSIONMASTER_SD_PARAMETERS_344,DIMENSIONMASTER_SD_SWITCHES_344},
    {345u,"effect.ue3.sd-345-native.v1","fx_m_mi_w_00.mi.fx_w_pa_fd_01_3_tr","fx_mastermaterial.fx_mm.fx_mm_fluid_01_tr","ue3.material.fx.mastermaterial.fx.mm.fx.mm.fluid.01.tr.99f00cf3e57f",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_345,DIMENSIONMASTER_SD_PARAMETERS_345,DIMENSIONMASTER_SD_SWITCHES_345},
    {347u,"effect.ue3.sd-347-native.v1","fx_m_mi_s_00.fx_mi.fx_s_pa_glasshole_02_01","fx_m_mi_s_00.fx_m.fx_s_pa_glasshole_02_tr","ue3.material.fx.m.mi.s.00.fx.m.fx.s.pa.glasshole.02.tr.eca0042e0e8e",false,"sprite",false,true,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_347,DIMENSIONMASTER_SD_PARAMETERS_347,DIMENSIONMASTER_SD_SWITCHES_347},
    {348u,"effect.ue3.sd-348-native.v1","fx_m_mi_y_00.fx_mi.fx_y_pa_hole_10_01_tr","fx_m_mi_00.fx_m.fx_d_pa_hole_07_tr","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.hole.07.tr.382f7667c8a2",false,"sprite",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_348,DIMENSIONMASTER_SD_PARAMETERS_348,DIMENSIONMASTER_SD_SWITCHES_348},
    {349u,"effect.ue3.sd-349-native.v1","fx_m_mi_w_00.mi.fx_w_pa_ringmaster_01_20_dt_ad","fx_m_mi_03.fx_m.fx_d_pa_ringmaster_01_ad","ue3.material.fx.m.mi.03.fx.m.fx.d.pa.ringmaster.01.ad.f754ad06cfe6",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ADDITIVE_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_349,DIMENSIONMASTER_SD_PARAMETERS_349,DIMENSIONMASTER_SD_SWITCHES_349},
    {351u,"effect.ue3.sd-351-native.v1","fx_m_mi_s_00.fx_mi.fx_s_pa_turbulence_01_11_dt_tr","fx_m_mi_03.fx_m.fx_d_pa_turbulence_01_tr","ue3.material.fx.m.mi.03.fx.m.fx.d.pa.turbulence.01.tr.324978c21e60",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_351,DIMENSIONMASTER_SD_PARAMETERS_351,DIMENSIONMASTER_SD_SWITCHES_351},
    {352u,"effect.ue3.sd-352-native.v1","fx_m_mi_d_00.fx_mi.fx_d_pa_afterburn_01_101_dt_tr","fx_m_mi_00.fx_m.fx_d_pa_afterburn_01_tr","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.afterburn.01.tr.75ee17c3dfee",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_352,DIMENSIONMASTER_SD_PARAMETERS_352,DIMENSIONMASTER_SD_SWITCHES_352},
    {360u,"effect.ue3.sd-360-native.v1","fx_m_mi_00.fx_mi.fx_b_pa_gl_01_1_ad","fx_mastermaterial.fx_mm.fx_mm_simple_01_ad","ue3.material.fx.mastermaterial.fx.mm.fx.mm.simple.01.ad.9b97b139cca2",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ADDITIVE_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_360,DIMENSIONMASTER_SD_PARAMETERS_360,DIMENSIONMASTER_SD_SWITCHES_360},
    {361u,"effect.ue3.sd-361-native.v1","fx_m_mi_w_00.mi.fx_w_pa_worldoffset_02_40_tr","fx_m_mi_03.fx_mi.fx_m_pa_worldoffset_02_tr","ue3.material.fx.m.mi.03.fx.mi.fx.m.pa.worldoffset.02.tr.6507c4b13a9b",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_361,DIMENSIONMASTER_SD_PARAMETERS_361,DIMENSIONMASTER_SD_SWITCHES_361},
    {362u,"effect.ue3.sd-362-native.v1","fx_m_mi_w_00.mi.fx_w_me_master_06_00_tr","fx_m_mi_d_00.fx_m.fx_d_me_kazerosmark_tr","ue3.material.fx.m.mi.d.00.fx.m.fx.d.me.kazerosmark.tr.4050bfb1ad43",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_362,DIMENSIONMASTER_SD_PARAMETERS_362,DIMENSIONMASTER_SD_SWITCHES_362},
    {363u,"effect.ue3.sd-363-native.v1","fx_m_mi_w_00.mi.fx_w_me_flowtrail_03_09_ts_ad","fx_m_mi_02.fx_m.fx_k_me_flowtrail_01_ts_ad","ue3.material.fx.m.mi.02.fx.m.fx.k.me.flowtrail.01.ts.ad.363e47f44894",true,"mesh",false,false,false,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_363,DIMENSIONMASTER_SD_PARAMETERS_363,DIMENSIONMASTER_SD_SWITCHES_363},
    {364u,"effect.ue3.sd-364-native.v1","fx_m_mi_w_00.mi.fx_w_pa_spritewave_01_106_tr","fx_m_mi_m_00.fx_m.fx_m_pa_spritewave_01_tr","ue3.material.fx.m.mi.m.00.fx.m.fx.m.pa.spritewave.01.tr.21401ca3cd92",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_364,DIMENSIONMASTER_SD_PARAMETERS_364,DIMENSIONMASTER_SD_SWITCHES_364},
    {365u,"effect.ue3.sd-365-native.v1","fx_m_mi_02.fx_m.fx_j_me_splitline_01_1_ad","fx_m_mi_02.fx_m.fx_j_me_splitline_01_1_ad","ue3.material.fx.m.mi.02.fx.m.fx.j.me.splitline.01.1.ad.d9bf97c767a0",true,"mesh",true,true,true,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_365,DIMENSIONMASTER_SD_PARAMETERS_365,DIMENSIONMASTER_SD_SWITCHES_365},
    {366u,"effect.ue3.sd-366-native.v1","fx_m_mi_01.fx_mi.fx_o_me_master_01_04_ds_ad","fx_m_mi_00.fx_m.fx_d_pa_master_01_ad","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.master.01.ad.2bf3a6febe9f",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_366,DIMENSIONMASTER_SD_PARAMETERS_366,DIMENSIONMASTER_SD_SWITCHES_366},
    {367u,"effect.ue3.sd-367-native.v1","fx_m_mi_w_00.mi.fx_w_me_master_01_3_ad","fx_m_mi_00.fx_m.fx_d_pa_master_01_ad","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.master.01.ad.2bf3a6febe9f",true,"mesh",false,true,false,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_367,DIMENSIONMASTER_SD_PARAMETERS_367,DIMENSIONMASTER_SD_SWITCHES_367},
    {368u,"effect.ue3.sd-368-native.v1","fx_m_mi_01.fx_mi.fx_d_pa_shine_01_10_ad","bfx_m_mi_00.bfx_m.bfx_d_pa_shine_01_ad","ue3.material.bfx.m.mi.00.bfx.m.bfx.d.pa.shine.01.ad.d944bc82b616",false,"sprite",false,false,true,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_368,DIMENSIONMASTER_SD_PARAMETERS_368,DIMENSIONMASTER_SD_SWITCHES_368},
    {369u,"effect.ue3.sd-369-native.v1","fx_m_mi_w_00.mi.fx_w_pa_spritewave_01_105_tr","fx_m_mi_m_00.fx_m.fx_m_pa_spritewave_01_tr","ue3.material.fx.m.mi.m.00.fx.m.fx.m.pa.spritewave.01.tr.21401ca3cd92",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_369,DIMENSIONMASTER_SD_PARAMETERS_369,DIMENSIONMASTER_SD_SWITCHES_369},
    {370u,"effect.ue3.sd-370-native.v1","bfx_m_mi_00.bfx_mi.bfx_d_pa_afterburn_01_39_tr","fx_m_mi_00.fx_m.fx_d_pa_afterburn_01_tr","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.afterburn.01.tr.75ee17c3dfee",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_370,DIMENSIONMASTER_SD_PARAMETERS_370,DIMENSIONMASTER_SD_SWITCHES_370},
    {371u,"effect.ue3.sd-371-native.v1","fx_m_mi_03.fx_mi.fx_d_pa_ring_11_09_ts_tr","fx_m_mi_03.fx_m.fx_d_pa_ring_11_tr","ue3.material.fx.m.mi.03.fx.m.fx.d.pa.ring.11.tr.a0ed9ffc6d76",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_371,DIMENSIONMASTER_SD_PARAMETERS_371,DIMENSIONMASTER_SD_SWITCHES_371},
    {372u,"effect.ue3.sd-372-native.v1","fx_m_mi_w_00.mi.fx_w_pa_blackvoid_01_01_tr","fx_m_mi_j_00.fx_m.fx_j_pa_blackvoid_01_tr","ue3.material.fx.m.mi.j.00.fx.m.fx.j.pa.blackvoid.01.tr.7f060283cccc",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_372,DIMENSIONMASTER_SD_PARAMETERS_372,DIMENSIONMASTER_SD_SWITCHES_372},
    {373u,"effect.ue3.sd-373-native.v1","fx_m_mi_w_00.mi.fx_w_pa_afterburn_01_27_dt_tr","fx_m_mi_00.fx_m.fx_d_pa_afterburn_01_tr","ue3.material.fx.m.mi.00.fx.m.fx.d.pa.afterburn.01.tr.75ee17c3dfee",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_373,DIMENSIONMASTER_SD_PARAMETERS_373,DIMENSIONMASTER_SD_SWITCHES_373},
    {375u,"effect.ue3.sd-375-native.v1","fx_m_mi_j_00.fx_mi.fx_j_pa_hologram_01_01_tr","fx_m_mi_j_00.fx_m.fx_j_me_hologram_01_tr","ue3.material.fx.m.mi.j.00.fx.m.fx.j.me.hologram.01.tr.e6febdda35c4",false,"sprite",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_375,DIMENSIONMASTER_SD_PARAMETERS_375,DIMENSIONMASTER_SD_SWITCHES_375},
    {374u,"effect.ue3.sd-374-native.v1","fx_mastermaterial.fx_mi.fx_mm_onelayerdistortion_02_01_ad","fx_mastermaterial.fx_mm.fx_mm_onelayerdistortion_02_ad","ue3.material.fx.mastermaterial.fx.mm.fx.mm.onelayerdistortion.02.ad.6f0e183fe955",false,"sprite",true,false,false,EFFECT_RENDER_PROFILE::ADDITIVE_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_374,DIMENSIONMASTER_SD_PARAMETERS_374,DIMENSIONMASTER_SD_SWITCHES_374,true},
    {389u,"effect.ue3.sd-389-native.v1","fx_m_mi_02.fx_mi.fx_k_pa_shine_01_tr","fx_m_mi_02.fx_m.fx_f_pa_shine_01_0_tr","ue3.material.fx.m.mi.02.fx.m.fx.f.pa.shine.01.0.tr.3d21bd1f3e79",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_389,DIMENSIONMASTER_SD_PARAMETERS_389,DIMENSIONMASTER_SD_SWITCHES_389},
    {390u,"effect.ue3.sd-390-native.v1","fx_m_mi_j_00.fx_mi.fx_j_pa_shine_02_04_tr","fx_m_mi_02.fx_m.fx_d_pa_shine_02_tr","ue3.material.fx.m.mi.02.fx.m.fx.d.pa.shine.02.tr.62e708fe3f21",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_390,DIMENSIONMASTER_SD_PARAMETERS_390,DIMENSIONMASTER_SD_SWITCHES_390},
    {391u,"effect.ue3.sd-391-native.v1","fx_m_mi_j_00.fx_mi.fx_j_me_makeflow_03_06_tr","fx_m_mi_k_00.fx_m.fx_k_me_makeflow_03_tr","ue3.material.fx.m.mi.k.00.fx.m.fx.k.me.makeflow.03.tr.6e5c0dd36299",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_391,DIMENSIONMASTER_SD_PARAMETERS_391,DIMENSIONMASTER_SD_SWITCHES_391},
    {392u,"effect.ue3.sd-392-native.v1","fx_m_mi_j_00.fx_mi.fx_j_me_linearflow_02_14_tr","fx_m_mi_j_00.fx_m.fx_j_pa_linearflow_02_tr","ue3.material.fx.m.mi.j.00.fx.m.fx.j.pa.linearflow.02.tr.ac0bdcfd95f7",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_392,DIMENSIONMASTER_SD_PARAMETERS_392,DIMENSIONMASTER_SD_SWITCHES_392},
    {393u,"effect.ue3.sd-393-native.v1","fx_m_mi_s_00.fx_mi.fx_s_pa_ring_01_1_ts_tr","fx_m_mi_03.fx_m.fx_n_pa_ring_05_tr","ue3.material.fx.m.mi.03.fx.m.fx.n.pa.ring.05.tr.f23a0bf40d4e",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_393,DIMENSIONMASTER_SD_PARAMETERS_393,DIMENSIONMASTER_SD_SWITCHES_393},
    {394u,"effect.ue3.sd-394-native.v1","fx_m_mi_o_00.fx_mi.fx_o_me_makeflow_03_06_tr","fx_m_mi_k_00.fx_m.fx_k_me_makeflow_03_tr","ue3.material.fx.m.mi.k.00.fx.m.fx.k.me.makeflow.03.tr.6e5c0dd36299",true,"mesh",false,false,true,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_394,DIMENSIONMASTER_SD_PARAMETERS_394,DIMENSIONMASTER_SD_SWITCHES_394},
    {395u,"effect.ue3.sd-395-native.v1","fx_m_mi_s_00.fx_mi.fx_s_pa_trail_03_01_tr","fx_m_mi_03.fx_mi.fx_m_pa_trail_01_tr","ue3.material.fx.m.mi.03.fx.mi.fx.m.pa.trail.01.tr.2372f1d945ed",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_395,DIMENSIONMASTER_SD_PARAMETERS_395,DIMENSIONMASTER_SD_SWITCHES_395},
    {396u,"effect.ue3.sd-396-native.v1","fx_m_mi_m_00.fx_mi.fx_m_pa_trail_01_6_tr","fx_m_mi_03.fx_mi.fx_m_pa_trail_01_tr","ue3.material.fx.m.mi.03.fx.mi.fx.m.pa.trail.01.tr.2372f1d945ed",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_396,DIMENSIONMASTER_SD_PARAMETERS_396,DIMENSIONMASTER_SD_SWITCHES_396},
    {397u,"effect.ue3.sd-397-native.v1","fx_m_mi_j_00.fx_mi.fx_j_pa_utillight_01_01_tr","fx_m_mi_j_00.fx_m.fx_j_pa_utillight_01_tr","ue3.material.fx.m.mi.j.00.fx.m.fx.j.pa.utillight.01.tr.8ef270d83e55",false,"sprite",false,true,false,EFFECT_RENDER_PROFILE::ADDITIVE_ONE_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_397,DIMENSIONMASTER_SD_PARAMETERS_397,DIMENSIONMASTER_SD_SWITCHES_397},
    {399u,"effect.ue3.sd-399-native.v1","fx_m_mi_j_00.fx_mi.fx_j_pa_uvcoreoffset_01_06_tr","fx_m_mi_j_00.fx_m.fx_j_pa_uvcoreoffset_01_tr","ue3.material.fx.m.mi.j.00.fx.m.fx.j.pa.uvcoreoffset.01.tr.bc7cbcaefbe6",false,"sprite",false,false,false,EFFECT_RENDER_PROFILE::ALPHA_TWO_SIDED_DEPTH_READ,DIMENSIONMASTER_SD_TEXTURES_399,DIMENSIONMASTER_SD_PARAMETERS_399,DIMENSIONMASTER_SD_SWITCHES_399},
}};
