// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_k_pa_makeflow_02_tr_Constants0 : register(b0)
{
    float4 cb0[16];
};
cbuffer Shade_Ue3_fx_k_pa_makeflow_02_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);

struct Shade_Ue3_fx_k_pa_makeflow_02_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_k_pa_makeflow_02_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_k_pa_makeflow_02_tr_OUTPUT Shade_Ue3_fx_k_pa_makeflow_02_tr(Shade_Ue3_fx_k_pa_makeflow_02_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // add r0.xy, v2.yxyy, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.y + -0.5f;
    float stage1_y = v2.x + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.y|, |r0.x|
    r0.z = max(abs(r0.y), abs(r0.x));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.y|, |r0.x|
    r0.w = min(abs(r0.y), abs(r0.x));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.y|, |r0.x|
    r1.y = asfloat((abs(r0.y) < abs(r0.x)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.y, -r0.y
    r0.w = asfloat((r0.y < -r0.y) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.y, r0.x
    r0.w = min(r0.y, r0.x);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.y, r0.x
    r1.x = max(r0.y, r0.x);
    // ge r1.x, r1.x, -r1.x
    r1.x = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, r1.x
    r0.w = asfloat(asuint(r0.w) & asuint(r1.x));
    // movc r0.z, r0.w, -r0.z, r0.z
    r0.z = asuint(r0.w) != 0u ? -r0.z : r0.z;
    // mad r0.z, r0.z, l(0.318471), l(1.000000)
    r0.z = r0.z * 0.318471f + 1.0f;
    // mul r1.x, r0.z, l(0.500000)
    r1.x = r0.z * 0.5f;
    // mul r2.x, r1.x, cb0[10].z
    r2.x = r1.x * cb0[10].z;
    // dp2 r0.z, -r0.xyxx, -r0.xyxx
    r0.z = dot(-r0.xy, -r0.xy);
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // sqrt r1.y, r0.z
    r1.y = sqrt(r0.z);
    // mad r0.yz, r1.xxyx, cb0[2].xxyx, cb0[3].xxyx
    float stage2_y = r1.x * cb0[2].x + cb0[3].x;
    float stage2_z = r1.y * cb0[2].y + cb0[3].y;
    r0.y = stage2_y;
    r0.z = stage2_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.w, r0.yzyy, t1.yzwx, s0, l(0.000000)
    float4 fetch3 = t1.SampleBias(s0, r0.yz, 0.0f);
    r0.w = fetch3.x;
    // mov r3.y, cb0[10].w
    r3.y = cb0[10].w;
    // mov r3.xz, l(0,0,0,0)
    float stage4_x = asfloat(0u);
    float stage4_z = asfloat(0u);
    r3.x = stage4_x;
    r3.z = stage4_z;
    // add r4.xyzw, r0.yzyz, r3.yxxy
    float stage5_x = r0.y + r3.y;
    float stage5_y = r0.z + r3.x;
    float stage5_z = r0.y + r3.x;
    float stage5_w = r0.z + r3.y;
    r4.x = stage5_x;
    r4.y = stage5_y;
    r4.z = stage5_z;
    r4.w = stage5_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r4.xyxx, t1.yxzw, s0, l(0.000000)
    float4 fetch6 = t1.SampleBias(s0, r4.xy, 0.0f);
    r0.y = fetch6.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r4.zwzz, t1.yzxw, s0, l(0.000000)
    float4 fetch7 = t1.SampleBias(s0, r4.zw, 0.0f);
    r0.z = fetch7.x;
    // add r3.xy, -r0.wwww, r0.yzyy
    float stage8_x = -r0.w + r0.y;
    float stage8_y = -r0.w + r0.z;
    r3.x = stage8_x;
    r3.y = stage8_y;
    // mul r4.xy, r3.xyxx, l(8.000000, 8.000000, 0.000000, 0.000000)
    float stage9_x = r3.x * 8.0f;
    float stage9_y = r3.y * 8.0f;
    r4.x = stage9_x;
    r4.y = stage9_y;
    // mov r4.z, l(0)
    r4.z = asfloat(0u);
    // add r0.yzw, -r4.xxyz, l(0.000000, 0.000000, 0.000000, 1.000000)
    float stage10_y = -r4.x + 0.0f;
    float stage10_z = -r4.y + 0.0f;
    float stage10_w = -r4.z + 1.0f;
    r0.y = stage10_y;
    r0.z = stage10_z;
    r0.w = stage10_w;
    // dp3 r0.w, r0.yzwy, r0.yzwy
    r0.w = dot(r0.yzw, r0.yzw);
    // sqrt r0.w, r0.w
    r0.w = sqrt(r0.w);
    // div r0.yz, r0.yyzy, r0.wwww
    float stage11_y = r0.y / r0.w;
    float stage11_z = r0.z / r0.w;
    r0.y = stage11_y;
    r0.z = stage11_z;
    // mad r0.yz, r0.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000), l(0.000000, 0.500000, 0.500000, 0.000000)
    float stage12_y = r0.y * 0.5f + 0.5f;
    float stage12_z = r0.z * 0.5f + 0.5f;
    r0.y = stage12_y;
    r0.z = stage12_z;
    // mul r0.yz, r0.yyzy, v4.xxxx
    float stage13_y = r0.y * v4.x;
    float stage13_z = r0.z * v4.x;
    r0.y = stage13_y;
    r0.z = stage13_z;
    // log r0.w, |cb0[10].y|
    r0.w = log2(abs(cb0[10].y));
    // mul r0.w, r0.w, cb0[10].x
    r0.w = r0.w * cb0[10].x;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // lt r1.z, |cb0[10].y|, l(0.000001)
    r1.z = asfloat((abs(cb0[10].y) < 1e-06f) ? 0xffffffffu : 0u);
    // movc r0.w, r1.z, l(0), r0.w
    r0.w = asuint(r1.z) != 0u ? asfloat(0u) : r0.w;
    // mul r2.y, r0.w, r1.y
    r2.y = r0.w * r1.y;
    // max r0.w, v4.z, l(0.000010)
    r0.w = max(v4.z, 1e-05f);
    // div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
    r0.w = 1.0f / r0.w;
    // mad r0.w, -r0.x, r0.w, l(1.000000)
    r0.w = -r0.x * r0.w + 1.0f;
    // mul_sat r0.w, r0.w, l(1.428571)
    r0.w = saturate(r0.w * 1.428571f);
    // mad r1.zw, r0.wwww, r0.yyyz, r2.xxxy
    float stage14_z = r0.w * r0.y + r2.x;
    float stage14_w = r0.w * r0.z + r2.y;
    r1.z = stage14_z;
    r1.w = stage14_w;
    // mov r3.w, v4.w
    r3.w = v4.w;
    // add r1.zw, r1.zzzw, r3.zzzw
    float stage15_z = r1.z + r3.z;
    float stage15_w = r1.w + r3.w;
    r1.z = stage15_z;
    r1.w = stage15_w;
    // add r1.zw, r1.zzzw, cb0[4].xxxy
    float stage16_z = r1.z + cb0[4].x;
    float stage16_w = r1.w + cb0[4].y;
    r1.z = stage16_z;
    r1.w = stage16_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xyz, r1.zwzz, t3.xyzw, s1, l(0.000000)
    float4 fetch17 = t3.SampleBias(s1, r1.zw, 0.0f);
    r2.x = fetch17.x;
    r2.y = fetch17.y;
    r2.z = fetch17.z;
    // mul r3.x, r1.x, cb0[12].x
    r3.x = r1.x * cb0[12].x;
    // mad r1.xz, r1.xxyx, cb0[7].xxyx, l(-0.500000, 0.000000, -0.500000, 0.000000)
    float stage18_x = r1.x * cb0[7].x + -0.5f;
    float stage18_z = r1.y * cb0[7].y + -0.5f;
    r1.x = stage18_x;
    r1.z = stage18_z;
    // log r1.w, |cb0[11].w|
    r1.w = log2(abs(cb0[11].w));
    // mul r1.w, r1.w, cb0[10].x
    r1.w = r1.w * cb0[10].x;
    // exp r1.w, r1.w
    r1.w = exp2(r1.w);
    // lt r2.w, |cb0[11].w|, l(0.000001)
    r2.w = asfloat((abs(cb0[11].w) < 1e-06f) ? 0xffffffffu : 0u);
    // movc r1.w, r2.w, l(0), r1.w
    r1.w = asuint(r2.w) != 0u ? asfloat(0u) : r1.w;
    // mul r3.y, r1.w, r1.y
    r3.y = r1.w * r1.y;
    // mad r1.yw, r0.wwww, r0.yyyz, r3.xxxy
    float stage19_y = r0.w * r0.y + r3.x;
    float stage19_w = r0.w * r0.z + r3.y;
    r1.y = stage19_y;
    r1.w = stage19_w;
    // mul r0.yz, r0.yyzy, r0.wwww
    float stage20_y = r0.y * r0.w;
    float stage20_z = r0.z * r0.w;
    r0.y = stage20_y;
    r0.z = stage20_z;
    // add r1.yw, r1.yyyw, cb0[5].xxxy
    float stage21_y = r1.y + cb0[5].x;
    float stage21_w = r1.w + cb0[5].y;
    r1.y = stage21_y;
    r1.w = stage21_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r3.xyz, r1.ywyy, t4.xyzw, s2, l(0.000000)
    float4 fetch22 = t4.SampleBias(s2, r1.yw, 0.0f);
    r3.x = fetch22.x;
    r3.y = fetch22.y;
    r3.z = fetch22.z;
    // mul r4.xyz, r2.xyzx, r3.xyzx
    float stage23_x = r2.x * r3.x;
    float stage23_y = r2.y * r3.y;
    float stage23_z = r2.z * r3.z;
    r4.x = stage23_x;
    r4.y = stage23_y;
    r4.z = stage23_z;
    // dp3 r1.y, r4.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.y = dot(r4.xyz, float3(0.3f, 0.59f, 0.11f));
    // mad r2.xyz, -r2.xyzx, r3.xyzx, r1.yyyy
    float stage24_x = -r2.x * r3.x + r1.y;
    float stage24_y = -r2.y * r3.y + r1.y;
    float stage24_z = -r2.z * r3.z + r1.y;
    r2.x = stage24_x;
    r2.y = stage24_y;
    r2.z = stage24_z;
    // mad r2.xyz, cb0[13].yyyy, r2.xyzx, r4.xyzx
    float stage25_x = cb0[13].y * r2.x + r4.x;
    float stage25_y = cb0[13].y * r2.y + r4.y;
    float stage25_z = cb0[13].y * r2.z + r4.z;
    r2.x = stage25_x;
    r2.y = stage25_y;
    r2.z = stage25_z;
    // max r2.xyz, |r2.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage26_x = max(abs(r2.x), 1e-06f);
    float stage26_y = max(abs(r2.y), 1e-06f);
    float stage26_z = max(abs(r2.z), 1e-06f);
    r2.x = stage26_x;
    r2.y = stage26_y;
    r2.z = stage26_z;
    // log r2.xyz, r2.xyzx
    float stage27_x = log2(r2.x);
    float stage27_y = log2(r2.y);
    float stage27_z = log2(r2.z);
    r2.x = stage27_x;
    r2.y = stage27_y;
    r2.z = stage27_z;
    // mul r2.xyz, r2.xyzx, cb0[13].zzzz
    float stage28_x = r2.x * cb0[13].z;
    float stage28_y = r2.y * cb0[13].z;
    float stage28_z = r2.z * cb0[13].z;
    r2.x = stage28_x;
    r2.y = stage28_y;
    r2.z = stage28_z;
    // exp r2.xyz, r2.xyzx
    float stage29_x = exp2(r2.x);
    float stage29_y = exp2(r2.y);
    float stage29_z = exp2(r2.z);
    r2.x = stage29_x;
    r2.y = stage29_y;
    r2.z = stage29_z;
    // mul r2.xyz, r2.xyzx, cb0[13].wwww
    float stage30_x = r2.x * cb0[13].w;
    float stage30_y = r2.y * cb0[13].w;
    float stage30_z = r2.z * cb0[13].w;
    r2.x = stage30_x;
    r2.y = stage30_y;
    r2.z = stage30_z;
    // mad r2.xyz, r0.wwww, r2.xyzx, cb0[6].xyzx
    float stage31_x = r0.w * r2.x + cb0[6].x;
    float stage31_y = r0.w * r2.y + cb0[6].y;
    float stage31_z = r0.w * r2.z + cb0[6].z;
    r2.x = stage31_x;
    r2.y = stage31_y;
    r2.z = stage31_z;
    // mad r2.xyz, v3.xyzx, r2.xyzx, cb0[1].xyzx
    float stage32_x = v3.x * r2.x + cb0[1].x;
    float stage32_y = v3.y * r2.y + cb0[1].y;
    float stage32_z = v3.z * r2.z + cb0[1].z;
    r2.x = stage32_x;
    r2.y = stage32_y;
    r2.z = stage32_z;
    // mad o0.xyz, r2.xyzx, v5.wwww, v5.xyzx
    float stage33_x = r2.x * v5.w + v5.x;
    float stage33_y = r2.y * v5.w + v5.y;
    float stage33_z = r2.z * v5.w + v5.z;
    o0.x = stage33_x;
    o0.y = stage33_y;
    o0.z = stage33_z;
    // dp2 r0.w, cb0[9].xyxx, r1.xzxx
    r0.w = dot(cb0[9].xy, r1.xz);
    // dp2 r1.x, cb0[8].xyxx, r1.xzxx
    r1.x = dot(cb0[8].xy, r1.xz);
    // add r1.y, r0.w, v4.y
    r1.y = r0.w + v4.y;
    // add r1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage34_x = r1.x + 0.5f;
    float stage34_y = r1.y + 0.5f;
    r1.x = stage34_x;
    r1.y = stage34_y;
    // mad r0.yz, cb0[14].wwww, r0.yyzy, r1.xxyx
    float stage35_y = cb0[14].w * r0.y + r1.x;
    float stage35_z = cb0[14].w * r0.z + r1.y;
    r0.y = stage35_y;
    r0.z = stage35_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t2.yxzw, s4, l(0.000000)
    float4 fetch36 = t2.SampleBias(s4, r0.yz, 0.0f);
    r0.y = fetch36.x;
    // add r0.z, v4.z, l(0.200000)
    r0.z = v4.z + 0.2f;
    // max r0.z, r0.z, l(0.000010)
    r0.z = max(r0.z, 1e-05f);
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // mad r0.x, -r0.x, r0.z, l(1.000000)
    r0.x = -r0.x * r0.z + 1.0f;
    // mul_sat r0.x, r0.x, l(1.428571)
    r0.x = saturate(r0.x * 1.428571f);
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, v2.xyxx, t0.yzxw, s3, l(0.000000)
    float4 fetch37 = t0.SampleBias(s3, v2.xy, 0.0f);
    r0.z = fetch37.x;
    // mul r0.x, r0.z, r0.x
    r0.x = r0.z * r0.x;
    // mul r0.x, r0.y, r0.x
    r0.x = r0.y * r0.x;
    // max r0.x, |r0.x|, l(0.000001)
    r0.x = max(abs(r0.x), 1e-06f);
    // log r0.x, r0.x
    r0.x = log2(r0.x);
    // mul r0.x, r0.x, cb0[15].x
    r0.x = r0.x * cb0[15].x;
    // exp r0.x, r0.x
    r0.x = exp2(r0.x);
    // mul_sat r0.x, r0.x, cb0[15].y
    r0.x = saturate(r0.x * cb0[15].y);
    // mul r0.x, r0.x, v3.w
    r0.x = r0.x * v3.w;
    // mul o0.w, r0.x, cb0[0].x
    o0.w = r0.x * cb0[0].x;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage38_x = r0.x * v1.x;
    float stage38_y = r0.x * v1.y;
    float stage38_z = r0.x * v1.z;
    r0.x = stage38_x;
    r0.y = stage38_y;
    r0.z = stage38_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage39_x = r0.w * v0.z;
    float stage39_y = r0.w * v0.x;
    float stage39_z = r0.w * v0.y;
    r1.x = stage39_x;
    r1.y = stage39_y;
    r1.z = stage39_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage40_x = r0.x * r1.x;
    float stage40_y = r0.x * r1.y;
    float stage40_z = r0.x * r1.z;
    r0.x = stage40_x;
    r0.y = stage40_y;
    r0.z = stage40_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage41_x = r0.x / r0.w;
    float stage41_y = r0.y / r0.w;
    r0.x = stage41_x;
    r0.y = stage41_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage42_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage42_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage42_x;
    r1.y = stage42_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage43_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage43_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage43_x;
    r1.y = stage43_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage44_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage44_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage44_x;
    r1.y = stage44_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage45_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage45_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage45_x;
    r0.y = stage45_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage46_x = r0.x * 0.5f + 0.5f;
    float stage46_y = r0.y * 0.5f + 0.5f;
    o2.x = stage46_x;
    o2.y = stage46_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage47_z = 1.0f;
    float stage47_w = asfloat(0u);
    o2.z = stage47_z;
    o2.w = stage47_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage48_x = cb2[3].x;
    float stage48_y = cb2[3].y;
    float stage48_z = cb2[3].z;
    o3.x = stage48_x;
    o3.y = stage48_y;
    o3.z = stage48_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage49_x = asfloat(0u);
    float stage49_y = asfloat(0u);
    float stage49_z = asfloat(0u);
    float stage49_w = asfloat(0u);
    o4.x = stage49_x;
    o4.y = stage49_y;
    o4.z = stage49_z;
    o4.w = stage49_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage50_x = asfloat(0u);
    float stage50_y = asfloat(0u);
    float stage50_z = asfloat(0u);
    float stage50_w = asfloat(0u);
    o5.x = stage50_x;
    o5.y = stage50_y;
    o5.z = stage50_z;
    o5.w = stage50_w;

    Shade_Ue3_fx_k_pa_makeflow_02_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
