// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_l_me_icesurfacee_01_tr_Constants0 : register(b0)
{
    float4 cb0[3];
};
cbuffer Shade_Ue3_fx_l_me_icesurfacee_01_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};

struct Shade_Ue3_fx_l_me_icesurfacee_01_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v4;
    float4 v5;
    float4 v6;
};

struct Shade_Ue3_fx_l_me_icesurfacee_01_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_l_me_icesurfacee_01_tr_OUTPUT Shade_Ue3_fx_l_me_icesurfacee_01_tr(Shade_Ue3_fx_l_me_icesurfacee_01_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v6 = stage.v6;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 r5 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // dp3 r0.x, v5.xyzx, v5.xyzx
    r0.x = dot(v5.xyz, v5.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul_sat r0.x, r0.x, v5.z
    r0.x = saturate(r0.x * v5.z);
    // add r0.x, -r0.x, l(1.000000)
    r0.x = -r0.x + 1.0f;
    // lt r0.y, r0.x, l(0.000001)
    r0.y = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.x, r0.x, r0.x
    r0.x = r0.x * r0.x;
    // movc r0.x, r0.y, l(0), r0.x
    r0.x = asuint(r0.y) != 0u ? asfloat(0u) : r0.x;
    // mul r0.y, r0.x, l(2.500000)
    r0.y = r0.x * 2.5f;
    // mul r0.x, r0.x, cb0[1].w
    r0.x = r0.x * cb0[1].w;
    // mul o0.w, r0.x, cb0[0].w
    o0.w = r0.x * cb0[0].w;
    // mad r0.xyz, r0.yyyy, cb0[1].xyzx, cb0[2].xyzx
    float stage1_x = r0.y * cb0[1].x + cb0[2].x;
    float stage1_y = r0.y * cb0[1].y + cb0[2].y;
    float stage1_z = r0.y * cb0[1].z + cb0[2].z;
    r0.x = stage1_x;
    r0.y = stage1_y;
    r0.z = stage1_z;
    // mad o0.xyz, r0.xyzx, v4.wwww, v4.xyzx
    float stage2_x = r0.x * v4.w + v4.x;
    float stage2_y = r0.y * v4.w + v4.y;
    float stage2_z = r0.z * v4.w + v4.z;
    o0.x = stage2_x;
    o0.y = stage2_y;
    o0.z = stage2_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage3_x = r0.x * v1.x;
    float stage3_y = r0.x * v1.y;
    float stage3_z = r0.x * v1.z;
    r0.x = stage3_x;
    r0.y = stage3_y;
    r0.z = stage3_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.xyzx
    float stage4_x = r0.w * v0.x;
    float stage4_y = r0.w * v0.y;
    float stage4_z = r0.w * v0.z;
    r1.x = stage4_x;
    r1.y = stage4_y;
    r1.z = stage4_z;
    // mul r2.xyz, r0.zxyz, r1.yzxy
    float stage5_x = r0.z * r1.y;
    float stage5_y = r0.x * r1.z;
    float stage5_z = r0.y * r1.x;
    r2.x = stage5_x;
    r2.y = stage5_y;
    r2.z = stage5_z;
    // mad r2.xyz, r0.yzxy, r1.zxyz, -r2.xyzx
    float stage6_x = r0.y * r1.z + -r2.x;
    float stage6_y = r0.z * r1.x + -r2.y;
    float stage6_z = r0.x * r1.y + -r2.z;
    r2.x = stage6_x;
    r2.y = stage6_y;
    r2.z = stage6_z;
    // mul r2.xyz, r2.xyzx, v1.wwww
    float stage7_x = r2.x * v1.w;
    float stage7_y = r2.y * v1.w;
    float stage7_z = r2.z * v1.w;
    r2.x = stage7_x;
    r2.y = stage7_y;
    r2.z = stage7_z;
    // add r3.xyz, v6.yzxy, cb0[0].yzxy
    float stage8_x = v6.y + cb0[0].y;
    float stage8_y = v6.z + cb0[0].z;
    float stage8_z = v6.x + cb0[0].x;
    r3.x = stage8_x;
    r3.y = stage8_y;
    r3.z = stage8_z;
    // deriv_rtx_coarse r4.xyz, r3.yzxy
    float stage9_x = ddx_coarse(r3.y);
    float stage9_y = ddx_coarse(r3.z);
    float stage9_z = ddx_coarse(r3.x);
    r4.x = stage9_x;
    r4.y = stage9_y;
    r4.z = stage9_z;
    // deriv_rty_coarse r3.xyz, r3.xyzx
    float stage10_x = ddy_coarse(r3.x);
    float stage10_y = ddy_coarse(r3.y);
    float stage10_z = ddy_coarse(r3.z);
    r3.x = stage10_x;
    r3.y = stage10_y;
    r3.z = stage10_z;
    // mul r5.xyz, r3.xyzx, r4.xyzx
    float stage11_x = r3.x * r4.x;
    float stage11_y = r3.y * r4.y;
    float stage11_z = r3.z * r4.z;
    r5.x = stage11_x;
    r5.y = stage11_y;
    r5.z = stage11_z;
    // mad r3.xyz, r4.zxyz, r3.yzxy, -r5.xyzx
    float stage12_x = r4.z * r3.y + -r5.x;
    float stage12_y = r4.x * r3.z + -r5.y;
    float stage12_z = r4.y * r3.x + -r5.z;
    r3.x = stage12_x;
    r3.y = stage12_y;
    r3.z = stage12_z;
    // dp3 r0.w, r3.xyzx, r3.xyzx
    r0.w = dot(r3.xyz, r3.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r3.xyz, r0.wwww, r3.xyzx
    float stage13_x = r0.w * r3.x;
    float stage13_y = r0.w * r3.y;
    float stage13_z = r0.w * r3.z;
    r3.x = stage13_x;
    r3.y = stage13_y;
    r3.z = stage13_z;
    // dp3 r2.y, r2.xyzx, r3.xyzx
    r2.y = dot(r2.xyz, r3.xyz);
    // dp3 r2.x, r1.xyzx, r3.xyzx
    r2.x = dot(r1.xyz, r3.xyz);
    // dp3 r2.z, r0.xyzx, r3.xyzx
    r2.z = dot(r0.xyz, r3.xyz);
    // dp3 r0.x, r2.xyzx, r2.xyzx
    r0.x = dot(r2.xyz, r2.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r2.xyzx
    float stage14_x = r0.x * r2.x;
    float stage14_y = r0.x * r2.y;
    float stage14_z = r0.x * r2.z;
    r0.x = stage14_x;
    r0.y = stage14_y;
    r0.z = stage14_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage15_x = r0.x / r0.w;
    float stage15_y = r0.y / r0.w;
    r0.x = stage15_x;
    r0.y = stage15_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage16_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage16_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage16_x;
    r1.y = stage16_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage17_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage17_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage17_x;
    r1.y = stage17_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage18_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage18_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage18_x;
    r1.y = stage18_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage19_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage19_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage19_x;
    r0.y = stage19_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage20_x = r0.x * 0.5f + 0.5f;
    float stage20_y = r0.y * 0.5f + 0.5f;
    o2.x = stage20_x;
    o2.y = stage20_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage21_z = 1.0f;
    float stage21_w = asfloat(0u);
    o2.z = stage21_z;
    o2.w = stage21_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage22_x = cb2[3].x;
    float stage22_y = cb2[3].y;
    float stage22_z = cb2[3].z;
    o3.x = stage22_x;
    o3.y = stage22_y;
    o3.z = stage22_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage23_x = asfloat(0u);
    float stage23_y = asfloat(0u);
    float stage23_z = asfloat(0u);
    float stage23_w = asfloat(0u);
    o4.x = stage23_x;
    o4.y = stage23_y;
    o4.z = stage23_z;
    o4.w = stage23_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage24_x = asfloat(0u);
    float stage24_y = asfloat(0u);
    float stage24_z = asfloat(0u);
    float stage24_w = asfloat(0u);
    o5.x = stage24_x;
    o5.y = stage24_y;
    o5.z = stage24_z;
    o5.w = stage24_w;

    Shade_Ue3_fx_l_me_icesurfacee_01_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
