// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_j_pa_spriteinvert_01_tr_Constants0 : register(b0)
{
    float4 cb0[8];
};
cbuffer Shade_Ue3_fx_j_pa_spriteinvert_01_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);

struct Shade_Ue3_fx_j_pa_spriteinvert_01_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_j_pa_spriteinvert_01_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_j_pa_spriteinvert_01_tr_OUTPUT Shade_Ue3_fx_j_pa_spriteinvert_01_tr(Shade_Ue3_fx_j_pa_spriteinvert_01_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mad r0.x, v2.x, cb0[3].z, cb0[4].z
    r0.x = v2.x * cb0[3].z + cb0[4].z;
    // mad r0.y, v2.y, cb0[3].w, cb0[5].x
    r0.y = v2.y * cb0[3].w + cb0[5].x;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch1 = t0.SampleBias(s0, r0.xy, 0.0f);
    r0.x = fetch1.x;
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // mul r0.y, r0.y, v4.x
    r0.y = r0.y * v4.x;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // lt r0.z, |r0.x|, l(0.000001)
    r0.z = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // movc r0.y, r0.z, l(0), r0.y
    r0.y = asuint(r0.z) != 0u ? asfloat(0u) : r0.y;
    // add r0.z, v4.y, l(-1.000000)
    r0.z = v4.y + -1.0f;
    // mul r0.z, r0.z, cb0[5].y
    r0.z = r0.z * cb0[5].y;
    // mad r1.x, v2.x, cb0[2].x, cb0[2].w
    r1.x = v2.x * cb0[2].x + cb0[2].w;
    // mad r1.y, v2.y, cb0[2].y, cb0[3].y
    r1.y = v2.y * cb0[2].y + cb0[3].y;
    // mad r0.xz, r0.xxxx, r0.zzzz, r1.xxyx
    float stage2_x = r0.x * r0.z + r1.x;
    float stage2_z = r0.x * r0.z + r1.y;
    r0.x = stage2_x;
    r0.z = stage2_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xzxx, t1.xyzw, s1, l(0.000000)
    float4 fetch3 = t1.SampleBias(s1, r0.xz, 0.0f);
    r0.x = fetch3.x;
    // mul r0.x, r0.y, r0.x
    r0.x = r0.y * r0.x;
    // mul r0.y, r0.x, cb0[5].z
    r0.y = r0.x * cb0[5].z;
    // log r0.z, |r0.y|
    r0.z = log2(abs(r0.y));
    // lt r0.y, |r0.y|, l(0.000001)
    r0.y = asfloat((abs(r0.y) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, cb0[5].w
    r0.z = r0.z * cb0[5].w;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // mul_sat r0.z, r0.z, cb0[6].x
    r0.z = saturate(r0.z * cb0[6].x);
    // movc r0.y, r0.y, l(0), r0.z
    r0.y = asuint(r0.y) != 0u ? asfloat(0u) : r0.z;
    // mad_sat r0.x, -r0.x, cb0[6].y, r0.y
    r0.x = saturate(-r0.x * cb0[6].y + r0.y);
    // mul_sat r0.y, r0.y, v3.w
    r0.y = saturate(r0.y * v3.w);
    // mul o0.w, r0.y, cb0[0].x
    o0.w = r0.y * cb0[0].x;
    // log r0.y, r0.x
    r0.y = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[6].z
    r0.y = r0.y * cb0[6].z;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul r0.y, r0.y, cb0[6].w
    r0.y = r0.y * cb0[6].w;
    // mul r0.y, r0.y, cb0[7].w
    r0.y = r0.y * cb0[7].w;
    // mul r0.yzw, r0.yyyy, v3.xxyz
    float stage4_y = r0.y * v3.x;
    float stage4_z = r0.y * v3.y;
    float stage4_w = r0.y * v3.z;
    r0.y = stage4_y;
    r0.z = stage4_z;
    r0.w = stage4_w;
    // movc r0.xyz, r0.xxxx, l(0,0,0,0), r0.yzwy
    float stage5_x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    float stage5_y = asuint(r0.x) != 0u ? asfloat(0u) : r0.z;
    float stage5_z = asuint(r0.x) != 0u ? asfloat(0u) : r0.w;
    r0.x = stage5_x;
    r0.y = stage5_y;
    r0.z = stage5_z;
    // add r0.xyz, r0.xyzx, cb0[1].xyzx
    float stage6_x = r0.x + cb0[1].x;
    float stage6_y = r0.y + cb0[1].y;
    float stage6_z = r0.z + cb0[1].z;
    r0.x = stage6_x;
    r0.y = stage6_y;
    r0.z = stage6_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage7_x = r0.x * v5.w + v5.x;
    float stage7_y = r0.y * v5.w + v5.y;
    float stage7_z = r0.z * v5.w + v5.z;
    o0.x = stage7_x;
    o0.y = stage7_y;
    o0.z = stage7_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage8_x = r0.x * v1.x;
    float stage8_y = r0.x * v1.y;
    float stage8_z = r0.x * v1.z;
    r0.x = stage8_x;
    r0.y = stage8_y;
    r0.z = stage8_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage9_x = r0.w * v0.z;
    float stage9_y = r0.w * v0.x;
    float stage9_z = r0.w * v0.y;
    r1.x = stage9_x;
    r1.y = stage9_y;
    r1.z = stage9_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage10_x = r0.x * r1.x;
    float stage10_y = r0.x * r1.y;
    float stage10_z = r0.x * r1.z;
    r0.x = stage10_x;
    r0.y = stage10_y;
    r0.z = stage10_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage11_x = r0.x / r0.w;
    float stage11_y = r0.y / r0.w;
    r0.x = stage11_x;
    r0.y = stage11_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage12_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage12_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage12_x;
    r1.y = stage12_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage13_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage13_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage13_x;
    r1.y = stage13_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage14_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage14_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage14_x;
    r1.y = stage14_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage15_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage15_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage15_x;
    r0.y = stage15_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage16_x = r0.x * 0.5f + 0.5f;
    float stage16_y = r0.y * 0.5f + 0.5f;
    o2.x = stage16_x;
    o2.y = stage16_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage17_z = 1.0f;
    float stage17_w = asfloat(0u);
    o2.z = stage17_z;
    o2.w = stage17_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage18_x = cb2[3].x;
    float stage18_y = cb2[3].y;
    float stage18_z = cb2[3].z;
    o3.x = stage18_x;
    o3.y = stage18_y;
    o3.z = stage18_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage19_x = asfloat(0u);
    float stage19_y = asfloat(0u);
    float stage19_z = asfloat(0u);
    float stage19_w = asfloat(0u);
    o4.x = stage19_x;
    o4.y = stage19_y;
    o4.z = stage19_z;
    o4.w = stage19_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage20_x = asfloat(0u);
    float stage20_y = asfloat(0u);
    float stage20_z = asfloat(0u);
    float stage20_w = asfloat(0u);
    o5.x = stage20_x;
    o5.y = stage20_y;
    o5.z = stage20_z;
    o5.w = stage20_w;

    Shade_Ue3_fx_j_pa_spriteinvert_01_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
