// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_flare_02_ad_Constants0 : register(b0)
{
    float4 cb0[4];
};
cbuffer Shade_Ue3_fx_d_pa_flare_02_ad_Constants2 : register(b2)
{
    float4 cb2[2];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);

struct Shade_Ue3_fx_d_pa_flare_02_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_d_pa_flare_02_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_d_pa_flare_02_ad_OUTPUT Shade_Ue3_fx_d_pa_flare_02_ad(Shade_Ue3_fx_d_pa_flare_02_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;

    // add r0.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.x + -0.5f;
    float stage1_y = v2.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.y|, |r0.x|
    r0.z = max(abs(r0.y), abs(r0.x));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.y|, |r0.x|
    r0.w = min(abs(r0.y), abs(r0.x));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.y|, |r0.x|
    r1.y = asfloat((abs(r0.y) < abs(r0.x)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.y, -r0.y
    r0.w = asfloat((r0.y < -r0.y) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.y, r0.x
    r0.w = min(r0.y, r0.x);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.y, r0.x
    r1.x = max(r0.y, r0.x);
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // mad r0.x, -r0.x, l(2.000000), l(1.000000)
    r0.x = -r0.x * 2.0f + 1.0f;
    // max r0.x, r0.x, l(0.000000)
    r0.x = max(r0.x, 0.0f);
    // ge r0.y, r1.x, -r1.x
    r0.y = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.y, r0.y, r0.w
    r0.y = asfloat(asuint(r0.y) & asuint(r0.w));
    // movc r0.y, r0.y, -r0.z, r0.z
    r0.y = asuint(r0.y) != 0u ? -r0.z : r0.z;
    // mul r1.x, r0.y, l(0.159155)
    r1.x = r0.y * 0.159155f;
    // mad r1.y, r0.y, l(0.159155), l(0.500000)
    r1.y = r0.y * 0.159155f + 0.5f;
    // mov r2.xz, l(0.500000,0,0.500000,0)
    float stage2_x = 0.5f;
    float stage2_z = 0.5f;
    r2.x = stage2_x;
    r2.z = stage2_z;
    // mul r2.yw, v4.xxxx, l(0.000000, 0.400000, 0.000000, -0.700000)
    float stage3_y = v4.x * 0.4f;
    float stage3_w = v4.x * -0.7f;
    r2.y = stage3_y;
    r2.w = stage3_w;
    // add r1.xyzw, r1.xyxy, r2.xyzw
    float stage4_x = r1.x + r2.x;
    float stage4_y = r1.y + r2.y;
    float stage4_z = r1.x + r2.z;
    float stage4_w = r1.y + r2.w;
    r1.x = stage4_x;
    r1.y = stage4_y;
    r1.z = stage4_z;
    r1.w = stage4_w;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.yzw, r1.xyxx, t0.wxyz, s1, l(-1.000000)
    float4 fetch5 = t0.SampleLevel(s1, r1.xy, -1.0f);
    r0.y = fetch5.x;
    r0.z = fetch5.y;
    r0.w = fetch5.z;
    // sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, r1.zwzz, t0.xyzw, s1, l(-1.000000)
    float4 fetch6 = t0.SampleLevel(s1, r1.zw, -1.0f);
    r1.x = fetch6.x;
    r1.y = fetch6.y;
    r1.z = fetch6.z;
    // add r0.y, r0.z, r0.y
    r0.y = r0.z + r0.y;
    // add r0.y, r0.w, r0.y
    r0.y = r0.w + r0.y;
    // add r0.z, r1.y, r1.x
    r0.z = r1.y + r1.x;
    // add r0.z, r1.z, r0.z
    r0.z = r1.z + r0.z;
    // mul r0.y, r0.z, r0.y
    r0.y = r0.z * r0.y;
    // log r0.z, r0.x
    r0.z = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.zw, r0.zzzz, cb0[2].xxxz
    float stage7_z = r0.z * cb0[2].x;
    float stage7_w = r0.z * cb0[2].z;
    r0.z = stage7_z;
    r0.w = stage7_w;
    // exp r0.zw, r0.zzzw
    float stage8_z = exp2(r0.z);
    float stage8_w = exp2(r0.w);
    r0.z = stage8_z;
    r0.w = stage8_w;
    // mul r0.yz, r0.yyzy, cb0[2].wwyw
    float stage9_y = r0.y * cb0[2].w;
    float stage9_z = r0.z * cb0[2].y;
    r0.y = stage9_y;
    r0.z = stage9_z;
    // movc r0.w, r0.x, l(0), r0.w
    r0.w = asuint(r0.x) != 0u ? asfloat(0u) : r0.w;
    // movc r0.x, r0.x, l(0), r0.z
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.z;
    // mad r0.x, r0.w, r0.y, r0.x
    r0.x = r0.w * r0.y + r0.x;
    // div r0.yz, v7.xxyx, v7.wwww
    float stage10_y = v7.x / v7.w;
    float stage10_z = v7.y / v7.w;
    r0.y = stage10_y;
    r0.z = stage10_z;
    // mad r0.yz, r0.yyzy, cb2[0].xxyx, cb2[0].wwzw
    float stage11_y = r0.y * cb2[0].x + cb2[0].w;
    float stage11_z = r0.z * cb2[0].y + cb2[0].z;
    r0.y = stage11_y;
    r0.z = stage11_z;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t1.yxzw, s0, l(0.000000)
    float4 fetch12 = t1.SampleLevel(s0, r0.yz, 0.0f);
    r0.y = fetch12.x;
    // min r0.y, r0.y, l(0.999000)
    r0.y = min(r0.y, 0.999f);
    // mad r0.z, r0.y, cb2[1].z, -cb2[1].w
    r0.z = r0.y * cb2[1].z + -cb2[1].w;
    // mad r0.y, r0.y, cb2[1].x, cb2[1].y
    r0.y = r0.y * cb2[1].x + cb2[1].y;
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // add r0.y, r0.z, r0.y
    r0.y = r0.z + r0.y;
    // add r0.y, r0.y, -v7.w
    r0.y = r0.y + -v7.w;
    // add r0.z, -cb0[3].x, l(1.000000)
    r0.z = -cb0[3].x + 1.0f;
    // max r0.z, -r0.z, l(0.001000)
    r0.z = max(-r0.z, 0.001f);
    // div_sat r0.y, r0.y, r0.z
    r0.y = saturate(r0.y / r0.z);
    // mul r0.x, r0.y, r0.x
    r0.x = r0.y * r0.x;
    // mul_sat r0.x, r0.x, v3.w
    r0.x = saturate(r0.x * v3.w);
    // mul r0.x, r0.x, cb0[0].x
    r0.x = r0.x * cb0[0].x;
    // add r0.yzw, v3.xxyz, cb0[1].xxyz
    float stage13_y = v3.x + cb0[1].x;
    float stage13_z = v3.y + cb0[1].y;
    float stage13_w = v3.z + cb0[1].z;
    r0.y = stage13_y;
    r0.z = stage13_z;
    r0.w = stage13_w;
    // mul r0.yzw, r0.yyzw, v5.wwww
    float stage14_y = r0.y * v5.w;
    float stage14_z = r0.z * v5.w;
    float stage14_w = r0.w * v5.w;
    r0.y = stage14_y;
    r0.z = stage14_z;
    r0.w = stage14_w;
    // mul o0.xyz, r0.xxxx, r0.yzwy
    float stage15_x = r0.x * r0.y;
    float stage15_y = r0.x * r0.z;
    float stage15_z = r0.x * r0.w;
    o0.x = stage15_x;
    o0.y = stage15_y;
    o0.z = stage15_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_d_pa_flare_02_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
