// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_ringmaster_01_tr_Constants0 : register(b0)
{
    float4 cb0[16];
};
cbuffer Shade_Ue3_fx_d_pa_ringmaster_01_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
SamplerState s5 : register(s5);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);
Texture2D t5 : register(t5);

struct Shade_Ue3_fx_d_pa_ringmaster_01_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v6;
    float4 v7;
};

struct Shade_Ue3_fx_d_pa_ringmaster_01_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_d_pa_ringmaster_01_tr_OUTPUT Shade_Ue3_fx_d_pa_ringmaster_01_tr(Shade_Ue3_fx_d_pa_ringmaster_01_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v6 = stage.v6;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // add r0.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.x + -0.5f;
    float stage1_y = v2.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.y|, |r0.x|
    r0.z = max(abs(r0.y), abs(r0.x));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.y|, |r0.x|
    r0.w = min(abs(r0.y), abs(r0.x));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.y|, |r0.x|
    r1.y = asfloat((abs(r0.y) < abs(r0.x)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.y, -r0.y
    r0.w = asfloat((r0.y < -r0.y) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.y, r0.x
    r0.w = min(r0.y, r0.x);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.y, r0.x
    r1.x = max(r0.y, r0.x);
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // ge r0.y, r1.x, -r1.x
    r0.y = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.y, r0.y, r0.w
    r0.y = asfloat(asuint(r0.y) & asuint(r0.w));
    // movc r0.y, r0.y, -r0.z, r0.z
    r0.y = asuint(r0.y) != 0u ? -r0.z : r0.z;
    // mad r1.x, r0.y, l(0.159155), l(0.500000)
    r1.x = r0.y * 0.159155f + 0.5f;
    // mul r0.yz, v2.xxyx, cb0[10].xxyx
    float stage2_y = v2.x * cb0[10].x;
    float stage2_z = v2.y * cb0[10].y;
    r0.y = stage2_y;
    r0.z = stage2_z;
    // mad r2.x, cb0[9].w, cb0[9].z, r0.y
    r2.x = cb0[9].w * cb0[9].z + r0.y;
    // mad r2.y, cb0[9].w, cb0[10].z, r0.z
    r2.y = cb0[9].w * cb0[10].z + r0.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.yz, r2.xyxx, t0.zxyw, s2, l(0.000000)
    float4 fetch3 = t0.SampleBias(s2, r2.xy, 0.0f);
    r0.y = fetch3.x;
    r0.z = fetch3.y;
    // mul r0.w, v4.y, cb0[10].w
    r0.w = v4.y * cb0[10].w;
    // mul r1.z, v4.z, cb0[9].y
    r1.z = v4.z * cb0[9].y;
    // add r1.w, r0.x, r0.x
    r1.w = r0.x + r0.x;
    // log r1.w, r1.w
    r1.w = log2(r1.w);
    // mul r1.z, r1.w, r1.z
    r1.z = r1.w * r1.z;
    // exp r1.z, r1.z
    r1.z = exp2(r1.z);
    // lt r1.w, r0.x, l(0.000000)
    r1.w = asfloat((r0.x < 0.0f) ? 0xffffffffu : 0u);
    // movc r1.y, r1.w, l(0), r1.z
    r1.y = asuint(r1.w) != 0u ? asfloat(0u) : r1.z;
    // mad r0.yz, r0.wwww, r0.yyzy, r1.xxyx
    float stage4_y = r0.w * r0.y + r1.x;
    float stage4_z = r0.w * r0.z + r1.y;
    r0.y = stage4_y;
    r0.z = stage4_z;
    // mul r1.x, r0.y, cb0[3].x
    r1.x = r0.y * cb0[3].x;
    // mad r2.z, r0.z, cb0[3].y, v4.x
    r2.z = r0.z * cb0[3].y + v4.x;
    // mul r2.x, cb0[9].w, cb0[11].z
    r2.x = cb0[9].w * cb0[11].z;
    // mov r1.z, l(-1.000000)
    r1.z = -1.0f;
    // add r1.xy, r1.xzxx, r2.xzxx
    float stage5_x = r1.x + r2.x;
    float stage5_y = r1.z + r2.z;
    r1.x = stage5_x;
    r1.y = stage5_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t1.yzwx, s1, l(-1.000000)
    float4 fetch6 = t1.SampleLevel(s1, r1.xy, -1.0f);
    r0.w = fetch6.x;
    // mad r1.x, -r0.x, cb0[6].x, l(1.000000)
    r1.x = -r0.x * cb0[6].x + 1.0f;
    // mad r0.x, -r0.x, cb0[7].w, l(1.000000)
    r0.x = -r0.x * cb0[7].w + 1.0f;
    // mul_sat r0.x, r0.x, cb0[8].w
    r0.x = saturate(r0.x * cb0[8].w);
    // mul_sat r1.x, r1.x, cb0[7].x
    r1.x = saturate(r1.x * cb0[7].x);
    // add r1.x, -r1.x, l(1.000000)
    r1.x = -r1.x + 1.0f;
    // mul r0.x, r0.x, r1.x
    r0.x = r0.x * r1.x;
    // lt r1.x, r0.x, l(0.000001)
    r1.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // log r0.x, r0.x
    r0.x = log2(r0.x);
    // mul r0.x, r0.x, cb0[9].x
    r0.x = r0.x * cb0[9].x;
    // exp r0.x, r0.x
    r0.x = exp2(r0.x);
    // movc r0.x, r1.x, l(0), r0.x
    r0.x = asuint(r1.x) != 0u ? asfloat(0u) : r0.x;
    // mul r0.x, r0.w, r0.x
    r0.x = r0.w * r0.x;
    // mul r1.xy, r0.yzyy, cb0[12].xyxx
    float stage7_x = r0.y * cb0[12].x;
    float stage7_y = r0.z * cb0[12].y;
    r1.x = stage7_x;
    r1.y = stage7_y;
    // mul r0.yz, r0.yyzy, cb0[13].xxyx
    float stage8_y = r0.y * cb0[13].x;
    float stage8_z = r0.z * cb0[13].y;
    r0.y = stage8_y;
    r0.z = stage8_z;
    // mad r2.x, cb0[11].w, cb0[9].w, r1.x
    r2.x = cb0[11].w * cb0[9].w + r1.x;
    // mad r2.y, cb0[9].w, cb0[12].z, r1.y
    r2.y = cb0[9].w * cb0[12].z + r1.y;
    // sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, r2.xyxx, t3.xyzw, s3, l(-1.000000)
    float4 fetch9 = t3.SampleLevel(s3, r2.xy, -1.0f);
    r1.x = fetch9.x;
    r1.y = fetch9.y;
    r1.z = fetch9.z;
    // mad r2.x, cb0[9].w, cb0[12].w, r0.y
    r2.x = cb0[9].w * cb0[12].w + r0.y;
    // mad r2.y, cb0[9].w, cb0[13].z, r0.z
    r2.y = cb0[9].w * cb0[13].z + r0.z;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.yzw, r2.xyxx, t4.wxyz, s4, l(-1.000000)
    float4 fetch10 = t4.SampleLevel(s4, r2.xy, -1.0f);
    r0.y = fetch10.x;
    r0.z = fetch10.y;
    r0.w = fetch10.z;
    // add r0.yzw, r0.yyzw, r1.xxyz
    float stage11_y = r0.y + r1.x;
    float stage11_z = r0.z + r1.y;
    float stage11_w = r0.w + r1.z;
    r0.y = stage11_y;
    r0.z = stage11_z;
    r0.w = stage11_w;
    // add r1.x, r0.z, r0.y
    r1.x = r0.z + r0.y;
    // add r1.x, r0.w, r1.x
    r1.x = r0.w + r1.x;
    // mad r1.x, r1.x, l(0.333330), -r0.x
    r1.x = r1.x * 0.33333f + -r0.x;
    // mad r1.x, cb0[13].w, r1.x, r0.x
    r1.x = cb0[13].w * r1.x + r0.x;
    // mul_sat r0.x, r0.x, cb0[15].y
    r0.x = saturate(r0.x * cb0[15].y);
    // mul r1.x, r1.x, cb0[14].x
    r1.x = r1.x * cb0[14].x;
    // dp3 r1.y, v6.xyzx, v6.xyzx
    r1.y = dot(v6.xyz, v6.xyz);
    // rsq r1.y, r1.y
    r1.y = rsqrt(r1.y);
    // mul r1.yzw, r1.yyyy, v6.xxyz
    float stage12_y = r1.y * v6.x;
    float stage12_z = r1.y * v6.y;
    float stage12_w = r1.y * v6.z;
    r1.y = stage12_y;
    r1.z = stage12_z;
    r1.w = stage12_w;
    // mad r1.yz, r1.yyzy, l(0.000000, -0.500000, -0.500000, 0.000000), l(0.000000, 0.500000, 0.500000, 0.000000)
    float stage13_y = r1.y * -0.5f + 0.5f;
    float stage13_z = r1.z * -0.5f + 0.5f;
    r1.y = stage13_y;
    r1.z = stage13_z;
    // add r1.w, -|r1.w|, l(1.000000)
    r1.w = -(abs(r1.w)) + 1.0f;
    // mul r1.w, r1.w, r1.w
    r1.w = r1.w * r1.w;
    // mad r1.xy, r1.yzyy, cb0[2].xyxx, r1.xxxx
    float stage14_x = r1.y * cb0[2].x + r1.x;
    float stage14_y = r1.z * cb0[2].y + r1.x;
    r1.x = stage14_x;
    r1.y = stage14_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t5.xyzw, s5, l(0.000000)
    float4 fetch15 = t5.SampleBias(s5, r1.xy, 0.0f);
    r1.x = fetch15.x;
    r1.y = fetch15.y;
    r1.z = fetch15.z;
    // dp3 r2.x, r1.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r2.x = dot(r1.xyz, float3(0.3f, 0.59f, 0.11f));
    // add r2.xyz, -r1.xyzx, r2.xxxx
    float stage16_x = -r1.x + r2.x;
    float stage16_y = -r1.y + r2.x;
    float stage16_z = -r1.z + r2.x;
    r2.x = stage16_x;
    r2.y = stage16_y;
    r2.z = stage16_z;
    // mad r1.xyz, cb0[14].yyyy, r2.xyzx, r1.xyzx
    float stage17_x = cb0[14].y * r2.x + r1.x;
    float stage17_y = cb0[14].y * r2.y + r1.y;
    float stage17_z = cb0[14].y * r2.z + r1.z;
    r1.x = stage17_x;
    r1.y = stage17_y;
    r1.z = stage17_z;
    // max r1.xyz, |r1.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage18_x = max(abs(r1.x), 1e-06f);
    float stage18_y = max(abs(r1.y), 1e-06f);
    float stage18_z = max(abs(r1.z), 1e-06f);
    r1.x = stage18_x;
    r1.y = stage18_y;
    r1.z = stage18_z;
    // log r1.xyz, r1.xyzx
    float stage19_x = log2(r1.x);
    float stage19_y = log2(r1.y);
    float stage19_z = log2(r1.z);
    r1.x = stage19_x;
    r1.y = stage19_y;
    r1.z = stage19_z;
    // mul r1.xyz, r1.xyzx, cb0[14].zzzz
    float stage20_x = r1.x * cb0[14].z;
    float stage20_y = r1.y * cb0[14].z;
    float stage20_z = r1.z * cb0[14].z;
    r1.x = stage20_x;
    r1.y = stage20_y;
    r1.z = stage20_z;
    // exp r1.xyz, r1.xyzx
    float stage21_x = exp2(r1.x);
    float stage21_y = exp2(r1.y);
    float stage21_z = exp2(r1.z);
    r1.x = stage21_x;
    r1.y = stage21_y;
    r1.z = stage21_z;
    // mul r2.xyz, cb0[4].xyzx, cb0[4].wwww
    float stage22_x = cb0[4].x * cb0[4].w;
    float stage22_y = cb0[4].y * cb0[4].w;
    float stage22_z = cb0[4].z * cb0[4].w;
    r2.x = stage22_x;
    r2.y = stage22_y;
    r2.z = stage22_z;
    // mul r1.xyz, r1.xyzx, r2.xyzx
    float stage23_x = r1.x * r2.x;
    float stage23_y = r1.y * r2.y;
    float stage23_z = r1.z * r2.z;
    r1.x = stage23_x;
    r1.y = stage23_y;
    r1.z = stage23_z;
    // dp3 r2.x, r0.yzwy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r2.x = dot(r0.yzw, float3(0.3f, 0.59f, 0.11f));
    // add r2.xyz, -r0.yzwy, r2.xxxx
    float stage24_x = -r0.y + r2.x;
    float stage24_y = -r0.z + r2.x;
    float stage24_z = -r0.w + r2.x;
    r2.x = stage24_x;
    r2.y = stage24_y;
    r2.z = stage24_z;
    // mad r0.yzw, cb0[14].wwww, r2.xxyz, r0.yyzw
    float stage25_y = cb0[14].w * r2.x + r0.y;
    float stage25_z = cb0[14].w * r2.y + r0.z;
    float stage25_w = cb0[14].w * r2.z + r0.w;
    r0.y = stage25_y;
    r0.z = stage25_z;
    r0.w = stage25_w;
    // max r0.yzw, |r0.yyzw|, l(0.000000, 0.000001, 0.000001, 0.000001)
    float stage26_y = max(abs(r0.y), 1e-06f);
    float stage26_z = max(abs(r0.z), 1e-06f);
    float stage26_w = max(abs(r0.w), 1e-06f);
    r0.y = stage26_y;
    r0.z = stage26_z;
    r0.w = stage26_w;
    // log r0.yzw, r0.yyzw
    float stage27_y = log2(r0.y);
    float stage27_z = log2(r0.z);
    float stage27_w = log2(r0.w);
    r0.y = stage27_y;
    r0.z = stage27_z;
    r0.w = stage27_w;
    // mul r0.yzw, r0.yyzw, cb0[15].xxxx
    float stage28_y = r0.y * cb0[15].x;
    float stage28_z = r0.z * cb0[15].x;
    float stage28_w = r0.w * cb0[15].x;
    r0.y = stage28_y;
    r0.z = stage28_z;
    r0.w = stage28_w;
    // exp r0.yzw, r0.yyzw
    float stage29_y = exp2(r0.y);
    float stage29_z = exp2(r0.z);
    float stage29_w = exp2(r0.w);
    r0.y = stage29_y;
    r0.z = stage29_z;
    r0.w = stage29_w;
    // mul r2.xyz, cb0[5].xyzx, cb0[5].wwww
    float stage30_x = cb0[5].x * cb0[5].w;
    float stage30_y = cb0[5].y * cb0[5].w;
    float stage30_z = cb0[5].z * cb0[5].w;
    r2.x = stage30_x;
    r2.y = stage30_y;
    r2.z = stage30_z;
    // mul r0.yzw, r0.yyzw, r2.xxyz
    float stage31_y = r0.y * r2.x;
    float stage31_z = r0.z * r2.y;
    float stage31_w = r0.w * r2.z;
    r0.y = stage31_y;
    r0.z = stage31_z;
    r0.w = stage31_w;
    // mad r0.yzw, r1.wwww, r1.xxyz, r0.yyzw
    float stage32_y = r1.w * r1.x + r0.y;
    float stage32_z = r1.w * r1.y + r0.z;
    float stage32_w = r1.w * r1.z + r0.w;
    r0.y = stage32_y;
    r0.z = stage32_z;
    r0.w = stage32_w;
    // mad r0.yzw, r0.yyzw, v3.xxyz, cb0[1].xxyz
    float stage33_y = r0.y * v3.x + cb0[1].x;
    float stage33_z = r0.z * v3.y + cb0[1].y;
    float stage33_w = r0.w * v3.z + cb0[1].z;
    r0.y = stage33_y;
    r0.z = stage33_z;
    r0.w = stage33_w;
    // mad o0.xyz, r0.yzwy, v5.wwww, v5.xyzx
    float stage34_x = r0.y * v5.w + v5.x;
    float stage34_y = r0.z * v5.w + v5.y;
    float stage34_z = r0.w * v5.w + v5.z;
    o0.x = stage34_x;
    o0.y = stage34_y;
    o0.z = stage34_z;
    // log r0.y, r0.x
    r0.y = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[15].z
    r0.y = r0.y * cb0[15].z;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // div r0.yz, v7.xxyx, v7.wwww
    float stage35_y = v7.x / v7.w;
    float stage35_z = v7.y / v7.w;
    r0.y = stage35_y;
    r0.z = stage35_z;
    // mad r0.yz, r0.yyzy, cb2[0].xxyx, cb2[0].wwzw
    float stage36_y = r0.y * cb2[0].x + cb2[0].w;
    float stage36_z = r0.z * cb2[0].y + cb2[0].z;
    r0.y = stage36_y;
    r0.z = stage36_z;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t2.yxzw, s0, l(0.000000)
    float4 fetch37 = t2.SampleLevel(s0, r0.yz, 0.0f);
    r0.y = fetch37.x;
    // min r0.y, r0.y, l(0.999000)
    r0.y = min(r0.y, 0.999f);
    // mad r0.z, r0.y, cb2[1].z, -cb2[1].w
    r0.z = r0.y * cb2[1].z + -cb2[1].w;
    // mad r0.y, r0.y, cb2[1].x, cb2[1].y
    r0.y = r0.y * cb2[1].x + cb2[1].y;
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // add r0.y, r0.z, r0.y
    r0.y = r0.z + r0.y;
    // add r0.y, r0.y, -v7.w
    r0.y = r0.y + -v7.w;
    // add r0.z, -cb0[15].w, l(1.000000)
    r0.z = -cb0[15].w + 1.0f;
    // max r0.z, -r0.z, l(0.001000)
    r0.z = max(-r0.z, 0.001f);
    // div_sat r0.y, r0.y, r0.z
    r0.y = saturate(r0.y / r0.z);
    // mul r0.x, r0.y, r0.x
    r0.x = r0.y * r0.x;
    // mul_sat r0.x, r0.x, v3.w
    r0.x = saturate(r0.x * v3.w);
    // mul o0.w, r0.x, cb0[0].x
    o0.w = r0.x * cb0[0].x;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage38_x = r0.x * v1.x;
    float stage38_y = r0.x * v1.y;
    float stage38_z = r0.x * v1.z;
    r0.x = stage38_x;
    r0.y = stage38_y;
    r0.z = stage38_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage39_x = r0.w * v0.z;
    float stage39_y = r0.w * v0.x;
    float stage39_z = r0.w * v0.y;
    r1.x = stage39_x;
    r1.y = stage39_y;
    r1.z = stage39_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage40_x = r0.x * r1.x;
    float stage40_y = r0.x * r1.y;
    float stage40_z = r0.x * r1.z;
    r0.x = stage40_x;
    r0.y = stage40_y;
    r0.z = stage40_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage41_x = r0.x / r0.w;
    float stage41_y = r0.y / r0.w;
    r0.x = stage41_x;
    r0.y = stage41_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage42_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage42_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage42_x;
    r1.y = stage42_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage43_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage43_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage43_x;
    r1.y = stage43_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage44_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage44_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage44_x;
    r1.y = stage44_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage45_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage45_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage45_x;
    r0.y = stage45_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage46_x = r0.x * 0.5f + 0.5f;
    float stage46_y = r0.y * 0.5f + 0.5f;
    o2.x = stage46_x;
    o2.y = stage46_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage47_z = 1.0f;
    float stage47_w = asfloat(0u);
    o2.z = stage47_z;
    o2.w = stage47_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage48_x = cb2[3].x;
    float stage48_y = cb2[3].y;
    float stage48_z = cb2[3].z;
    o3.x = stage48_x;
    o3.y = stage48_y;
    o3.z = stage48_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage49_x = asfloat(0u);
    float stage49_y = asfloat(0u);
    float stage49_z = asfloat(0u);
    float stage49_w = asfloat(0u);
    o4.x = stage49_x;
    o4.y = stage49_y;
    o4.z = stage49_z;
    o4.w = stage49_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage50_x = asfloat(0u);
    float stage50_y = asfloat(0u);
    float stage50_z = asfloat(0u);
    float stage50_w = asfloat(0u);
    o5.x = stage50_x;
    o5.y = stage50_y;
    o5.z = stage50_z;
    o5.w = stage50_w;

    Shade_Ue3_fx_d_pa_ringmaster_01_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
