// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_ring_11_ad_Constants0 : register(b0)
{
    float4 cb0[6];
};
SamplerState s0 : register(s0);
Texture2D t0 : register(t0);

struct Shade_Ue3_fx_d_pa_ring_11_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_d_pa_ring_11_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_d_pa_ring_11_ad_OUTPUT Shade_Ue3_fx_d_pa_ring_11_ad(Shade_Ue3_fx_d_pa_ring_11_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;

    // add r0.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.x + -0.5f;
    float stage1_y = v2.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.y|, |r0.x|
    r0.z = max(abs(r0.y), abs(r0.x));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.y|, |r0.x|
    r0.w = min(abs(r0.y), abs(r0.x));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.y|, |r0.x|
    r1.y = asfloat((abs(r0.y) < abs(r0.x)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.y, -r0.y
    r0.w = asfloat((r0.y < -r0.y) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.y, r0.x
    r0.w = min(r0.y, r0.x);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.y, r0.x
    r1.x = max(r0.y, r0.x);
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // ge r0.y, r1.x, -r1.x
    r0.y = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.y, r0.y, r0.w
    r0.y = asfloat(asuint(r0.y) & asuint(r0.w));
    // movc r0.y, r0.y, -r0.z, r0.z
    r0.y = asuint(r0.y) != 0u ? -r0.z : r0.z;
    // mad r0.y, r0.y, l(0.159155), l(0.500000)
    r0.y = r0.y * 0.159155f + 0.5f;
    // mul r0.y, r0.y, cb0[2].w
    r0.y = r0.y * cb0[2].w;
    // mad r1.x, cb0[2].z, cb0[2].y, r0.y
    r1.x = cb0[2].z * cb0[2].y + r0.y;
    // mul r0.y, r0.x, cb0[3].x
    r0.y = r0.x * cb0[3].x;
    // mad r0.x, -r0.x, cb0[4].z, l(1.000000)
    r0.x = -r0.x * cb0[4].z + 1.0f;
    // mul r0.y, r0.y, l(2.000000)
    r0.y = r0.y * 2.0f;
    // mad r1.y, cb0[2].z, cb0[3].y, r0.y
    r1.y = cb0[2].z * cb0[3].y + r0.y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.yzw, r1.xyxx, t0.wxyz, s0, cb0[2].x
    float4 fetch2 = t0.SampleLevel(s0, r1.xy, cb0[2].x);
    r0.y = fetch2.x;
    r0.z = fetch2.y;
    r0.w = fetch2.z;
    // add r0.y, r0.z, r0.y
    r0.y = r0.z + r0.y;
    // add r0.y, r0.w, r0.y
    r0.y = r0.w + r0.y;
    // mul r0.y, r0.y, cb0[3].z
    r0.y = r0.y * cb0[3].z;
    // mul_sat r0.y, r0.y, l(0.330000)
    r0.y = saturate(r0.y * 0.33f);
    // log r0.z, r0.y
    r0.z = log2(r0.y);
    // lt r0.y, r0.y, l(0.000001)
    r0.y = asfloat((r0.y < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, cb0[3].w
    r0.z = r0.z * cb0[3].w;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // movc r0.y, r0.y, l(0), r0.z
    r0.y = asuint(r0.y) != 0u ? asfloat(0u) : r0.z;
    // mov_sat r0.z, v4.z
    r0.z = saturate(v4.z);
    // mul_sat r0.w, v4.y, cb0[4].w
    r0.w = saturate(v4.y * cb0[4].w);
    // add r0.zw, -r0.zzzw, l(0.000000, 0.000000, 1.000000, 1.000000)
    float stage3_z = -r0.z + 1.0f;
    float stage3_w = -r0.w + 1.0f;
    r0.z = stage3_z;
    r0.w = stage3_w;
    // add r0.w, -r0.w, l(1.000000)
    r0.w = -r0.w + 1.0f;
    // max r0.w, r0.w, l(0.000010)
    r0.w = max(r0.w, 1e-05f);
    // div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
    r0.w = 1.0f / r0.w;
    // mul_sat r0.x, r0.w, r0.x
    r0.x = saturate(r0.w * r0.x);
    // mad r0.x, r0.x, l(-2.000000), l(1.000000)
    r0.x = r0.x * -2.0f + 1.0f;
    // add r0.x, -|r0.x|, l(1.000000)
    r0.x = -(abs(r0.x)) + 1.0f;
    // log r0.w, r0.x
    r0.w = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.x, v4.x, cb0[5].x
    r1.x = v4.x * cb0[5].x;
    // mul r0.w, r0.w, r1.x
    r0.w = r0.w * r1.x;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // movc r0.x, r0.x, l(0), r0.w
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.w;
    // mad_sat r0.x, r0.y, r0.x, -r0.z
    r0.x = saturate(r0.y * r0.x + -r0.z);
    // mul_sat r0.x, r0.x, v3.w
    r0.x = saturate(r0.x * v3.w);
    // mul r0.x, r0.x, cb0[0].x
    r0.x = r0.x * cb0[0].x;
    // add r0.yzw, v3.xxyz, cb0[1].xxyz
    float stage4_y = v3.x + cb0[1].x;
    float stage4_z = v3.y + cb0[1].y;
    float stage4_w = v3.z + cb0[1].z;
    r0.y = stage4_y;
    r0.z = stage4_z;
    r0.w = stage4_w;
    // mul r0.yzw, r0.yyzw, v5.wwww
    float stage5_y = r0.y * v5.w;
    float stage5_z = r0.z * v5.w;
    float stage5_w = r0.w * v5.w;
    r0.y = stage5_y;
    r0.z = stage5_z;
    r0.w = stage5_w;
    // mul o0.xyz, r0.xxxx, r0.yzwy
    float stage6_x = r0.x * r0.y;
    float stage6_y = r0.x * r0.z;
    float stage6_z = r0.x * r0.w;
    o0.x = stage6_x;
    o0.y = stage6_y;
    o0.z = stage6_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_d_pa_ring_11_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
