// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_me_kazerosmark_tr_Constants0 : register(b0)
{
    float4 cb0[11];
};
cbuffer Shade_Ue3_fx_d_me_kazerosmark_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
SamplerState s5 : register(s5);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);
Texture2D t5 : register(t5);

struct Shade_Ue3_fx_d_me_kazerosmark_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v4;
    float4 v5;
    float4 v6;
    float4 v7;
};

struct Shade_Ue3_fx_d_me_kazerosmark_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_d_me_kazerosmark_tr_OUTPUT Shade_Ue3_fx_d_me_kazerosmark_tr(Shade_Ue3_fx_d_me_kazerosmark_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v6 = stage.v6;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mul r0.xy, v4.xyxx, cb0[6].zwzz
    float stage1_x = v4.x * cb0[6].z;
    float stage1_y = v4.y * cb0[6].w;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // mad r1.x, cb0[6].y, cb0[6].x, r0.x
    r1.x = cb0[6].y * cb0[6].x + r0.x;
    // mad r1.y, cb0[6].y, cb0[7].x, r0.y
    r1.y = cb0[6].y * cb0[7].x + r0.y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.xy, r1.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch2 = t0.SampleBias(s0, r1.xy, 0.0f);
    r0.x = fetch2.x;
    r0.y = fetch2.y;
    // mad r0.xy, r0.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
    float stage3_x = r0.x * 2.0f + -1.0f;
    float stage3_y = r0.y * 2.0f + -1.0f;
    r0.x = stage3_x;
    r0.y = stage3_y;
    // mul r0.zw, r0.xxxy, cb0[7].yyyy
    float stage4_z = r0.x * cb0[7].y;
    float stage4_w = r0.y * cb0[7].y;
    r0.z = stage4_z;
    r0.w = stage4_w;
    // div r1.xy, v7.xyxx, v7.wwww
    float stage5_x = v7.x / v7.w;
    float stage5_y = v7.y / v7.w;
    r1.x = stage5_x;
    r1.y = stage5_y;
    // mad r1.xy, r1.xyxx, cb2[0].xyxx, cb2[0].wzww
    float stage6_x = r1.x * cb2[0].x + cb2[0].w;
    float stage6_y = r1.y * cb2[0].y + cb2[0].z;
    r1.x = stage6_x;
    r1.y = stage6_y;
    // mad r1.zw, r1.xxxy, l(0.000000, 0.000000, 12.000000, 12.000000), r0.zzzw
    float stage7_z = r1.x * 12.0f + r0.z;
    float stage7_w = r1.y * 12.0f + r0.w;
    r1.z = stage7_z;
    r1.w = stage7_w;
    // mad r0.zw, r1.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), r0.zzzw
    float stage8_z = r1.x * 2.0f + r0.z;
    float stage8_w = r1.y * 2.0f + r0.w;
    r0.z = stage8_z;
    r0.w = stage8_w;
    // mul r1.xy, r1.xyxx, l(12.000000, 12.000000, 0.000000, 0.000000)
    float stage9_x = r1.x * 12.0f;
    float stage9_y = r1.y * 12.0f;
    r1.x = stage9_x;
    r1.y = stage9_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xyz, r1.xyxx, t4.xyzw, s1, l(0.000000)
    float4 fetch10 = t4.SampleBias(s1, r1.xy, 0.0f);
    r2.x = fetch10.x;
    r2.y = fetch10.y;
    r2.z = fetch10.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r3.xyz, r0.zwzz, t5.xyzw, s2, l(0.000000)
    float4 fetch11 = t5.SampleBias(s2, r0.zw, 0.0f);
    r3.x = fetch11.x;
    r3.y = fetch11.y;
    r3.z = fetch11.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyz, r1.zwzz, t4.xyzw, s1, l(0.000000)
    float4 fetch12 = t4.SampleBias(s1, r1.zw, 0.0f);
    r1.x = fetch12.x;
    r1.y = fetch12.y;
    r1.z = fetch12.z;
    // mul r1.xyz, r2.xyzx, r1.xyzx
    float stage13_x = r2.x * r1.x;
    float stage13_y = r2.y * r1.y;
    float stage13_z = r2.z * r1.z;
    r1.x = stage13_x;
    r1.y = stage13_y;
    r1.z = stage13_z;
    // max r1.xyz, |r1.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage14_x = max(abs(r1.x), 1e-06f);
    float stage14_y = max(abs(r1.y), 1e-06f);
    float stage14_z = max(abs(r1.z), 1e-06f);
    r1.x = stage14_x;
    r1.y = stage14_y;
    r1.z = stage14_z;
    // mul r1.xyz, r1.xyzx, r1.xyzx
    float stage15_x = r1.x * r1.x;
    float stage15_y = r1.y * r1.y;
    float stage15_z = r1.z * r1.z;
    r1.x = stage15_x;
    r1.y = stage15_y;
    r1.z = stage15_z;
    // mul r1.xyz, r1.xyzx, r1.xyzx
    float stage16_x = r1.x * r1.x;
    float stage16_y = r1.y * r1.y;
    float stage16_z = r1.z * r1.z;
    r1.x = stage16_x;
    r1.y = stage16_y;
    r1.z = stage16_z;
    // mad r1.xyz, r1.xyzx, l(5.000000, 5.000000, 5.000000, 0.000000), r3.xyzx
    float stage17_x = r1.x * 5.0f + r3.x;
    float stage17_y = r1.y * 5.0f + r3.y;
    float stage17_z = r1.z * 5.0f + r3.z;
    r1.x = stage17_x;
    r1.y = stage17_y;
    r1.z = stage17_z;
    // dp3 r0.z, r1.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.z = dot(r1.xyz, float3(0.3f, 0.59f, 0.11f));
    // add r2.xyz, -r1.xyzx, r0.zzzz
    float stage18_x = -r1.x + r0.z;
    float stage18_y = -r1.y + r0.z;
    float stage18_z = -r1.z + r0.z;
    r2.x = stage18_x;
    r2.y = stage18_y;
    r2.z = stage18_z;
    // mad r1.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx
    float stage19_x = r2.x * 0.5f + r1.x;
    float stage19_y = r2.y * 0.5f + r1.y;
    float stage19_z = r2.z * 0.5f + r1.z;
    r1.x = stage19_x;
    r1.y = stage19_y;
    r1.z = stage19_z;
    // mad r0.zw, cb0[7].yyyy, r0.xxxy, v4.xxxy
    float stage20_z = cb0[7].y * r0.x + v4.x;
    float stage20_w = cb0[7].y * r0.y + v4.y;
    r0.z = stage20_z;
    r0.w = stage20_w;
    // dp3 r1.w, v6.xyzx, v6.xyzx
    r1.w = dot(v6.xyz, v6.xyz);
    // rsq r1.w, r1.w
    r1.w = rsqrt(r1.w);
    // mul r2.xyz, r1.wwww, v6.xyzx
    float stage21_x = r1.w * v6.x;
    float stage21_y = r1.w * v6.y;
    float stage21_z = r1.w * v6.z;
    r2.x = stage21_x;
    r2.y = stage21_y;
    r2.z = stage21_z;
    // mad r2.xy, r2.xyxx, l(-1.525000, -1.525000, 0.000000, 0.000000), r0.zwzz
    float stage22_x = r2.x * -1.525f + r0.z;
    float stage22_y = r2.y * -1.525f + r0.w;
    r2.x = stage22_x;
    r2.y = stage22_y;
    // add r1.w, -|r2.z|, l(1.000000)
    r1.w = -(abs(r2.z)) + 1.0f;
    // add r2.xy, r2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage23_x = r2.x + -0.5f;
    float stage23_y = r2.y + -0.5f;
    r2.x = stage23_x;
    r2.y = stage23_y;
    // dp2 r2.x, r2.xyxx, r2.xyxx
    r2.x = dot(r2.xy, r2.xy);
    // sqrt r2.x, r2.x
    r2.x = sqrt(r2.x);
    // min r2.x, r2.x, l(1.000000)
    r2.x = min(r2.x, 1.0f);
    // add r2.x, -r2.x, l(1.000000)
    r2.x = -r2.x + 1.0f;
    // mul r2.y, r2.x, r2.x
    r2.y = r2.x * r2.x;
    // mul r2.y, r2.y, r2.x
    r2.y = r2.y * r2.x;
    // lt r2.x, r2.x, l(0.000001)
    r2.x = asfloat((r2.x < 1e-06f) ? 0xffffffffu : 0u);
    // movc r2.x, r2.x, l(0), r2.y
    r2.x = asuint(r2.x) != 0u ? asfloat(0u) : r2.y;
    // mul r2.xyz, r1.xyzx, r2.xxxx
    float stage24_x = r1.x * r2.x;
    float stage24_y = r1.y * r2.x;
    float stage24_z = r1.z * r2.x;
    r2.x = stage24_x;
    r2.y = stage24_y;
    r2.z = stage24_z;
    // mul r2.xyz, r2.xyzx, l(0.900000, 0.900000, 0.900000, 0.000000)
    float stage25_x = r2.x * 0.9f;
    float stage25_y = r2.y * 0.9f;
    float stage25_z = r2.z * 0.9f;
    r2.x = stage25_x;
    r2.y = stage25_y;
    r2.z = stage25_z;
    // mad r1.xyz, r1.xyzx, l(0.100000, 0.100000, 0.100000, 0.000000), r2.xyzx
    float stage26_x = r1.x * 0.1f + r2.x;
    float stage26_y = r1.y * 0.1f + r2.y;
    float stage26_z = r1.z * 0.1f + r2.z;
    r1.x = stage26_x;
    r1.y = stage26_y;
    r1.z = stage26_z;
    // mul r2.xyz, cb0[3].xyzx, cb0[3].wwww
    float stage27_x = cb0[3].x * cb0[3].w;
    float stage27_y = cb0[3].y * cb0[3].w;
    float stage27_z = cb0[3].z * cb0[3].w;
    r2.x = stage27_x;
    r2.y = stage27_y;
    r2.z = stage27_z;
    // mul r1.xyz, r1.xyzx, r2.xyzx
    float stage28_x = r1.x * r2.x;
    float stage28_y = r1.y * r2.y;
    float stage28_z = r1.z * r2.z;
    r1.x = stage28_x;
    r1.y = stage28_y;
    r1.z = stage28_z;
    // mul r2.xy, v4.xyxx, cb0[5].xyxx
    float stage29_x = v4.x * cb0[5].x;
    float stage29_y = v4.y * cb0[5].y;
    r2.x = stage29_x;
    r2.y = stage29_y;
    // mad r0.xy, cb0[7].yyyy, r0.xyxx, |r2.xyxx|
    float stage30_x = cb0[7].y * r0.x + abs(r2.x);
    float stage30_y = cb0[7].y * r0.y + abs(r2.y);
    r0.x = stage30_x;
    r0.y = stage30_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xyz, r0.xyxx, t3.xyzw, s3, l(0.000000)
    float4 fetch31 = t3.SampleBias(s3, r0.xy, 0.0f);
    r2.x = fetch31.x;
    r2.y = fetch31.y;
    r2.z = fetch31.z;
    // add r0.x, r2.y, r2.x
    r0.x = r2.y + r2.x;
    // add r0.x, r2.z, r0.x
    r0.x = r2.z + r0.x;
    // mad r0.y, -r0.x, l(0.333330), l(1.000000)
    r0.y = -r0.x * 0.33333f + 1.0f;
    // log r2.x, |r0.y|
    r2.x = log2(abs(r0.y));
    // lt r0.y, |r0.y|, l(0.000001)
    r0.y = asfloat((abs(r0.y) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r2.x, r2.x, l(17.000000)
    r2.x = r2.x * 17.0f;
    // exp r2.x, r2.x
    r2.x = exp2(r2.x);
    // movc r0.y, r0.y, l(0), r2.x
    r0.y = asuint(r0.y) != 0u ? asfloat(0u) : r2.x;
    // mul r2.xyz, cb0[4].xyzx, cb0[4].wwww
    float stage32_x = cb0[4].x * cb0[4].w;
    float stage32_y = cb0[4].y * cb0[4].w;
    float stage32_z = cb0[4].z * cb0[4].w;
    r2.x = stage32_x;
    r2.y = stage32_y;
    r2.z = stage32_z;
    // mad r2.xyz, r0.yyyy, r2.xyzx, -r1.xyzx
    float stage33_x = r0.y * r2.x + -r1.x;
    float stage33_y = r0.y * r2.y + -r1.y;
    float stage33_z = r0.y * r2.z + -r1.z;
    r2.x = stage33_x;
    r2.y = stage33_y;
    r2.z = stage33_z;
    // mad r1.xyz, r0.yyyy, r2.xyzx, r1.xyzx
    float stage34_x = r0.y * r2.x + r1.x;
    float stage34_y = r0.y * r2.y + r1.y;
    float stage34_z = r0.y * r2.z + r1.z;
    r1.x = stage34_x;
    r1.y = stage34_y;
    r1.z = stage34_z;
    // mad r1.xyz, r1.xyzx, cb0[1].xyzx, cb0[2].xyzx
    float stage35_x = r1.x * cb0[1].x + cb0[2].x;
    float stage35_y = r1.y * cb0[1].y + cb0[2].y;
    float stage35_z = r1.z * cb0[1].z + cb0[2].z;
    r1.x = stage35_x;
    r1.y = stage35_y;
    r1.z = stage35_z;
    // mad o0.xyz, r1.xyzx, v5.wwww, v5.xyzx
    float stage36_x = r1.x * v5.w + v5.x;
    float stage36_y = r1.y * v5.w + v5.y;
    float stage36_z = r1.z * v5.w + v5.z;
    o0.x = stage36_x;
    o0.y = stage36_y;
    o0.z = stage36_z;
    // mul r1.xy, r0.zwzz, cb0[8].yzyy
    float stage37_x = r0.z * cb0[8].y;
    float stage37_y = r0.w * cb0[8].z;
    r1.x = stage37_x;
    r1.y = stage37_y;
    // mul r0.yz, r0.zzwz, cb0[9].yyzy
    float stage38_y = r0.z * cb0[9].y;
    float stage38_z = r0.w * cb0[9].z;
    r0.y = stage38_y;
    r0.z = stage38_z;
    // mad r0.yz, cb0[6].yyyy, cb0[9].xxwx, r0.yyzy
    float stage39_y = cb0[6].y * cb0[9].x + r0.y;
    float stage39_z = cb0[6].y * cb0[9].w + r0.z;
    r0.y = stage39_y;
    r0.z = stage39_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.yzw, r0.yzyy, t2.wxyz, s5, l(0.000000)
    float4 fetch40 = t2.SampleBias(s5, r0.yz, 0.0f);
    r0.y = fetch40.x;
    r0.z = fetch40.y;
    r0.w = fetch40.z;
    // mad r1.xy, cb0[6].yyyy, cb0[8].xwxx, r1.xyxx
    float stage41_x = cb0[6].y * cb0[8].x + r1.x;
    float stage41_y = cb0[6].y * cb0[8].w + r1.y;
    r1.x = stage41_x;
    r1.y = stage41_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t1.xyzw, s4, l(0.000000)
    float4 fetch42 = t1.SampleBias(s4, r1.xy, 0.0f);
    r1.x = fetch42.x;
    r1.y = fetch42.y;
    r1.z = fetch42.z;
    // add r0.yzw, r0.yyzw, r1.xxyz
    float stage43_y = r0.y + r1.x;
    float stage43_z = r0.z + r1.y;
    float stage43_w = r0.w + r1.z;
    r0.y = stage43_y;
    r0.z = stage43_z;
    r0.w = stage43_w;
    // add r0.y, r0.z, r0.y
    r0.y = r0.z + r0.y;
    // add r0.y, r0.w, r0.y
    r0.y = r0.w + r0.y;
    // mul r0.z, r0.y, l(0.333330)
    r0.z = r0.y * 0.33333f;
    // mad r0.y, r0.y, l(0.333330), l(1.000000)
    r0.y = r0.y * 0.33333f + 1.0f;
    // dp2 r0.z, r0.zzzz, r0.zzzz
    r0.z = dot(r0.zz, r0.zz);
    // mad r0.z, r0.x, l(0.333330), r0.z
    r0.z = r0.x * 0.33333f + r0.z;
    // mul r0.x, r0.x, l(0.333330)
    r0.x = r0.x * 0.33333f;
    // mad r0.x, r0.z, r0.x, -cb0[10].x
    r0.x = r0.z * r0.x + -cb0[10].x;
    // mad r0.x, -r1.w, r1.w, r0.x
    r0.x = -r1.w * r1.w + r0.x;
    // mul_sat r0.x, r0.x, l(200.000000)
    r0.x = saturate(r0.x * 200.0f);
    // mov_sat r0.z, cb0[1].w
    r0.z = saturate(cb0[1].w);
    // add r0.z, -r0.z, l(1.000000)
    r0.z = -r0.z + 1.0f;
    // mad r0.x, -r0.z, r0.y, r0.x
    r0.x = -r0.z * r0.y + r0.x;
    // mul_sat r0.x, r0.x, l(50.000000)
    r0.x = saturate(r0.x * 50.0f);
    // mul o0.w, r0.x, cb0[0].x
    o0.w = r0.x * cb0[0].x;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage44_x = r0.x * v1.x;
    float stage44_y = r0.x * v1.y;
    float stage44_z = r0.x * v1.z;
    r0.x = stage44_x;
    r0.y = stage44_y;
    r0.z = stage44_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage45_x = r0.w * v0.z;
    float stage45_y = r0.w * v0.x;
    float stage45_z = r0.w * v0.y;
    r1.x = stage45_x;
    r1.y = stage45_y;
    r1.z = stage45_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage46_x = r0.x * r1.x;
    float stage46_y = r0.x * r1.y;
    float stage46_z = r0.x * r1.z;
    r0.x = stage46_x;
    r0.y = stage46_y;
    r0.z = stage46_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage47_x = r0.x / r0.w;
    float stage47_y = r0.y / r0.w;
    r0.x = stage47_x;
    r0.y = stage47_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage48_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage48_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage48_x;
    r1.y = stage48_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage49_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage49_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage49_x;
    r1.y = stage49_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage50_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage50_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage50_x;
    r1.y = stage50_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage51_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage51_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage51_x;
    r0.y = stage51_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage52_x = r0.x * 0.5f + 0.5f;
    float stage52_y = r0.y * 0.5f + 0.5f;
    o2.x = stage52_x;
    o2.y = stage52_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage53_z = 1.0f;
    float stage53_w = asfloat(0u);
    o2.z = stage53_z;
    o2.w = stage53_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage54_x = cb2[3].x;
    float stage54_y = cb2[3].y;
    float stage54_z = cb2[3].z;
    o3.x = stage54_x;
    o3.y = stage54_y;
    o3.z = stage54_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage55_x = asfloat(0u);
    float stage55_y = asfloat(0u);
    float stage55_z = asfloat(0u);
    float stage55_w = asfloat(0u);
    o4.x = stage55_x;
    o4.y = stage55_y;
    o4.z = stage55_z;
    o4.w = stage55_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage56_x = asfloat(0u);
    float stage56_y = asfloat(0u);
    float stage56_z = asfloat(0u);
    float stage56_w = asfloat(0u);
    o5.x = stage56_x;
    o5.y = stage56_y;
    o5.z = stage56_z;
    o5.w = stage56_w;

    Shade_Ue3_fx_d_me_kazerosmark_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
