// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_me_worldpositionoffset_sinwave_01_ad_Constants0 : register(b0)
{
    float4 cb0[12];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);

struct Shade_Ue3_fx_d_me_worldpositionoffset_sinwave_01_ad_INPUT
{
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_d_me_worldpositionoffset_sinwave_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_d_me_worldpositionoffset_sinwave_01_ad_OUTPUT Shade_Ue3_fx_d_me_worldpositionoffset_sinwave_01_ad(Shade_Ue3_fx_d_me_worldpositionoffset_sinwave_01_ad_INPUT stage)
{
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;

    // add r0.x, cb0[4].z, l(-1.000000)
    r0.x = cb0[4].z + -1.0f;
    // add r0.yz, v4.xxyx, l(0.000000, -0.500000, -0.500000, 0.000000)
    float stage1_y = v4.x + -0.5f;
    float stage1_z = v4.y + -0.5f;
    r0.y = stage1_y;
    r0.z = stage1_z;
    // dp2 r0.w, cb0[5].xyxx, r0.yzyy
    r0.w = dot(cb0[5].xy, r0.yz);
    // dp2 r0.y, cb0[6].xyxx, r0.yzyy
    r0.y = dot(cb0[6].xy, r0.yz);
    // mul r1.z, r0.y, cb0[7].y
    r1.z = r0.y * cb0[7].y;
    // mad r1.x, r0.w, cb0[7].x, r0.x
    r1.x = r0.w * cb0[7].x + r0.x;
    // add r0.xy, r1.xzxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage2_x = r1.x + 0.5f;
    float stage2_y = r1.z + 0.5f;
    r0.x = stage2_x;
    r0.y = stage2_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyxx, t0.xyzw, s1, l(0.000000)
    float4 fetch3 = t0.SampleBias(s1, r0.xy, 0.0f);
    r0.x = fetch3.x;
    r0.y = fetch3.y;
    r0.z = fetch3.z;
    // add r0.x, r0.y, r0.x
    r0.x = r0.y + r0.x;
    // add r0.x, r0.z, r0.x
    r0.x = r0.z + r0.x;
    // mul r0.x, r0.x, cb0[10].w
    r0.x = r0.x * cb0[10].w;
    // mul_sat r0.x, r0.x, l(0.333330)
    r0.x = saturate(r0.x * 0.33333f);
    // log r0.y, r0.x
    r0.y = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[11].x
    r0.y = r0.y * cb0[11].x;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // mov_sat r0.y, cb0[4].y
    r0.y = saturate(cb0[4].y);
    // add r0.y, -r0.y, l(1.000000)
    r0.y = -r0.y + 1.0f;
    // add_sat r0.x, -r0.y, r0.x
    r0.x = saturate(-r0.y + r0.x);
    // mul_sat r0.x, r0.x, cb0[1].w
    r0.x = saturate(r0.x * cb0[1].w);
    // mul r0.x, r0.x, cb0[0].x
    r0.x = r0.x * cb0[0].x;
    // mul r0.yz, v4.xxyx, cb0[8].zzwz
    float stage4_y = v4.x * cb0[8].z;
    float stage4_z = v4.y * cb0[8].w;
    r0.y = stage4_y;
    r0.z = stage4_z;
    // mad r1.x, cb0[8].y, cb0[8].x, r0.y
    r1.x = cb0[8].y * cb0[8].x + r0.y;
    // mad r1.y, cb0[8].y, cb0[9].x, r0.z
    r1.y = cb0[8].y * cb0[9].x + r0.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.yzw, r1.xyxx, t1.wxyz, s0, l(0.000000)
    float4 fetch5 = t1.SampleBias(s0, r1.xy, 0.0f);
    r0.y = fetch5.x;
    r0.z = fetch5.y;
    r0.w = fetch5.z;
    // dp3 r1.x, r0.yzwy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.x = dot(r0.yzw, float3(0.3f, 0.59f, 0.11f));
    // add r1.xyz, -r0.yzwy, r1.xxxx
    float stage6_x = -r0.y + r1.x;
    float stage6_y = -r0.z + r1.x;
    float stage6_z = -r0.w + r1.x;
    r1.x = stage6_x;
    r1.y = stage6_y;
    r1.z = stage6_z;
    // mad r0.yzw, cb0[9].yyyy, r1.xxyz, r0.yyzw
    float stage7_y = cb0[9].y * r1.x + r0.y;
    float stage7_z = cb0[9].y * r1.y + r0.z;
    float stage7_w = cb0[9].y * r1.z + r0.w;
    r0.y = stage7_y;
    r0.z = stage7_z;
    r0.w = stage7_w;
    // max r0.yzw, |r0.yyzw|, l(0.000000, 0.000001, 0.000001, 0.000001)
    float stage8_y = max(abs(r0.y), 1e-06f);
    float stage8_z = max(abs(r0.z), 1e-06f);
    float stage8_w = max(abs(r0.w), 1e-06f);
    r0.y = stage8_y;
    r0.z = stage8_z;
    r0.w = stage8_w;
    // log r0.yzw, r0.yyzw
    float stage9_y = log2(r0.y);
    float stage9_z = log2(r0.z);
    float stage9_w = log2(r0.w);
    r0.y = stage9_y;
    r0.z = stage9_z;
    r0.w = stage9_w;
    // mul r0.yzw, r0.yyzw, cb0[9].zzzz
    float stage10_y = r0.y * cb0[9].z;
    float stage10_z = r0.z * cb0[9].z;
    float stage10_w = r0.w * cb0[9].z;
    r0.y = stage10_y;
    r0.z = stage10_z;
    r0.w = stage10_w;
    // exp r0.yzw, r0.yyzw
    float stage11_y = exp2(r0.y);
    float stage11_z = exp2(r0.z);
    float stage11_w = exp2(r0.w);
    r0.y = stage11_y;
    r0.z = stage11_z;
    r0.w = stage11_w;
    // mul r1.xyz, cb0[3].xyzx, cb0[3].wwww
    float stage12_x = cb0[3].x * cb0[3].w;
    float stage12_y = cb0[3].y * cb0[3].w;
    float stage12_z = cb0[3].z * cb0[3].w;
    r1.x = stage12_x;
    r1.y = stage12_y;
    r1.z = stage12_z;
    // mul r0.yzw, r0.yyzw, r1.xxyz
    float stage13_y = r0.y * r1.x;
    float stage13_z = r0.z * r1.y;
    float stage13_w = r0.w * r1.z;
    r0.y = stage13_y;
    r0.z = stage13_z;
    r0.w = stage13_w;
    // mad r0.yzw, r0.yyzw, cb0[1].xxyz, cb0[2].xxyz
    float stage14_y = r0.y * cb0[1].x + cb0[2].x;
    float stage14_z = r0.z * cb0[1].y + cb0[2].y;
    float stage14_w = r0.w * cb0[1].z + cb0[2].z;
    r0.y = stage14_y;
    r0.z = stage14_z;
    r0.w = stage14_w;
    // mul r0.yzw, r0.yyzw, v5.wwww
    float stage15_y = r0.y * v5.w;
    float stage15_z = r0.z * v5.w;
    float stage15_w = r0.w * v5.w;
    r0.y = stage15_y;
    r0.z = stage15_z;
    r0.w = stage15_w;
    // mul o0.xyz, r0.xxxx, r0.yzwy
    float stage16_x = r0.x * r0.y;
    float stage16_y = r0.x * r0.z;
    float stage16_z = r0.x * r0.w;
    o0.x = stage16_x;
    o0.y = stage16_y;
    o0.z = stage16_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_d_me_worldpositionoffset_sinwave_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
