// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_m_pa_spritewave_01_tr_ffa2f8a8fca4c73619660a6f731803f92f76262b9cf2fbb664bdb7bd1342e1ff_Constants0 : register(b0)
{
    float4 cb0[20];
};
cbuffer Shade_Ue3_fx_m_pa_spritewave_01_tr_ffa2f8a8fca4c73619660a6f731803f92f76262b9cf2fbb664bdb7bd1342e1ff_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);

struct Shade_Ue3_fx_m_pa_spritewave_01_tr_ffa2f8a8fca4c73619660a6f731803f92f76262b9cf2fbb664bdb7bd1342e1ff_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_m_pa_spritewave_01_tr_ffa2f8a8fca4c73619660a6f731803f92f76262b9cf2fbb664bdb7bd1342e1ff_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_m_pa_spritewave_01_tr_ffa2f8a8fca4c73619660a6f731803f92f76262b9cf2fbb664bdb7bd1342e1ff_OUTPUT Shade_Ue3_fx_m_pa_spritewave_01_tr_ffa2f8a8fca4c73619660a6f731803f92f76262b9cf2fbb664bdb7bd1342e1ff(Shade_Ue3_fx_m_pa_spritewave_01_tr_ffa2f8a8fca4c73619660a6f731803f92f76262b9cf2fbb664bdb7bd1342e1ff_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mul r0.xy, v2.xyxx, cb0[11].zwzz
    float stage1_x = v2.x * cb0[11].z;
    float stage1_y = v2.y * cb0[11].w;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // mad r1.x, cb0[8].w, cb0[11].y, r0.x
    r1.x = cb0[8].w * cb0[11].y + r0.x;
    // mad r1.y, cb0[8].w, cb0[12].x, r0.y
    r1.y = cb0[8].w * cb0[12].x + r0.y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r1.xyxx, t0.xyzw, s1, l(0.000000)
    float4 fetch2 = t0.SampleBias(s1, r1.xy, 0.0f);
    r0.x = fetch2.x;
    // mad r0.xy, r0.xxxx, cb0[12].yyyy, v2.xyxx
    float stage3_x = r0.x * cb0[12].y + v2.x;
    float stage3_y = r0.x * cb0[12].y + v2.y;
    r0.x = stage3_x;
    r0.y = stage3_y;
    // mul r0.x, r0.x, cb0[10].w
    r0.x = r0.x * cb0[10].w;
    // mad r1.x, cb0[8].w, cb0[10].z, r0.x
    r1.x = cb0[8].w * cb0[10].z + r0.x;
    // mul r0.x, cb0[8].w, cb0[12].z
    r0.x = cb0[8].w * cb0[12].z;
    // mad r1.y, cb0[11].x, r0.y, r0.x
    r1.y = cb0[11].x * r0.y + r0.x;
    // mul r0.x, v4.w, cb0[12].w
    r0.x = v4.w * cb0[12].w;
    // mul r0.y, v4.w, cb0[13].x
    r0.y = v4.w * cb0[13].x;
    // add r0.xy, r0.xyxx, r1.xyxx
    float stage4_x = r0.x + r1.x;
    float stage4_y = r0.y + r1.y;
    r0.x = stage4_x;
    r0.y = stage4_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t1.xyzw, s2, l(0.000000)
    float4 fetch5 = t1.SampleBias(s2, r0.xy, 0.0f);
    r0.x = fetch5.x;
    // add r0.y, v4.z, cb0[13].y
    r0.y = v4.z + cb0[13].y;
    // mad r0.xy, r0.xxxx, r0.yyyy, cb0[2].xyxx
    float stage6_x = r0.x * r0.y + cb0[2].x;
    float stage6_y = r0.x * r0.y + cb0[2].y;
    r0.x = stage6_x;
    r0.y = stage6_y;
    // add r0.zw, v2.xxxy, l(0.000000, 0.000000, -0.500000, -0.500000)
    float stage7_z = v2.x + -0.5f;
    float stage7_w = v2.y + -0.5f;
    r0.z = stage7_z;
    r0.w = stage7_w;
    // max r1.x, |r0.w|, |r0.z|
    r1.x = max(abs(r0.w), abs(r0.z));
    // div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
    r1.x = 1.0f / r1.x;
    // min r1.y, |r0.w|, |r0.z|
    r1.y = min(abs(r0.w), abs(r0.z));
    // mul r1.x, r1.x, r1.y
    r1.x = r1.x * r1.y;
    // mul r1.y, r1.x, r1.x
    r1.y = r1.x * r1.x;
    // mad r1.z, r1.y, l(0.020835), l(-0.085133)
    r1.z = r1.y * 0.020835f + -0.085133f;
    // mad r1.z, r1.y, r1.z, l(0.180141)
    r1.z = r1.y * r1.z + 0.180141f;
    // mad r1.z, r1.y, r1.z, l(-0.330299)
    r1.z = r1.y * r1.z + -0.330299f;
    // mad r1.y, r1.y, r1.z, l(0.999866)
    r1.y = r1.y * r1.z + 0.999866f;
    // mul r1.z, r1.y, r1.x
    r1.z = r1.y * r1.x;
    // mad r1.z, r1.z, l(-2.000000), l(1.570796)
    r1.z = r1.z * -2.0f + 1.570796f;
    // lt r1.w, |r0.w|, |r0.z|
    r1.w = asfloat((abs(r0.w) < abs(r0.z)) ? 0xffffffffu : 0u);
    // and r1.z, r1.w, r1.z
    r1.z = asfloat(asuint(r1.w) & asuint(r1.z));
    // mad r1.x, r1.x, r1.y, r1.z
    r1.x = r1.x * r1.y + r1.z;
    // lt r1.y, r0.w, -r0.w
    r1.y = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // and r1.y, r1.y, l(0xc0490fdb)
    r1.y = asfloat(asuint(r1.y) & asuint(-3.1415927410125732f));
    // add r1.x, r1.y, r1.x
    r1.x = r1.y + r1.x;
    // min r1.y, r0.w, r0.z
    r1.y = min(r0.w, r0.z);
    // lt r1.y, r1.y, -r1.y
    r1.y = asfloat((r1.y < -r1.y) ? 0xffffffffu : 0u);
    // max r1.z, r0.w, r0.z
    r1.z = max(r0.w, r0.z);
    // ge r1.z, r1.z, -r1.z
    r1.z = asfloat((r1.z >= -r1.z) ? 0xffffffffu : 0u);
    // and r1.y, r1.z, r1.y
    r1.y = asfloat(asuint(r1.z) & asuint(r1.y));
    // movc r1.x, r1.y, -r1.x, r1.x
    r1.x = asuint(r1.y) != 0u ? -r1.x : r1.x;
    // mad r1.x, r1.x, l(0.159155), l(0.500000)
    r1.x = r1.x * 0.159155f + 0.5f;
    // dp2 r1.z, r0.zwzz, r0.zwzz
    r1.z = dot(r0.zw, r0.zw);
    // sqrt r1.z, r1.z
    r1.z = sqrt(r1.z);
    // log r1.w, r1.z
    r1.w = log2(r1.z);
    // mul r1.w, r1.w, cb0[9].z
    r1.w = r1.w * cb0[9].z;
    // exp r1.w, r1.w
    r1.w = exp2(r1.w);
    // lt r2.x, r1.z, l(0.000001)
    r2.x = asfloat((r1.z < 1e-06f) ? 0xffffffffu : 0u);
    // mad r1.z, -r1.z, l(2.000000), l(1.000000)
    r1.z = -r1.z * 2.0f + 1.0f;
    // max r1.z, r1.z, l(0.000000)
    r1.z = max(r1.z, 0.0f);
    // mul r1.z, r1.z, cb0[19].x
    r1.z = r1.z * cb0[19].x;
    // max r1.z, r1.z, cb0[19].z
    r1.z = max(r1.z, cb0[19].z);
    // min r1.z, r1.z, cb0[19].y
    r1.z = min(r1.z, cb0[19].y);
    // movc r1.y, r2.x, l(0), r1.w
    r1.y = asuint(r2.x) != 0u ? asfloat(0u) : r1.w;
    // mul r1.xy, r1.xyxx, cb0[9].xyxx
    float stage8_x = r1.x * cb0[9].x;
    float stage8_y = r1.y * cb0[9].y;
    r1.x = stage8_x;
    r1.y = stage8_y;
    // mad r2.x, cb0[8].w, cb0[8].z, r1.x
    r2.x = cb0[8].w * cb0[8].z + r1.x;
    // mad r2.y, cb0[8].w, cb0[9].w, r1.y
    r2.y = cb0[8].w * cb0[9].w + r1.y;
    // add r1.xy, r2.xyxx, r2.xyxx
    float stage9_x = r2.x + r2.x;
    float stage9_y = r2.y + r2.y;
    r1.x = stage9_x;
    r1.y = stage9_y;
    // mad r1.xy, cb0[10].xyxx, v4.xxxx, r1.xyxx
    float stage10_x = cb0[10].x * v4.x + r1.x;
    float stage10_y = cb0[10].y * v4.x + r1.y;
    r1.x = stage10_x;
    r1.y = stage10_y;
    // add r0.xy, r0.xyxx, r1.xyxx
    float stage11_x = r0.x + r1.x;
    float stage11_y = r0.y + r1.y;
    r0.x = stage11_x;
    r0.y = stage11_y;
    // add r0.xy, r0.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage12_x = r0.x + -0.5f;
    float stage12_y = r0.y + -0.5f;
    r0.x = stage12_x;
    r0.y = stage12_y;
    // dp2 r1.x, cb0[3].xyxx, r0.xyxx
    r1.x = dot(cb0[3].xy, r0.xy);
    // dp2 r1.y, cb0[4].xyxx, r0.xyxx
    r1.y = dot(cb0[4].xy, r0.xy);
    // add r0.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage13_x = r1.x + 0.5f;
    float stage13_y = r1.y + 0.5f;
    r0.x = stage13_x;
    r0.y = stage13_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t2.xyzw, s0, l(-1.000000)
    float4 fetch14 = t2.SampleLevel(s0, r0.xy, -1.0f);
    r0.x = fetch14.x;
    // mul r1.xy, v2.xyxx, cb0[14].yzyy
    float stage15_x = v2.x * cb0[14].y;
    float stage15_y = v2.y * cb0[14].z;
    r1.x = stage15_x;
    r1.y = stage15_y;
    // mad r1.xy, cb0[8].wwww, cb0[14].xwxx, r1.xyxx
    float stage16_x = cb0[8].w * cb0[14].x + r1.x;
    float stage16_y = cb0[8].w * cb0[14].w + r1.y;
    r1.x = stage16_x;
    r1.y = stage16_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r1.xyxx, t4.yxzw, s3, l(0.000000)
    float4 fetch17 = t4.SampleBias(s3, r1.xy, 0.0f);
    r0.y = fetch17.x;
    // mul r0.y, r0.y, r0.x
    r0.y = r0.y * r0.x;
    // log r1.x, |r0.y|
    r1.x = log2(abs(r0.y));
    // mul r1.x, r1.x, cb0[15].x
    r1.x = r1.x * cb0[15].x;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // mul r1.x, r1.x, cb0[15].y
    r1.x = r1.x * cb0[15].y;
    // lt r1.y, |r0.y|, l(0.000001)
    r1.y = asfloat((abs(r0.y) < 1e-06f) ? 0xffffffffu : 0u);
    // movc r1.x, r1.y, l(0), r1.x
    r1.x = asuint(r1.y) != 0u ? asfloat(0u) : r1.x;
    // mad r0.y, r0.y, cb0[15].z, r1.x
    r0.y = r0.y * cb0[15].z + r1.x;
    // dp2 r1.x, cb0[5].xyxx, r0.zwzz
    r1.x = dot(cb0[5].xy, r0.zw);
    // dp2 r1.y, cb0[6].xyxx, r0.zwzz
    r1.y = dot(cb0[6].xy, r0.zw);
    // add r0.zw, r1.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
    float stage18_z = r1.x + 0.5f;
    float stage18_w = r1.y + 0.5f;
    r0.z = stage18_z;
    r0.w = stage18_w;
    // mul r0.zw, r0.zzzw, cb0[16].xxxy
    float stage19_z = r0.z * cb0[16].x;
    float stage19_w = r0.w * cb0[16].y;
    r0.z = stage19_z;
    r0.w = stage19_w;
    // mad r1.x, cb0[8].w, cb0[15].w, r0.z
    r1.x = cb0[8].w * cb0[15].w + r0.z;
    // mad r1.y, cb0[8].w, cb0[17].w, r0.w
    r1.y = cb0[8].w * cb0[17].w + r0.w;
    // add r0.zw, r1.xxxy, cb0[18].xxxy
    float stage20_z = r1.x + cb0[18].x;
    float stage20_w = r1.y + cb0[18].y;
    r0.z = stage20_z;
    r0.w = stage20_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t3.yzxw, s4, l(0.000000)
    float4 fetch21 = t3.SampleBias(s4, r0.zw, 0.0f);
    r0.z = fetch21.x;
    // add r0.z, r0.z, l(0.100000)
    r0.z = r0.z + 0.1f;
    // add r0.w, v4.y, l(-1.000000)
    r0.w = v4.y + -1.0f;
    // add_sat r0.z, -r0.w, r0.z
    r0.z = saturate(-r0.w + r0.z);
    // log r0.w, r0.z
    r0.w = log2(r0.z);
    // mul r0.w, r0.w, cb0[18].w
    r0.w = r0.w * cb0[18].w;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // mul_sat r0.w, r0.w, cb0[18].z
    r0.w = saturate(r0.w * cb0[18].z);
    // lt r1.x, r0.z, l(0.000001)
    r1.x = asfloat((r0.z < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, cb0[18].z
    r0.z = r0.z * cb0[18].z;
    // movc r0.w, r1.x, l(-0.000000), -r0.w
    r0.w = asuint(r1.x) != 0u ? -0.0f : -r0.w;
    // mov_sat r1.x, r0.z
    r1.x = saturate(r0.z);
    // mul r0.x, r0.z, r0.x
    r0.x = r0.z * r0.x;
    // mul r0.x, r0.x, cb0[19].w
    r0.x = r0.x * cb0[19].w;
    // mul_sat r0.x, r0.x, v3.w
    r0.x = saturate(r0.x * v3.w);
    // mul r0.x, r0.x, r1.z
    r0.x = r0.x * r1.z;
    // mul o0.w, r0.x, cb0[0].x
    o0.w = r0.x * cb0[0].x;
    // add r0.x, r0.w, r1.x
    r0.x = r0.w + r1.x;
    // max r0.x, r0.x, l(0.000000)
    r0.x = max(r0.x, 0.0f);
    // mad r0.xyz, r0.xxxx, cb0[7].xyzx, r0.yyyy
    float stage22_x = r0.x * cb0[7].x + r0.y;
    float stage22_y = r0.x * cb0[7].y + r0.y;
    float stage22_z = r0.x * cb0[7].z + r0.y;
    r0.x = stage22_x;
    r0.y = stage22_y;
    r0.z = stage22_z;
    // mad r0.xyz, r0.xyzx, v3.xyzx, cb0[1].xyzx
    float stage23_x = r0.x * v3.x + cb0[1].x;
    float stage23_y = r0.y * v3.y + cb0[1].y;
    float stage23_z = r0.z * v3.z + cb0[1].z;
    r0.x = stage23_x;
    r0.y = stage23_y;
    r0.z = stage23_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage24_x = r0.x * v5.w + v5.x;
    float stage24_y = r0.y * v5.w + v5.y;
    float stage24_z = r0.z * v5.w + v5.z;
    o0.x = stage24_x;
    o0.y = stage24_y;
    o0.z = stage24_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage25_x = r0.x * v1.x;
    float stage25_y = r0.x * v1.y;
    float stage25_z = r0.x * v1.z;
    r0.x = stage25_x;
    r0.y = stage25_y;
    r0.z = stage25_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage26_x = r0.w * v0.z;
    float stage26_y = r0.w * v0.x;
    float stage26_z = r0.w * v0.y;
    r1.x = stage26_x;
    r1.y = stage26_y;
    r1.z = stage26_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage27_x = r0.x * r1.x;
    float stage27_y = r0.x * r1.y;
    float stage27_z = r0.x * r1.z;
    r0.x = stage27_x;
    r0.y = stage27_y;
    r0.z = stage27_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage28_x = r0.x / r0.w;
    float stage28_y = r0.y / r0.w;
    r0.x = stage28_x;
    r0.y = stage28_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage29_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage29_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage29_x;
    r1.y = stage29_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage30_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage30_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage30_x;
    r1.y = stage30_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage31_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage31_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage31_x;
    r1.y = stage31_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage32_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage32_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage32_x;
    r0.y = stage32_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage33_x = r0.x * 0.5f + 0.5f;
    float stage33_y = r0.y * 0.5f + 0.5f;
    o2.x = stage33_x;
    o2.y = stage33_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage34_z = 1.0f;
    float stage34_w = asfloat(0u);
    o2.z = stage34_z;
    o2.w = stage34_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage35_x = cb2[3].x;
    float stage35_y = cb2[3].y;
    float stage35_z = cb2[3].z;
    o3.x = stage35_x;
    o3.y = stage35_y;
    o3.z = stage35_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage36_x = asfloat(0u);
    float stage36_y = asfloat(0u);
    float stage36_z = asfloat(0u);
    float stage36_w = asfloat(0u);
    o4.x = stage36_x;
    o4.y = stage36_y;
    o4.z = stage36_z;
    o4.w = stage36_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage37_x = asfloat(0u);
    float stage37_y = asfloat(0u);
    float stage37_z = asfloat(0u);
    float stage37_w = asfloat(0u);
    o5.x = stage37_x;
    o5.y = stage37_y;
    o5.z = stage37_z;
    o5.w = stage37_w;

    Shade_Ue3_fx_m_pa_spritewave_01_tr_ffa2f8a8fca4c73619660a6f731803f92f76262b9cf2fbb664bdb7bd1342e1ff_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
