// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_k_me_makeflow_01_tr_Constants0 : register(b0)
{
    float4 cb0[16];
};
cbuffer Shade_Ue3_fx_k_me_makeflow_01_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);

struct Shade_Ue3_fx_k_me_makeflow_01_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_k_me_makeflow_01_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_k_me_makeflow_01_tr_OUTPUT Shade_Ue3_fx_k_me_makeflow_01_tr(Shade_Ue3_fx_k_me_makeflow_01_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mov r0.y, cb0[12].z
    r0.y = cb0[12].z;
    // mov r0.x, l(0)
    r0.x = asfloat(0u);
    // mad r0.xyzw, v4.xyxy, cb0[4].xyxy, r0.yxxy
    float stage1_x = v4.x * cb0[4].x + r0.y;
    float stage1_y = v4.y * cb0[4].y + r0.x;
    float stage1_z = v4.x * cb0[4].x + r0.x;
    float stage1_w = v4.y * cb0[4].y + r0.y;
    r0.x = stage1_x;
    r0.y = stage1_y;
    r0.z = stage1_z;
    r0.w = stage1_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch2 = t0.SampleBias(s0, r0.xy, 0.0f);
    r0.x = fetch2.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r0.zwzz, t0.yxzw, s0, l(0.000000)
    float4 fetch3 = t0.SampleBias(s0, r0.zw, 0.0f);
    r0.y = fetch3.x;
    // mul r0.zw, v4.xxxy, cb0[4].xxxy
    float stage4_z = v4.x * cb0[4].x;
    float stage4_w = v4.y * cb0[4].y;
    r0.z = stage4_z;
    r0.w = stage4_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t0.yzxw, s0, l(0.000000)
    float4 fetch5 = t0.SampleBias(s0, r0.zw, 0.0f);
    r0.z = fetch5.x;
    // add r1.xy, -r0.zzzz, r0.xyxx
    float stage6_x = -r0.z + r0.x;
    float stage6_y = -r0.z + r0.y;
    r1.x = stage6_x;
    r1.y = stage6_y;
    // mul r0.xy, r1.xyxx, l(8.000000, 8.000000, 0.000000, 0.000000)
    float stage7_x = r1.x * 8.0f;
    float stage7_y = r1.y * 8.0f;
    r0.x = stage7_x;
    r0.y = stage7_y;
    // mov r0.z, l(0)
    r0.z = asfloat(0u);
    // add r0.xyz, -r0.xyzx, l(0.000000, 0.000000, 1.000000, 0.000000)
    float stage8_x = -r0.x + 0.0f;
    float stage8_y = -r0.y + 0.0f;
    float stage8_z = -r0.z + 1.0f;
    r0.x = stage8_x;
    r0.y = stage8_y;
    r0.z = stage8_z;
    // dp3 r0.z, r0.xyzx, r0.xyzx
    r0.z = dot(r0.xyz, r0.xyz);
    // sqrt r0.z, r0.z
    r0.z = sqrt(r0.z);
    // div r0.xy, r0.xyxx, r0.zzzz
    float stage9_x = r0.x / r0.z;
    float stage9_y = r0.y / r0.z;
    r0.x = stage9_x;
    r0.y = stage9_y;
    // mad r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage10_x = r0.x * 0.5f + 0.5f;
    float stage10_y = r0.y * 0.5f + 0.5f;
    r0.x = stage10_x;
    r0.y = stage10_y;
    // mul r0.xy, r0.xyxx, cb0[5].xxxx
    float stage11_x = r0.x * cb0[5].x;
    float stage11_y = r0.y * cb0[5].x;
    r0.x = stage11_x;
    r0.y = stage11_y;
    // mad r0.zw, v4.xxxy, cb0[7].xxxy, r0.xxxy
    float stage12_z = v4.x * cb0[7].x + r0.x;
    float stage12_w = v4.y * cb0[7].y + r0.y;
    r0.z = stage12_z;
    r0.w = stage12_w;
    // mad r0.xy, v4.xyxx, cb0[3].xyxx, r0.xyxx
    float stage13_x = v4.x * cb0[3].x + r0.x;
    float stage13_y = v4.y * cb0[3].y + r0.y;
    r0.x = stage13_x;
    r0.y = stage13_y;
    // add r0.xy, r0.xyxx, cb0[6].xyxx
    float stage14_x = r0.x + cb0[6].x;
    float stage14_y = r0.y + cb0[6].y;
    r0.x = stage14_x;
    r0.y = stage14_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyz, r0.xyxx, t1.xyzw, s1, l(0.000000)
    float4 fetch15 = t1.SampleBias(s1, r0.xy, 0.0f);
    r1.x = fetch15.x;
    r1.y = fetch15.y;
    r1.z = fetch15.z;
    // add r0.xy, r0.zwzz, cb0[8].xyxx
    float stage16_x = r0.z + cb0[8].x;
    float stage16_y = r0.w + cb0[8].y;
    r0.x = stage16_x;
    r0.y = stage16_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyxx, t3.xyzw, s2, l(0.000000)
    float4 fetch17 = t3.SampleBias(s2, r0.xy, 0.0f);
    r0.x = fetch17.x;
    r0.y = fetch17.y;
    r0.z = fetch17.z;
    // mul r2.xyz, r0.xyzx, r1.xyzx
    float stage18_x = r0.x * r1.x;
    float stage18_y = r0.y * r1.y;
    float stage18_z = r0.z * r1.z;
    r2.x = stage18_x;
    r2.y = stage18_y;
    r2.z = stage18_z;
    // dp3 r0.w, r2.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.w = dot(r2.xyz, float3(0.3f, 0.59f, 0.11f));
    // mad r0.xyz, -r1.xyzx, r0.xyzx, r0.wwww
    float stage19_x = -r1.x * r0.x + r0.w;
    float stage19_y = -r1.y * r0.y + r0.w;
    float stage19_z = -r1.z * r0.z + r0.w;
    r0.x = stage19_x;
    r0.y = stage19_y;
    r0.z = stage19_z;
    // mad r0.xyz, cb0[13].xxxx, r0.xyzx, r2.xyzx
    float stage20_x = cb0[13].x * r0.x + r2.x;
    float stage20_y = cb0[13].x * r0.y + r2.y;
    float stage20_z = cb0[13].x * r0.z + r2.z;
    r0.x = stage20_x;
    r0.y = stage20_y;
    r0.z = stage20_z;
    // max r0.xyz, |r0.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage21_x = max(abs(r0.x), 1e-06f);
    float stage21_y = max(abs(r0.y), 1e-06f);
    float stage21_z = max(abs(r0.z), 1e-06f);
    r0.x = stage21_x;
    r0.y = stage21_y;
    r0.z = stage21_z;
    // log r0.xyz, r0.xyzx
    float stage22_x = log2(r0.x);
    float stage22_y = log2(r0.y);
    float stage22_z = log2(r0.z);
    r0.x = stage22_x;
    r0.y = stage22_y;
    r0.z = stage22_z;
    // mul r0.xyz, r0.xyzx, cb0[13].yyyy
    float stage23_x = r0.x * cb0[13].y;
    float stage23_y = r0.y * cb0[13].y;
    float stage23_z = r0.z * cb0[13].y;
    r0.x = stage23_x;
    r0.y = stage23_y;
    r0.z = stage23_z;
    // exp r0.xyz, r0.xyzx
    float stage24_x = exp2(r0.x);
    float stage24_y = exp2(r0.y);
    float stage24_z = exp2(r0.z);
    r0.x = stage24_x;
    r0.y = stage24_y;
    r0.z = stage24_z;
    // mul r0.xyz, r0.xyzx, cb0[13].zzzz
    float stage25_x = r0.x * cb0[13].z;
    float stage25_y = r0.y * cb0[13].z;
    float stage25_z = r0.z * cb0[13].z;
    r0.x = stage25_x;
    r0.y = stage25_y;
    r0.z = stage25_z;
    // mad r0.xyz, cb0[1].xyzx, r0.xyzx, cb0[2].xyzx
    float stage26_x = cb0[1].x * r0.x + cb0[2].x;
    float stage26_y = cb0[1].y * r0.y + cb0[2].y;
    float stage26_z = cb0[1].z * r0.z + cb0[2].z;
    r0.x = stage26_x;
    r0.y = stage26_y;
    r0.z = stage26_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage27_x = r0.x * v5.w + v5.x;
    float stage27_y = r0.y * v5.w + v5.y;
    float stage27_z = r0.z * v5.w + v5.z;
    o0.x = stage27_x;
    o0.y = stage27_y;
    o0.z = stage27_z;
    // mad r0.xy, v4.xyxx, cb0[9].xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage28_x = v4.x * cb0[9].x + -0.5f;
    float stage28_y = v4.y * cb0[9].y + -0.5f;
    r0.x = stage28_x;
    r0.y = stage28_y;
    // dp2 r2.x, cb0[10].xyxx, r0.xyxx
    r2.x = dot(cb0[10].xy, r0.xy);
    // dp2 r2.y, cb0[11].xyxx, r0.xyxx
    r2.y = dot(cb0[11].xy, r0.xy);
    // add r0.xy, r2.xyxx, cb0[5].zyzz
    float stage29_x = r2.x + cb0[5].z;
    float stage29_y = r2.y + cb0[5].y;
    r0.x = stage29_x;
    r0.y = stage29_y;
    // add r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage30_x = r0.x + 0.5f;
    float stage30_y = r0.y + 0.5f;
    r0.x = stage30_x;
    r0.y = stage30_y;
    // mad r0.xy, r1.xxxx, cb0[14].zzzz, r0.xyxx
    float stage31_x = r1.x * cb0[14].z + r0.x;
    float stage31_y = r1.x * cb0[14].z + r0.y;
    r0.x = stage31_x;
    r0.y = stage31_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t2.xyzw, s3, l(0.000000)
    float4 fetch32 = t2.SampleBias(s3, r0.xy, 0.0f);
    r0.x = fetch32.x;
    // mad r0.y, v4.y, l(2.000000), l(-1.000000)
    r0.y = v4.y * 2.0f + -1.0f;
    // add r0.y, -|r0.y|, l(1.000000)
    r0.y = -(abs(r0.y)) + 1.0f;
    // log r0.z, |r0.y|
    r0.z = log2(abs(r0.y));
    // lt r0.y, |r0.y|, l(0.000001)
    r0.y = asfloat((abs(r0.y) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, cb0[14].w
    r0.z = r0.z * cb0[14].w;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // movc r0.y, r0.y, l(0), r0.z
    r0.y = asuint(r0.y) != 0u ? asfloat(0u) : r0.z;
    // mul r0.x, r0.x, r0.y
    r0.x = r0.x * r0.y;
    // max r0.x, |r0.x|, l(0.000001)
    r0.x = max(abs(r0.x), 1e-06f);
    // log r0.x, r0.x
    r0.x = log2(r0.x);
    // mul r0.x, r0.x, cb0[15].x
    r0.x = r0.x * cb0[15].x;
    // exp r0.x, r0.x
    r0.x = exp2(r0.x);
    // min r0.x, r0.x, l(1.000000)
    r0.x = min(r0.x, 1.0f);
    // mul r0.x, r0.x, cb0[1].w
    r0.x = r0.x * cb0[1].w;
    // mul o0.w, r0.x, cb0[0].x
    o0.w = r0.x * cb0[0].x;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage33_x = r0.x * v1.x;
    float stage33_y = r0.x * v1.y;
    float stage33_z = r0.x * v1.z;
    r0.x = stage33_x;
    r0.y = stage33_y;
    r0.z = stage33_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage34_x = r0.w * v0.z;
    float stage34_y = r0.w * v0.x;
    float stage34_z = r0.w * v0.y;
    r1.x = stage34_x;
    r1.y = stage34_y;
    r1.z = stage34_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage35_x = r0.x * r1.x;
    float stage35_y = r0.x * r1.y;
    float stage35_z = r0.x * r1.z;
    r0.x = stage35_x;
    r0.y = stage35_y;
    r0.z = stage35_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage36_x = r0.x / r0.w;
    float stage36_y = r0.y / r0.w;
    r0.x = stage36_x;
    r0.y = stage36_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage37_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage37_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage37_x;
    r1.y = stage37_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage38_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage38_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage38_x;
    r1.y = stage38_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage39_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage39_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage39_x;
    r1.y = stage39_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage40_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage40_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage40_x;
    r0.y = stage40_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage41_x = r0.x * 0.5f + 0.5f;
    float stage41_y = r0.y * 0.5f + 0.5f;
    o2.x = stage41_x;
    o2.y = stage41_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage42_z = 1.0f;
    float stage42_w = asfloat(0u);
    o2.z = stage42_z;
    o2.w = stage42_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage43_x = cb2[3].x;
    float stage43_y = cb2[3].y;
    float stage43_z = cb2[3].z;
    o3.x = stage43_x;
    o3.y = stage43_y;
    o3.z = stage43_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage44_x = asfloat(0u);
    float stage44_y = asfloat(0u);
    float stage44_z = asfloat(0u);
    float stage44_w = asfloat(0u);
    o4.x = stage44_x;
    o4.y = stage44_y;
    o4.z = stage44_z;
    o4.w = stage44_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage45_x = asfloat(0u);
    float stage45_y = asfloat(0u);
    float stage45_z = asfloat(0u);
    float stage45_w = asfloat(0u);
    o5.x = stage45_x;
    o5.y = stage45_y;
    o5.z = stage45_z;
    o5.w = stage45_w;

    Shade_Ue3_fx_k_me_makeflow_01_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
