// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_shockwave_02_ad_Constants0 : register(b0)
{
    float4 cb0[8];
};
cbuffer Shade_Ue3_fx_d_pa_shockwave_02_ad_Constants2 : register(b2)
{
    float4 cb2[2];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);

struct Shade_Ue3_fx_d_pa_shockwave_02_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_d_pa_shockwave_02_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_d_pa_shockwave_02_ad_OUTPUT Shade_Ue3_fx_d_pa_shockwave_02_ad(Shade_Ue3_fx_d_pa_shockwave_02_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;

    // mad r0.xy, v2.xyxx, l(1.000000, 0.500000, 0.000000, 0.000000), l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.x * 1.0f + -0.5f;
    float stage1_y = v2.y * 0.5f + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.x|, |r0.y|
    r0.z = max(abs(r0.x), abs(r0.y));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.x|, |r0.y|
    r0.w = min(abs(r0.x), abs(r0.y));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.x|, |r0.y|
    r1.y = asfloat((abs(r0.x) < abs(r0.y)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.x, -r0.x
    r0.w = asfloat((r0.x < -r0.x) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.x, r0.y
    r0.w = min(r0.x, r0.y);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.x, r0.y
    r1.x = max(r0.x, r0.y);
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // ge r0.y, r1.x, -r1.x
    r0.y = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.y, r0.y, r0.w
    r0.y = asfloat(asuint(r0.y) & asuint(r0.w));
    // movc r0.y, r0.y, -r0.z, r0.z
    r0.y = asuint(r0.y) != 0u ? -r0.z : r0.z;
    // mad r0.yz, r0.yyyy, l(0.000000, 0.159155, 0.159155, 0.000000), l(0.000000, 0.500000, 0.250000, 0.000000)
    float stage2_y = r0.y * 0.159155f + 0.5f;
    float stage2_z = r0.y * 0.159155f + 0.25f;
    r0.y = stage2_y;
    r0.z = stage2_z;
    // mad r0.z, -|r0.z|, l(4.000000), l(1.000000)
    r0.z = -(abs(r0.z)) * 4.0f + 1.0f;
    // add r1.x, r0.y, r0.y
    r1.x = r0.y + r0.y;
    // mov_sat r0.y, v4.x
    r0.y = saturate(v4.x);
    // add r0.y, -r0.y, l(1.000000)
    r0.y = -r0.y + 1.0f;
    // add r0.w, -r0.y, r0.z
    r0.w = -r0.y + r0.z;
    // add r0.z, r0.z, -cb0[5].z
    r0.z = r0.z + -cb0[5].z;
    // mul_sat r0.z, r0.z, cb0[5].w
    r0.z = saturate(r0.z * cb0[5].w);
    // add r0.y, -r0.y, l(1.000000)
    r0.y = -r0.y + 1.0f;
    // div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
    r0.y = 1.0f / r0.y;
    // mul_sat r0.y, r0.y, r0.w
    r0.y = saturate(r0.y * r0.w);
    // mul r0.y, r0.y, l(10.000000)
    r0.y = r0.y * 10.0f;
    // min r0.y, r0.y, l(1.000000)
    r0.y = min(r0.y, 1.0f);
    // mul r0.y, r0.y, r0.z
    r0.y = r0.y * r0.z;
    // mad r0.z, -r0.x, l(2.000000), l(1.000000)
    r0.z = -r0.x * 2.0f + 1.0f;
    // max r0.z, r0.z, l(0.000000)
    r0.z = max(r0.z, 0.0f);
    // add r0.w, -r0.z, l(1.000000)
    r0.w = -r0.z + 1.0f;
    // mul_sat r0.z, r0.z, cb0[6].x
    r0.z = saturate(r0.z * cb0[6].x);
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // log r0.w, r0.z
    r0.w = log2(r0.z);
    // lt r0.z, r0.z, l(0.000001)
    r0.z = asfloat((r0.z < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.w, r0.w, cb0[6].y
    r0.w = r0.w * cb0[6].y;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // mul r0.y, r0.w, r0.y
    r0.y = r0.w * r0.y;
    // movc r0.y, r0.z, l(0), r0.y
    r0.y = asuint(r0.z) != 0u ? asfloat(0u) : r0.y;
    // add r0.z, r0.x, r0.x
    r0.z = r0.x + r0.x;
    // lt r0.x, r0.x, l(0.000000)
    r0.x = asfloat((r0.x < 0.0f) ? 0xffffffffu : 0u);
    // log r0.z, r0.z
    r0.z = log2(r0.z);
    // mul r0.z, r0.z, v4.y
    r0.z = r0.z * v4.y;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // movc r1.y, r0.x, l(0), r0.z
    r1.y = asuint(r0.x) != 0u ? asfloat(0u) : r0.z;
    // mul r0.x, r1.y, cb0[7].x
    r0.x = r1.y * cb0[7].x;
    // mul r0.zw, r1.xxxy, cb0[3].zzzw
    float stage3_z = r1.x * cb0[3].z;
    float stage3_w = r1.y * cb0[3].w;
    r0.z = stage3_z;
    r0.w = stage3_w;
    // mul r1.x, r1.x, cb0[6].w
    r1.x = r1.x * cb0[6].w;
    // mad r1.x, cb0[3].y, cb0[6].z, r1.x
    r1.x = cb0[3].y * cb0[6].z + r1.x;
    // mad r1.y, cb0[3].y, cb0[7].y, r0.x
    r1.y = cb0[3].y * cb0[7].y + r0.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r1.xyxx, t1.yxzw, s2, l(0.000000)
    float4 fetch4 = t1.SampleBias(s2, r1.xy, 0.0f);
    r0.x = fetch4.y;
    // mov_sat r1.x, v3.w
    r1.x = saturate(v3.w);
    // add r1.x, -r1.x, l(1.000000)
    r1.x = -r1.x + 1.0f;
    // add r0.x, r0.x, -r1.x
    r0.x = r0.x + -r1.x;
    // mul_sat r0.x, r0.x, cb0[7].z
    r0.x = saturate(r0.x * cb0[7].z);
    // log r1.x, r0.x
    r1.x = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.x, r1.x, cb0[7].w
    r1.x = r1.x * cb0[7].w;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // movc r0.x, r0.x, l(0), r1.x
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r1.x;
    // mul r0.x, r0.x, r0.y
    r0.x = r0.x * r0.y;
    // div r1.xy, v7.xyxx, v7.wwww
    float stage5_x = v7.x / v7.w;
    float stage5_y = v7.y / v7.w;
    r1.x = stage5_x;
    r1.y = stage5_y;
    // mad r1.xy, r1.xyxx, cb2[0].xyxx, cb2[0].wzww
    float stage6_x = r1.x * cb2[0].x + cb2[0].w;
    float stage6_y = r1.y * cb2[0].y + cb2[0].z;
    r1.x = stage6_x;
    r1.y = stage6_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.y, r1.xyxx, t0.yxzw, s0, l(0.000000)
    float4 fetch7 = t0.SampleLevel(s0, r1.xy, 0.0f);
    r0.y = fetch7.x;
    // min r0.y, r0.y, l(0.999000)
    r0.y = min(r0.y, 0.999f);
    // mad r1.x, r0.y, cb2[1].z, -cb2[1].w
    r1.x = r0.y * cb2[1].z + -cb2[1].w;
    // mad r0.y, r0.y, cb2[1].x, cb2[1].y
    r0.y = r0.y * cb2[1].x + cb2[1].y;
    // div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
    r1.x = 1.0f / r1.x;
    // add r0.y, r0.y, r1.x
    r0.y = r0.y + r1.x;
    // add r0.y, r0.y, -v7.w
    r0.y = r0.y + -v7.w;
    // add r1.x, -cb0[5].x, l(1.000000)
    r1.x = -cb0[5].x + 1.0f;
    // max r1.x, -r1.x, l(0.001000)
    r1.x = max(-r1.x, 0.001f);
    // div_sat r0.y, r0.y, r1.x
    r0.y = saturate(r0.y / r1.x);
    // mul r0.x, r0.y, r0.x
    r0.x = r0.y * r0.x;
    // mul_sat r0.x, r0.x, v3.w
    r0.x = saturate(r0.x * v3.w);
    // mul r0.x, r0.x, cb0[0].x
    r0.x = r0.x * cb0[0].x;
    // mad r1.x, cb0[3].y, cb0[3].x, r0.z
    r1.x = cb0[3].y * cb0[3].x + r0.z;
    // mad r1.y, cb0[3].y, cb0[4].x, r0.w
    r1.y = cb0[3].y * cb0[4].x + r0.w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.yzw, r1.xyxx, t2.wxyz, s1, l(0.000000)
    float4 fetch8 = t2.SampleBias(s1, r1.xy, 0.0f);
    r0.y = fetch8.x;
    r0.z = fetch8.y;
    r0.w = fetch8.z;
    // dp3 r1.x, r0.yzwy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.x = dot(r0.yzw, float3(0.3f, 0.59f, 0.11f));
    // add r1.xyz, -r0.yzwy, r1.xxxx
    float stage9_x = -r0.y + r1.x;
    float stage9_y = -r0.z + r1.x;
    float stage9_z = -r0.w + r1.x;
    r1.x = stage9_x;
    r1.y = stage9_y;
    r1.z = stage9_z;
    // mad r0.yzw, cb0[4].yyyy, r1.xxyz, r0.yyzw
    float stage10_y = cb0[4].y * r1.x + r0.y;
    float stage10_z = cb0[4].y * r1.y + r0.z;
    float stage10_w = cb0[4].y * r1.z + r0.w;
    r0.y = stage10_y;
    r0.z = stage10_z;
    r0.w = stage10_w;
    // max r0.yzw, |r0.yyzw|, l(0.000000, 0.000001, 0.000001, 0.000001)
    float stage11_y = max(abs(r0.y), 1e-06f);
    float stage11_z = max(abs(r0.z), 1e-06f);
    float stage11_w = max(abs(r0.w), 1e-06f);
    r0.y = stage11_y;
    r0.z = stage11_z;
    r0.w = stage11_w;
    // log r0.yzw, r0.yyzw
    float stage12_y = log2(r0.y);
    float stage12_z = log2(r0.z);
    float stage12_w = log2(r0.w);
    r0.y = stage12_y;
    r0.z = stage12_z;
    r0.w = stage12_w;
    // mul r0.yzw, r0.yyzw, cb0[4].zzzz
    float stage13_y = r0.y * cb0[4].z;
    float stage13_z = r0.z * cb0[4].z;
    float stage13_w = r0.w * cb0[4].z;
    r0.y = stage13_y;
    r0.z = stage13_z;
    r0.w = stage13_w;
    // exp r0.yzw, r0.yyzw
    float stage14_y = exp2(r0.y);
    float stage14_z = exp2(r0.z);
    float stage14_w = exp2(r0.w);
    r0.y = stage14_y;
    r0.z = stage14_z;
    r0.w = stage14_w;
    // mul r0.yzw, r0.yyzw, cb0[4].wwww
    float stage15_y = r0.y * cb0[4].w;
    float stage15_z = r0.z * cb0[4].w;
    float stage15_w = r0.w * cb0[4].w;
    r0.y = stage15_y;
    r0.z = stage15_z;
    r0.w = stage15_w;
    // mul r1.xyz, cb0[2].xyzx, cb0[2].wwww
    float stage16_x = cb0[2].x * cb0[2].w;
    float stage16_y = cb0[2].y * cb0[2].w;
    float stage16_z = cb0[2].z * cb0[2].w;
    r1.x = stage16_x;
    r1.y = stage16_y;
    r1.z = stage16_z;
    // mul r0.yzw, r0.yyzw, r1.xxyz
    float stage17_y = r0.y * r1.x;
    float stage17_z = r0.z * r1.y;
    float stage17_w = r0.w * r1.z;
    r0.y = stage17_y;
    r0.z = stage17_z;
    r0.w = stage17_w;
    // mad r0.yzw, r0.yyzw, v3.xxyz, cb0[1].xxyz
    float stage18_y = r0.y * v3.x + cb0[1].x;
    float stage18_z = r0.z * v3.y + cb0[1].y;
    float stage18_w = r0.w * v3.z + cb0[1].z;
    r0.y = stage18_y;
    r0.z = stage18_z;
    r0.w = stage18_w;
    // mul r0.yzw, r0.yyzw, v5.wwww
    float stage19_y = r0.y * v5.w;
    float stage19_z = r0.z * v5.w;
    float stage19_w = r0.w * v5.w;
    r0.y = stage19_y;
    r0.z = stage19_z;
    r0.w = stage19_w;
    // mul o0.xyz, r0.xxxx, r0.yzwy
    float stage20_x = r0.x * r0.y;
    float stage20_y = r0.x * r0.z;
    float stage20_z = r0.x * r0.w;
    o0.x = stage20_x;
    o0.y = stage20_y;
    o0.z = stage20_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_d_pa_shockwave_02_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
