// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_afterburn_01_tr_Constants0 : register(b0)
{
    float4 cb0[15];
};
cbuffer Shade_Ue3_fx_d_pa_afterburn_01_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);

struct Shade_Ue3_fx_d_pa_afterburn_01_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_d_pa_afterburn_01_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_d_pa_afterburn_01_tr_OUTPUT Shade_Ue3_fx_d_pa_afterburn_01_tr(Shade_Ue3_fx_d_pa_afterburn_01_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mul r0.x, v4.w, cb0[10].y
    r0.x = v4.w * cb0[10].y;
    // mad r0.yz, r0.xxxx, v2.xxyx, l(0.000000, -0.500000, -0.500000, 0.000000)
    float stage1_y = r0.x * v2.x + -0.5f;
    float stage1_z = r0.x * v2.y + -0.5f;
    r0.y = stage1_y;
    r0.z = stage1_z;
    // mul r1.xyzw, r0.xxxx, l(1.330000, 1.330000, 1.768900, 1.768900)
    float stage2_x = r0.x * 1.33f;
    float stage2_y = r0.x * 1.33f;
    float stage2_z = r0.x * 1.7689f;
    float stage2_w = r0.x * 1.7689f;
    r1.x = stage2_x;
    r1.y = stage2_y;
    r1.z = stage2_z;
    r1.w = stage2_w;
    // mad r1.xyzw, r1.xyzw, v2.xyxy, l(-0.500000, -0.500000, -0.500000, -0.500000)
    float stage3_x = r1.x * v2.x + -0.5f;
    float stage3_y = r1.y * v2.y + -0.5f;
    float stage3_z = r1.z * v2.x + -0.5f;
    float stage3_w = r1.w * v2.y + -0.5f;
    r1.x = stage3_x;
    r1.y = stage3_y;
    r1.z = stage3_z;
    r1.w = stage3_w;
    // dp2 r0.x, cb0[5].xyxx, r0.yzyy
    r0.x = dot(cb0[5].xy, r0.yz);
    // dp2 r2.x, cb0[4].xyxx, r0.yzyy
    r2.x = dot(cb0[4].xy, r0.yz);
    // mad r2.y, v4.x, l(0.020000), r0.x
    r2.y = v4.x * 0.02f + r0.x;
    // add r0.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage4_x = r2.x + 0.5f;
    float stage4_y = r2.y + 0.5f;
    r0.x = stage4_x;
    r0.y = stage4_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t0.xyzw, s1, l(0.000000)
    float4 fetch5 = t0.SampleBias(s1, r0.xy, 0.0f);
    r0.x = fetch5.x;
    // dp2 r0.y, cb0[7].xyxx, r1.xyxx
    r0.y = dot(cb0[7].xy, r1.xy);
    // mad r2.y, v4.x, l(0.020000), r0.y
    r2.y = v4.x * 0.02f + r0.y;
    // dp2 r2.x, cb0[6].xyxx, r1.xyxx
    r2.x = dot(cb0[6].xy, r1.xy);
    // add r0.yz, r2.xxyx, l(0.000000, 0.500000, 0.500000, 0.000000)
    float stage6_y = r2.x + 0.5f;
    float stage6_z = r2.y + 0.5f;
    r0.y = stage6_y;
    r0.z = stage6_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t0.yxzw, s1, l(0.000000)
    float4 fetch7 = t0.SampleBias(s1, r0.yz, 0.0f);
    r0.y = fetch7.x;
    // mul r0.y, r0.y, l(0.333300)
    r0.y = r0.y * 0.3333f;
    // mad r0.x, r0.x, l(0.333300), r0.y
    r0.x = r0.x * 0.3333f + r0.y;
    // dp2 r0.y, cb0[9].xyxx, r1.zwzz
    r0.y = dot(cb0[9].xy, r1.zw);
    // dp2 r1.x, cb0[8].xyxx, r1.zwzz
    r1.x = dot(cb0[8].xy, r1.zw);
    // mad r1.y, v4.x, l(0.020000), r0.y
    r1.y = v4.x * 0.02f + r0.y;
    // add r0.yz, r1.xxyx, l(0.000000, 0.500000, 0.500000, 0.000000)
    float stage8_y = r1.x + 0.5f;
    float stage8_z = r1.y + 0.5f;
    r0.y = stage8_y;
    r0.z = stage8_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t0.yxzw, s1, l(0.000000)
    float4 fetch9 = t0.SampleBias(s1, r0.yz, 0.0f);
    r0.y = fetch9.x;
    // mad r0.x, r0.y, l(0.333300), r0.x
    r0.x = r0.y * 0.3333f + r0.x;
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // mul r0.y, r0.y, cb0[12].y
    r0.y = r0.y * cb0[12].y;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul r0.y, r0.y, cb0[12].w
    r0.y = r0.y * cb0[12].w;
    // mov_sat r0.z, v4.z
    r0.z = saturate(v4.z);
    // add r0.z, -r0.z, l(1.000000)
    r0.z = -r0.z + 1.0f;
    // mul r0.y, r0.z, r0.y
    r0.y = r0.z * r0.y;
    // lt r0.z, |r0.x|, l(0.000001)
    r0.z = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // add r0.x, -r0.x, l(1.000000)
    r0.x = -r0.x + 1.0f;
    // movc r0.y, r0.z, l(-0.000000), -r0.y
    r0.y = asuint(r0.z) != 0u ? -0.0f : -r0.y;
    // add r0.zw, v2.xxxy, l(0.000000, 0.000000, -0.500000, -0.500000)
    float stage10_z = v2.x + -0.5f;
    float stage10_w = v2.y + -0.5f;
    r0.z = stage10_z;
    r0.w = stage10_w;
    // dp2 r0.z, r0.zwzz, r0.zwzz
    r0.z = dot(r0.zw, r0.zw);
    // sqrt r0.z, r0.z
    r0.z = sqrt(r0.z);
    // mad r0.z, -r0.z, l(1.428571), l(1.000000)
    r0.z = -r0.z * 1.428571f + 1.0f;
    // max r0.z, r0.z, l(0.000000)
    r0.z = max(r0.z, 0.0f);
    // add r0.w, r0.z, r0.x
    r0.w = r0.z + r0.x;
    // mul_sat r0.x, r0.x, cb0[11].y
    r0.x = saturate(r0.x * cb0[11].y);
    // add r0.w, r0.w, -cb0[11].w
    r0.w = r0.w + -cb0[11].w;
    // mad r0.y, r0.w, r0.z, r0.y
    r0.y = r0.w * r0.z + r0.y;
    // mul_sat r0.y, r0.y, cb0[13].x
    r0.y = saturate(r0.y * cb0[13].x);
    // log r0.z, r0.y
    r0.z = log2(r0.y);
    // lt r0.y, r0.y, l(0.000001)
    r0.y = asfloat((r0.y < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, cb0[13].y
    r0.z = r0.z * cb0[13].y;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // div r1.xy, v7.xyxx, v7.wwww
    float stage11_x = v7.x / v7.w;
    float stage11_y = v7.y / v7.w;
    r1.x = stage11_x;
    r1.y = stage11_y;
    // mad r1.xy, r1.xyxx, cb2[0].xyxx, cb2[0].wzww
    float stage12_x = r1.x * cb2[0].x + cb2[0].w;
    float stage12_y = r1.y * cb2[0].y + cb2[0].z;
    r1.x = stage12_x;
    r1.y = stage12_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t1.yzwx, s0, l(0.000000)
    float4 fetch13 = t1.SampleLevel(s0, r1.xy, 0.0f);
    r0.w = fetch13.x;
    // min r0.w, r0.w, l(0.999000)
    r0.w = min(r0.w, 0.999f);
    // mad r1.x, r0.w, cb2[1].z, -cb2[1].w
    r1.x = r0.w * cb2[1].z + -cb2[1].w;
    // mad r0.w, r0.w, cb2[1].x, cb2[1].y
    r0.w = r0.w * cb2[1].x + cb2[1].y;
    // div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
    r1.x = 1.0f / r1.x;
    // add r0.w, r0.w, r1.x
    r0.w = r0.w + r1.x;
    // add r0.w, r0.w, -v7.w
    r0.w = r0.w + -v7.w;
    // add r1.x, -cb0[14].x, l(1.000000)
    r1.x = -cb0[14].x + 1.0f;
    // mul r1.x, r1.x, l(100.000000)
    r1.x = r1.x * 100.0f;
    // max r1.x, r1.x, l(0.001000)
    r1.x = max(r1.x, 0.001f);
    // div_sat r0.w, r0.w, r1.x
    r0.w = saturate(r0.w / r1.x);
    // mul r0.z, r0.w, r0.z
    r0.z = r0.w * r0.z;
    // mul_sat r0.z, r0.z, v3.w
    r0.z = saturate(r0.z * v3.w);
    // mul r0.z, r0.z, cb0[0].x
    r0.z = r0.z * cb0[0].x;
    // movc o0.w, r0.y, l(0), r0.z
    o0.w = asuint(r0.y) != 0u ? asfloat(0u) : r0.z;
    // log r0.y, r0.x
    r0.y = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[11].z
    r0.y = r0.y * cb0[11].z;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // mul r0.yzw, cb0[2].xxyz, cb0[2].wwww
    float stage14_y = cb0[2].x * cb0[2].w;
    float stage14_z = cb0[2].y * cb0[2].w;
    float stage14_w = cb0[2].z * cb0[2].w;
    r0.y = stage14_y;
    r0.z = stage14_z;
    r0.w = stage14_w;
    // mad r1.xyz, cb0[3].wwww, cb0[3].xyzx, -r0.yzwy
    float stage15_x = cb0[3].w * cb0[3].x + -r0.y;
    float stage15_y = cb0[3].w * cb0[3].y + -r0.z;
    float stage15_z = cb0[3].w * cb0[3].z + -r0.w;
    r1.x = stage15_x;
    r1.y = stage15_y;
    r1.z = stage15_z;
    // mad r0.xyz, r0.xxxx, r1.xyzx, r0.yzwy
    float stage16_x = r0.x * r1.x + r0.y;
    float stage16_y = r0.x * r1.y + r0.z;
    float stage16_z = r0.x * r1.z + r0.w;
    r0.x = stage16_x;
    r0.y = stage16_y;
    r0.z = stage16_z;
    // mad r0.xyz, r0.xyzx, v3.xyzx, cb0[1].xyzx
    float stage17_x = r0.x * v3.x + cb0[1].x;
    float stage17_y = r0.y * v3.y + cb0[1].y;
    float stage17_z = r0.z * v3.z + cb0[1].z;
    r0.x = stage17_x;
    r0.y = stage17_y;
    r0.z = stage17_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage18_x = r0.x * v5.w + v5.x;
    float stage18_y = r0.y * v5.w + v5.y;
    float stage18_z = r0.z * v5.w + v5.z;
    o0.x = stage18_x;
    o0.y = stage18_y;
    o0.z = stage18_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage19_x = r0.x * v1.x;
    float stage19_y = r0.x * v1.y;
    float stage19_z = r0.x * v1.z;
    r0.x = stage19_x;
    r0.y = stage19_y;
    r0.z = stage19_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage20_x = r0.w * v0.z;
    float stage20_y = r0.w * v0.x;
    float stage20_z = r0.w * v0.y;
    r1.x = stage20_x;
    r1.y = stage20_y;
    r1.z = stage20_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage21_x = r0.x * r1.x;
    float stage21_y = r0.x * r1.y;
    float stage21_z = r0.x * r1.z;
    r0.x = stage21_x;
    r0.y = stage21_y;
    r0.z = stage21_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage22_x = r0.x / r0.w;
    float stage22_y = r0.y / r0.w;
    r0.x = stage22_x;
    r0.y = stage22_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage23_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage23_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage23_x;
    r1.y = stage23_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage24_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage24_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage24_x;
    r1.y = stage24_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage25_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage25_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage25_x;
    r1.y = stage25_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage26_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage26_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage26_x;
    r0.y = stage26_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage27_x = r0.x * 0.5f + 0.5f;
    float stage27_y = r0.y * 0.5f + 0.5f;
    o2.x = stage27_x;
    o2.y = stage27_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage28_z = 1.0f;
    float stage28_w = asfloat(0u);
    o2.z = stage28_z;
    o2.w = stage28_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage29_x = cb2[3].x;
    float stage29_y = cb2[3].y;
    float stage29_z = cb2[3].z;
    o3.x = stage29_x;
    o3.y = stage29_y;
    o3.z = stage29_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage30_x = asfloat(0u);
    float stage30_y = asfloat(0u);
    float stage30_z = asfloat(0u);
    float stage30_w = asfloat(0u);
    o4.x = stage30_x;
    o4.y = stage30_y;
    o4.z = stage30_z;
    o4.w = stage30_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage31_x = asfloat(0u);
    float stage31_y = asfloat(0u);
    float stage31_z = asfloat(0u);
    float stage31_w = asfloat(0u);
    o5.x = stage31_x;
    o5.y = stage31_y;
    o5.z = stage31_z;
    o5.w = stage31_w;

    Shade_Ue3_fx_d_pa_afterburn_01_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
