// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_j_pa_highpixelring_01_ad_Constants0 : register(b0)
{
    float4 cb0[13];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);

struct Shade_Ue3_fx_j_pa_highpixelring_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_j_pa_highpixelring_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_j_pa_highpixelring_01_ad_OUTPUT Shade_Ue3_fx_j_pa_highpixelring_01_ad(Shade_Ue3_fx_j_pa_highpixelring_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;

    // mad r0.xy, v2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
    float stage1_x = v2.x * 2.0f + -1.0f;
    float stage1_y = v2.y * 2.0f + -1.0f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.x|, |r0.y|
    r0.z = max(abs(r0.x), abs(r0.y));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.x|, |r0.y|
    r0.w = min(abs(r0.x), abs(r0.y));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.x|, |r0.y|
    r1.y = asfloat((abs(r0.x) < abs(r0.y)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.x, -r0.x
    r0.w = asfloat((r0.x < -r0.x) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.x, r0.y
    r0.w = min(r0.x, r0.y);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.x, r0.y
    r1.x = max(r0.x, r0.y);
    // mul r0.xy, r0.xyxx, r0.xyxx
    float stage2_x = r0.x * r0.x;
    float stage2_y = r0.y * r0.y;
    r0.x = stage2_x;
    r0.y = stage2_y;
    // add r0.x, r0.y, r0.x
    r0.x = r0.y + r0.x;
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // mov r0.y, -r0.x
    r0.y = -r0.x;
    // ge r1.x, r1.x, -r1.x
    r1.x = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, r1.x
    r0.w = asfloat(asuint(r0.w) & asuint(r1.x));
    // movc r0.z, r0.w, -r0.z, r0.z
    r0.z = asuint(r0.w) != 0u ? -r0.z : r0.z;
    // mul r0.z, r0.z, l(0.159155)
    r0.z = r0.z * 0.159155f;
    // frc r0.x, r0.z
    r0.x = frac(r0.z);
    // add r0.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
    float stage3_x = r0.x + -0.5f;
    float stage3_y = r0.y + 0.5f;
    r0.x = stage3_x;
    r0.y = stage3_y;
    // mad r0.xy, r0.xyxx, cb0[9].yzyy, cb0[10].xzxx
    float stage4_x = r0.x * cb0[9].y + cb0[10].x;
    float stage4_y = r0.y * cb0[9].z + cb0[10].z;
    r0.x = stage4_x;
    r0.y = stage4_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t3.xyzw, s3, l(0.000000)
    float4 fetch5 = t3.SampleBias(s3, r0.xy, 0.0f);
    r0.x = fetch5.x;
    // mad r0.xy, r0.xxxx, cb0[10].wwww, v2.xyxx
    float stage6_x = r0.x * cb0[10].w + v2.x;
    float stage6_y = r0.x * cb0[10].w + v2.y;
    r0.x = stage6_x;
    r0.y = stage6_y;
    // mad r0.xy, r0.xyxx, cb0[11].xyxx, cb0[11].zwzz
    float stage7_x = r0.x * cb0[11].x + cb0[11].z;
    float stage7_y = r0.y * cb0[11].y + cb0[11].w;
    r0.x = stage7_x;
    r0.y = stage7_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t4.xyzw, s4, l(0.000000)
    float4 fetch8 = t4.SampleBias(s4, r0.xy, 0.0f);
    r0.x = fetch8.x;
    // mul r0.x, r0.x, cb0[12].x
    r0.x = r0.x * cb0[12].x;
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // lt r0.x, |r0.x|, l(0.000001)
    r0.x = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[12].y
    r0.y = r0.y * cb0[12].y;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // add r0.yz, v2.xxyx, cb0[3].xxyx
    float stage9_y = v2.x + cb0[3].x;
    float stage9_z = v2.y + cb0[3].y;
    r0.y = stage9_y;
    r0.z = stage9_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.yz, r0.yzyy, t0.zxyw, s0, l(0.000000)
    float4 fetch10 = t0.SampleBias(s0, r0.yz, 0.0f);
    r0.y = fetch10.x;
    r0.z = fetch10.y;
    // mad r0.yz, r0.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
    float stage11_y = r0.y * 2.0f + -1.0f;
    float stage11_z = r0.z * 2.0f + -1.0f;
    r0.y = stage11_y;
    r0.z = stage11_z;
    // mul r0.yz, r0.yyzy, l(0.000000, 0.050000, 0.050000, 0.000000)
    float stage12_y = r0.y * 0.05f;
    float stage12_z = r0.z * 0.05f;
    r0.y = stage12_y;
    r0.z = stage12_z;
    // mad r0.yz, cb0[2].xxyx, v2.xxyx, r0.yyzy
    float stage13_y = cb0[2].x * v2.x + r0.y;
    float stage13_z = cb0[2].y * v2.y + r0.z;
    r0.y = stage13_y;
    r0.z = stage13_z;
    // add r0.yz, r0.yyzy, cb0[4].xxyx
    float stage14_y = r0.y + cb0[4].x;
    float stage14_z = r0.z + cb0[4].y;
    r0.y = stage14_y;
    r0.z = stage14_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t1.yxzw, s1, l(0.000000)
    float4 fetch15 = t1.SampleBias(s1, r0.yz, 0.0f);
    r0.y = fetch15.x;
    // log r0.z, |r0.y|
    r0.z = log2(abs(r0.y));
    // lt r0.y, |r0.y|, l(0.000001)
    r0.y = asfloat((abs(r0.y) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, cb0[7].w
    r0.z = r0.z * cb0[7].w;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // movc r0.y, r0.y, l(0), r0.z
    r0.y = asuint(r0.y) != 0u ? asfloat(0u) : r0.z;
    // add r0.z, v4.y, cb0[8].x
    r0.z = v4.y + cb0[8].x;
    // add r0.y, -r0.z, r0.y
    r0.y = -r0.z + r0.y;
    // mul_sat r0.yz, r0.yyyy, l(0.000000, 10.000000, 8.000000, 0.000000)
    float stage16_y = saturate(r0.y * 10.0f);
    float stage16_z = saturate(r0.y * 8.0f);
    r0.y = stage16_y;
    r0.z = stage16_z;
    // add r0.z, -r0.z, r0.y
    r0.z = -r0.z + r0.y;
    // mul r0.z, r0.z, cb0[8].y
    r0.z = r0.z * cb0[8].y;
    // log r0.w, |r0.z|
    r0.w = log2(abs(r0.z));
    // lt r0.z, |r0.z|, l(0.000001)
    r0.z = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.w, r0.w, cb0[8].z
    r0.w = r0.w * cb0[8].z;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // movc r0.z, r0.z, l(0), r0.w
    r0.z = asuint(r0.z) != 0u ? asfloat(0u) : r0.w;
    // mul r1.xyz, v3.xyzx, cb0[5].xyzx
    float stage17_x = v3.x * cb0[5].x;
    float stage17_y = v3.y * cb0[5].y;
    float stage17_z = v3.z * cb0[5].z;
    r1.x = stage17_x;
    r1.y = stage17_y;
    r1.z = stage17_z;
    // mad r2.xy, v2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), cb0[6].xyxx
    float stage18_x = v2.x * 2.0f + cb0[6].x;
    float stage18_y = v2.y * 2.0f + cb0[6].y;
    r2.x = stage18_x;
    r2.y = stage18_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.w, r2.xyxx, t2.yzwx, s2, l(0.000000)
    float4 fetch19 = t2.SampleBias(s2, r2.xy, 0.0f);
    r0.w = fetch19.x;
    // mul r1.w, |r0.w|, |r0.w|
    r1.w = abs(r0.w) * abs(r0.w);
    // lt r0.w, |r0.w|, l(0.000001)
    r0.w = asfloat((abs(r0.w) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.xyz, r1.xyzx, r1.wwww
    float stage20_x = r1.x * r1.w;
    float stage20_y = r1.y * r1.w;
    float stage20_z = r1.z * r1.w;
    r1.x = stage20_x;
    r1.y = stage20_y;
    r1.z = stage20_z;
    // movc r1.xyz, r0.wwww, l(0,0,0,0), r1.xyzx
    float stage21_x = asuint(r0.w) != 0u ? asfloat(0u) : r1.x;
    float stage21_y = asuint(r0.w) != 0u ? asfloat(0u) : r1.y;
    float stage21_z = asuint(r0.w) != 0u ? asfloat(0u) : r1.z;
    r1.x = stage21_x;
    r1.y = stage21_y;
    r1.z = stage21_z;
    // mad r1.xyz, r0.zzzz, r1.xyzx, l(0.010000, 0.010000, 0.010000, 0.000000)
    float stage22_x = r0.z * r1.x + 0.01f;
    float stage22_y = r0.z * r1.y + 0.01f;
    float stage22_z = r0.z * r1.z + 0.01f;
    r1.x = stage22_x;
    r1.y = stage22_y;
    r1.z = stage22_z;
    // add r0.xzw, r0.xxxx, r1.xxyz
    float stage23_x = r0.x + r1.x;
    float stage23_z = r0.x + r1.y;
    float stage23_w = r0.x + r1.z;
    r0.x = stage23_x;
    r0.z = stage23_z;
    r0.w = stage23_w;
    // mad r0.xzw, r0.xxzw, v3.xxyz, cb0[1].xxyz
    float stage24_x = r0.x * v3.x + cb0[1].x;
    float stage24_z = r0.z * v3.y + cb0[1].y;
    float stage24_w = r0.w * v3.z + cb0[1].z;
    r0.x = stage24_x;
    r0.z = stage24_z;
    r0.w = stage24_w;
    // mul r0.xzw, r0.xxzw, v5.wwww
    float stage25_x = r0.x * v5.w;
    float stage25_z = r0.z * v5.w;
    float stage25_w = r0.w * v5.w;
    r0.x = stage25_x;
    r0.z = stage25_z;
    r0.w = stage25_w;
    // add r1.x, v4.x, cb0[12].z
    r1.x = v4.x + cb0[12].z;
    // add r1.x, r1.x, l(-1.000000)
    r1.x = r1.x + -1.0f;
    // mad r1.x, r1.x, l(10.000000), l(10.000000)
    r1.x = r1.x * 10.0f + 10.0f;
    // add r1.yz, v2.xxyx, l(0.000000, -0.500000, -0.500000, 0.000000)
    float stage26_y = v2.x + -0.5f;
    float stage26_z = v2.y + -0.5f;
    r1.y = stage26_y;
    r1.z = stage26_z;
    // mul r1.yz, r1.yyzy, r1.yyzy
    float stage27_y = r1.y * r1.y;
    float stage27_z = r1.z * r1.z;
    r1.y = stage27_y;
    r1.z = stage27_z;
    // add r1.y, r1.z, r1.y
    r1.y = r1.z + r1.y;
    // add r1.y, -r1.y, l(1.000000)
    r1.y = -r1.y + 1.0f;
    // log r1.z, |r1.y|
    r1.z = log2(abs(r1.y));
    // lt r1.y, |r1.y|, l(0.000001)
    r1.y = asfloat((abs(r1.y) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.x, r1.z, r1.x
    r1.x = r1.z * r1.x;
    // mul r1.z, r1.z, l(10.000000)
    r1.z = r1.z * 10.0f;
    // exp r1.z, r1.z
    r1.z = exp2(r1.z);
    // mul r1.z, r1.z, l(5.000000)
    r1.z = r1.z * 5.0f;
    // round_ni r1.z, r1.z
    r1.z = floor(r1.z);
    // min r1.z, r1.z, l(1.000000)
    r1.z = min(r1.z, 1.0f);
    // movc r1.z, r1.y, l(0), r1.z
    r1.z = asuint(r1.y) != 0u ? asfloat(0u) : r1.z;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // mul r1.x, r1.x, l(5.000000)
    r1.x = r1.x * 5.0f;
    // round_ni r1.x, r1.x
    r1.x = floor(r1.x);
    // min r1.x, r1.x, l(1.000000)
    r1.x = min(r1.x, 1.0f);
    // movc r1.x, r1.y, l(-0.000000), -r1.x
    r1.x = asuint(r1.y) != 0u ? -0.0f : -r1.x;
    // add r1.x, r1.x, r1.z
    r1.x = r1.x + r1.z;
    // mul r0.y, r0.y, r1.x
    r0.y = r0.y * r1.x;
    // max r0.y, r0.y, l(0.000000)
    r0.y = max(r0.y, 0.0f);
    // mul r0.y, r0.y, v3.w
    r0.y = r0.y * v3.w;
    // mul r0.y, r0.y, cb0[0].x
    r0.y = r0.y * cb0[0].x;
    // mul o0.xyz, r0.yyyy, r0.xzwx
    float stage28_x = r0.y * r0.x;
    float stage28_y = r0.y * r0.z;
    float stage28_z = r0.y * r0.w;
    o0.x = stage28_x;
    o0.y = stage28_y;
    o0.z = stage28_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_j_pa_highpixelring_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
