// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_e_pa_auradissolve_01_Constants0 : register(b0)
{
    float4 cb0[3];
};
cbuffer Shade_Ue3_fx_e_pa_auradissolve_01_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);

struct Shade_Ue3_fx_e_pa_auradissolve_01_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_e_pa_auradissolve_01_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_e_pa_auradissolve_01_OUTPUT Shade_Ue3_fx_e_pa_auradissolve_01(Shade_Ue3_fx_e_pa_auradissolve_01_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mov r0.x, l(0.500000)
    r0.x = 0.5f;
    // mul r0.z, v4.x, cb0[2].x
    r0.z = v4.x * cb0[2].x;
    // add r1.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.x + -0.5f;
    float stage1_y = v2.y + -0.5f;
    r1.x = stage1_x;
    r1.y = stage1_y;
    // mad r0.w, -v4.x, l(0.050000), l(1.000000)
    r0.w = -v4.x * 0.05f + 1.0f;
    // mad r1.zw, r0.wwww, r1.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
    float stage2_z = r0.w * r1.x + 0.5f;
    float stage2_w = r0.w * r1.y + 0.5f;
    r1.z = stage2_z;
    r1.w = stage2_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.z, r1.zwzz, t0.yzxw, s0, l(0.000000)
    float4 fetch3 = t0.SampleBias(s0, r1.zw, 0.0f);
    r1.z = fetch3.x;
    // mul r0.z, r0.z, r1.z
    r0.z = r0.z * r1.z;
    // mul r0.y, r0.z, l(7.500000)
    r0.y = r0.z * 7.5f;
    // mul r1.x, r1.x, r0.w
    r1.x = r1.x * r0.w;
    // mad r1.z, r0.w, r1.y, l(0.500000)
    r1.z = r0.w * r1.y + 0.5f;
    // add r0.xy, r0.xyxx, r1.xzxx
    float stage4_x = r0.x + r1.x;
    float stage4_y = r0.y + r1.z;
    r0.x = stage4_x;
    r0.y = stage4_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r0.xyxx, t2.yzxw, s2, l(0.000000)
    float4 fetch5 = t2.SampleBias(s2, r0.xy, 0.0f);
    r0.z = fetch5.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.xyxx, t1.xyzw, s1, l(0.000000)
    float4 fetch6 = t1.SampleBias(s1, r0.xy, 0.0f);
    r1.x = fetch6.x;
    r1.y = fetch6.y;
    r1.z = fetch6.z;
    r1.w = fetch6.w;
    // lt r0.x, |r0.z|, l(0.000001)
    r0.x = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // log r0.y, |r0.z|
    r0.y = log2(abs(r0.z));
    // mad r0.z, v4.x, l(1.200000), l(-1.000000)
    r0.z = v4.x * 1.2f + -1.0f;
    // mul r0.y, r0.y, r0.z
    r0.y = r0.y * r0.z;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // add r0.x, -r0.z, r0.x
    r0.x = -r0.z + r0.x;
    // add_sat r0.x, r0.x, l(1.000000)
    r0.x = saturate(r0.x + 1.0f);
    // mul r0.x, r0.x, r1.w
    r0.x = r0.x * r1.w;
    // mad r0.yzw, r1.xxyz, v3.xxyz, cb0[1].xxyz
    float stage7_y = r1.x * v3.x + cb0[1].x;
    float stage7_z = r1.y * v3.y + cb0[1].y;
    float stage7_w = r1.z * v3.z + cb0[1].z;
    r0.y = stage7_y;
    r0.z = stage7_z;
    r0.w = stage7_w;
    // mad o0.xyz, r0.yzwy, v5.wwww, v5.xyzx
    float stage8_x = r0.y * v5.w + v5.x;
    float stage8_y = r0.z * v5.w + v5.y;
    float stage8_z = r0.w * v5.w + v5.z;
    o0.x = stage8_x;
    o0.y = stage8_y;
    o0.z = stage8_z;
    // mul r0.x, r0.x, v3.w
    r0.x = r0.x * v3.w;
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // lt r0.x, |r0.x|, l(0.000001)
    r0.x = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, v4.y
    r0.y = r0.y * v4.y;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // min r0.y, r0.y, l(1.000000)
    r0.y = min(r0.y, 1.0f);
    // mul r0.y, r0.y, cb0[0].x
    r0.y = r0.y * cb0[0].x;
    // movc o0.w, r0.x, l(0), r0.y
    o0.w = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage9_x = r0.x * v1.x;
    float stage9_y = r0.x * v1.y;
    float stage9_z = r0.x * v1.z;
    r0.x = stage9_x;
    r0.y = stage9_y;
    r0.z = stage9_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage10_x = r0.w * v0.z;
    float stage10_y = r0.w * v0.x;
    float stage10_z = r0.w * v0.y;
    r1.x = stage10_x;
    r1.y = stage10_y;
    r1.z = stage10_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage11_x = r0.x * r1.x;
    float stage11_y = r0.x * r1.y;
    float stage11_z = r0.x * r1.z;
    r0.x = stage11_x;
    r0.y = stage11_y;
    r0.z = stage11_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage12_x = r0.x / r0.w;
    float stage12_y = r0.y / r0.w;
    r0.x = stage12_x;
    r0.y = stage12_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage13_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage13_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage13_x;
    r1.y = stage13_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage14_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage14_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage14_x;
    r1.y = stage14_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage15_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage15_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage15_x;
    r1.y = stage15_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage16_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage16_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage16_x;
    r0.y = stage16_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage17_x = r0.x * 0.5f + 0.5f;
    float stage17_y = r0.y * 0.5f + 0.5f;
    o2.x = stage17_x;
    o2.y = stage17_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage18_z = 1.0f;
    float stage18_w = asfloat(0u);
    o2.z = stage18_z;
    o2.w = stage18_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage19_x = cb2[3].x;
    float stage19_y = cb2[3].y;
    float stage19_z = cb2[3].z;
    o3.x = stage19_x;
    o3.y = stage19_y;
    o3.z = stage19_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage20_x = asfloat(0u);
    float stage20_y = asfloat(0u);
    float stage20_z = asfloat(0u);
    float stage20_w = asfloat(0u);
    o4.x = stage20_x;
    o4.y = stage20_y;
    o4.z = stage20_z;
    o4.w = stage20_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage21_x = asfloat(0u);
    float stage21_y = asfloat(0u);
    float stage21_z = asfloat(0u);
    float stage21_w = asfloat(0u);
    o5.x = stage21_x;
    o5.y = stage21_y;
    o5.z = stage21_z;
    o5.w = stage21_w;

    Shade_Ue3_fx_e_pa_auradissolve_01_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
