// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_mm_extraalpha_01_ad_Constants0 : register(b0)
{
    float4 cb0[7];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);

struct Shade_Ue3_fx_mm_extraalpha_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_mm_extraalpha_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_mm_extraalpha_01_ad_OUTPUT Shade_Ue3_fx_mm_extraalpha_01_ad(Shade_Ue3_fx_mm_extraalpha_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;

    // mul r0.xy, v2.xyxx, cb0[3].zwzz
    float stage1_x = v2.x * cb0[3].z;
    float stage1_y = v2.y * cb0[3].w;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // mad r1.x, cb0[3].y, cb0[3].x, r0.x
    r1.x = cb0[3].y * cb0[3].x + r0.x;
    // mad r1.y, cb0[3].y, cb0[4].x, r0.y
    r1.y = cb0[3].y * cb0[4].x + r0.y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.xy, r1.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch2 = t0.SampleBias(s0, r1.xy, 0.0f);
    r0.x = fetch2.x;
    r0.y = fetch2.y;
    // mad r0.zw, cb0[3].yyyy, cb0[2].xxxy, v2.xxxy
    float stage3_z = cb0[3].y * cb0[2].x + v2.x;
    float stage3_w = cb0[3].y * cb0[2].y + v2.y;
    r0.z = stage3_z;
    r0.w = stage3_w;
    // mad r0.xy, cb0[4].yyyy, r0.xyxx, r0.zwzz
    float stage4_x = cb0[4].y * r0.x + r0.z;
    float stage4_y = cb0[4].y * r0.y + r0.w;
    r0.x = stage4_x;
    r0.y = stage4_y;
    // add r0.z, cb0[5].x, l(-1.000000)
    r0.z = cb0[5].x + -1.0f;
    // mul r0.z, r0.z, l(0.500000)
    r0.z = r0.z * 0.5f;
    // mad r0.xy, cb0[5].xxxx, r0.xyxx, -r0.zzzz
    float stage5_x = cb0[5].x * r0.x + -r0.z;
    float stage5_y = cb0[5].x * r0.y + -r0.z;
    r0.x = stage5_x;
    r0.y = stage5_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r0.xyxx, t1.yzxw, s2, l(0.000000)
    float4 fetch6 = t1.SampleBias(s2, r0.xy, 0.0f);
    r0.z = fetch6.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.xyw, r0.xyxx, t3.xywz, s1, l(0.000000)
    float4 fetch7 = t3.SampleBias(s1, r0.xy, 0.0f);
    r0.x = fetch7.x;
    r0.y = fetch7.y;
    r0.w = fetch7.z;
    // log r1.x, |r0.z|
    r1.x = log2(abs(r0.z));
    // lt r0.z, |r0.z|, l(0.000001)
    r0.z = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.x, r1.x, cb0[6].y
    r1.x = r1.x * cb0[6].y;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // mul r1.x, r1.x, v3.w
    r1.x = r1.x * v3.w;
    // movc r0.z, r0.z, l(0), |r1.x|
    r0.z = asuint(r0.z) != 0u ? asfloat(0u) : abs(r1.x);
    // log r1.x, r0.z
    r1.x = log2(r0.z);
    // lt r0.z, r0.z, l(0.000001)
    r0.z = asfloat((r0.z < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.x, r1.x, v4.y
    r1.x = r1.x * v4.y;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // movc r0.z, r0.z, l(0), r1.x
    r0.z = asuint(r0.z) != 0u ? asfloat(0u) : r1.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.x, v2.xyxx, t2.xyzw, s3, l(0.000000)
    float4 fetch8 = t2.SampleBias(s3, v2.xy, 0.0f);
    r1.x = fetch8.x;
    // mul r0.z, r0.z, r1.x
    r0.z = r0.z * r1.x;
    // mul r0.z, r0.z, cb0[0].x
    r0.z = r0.z * cb0[0].x;
    // mul r1.xyz, r0.xywx, cb0[5].yyyy
    float stage9_x = r0.x * cb0[5].y;
    float stage9_y = r0.y * cb0[5].y;
    float stage9_z = r0.w * cb0[5].y;
    r1.x = stage9_x;
    r1.y = stage9_y;
    r1.z = stage9_z;
    // dp3 r1.w, r1.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.w = dot(r1.xyz, float3(0.3f, 0.59f, 0.11f));
    // mad r0.xyw, -cb0[5].yyyy, r0.xyxw, r1.wwww
    float stage10_x = -cb0[5].y * r0.x + r1.w;
    float stage10_y = -cb0[5].y * r0.y + r1.w;
    float stage10_w = -cb0[5].y * r0.w + r1.w;
    r0.x = stage10_x;
    r0.y = stage10_y;
    r0.w = stage10_w;
    // mad r0.xyw, cb0[5].zzzz, r0.xyxw, r1.xyxz
    float stage11_x = cb0[5].z * r0.x + r1.x;
    float stage11_y = cb0[5].z * r0.y + r1.y;
    float stage11_w = cb0[5].z * r0.w + r1.z;
    r0.x = stage11_x;
    r0.y = stage11_y;
    r0.w = stage11_w;
    // mul r1.xyz, r0.xywx, cb0[5].wwww
    float stage12_x = r0.x * cb0[5].w;
    float stage12_y = r0.y * cb0[5].w;
    float stage12_z = r0.w * cb0[5].w;
    r1.x = stage12_x;
    r1.y = stage12_y;
    r1.z = stage12_z;
    // max r1.xyz, |r1.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage13_x = max(abs(r1.x), 1e-06f);
    float stage13_y = max(abs(r1.y), 1e-06f);
    float stage13_z = max(abs(r1.z), 1e-06f);
    r1.x = stage13_x;
    r1.y = stage13_y;
    r1.z = stage13_z;
    // log r1.xyz, r1.xyzx
    float stage14_x = log2(r1.x);
    float stage14_y = log2(r1.y);
    float stage14_z = log2(r1.z);
    r1.x = stage14_x;
    r1.y = stage14_y;
    r1.z = stage14_z;
    // mul r1.xyz, r1.xyzx, cb0[6].xxxx
    float stage15_x = r1.x * cb0[6].x;
    float stage15_y = r1.y * cb0[6].x;
    float stage15_z = r1.z * cb0[6].x;
    r1.x = stage15_x;
    r1.y = stage15_y;
    r1.z = stage15_z;
    // exp r1.xyz, r1.xyzx
    float stage16_x = exp2(r1.x);
    float stage16_y = exp2(r1.y);
    float stage16_z = exp2(r1.z);
    r1.x = stage16_x;
    r1.y = stage16_y;
    r1.z = stage16_z;
    // dp3 r1.x, r1.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.x = dot(r1.xyz, float3(0.3f, 0.59f, 0.11f));
    // add r0.xyw, r0.xyxw, r1.xxxx
    float stage17_x = r0.x + r1.x;
    float stage17_y = r0.y + r1.x;
    float stage17_w = r0.w + r1.x;
    r0.x = stage17_x;
    r0.y = stage17_y;
    r0.w = stage17_w;
    // mad r0.xyw, r0.xyxw, v3.xyxz, cb0[1].xyxz
    float stage18_x = r0.x * v3.x + cb0[1].x;
    float stage18_y = r0.y * v3.y + cb0[1].y;
    float stage18_w = r0.w * v3.z + cb0[1].z;
    r0.x = stage18_x;
    r0.y = stage18_y;
    r0.w = stage18_w;
    // mul r0.xyw, r0.xyxw, v5.wwww
    float stage19_x = r0.x * v5.w;
    float stage19_y = r0.y * v5.w;
    float stage19_w = r0.w * v5.w;
    r0.x = stage19_x;
    r0.y = stage19_y;
    r0.w = stage19_w;
    // mul o0.xyz, r0.zzzz, r0.xywx
    float stage20_x = r0.z * r0.x;
    float stage20_y = r0.z * r0.y;
    float stage20_z = r0.z * r0.w;
    o0.x = stage20_x;
    o0.y = stage20_y;
    o0.z = stage20_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_mm_extraalpha_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
