// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_dark_05_tr_Constants0 : register(b0)
{
    float4 cb0[4];
};
cbuffer Shade_Ue3_fx_d_pa_dark_05_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};

struct Shade_Ue3_fx_d_pa_dark_05_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_d_pa_dark_05_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_d_pa_dark_05_tr_OUTPUT Shade_Ue3_fx_d_pa_dark_05_tr(Shade_Ue3_fx_d_pa_dark_05_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // add r0.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.x + -0.5f;
    float stage1_y = v2.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // mul r0.y, v4.x, cb0[3].x
    r0.y = v4.x * cb0[3].x;
    // max r0.y, r0.y, l(0.000010)
    r0.y = max(r0.y, 1e-05f);
    // div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
    r0.y = 1.0f / r0.y;
    // mad r0.x, -r0.x, r0.y, l(1.000000)
    r0.x = -r0.x * r0.y + 1.0f;
    // mad r0.y, -cb0[3].y, v4.y, l(1.000000)
    r0.y = -cb0[3].y * v4.y + 1.0f;
    // max r0.y, r0.y, l(0.000010)
    r0.y = max(r0.y, 1e-05f);
    // div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
    r0.y = 1.0f / r0.y;
    // mul_sat r0.x, r0.y, r0.x
    r0.x = saturate(r0.y * r0.x);
    // mul_sat r0.x, r0.x, cb0[3].z
    r0.x = saturate(r0.x * cb0[3].z);
    // log r0.y, r0.x
    r0.y = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[3].w
    r0.y = r0.y * cb0[3].w;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul_sat r0.y, r0.y, v3.w
    r0.y = saturate(r0.y * v3.w);
    // mul r0.y, r0.y, cb0[0].x
    r0.y = r0.y * cb0[0].x;
    // movc o0.w, r0.x, l(0), r0.y
    o0.w = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // mad r0.xyz, cb0[2].xyzx, v3.xyzx, cb0[1].xyzx
    float stage2_x = cb0[2].x * v3.x + cb0[1].x;
    float stage2_y = cb0[2].y * v3.y + cb0[1].y;
    float stage2_z = cb0[2].z * v3.z + cb0[1].z;
    r0.x = stage2_x;
    r0.y = stage2_y;
    r0.z = stage2_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage3_x = r0.x * v5.w + v5.x;
    float stage3_y = r0.y * v5.w + v5.y;
    float stage3_z = r0.z * v5.w + v5.z;
    o0.x = stage3_x;
    o0.y = stage3_y;
    o0.z = stage3_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage4_x = r0.x * v1.x;
    float stage4_y = r0.x * v1.y;
    float stage4_z = r0.x * v1.z;
    r0.x = stage4_x;
    r0.y = stage4_y;
    r0.z = stage4_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage5_x = r0.w * v0.z;
    float stage5_y = r0.w * v0.x;
    float stage5_z = r0.w * v0.y;
    r1.x = stage5_x;
    r1.y = stage5_y;
    r1.z = stage5_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage6_x = r0.x * r1.x;
    float stage6_y = r0.x * r1.y;
    float stage6_z = r0.x * r1.z;
    r0.x = stage6_x;
    r0.y = stage6_y;
    r0.z = stage6_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage7_x = r0.x / r0.w;
    float stage7_y = r0.y / r0.w;
    r0.x = stage7_x;
    r0.y = stage7_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage8_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage8_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage8_x;
    r1.y = stage8_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage9_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage9_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage9_x;
    r1.y = stage9_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage10_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage10_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage10_x;
    r1.y = stage10_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage11_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage11_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage11_x;
    r0.y = stage11_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage12_x = r0.x * 0.5f + 0.5f;
    float stage12_y = r0.y * 0.5f + 0.5f;
    o2.x = stage12_x;
    o2.y = stage12_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage13_z = 1.0f;
    float stage13_w = asfloat(0u);
    o2.z = stage13_z;
    o2.w = stage13_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage14_x = cb2[3].x;
    float stage14_y = cb2[3].y;
    float stage14_z = cb2[3].z;
    o3.x = stage14_x;
    o3.y = stage14_y;
    o3.z = stage14_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage15_x = asfloat(0u);
    float stage15_y = asfloat(0u);
    float stage15_z = asfloat(0u);
    float stage15_w = asfloat(0u);
    o4.x = stage15_x;
    o4.y = stage15_y;
    o4.z = stage15_z;
    o4.w = stage15_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage16_x = asfloat(0u);
    float stage16_y = asfloat(0u);
    float stage16_z = asfloat(0u);
    float stage16_w = asfloat(0u);
    o5.x = stage16_x;
    o5.y = stage16_y;
    o5.z = stage16_z;
    o5.w = stage16_w;

    Shade_Ue3_fx_d_pa_dark_05_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
