// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_w_pa_area_01_tr_Constants0 : register(b0)
{
    float4 cb0[19];
};
cbuffer Shade_Ue3_fx_w_pa_area_01_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);

struct Shade_Ue3_fx_w_pa_area_01_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v6;
};

struct Shade_Ue3_fx_w_pa_area_01_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_w_pa_area_01_tr_OUTPUT Shade_Ue3_fx_w_pa_area_01_tr(Shade_Ue3_fx_w_pa_area_01_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v6 = stage.v6;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // dp3 r0.x, v6.xyzx, v6.xyzx
    r0.x = dot(v6.xyz, v6.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xy, r0.xxxx, v6.xyxx
    float stage1_x = r0.x * v6.x;
    float stage1_y = r0.x * v6.y;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // mul r0.xy, r0.xyxx, cb0[5].xyxx
    float stage2_x = r0.x * cb0[5].x;
    float stage2_y = r0.y * cb0[5].y;
    r0.x = stage2_x;
    r0.y = stage2_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyxx, t3.xyzw, s3, l(0.000000)
    float4 fetch3 = t3.SampleBias(s3, r0.xy, 0.0f);
    r0.x = fetch3.x;
    r0.y = fetch3.y;
    r0.z = fetch3.z;
    // dp3 r0.w, r0.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.w = dot(r0.xyz, float3(0.3f, 0.59f, 0.11f));
    // add r1.xyz, -r0.xyzx, r0.wwww
    float stage4_x = -r0.x + r0.w;
    float stage4_y = -r0.y + r0.w;
    float stage4_z = -r0.z + r0.w;
    r1.x = stage4_x;
    r1.y = stage4_y;
    r1.z = stage4_z;
    // mad r0.xyz, cb0[15].xxxx, r1.xyzx, r0.xyzx
    float stage5_x = cb0[15].x * r1.x + r0.x;
    float stage5_y = cb0[15].x * r1.y + r0.y;
    float stage5_z = cb0[15].x * r1.z + r0.z;
    r0.x = stage5_x;
    r0.y = stage5_y;
    r0.z = stage5_z;
    // max r0.xyz, |r0.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage6_x = max(abs(r0.x), 1e-06f);
    float stage6_y = max(abs(r0.y), 1e-06f);
    float stage6_z = max(abs(r0.z), 1e-06f);
    r0.x = stage6_x;
    r0.y = stage6_y;
    r0.z = stage6_z;
    // log r0.xyz, r0.xyzx
    float stage7_x = log2(r0.x);
    float stage7_y = log2(r0.y);
    float stage7_z = log2(r0.z);
    r0.x = stage7_x;
    r0.y = stage7_y;
    r0.z = stage7_z;
    // mul r0.xyz, r0.xyzx, cb0[15].yyyy
    float stage8_x = r0.x * cb0[15].y;
    float stage8_y = r0.y * cb0[15].y;
    float stage8_z = r0.z * cb0[15].y;
    r0.x = stage8_x;
    r0.y = stage8_y;
    r0.z = stage8_z;
    // exp r0.xyz, r0.xyzx
    float stage9_x = exp2(r0.x);
    float stage9_y = exp2(r0.y);
    float stage9_z = exp2(r0.z);
    r0.x = stage9_x;
    r0.y = stage9_y;
    r0.z = stage9_z;
    // mul r1.xy, v2.xyxx, cb0[9].yzyy
    float stage10_x = v2.x * cb0[9].y;
    float stage10_y = v2.y * cb0[9].z;
    r1.x = stage10_x;
    r1.y = stage10_y;
    // mad r1.xy, cb0[8].yyyy, cb0[9].xwxx, r1.xyxx
    float stage11_x = cb0[8].y * cb0[9].x + r1.x;
    float stage11_y = cb0[8].y * cb0[9].w + r1.y;
    r1.x = stage11_x;
    r1.y = stage11_y;
    // add r1.xy, r1.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage12_x = r1.x + -0.5f;
    float stage12_y = r1.y + -0.5f;
    r1.x = stage12_x;
    r1.y = stage12_y;
    // mad r0.w, cb0[8].y, cb0[8].z, cb0[8].w
    r0.w = cb0[8].y * cb0[8].z + cb0[8].w;
    // sincos r2.x, r3.x, r0.w
    float stage13_x = r0.w;
    r2.x = sin(stage13_x);
    r3.x = cos(stage13_x);
    // mov r4.x, -r2.x
    r4.x = -r2.x;
    // mov r4.y, r3.x
    r4.y = r3.x;
    // mov r4.z, r2.x
    r4.z = r2.x;
    // dp2 r2.y, r4.zyzz, r1.xyxx
    r2.y = dot(r4.zy, r1.xy);
    // dp2 r2.x, r4.yxyy, r1.xyxx
    r2.x = dot(r4.yx, r1.xy);
    // add r1.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage14_x = r2.x + 0.5f;
    float stage14_y = r2.y + 0.5f;
    r1.x = stage14_x;
    r1.y = stage14_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch15 = t0.SampleBias(s0, r1.xy, 0.0f);
    r1.x = fetch15.x;
    r1.y = fetch15.y;
    r1.z = fetch15.z;
    // mul r2.xy, v2.xyxx, cb0[10].yzyy
    float stage16_x = v2.x * cb0[10].y;
    float stage16_y = v2.y * cb0[10].z;
    r2.x = stage16_x;
    r2.y = stage16_y;
    // mad r2.xy, cb0[8].yyyy, cb0[10].xwxx, r2.xyxx
    float stage17_x = cb0[8].y * cb0[10].x + r2.x;
    float stage17_y = cb0[8].y * cb0[10].w + r2.y;
    r2.x = stage17_x;
    r2.y = stage17_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xyxx, t1.xyzw, s1, l(0.000000)
    float4 fetch18 = t1.SampleBias(s1, r2.xy, 0.0f);
    r2.x = fetch18.x;
    r2.y = fetch18.y;
    r2.z = fetch18.z;
    // mul r3.xyz, r1.xyzx, r2.xyzx
    float stage19_x = r1.x * r2.x;
    float stage19_y = r1.y * r2.y;
    float stage19_z = r1.z * r2.z;
    r3.x = stage19_x;
    r3.y = stage19_y;
    r3.z = stage19_z;
    // dp3 r0.w, r3.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.w = dot(r3.xyz, float3(0.3f, 0.59f, 0.11f));
    // mad r1.yzw, -r1.xxyz, r2.xxyz, r0.wwww
    float stage20_y = -r1.x * r2.x + r0.w;
    float stage20_z = -r1.y * r2.y + r0.w;
    float stage20_w = -r1.z * r2.z + r0.w;
    r1.y = stage20_y;
    r1.z = stage20_z;
    r1.w = stage20_w;
    // mad r1.yzw, cb0[15].wwww, r1.yyzw, r3.xxyz
    float stage21_y = cb0[15].w * r1.y + r3.x;
    float stage21_z = cb0[15].w * r1.z + r3.y;
    float stage21_w = cb0[15].w * r1.w + r3.z;
    r1.y = stage21_y;
    r1.z = stage21_z;
    r1.w = stage21_w;
    // max r1.yzw, |r1.yyzw|, l(0.000000, 0.000001, 0.000001, 0.000001)
    float stage22_y = max(abs(r1.y), 1e-06f);
    float stage22_z = max(abs(r1.z), 1e-06f);
    float stage22_w = max(abs(r1.w), 1e-06f);
    r1.y = stage22_y;
    r1.z = stage22_z;
    r1.w = stage22_w;
    // log r1.yzw, r1.yyzw
    float stage23_y = log2(r1.y);
    float stage23_z = log2(r1.z);
    float stage23_w = log2(r1.w);
    r1.y = stage23_y;
    r1.z = stage23_z;
    r1.w = stage23_w;
    // mul r1.yzw, r1.yyzw, cb0[16].xxxx
    float stage24_y = r1.y * cb0[16].x;
    float stage24_z = r1.z * cb0[16].x;
    float stage24_w = r1.w * cb0[16].x;
    r1.y = stage24_y;
    r1.z = stage24_z;
    r1.w = stage24_w;
    // exp r1.yzw, r1.yyzw
    float stage25_y = exp2(r1.y);
    float stage25_z = exp2(r1.z);
    float stage25_w = exp2(r1.w);
    r1.y = stage25_y;
    r1.z = stage25_z;
    r1.w = stage25_w;
    // mul_sat r1.yzw, r1.yyzw, cb0[16].yyyy
    float stage26_y = saturate(r1.y * cb0[16].y);
    float stage26_z = saturate(r1.z * cb0[16].y);
    float stage26_w = saturate(r1.w * cb0[16].y);
    r1.y = stage26_y;
    r1.z = stage26_z;
    r1.w = stage26_w;
    // mul r2.yzw, cb0[6].xxyz, cb0[6].wwww
    float stage27_y = cb0[6].x * cb0[6].w;
    float stage27_z = cb0[6].y * cb0[6].w;
    float stage27_w = cb0[6].z * cb0[6].w;
    r2.y = stage27_y;
    r2.z = stage27_z;
    r2.w = stage27_w;
    // mad r3.xyz, cb0[7].wwww, cb0[7].xyzx, -r2.yzwy
    float stage28_x = cb0[7].w * cb0[7].x + -r2.y;
    float stage28_y = cb0[7].w * cb0[7].y + -r2.z;
    float stage28_z = cb0[7].w * cb0[7].z + -r2.w;
    r3.x = stage28_x;
    r3.y = stage28_y;
    r3.z = stage28_z;
    // mad r1.yzw, r1.yyzw, r3.xxyz, r2.yyzw
    float stage29_y = r1.y * r3.x + r2.y;
    float stage29_z = r1.z * r3.y + r2.z;
    float stage29_w = r1.w * r3.z + r2.w;
    r1.y = stage29_y;
    r1.z = stage29_z;
    r1.w = stage29_w;
    // mad r0.xyz, cb0[15].zzzz, r0.xyzx, r1.yzwy
    float stage30_x = cb0[15].z * r0.x + r1.y;
    float stage30_y = cb0[15].z * r0.y + r1.z;
    float stage30_z = cb0[15].z * r0.z + r1.w;
    r0.x = stage30_x;
    r0.y = stage30_y;
    r0.z = stage30_z;
    // mul r1.yz, v2.xxyx, cb0[11].yyzy
    float stage31_y = v2.x * cb0[11].y;
    float stage31_z = v2.y * cb0[11].z;
    r1.y = stage31_y;
    r1.z = stage31_z;
    // mad r1.yz, cb0[8].yyyy, cb0[11].xxwx, r1.yyzy
    float stage32_y = cb0[8].y * cb0[11].x + r1.y;
    float stage32_z = cb0[8].y * cb0[11].w + r1.z;
    r1.y = stage32_y;
    r1.z = stage32_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.yzw, r1.yzyy, t2.wxyz, s2, l(0.000000)
    float4 fetch33 = t2.SampleBias(s2, r1.yz, 0.0f);
    r1.y = fetch33.x;
    r1.z = fetch33.y;
    r1.w = fetch33.z;
    // mad r2.xy, r1.xxxx, r2.xxxx, r1.yyyy
    float stage34_x = r1.x * r2.x + r1.y;
    float stage34_y = r1.x * r2.x + r1.y;
    r2.x = stage34_x;
    r2.y = stage34_y;
    // add r2.zw, v2.xxxy, l(0.000000, 0.000000, -0.500000, -0.500000)
    float stage35_z = v2.x + -0.5f;
    float stage35_w = v2.y + -0.5f;
    r2.z = stage35_z;
    r2.w = stage35_w;
    // dp2 r3.x, cb0[3].xyxx, r2.zwzz
    r3.x = dot(cb0[3].xy, r2.zw);
    // dp2 r3.y, cb0[4].xyxx, r2.zwzz
    r3.y = dot(cb0[4].xy, r2.zw);
    // dp2 r0.w, r2.zwzz, r2.zwzz
    r0.w = dot(r2.zw, r2.zw);
    // sqrt r0.w, r0.w
    r0.w = sqrt(r0.w);
    // mad r0.w, -r0.w, cb0[17].x, l(1.000000)
    r0.w = -r0.w * cb0[17].x + 1.0f;
    // mul_sat r0.w, r0.w, cb0[18].x
    r0.w = saturate(r0.w * cb0[18].x);
    // dp2 r1.x, r3.xyxx, r3.xyxx
    r1.x = dot(r3.xy, r3.xy);
    // sqrt r1.x, r1.x
    r1.x = sqrt(r1.x);
    // mad_sat r1.x, -r1.x, cb0[13].y, l(1.000000)
    r1.x = saturate(-r1.x * cb0[13].y + 1.0f);
    // add r1.x, -r1.x, l(1.100000)
    r1.x = -r1.x + 1.1f;
    // mad r2.xy, r2.xyxx, cb0[12].xxxx, r1.xxxx
    float stage36_x = r2.x * cb0[12].x + r1.x;
    float stage36_y = r2.y * cb0[12].x + r1.x;
    r2.x = stage36_x;
    r2.y = stage36_y;
    // mov_sat r1.x, v4.x
    r1.x = saturate(v4.x);
    // add r1.x, -r1.x, l(1.000000)
    r1.x = -r1.x + 1.0f;
    // add r2.xy, -r1.xxxx, r2.xyxx
    float stage37_x = -r1.x + r2.x;
    float stage37_y = -r1.x + r2.y;
    r2.x = stage37_x;
    r2.y = stage37_y;
    // mul r1.x, v4.z, cb0[13].z
    r1.x = v4.z * cb0[13].z;
    // mul_sat r2.xy, r1.xxxx, r2.xyxx
    float stage38_x = saturate(r1.x * r2.x);
    float stage38_y = saturate(r1.x * r2.y);
    r2.x = stage38_x;
    r2.y = stage38_y;
    // log r2.zw, r2.xxxy
    float stage39_z = log2(r2.x);
    float stage39_w = log2(r2.y);
    r2.z = stage39_z;
    r2.w = stage39_w;
    // lt r2.xy, r2.xyxx, l(0.000001, 0.000001, 0.000000, 0.000000)
    float stage40_x = asfloat((r2.x < 1e-06f) ? 0xffffffffu : 0u);
    float stage40_y = asfloat((r2.y < 1e-06f) ? 0xffffffffu : 0u);
    r2.x = stage40_x;
    r2.y = stage40_y;
    // mul r2.zw, r2.zzzw, cb0[13].wwww
    float stage41_z = r2.z * cb0[13].w;
    float stage41_w = r2.w * cb0[13].w;
    r2.z = stage41_z;
    r2.w = stage41_w;
    // exp r2.zw, r2.zzzw
    float stage42_z = exp2(r2.z);
    float stage42_w = exp2(r2.w);
    r2.z = stage42_z;
    r2.w = stage42_w;
    // movc r1.x, r2.y, l(0), r2.w
    r1.x = asuint(r2.y) != 0u ? asfloat(0u) : r2.w;
    // mul r0.w, r0.w, r2.z
    r0.w = r0.w * r2.z;
    // min r0.w, r0.w, l(1.000000)
    r0.w = min(r0.w, 1.0f);
    // mul_sat r0.w, r0.w, v3.w
    r0.w = saturate(r0.w * v3.w);
    // mul r0.w, r0.w, cb0[0].x
    r0.w = r0.w * cb0[0].x;
    // movc o0.w, r2.x, l(0), r0.w
    o0.w = asuint(r2.x) != 0u ? asfloat(0u) : r0.w;
    // add r0.w, -r1.x, l(1.000000)
    r0.w = -r1.x + 1.0f;
    // mad r1.yzw, r1.xxxx, r0.wwww, r1.yyzw
    float stage43_y = r1.x * r0.w + r1.y;
    float stage43_z = r1.x * r0.w + r1.z;
    float stage43_w = r1.x * r0.w + r1.w;
    r1.y = stage43_y;
    r1.z = stage43_z;
    r1.w = stage43_w;
    // mul r0.w, r0.w, r1.x
    r0.w = r0.w * r1.x;
    // mul r1.xyz, r1.yzwy, r0.wwww
    float stage44_x = r1.y * r0.w;
    float stage44_y = r1.z * r0.w;
    float stage44_z = r1.w * r0.w;
    r1.x = stage44_x;
    r1.y = stage44_y;
    r1.z = stage44_z;
    // mul r1.xyz, r1.xyzx, cb0[14].xxxx
    float stage45_x = r1.x * cb0[14].x;
    float stage45_y = r1.y * cb0[14].x;
    float stage45_z = r1.z * cb0[14].x;
    r1.x = stage45_x;
    r1.y = stage45_y;
    r1.z = stage45_z;
    // mul_sat r1.xyz, r1.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
    float stage46_x = saturate(r1.x * 4.0f);
    float stage46_y = saturate(r1.y * 4.0f);
    float stage46_z = saturate(r1.z * 4.0f);
    r1.x = stage46_x;
    r1.y = stage46_y;
    r1.z = stage46_z;
    // max r1.xyz, r1.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage47_x = max(r1.x, 1e-06f);
    float stage47_y = max(r1.y, 1e-06f);
    float stage47_z = max(r1.z, 1e-06f);
    r1.x = stage47_x;
    r1.y = stage47_y;
    r1.z = stage47_z;
    // log r1.xyz, r1.xyzx
    float stage48_x = log2(r1.x);
    float stage48_y = log2(r1.y);
    float stage48_z = log2(r1.z);
    r1.x = stage48_x;
    r1.y = stage48_y;
    r1.z = stage48_z;
    // mul r1.xyz, r1.xyzx, cb0[14].yyyy
    float stage49_x = r1.x * cb0[14].y;
    float stage49_y = r1.y * cb0[14].y;
    float stage49_z = r1.z * cb0[14].y;
    r1.x = stage49_x;
    r1.y = stage49_y;
    r1.z = stage49_z;
    // exp r1.xyz, r1.xyzx
    float stage50_x = exp2(r1.x);
    float stage50_y = exp2(r1.y);
    float stage50_z = exp2(r1.z);
    r1.x = stage50_x;
    r1.y = stage50_y;
    r1.z = stage50_z;
    // mul r2.xyz, cb0[2].xyzx, cb0[2].wwww
    float stage51_x = cb0[2].x * cb0[2].w;
    float stage51_y = cb0[2].y * cb0[2].w;
    float stage51_z = cb0[2].z * cb0[2].w;
    r2.x = stage51_x;
    r2.y = stage51_y;
    r2.z = stage51_z;
    // mul r2.xyz, r2.xyzx, v4.yyyy
    float stage52_x = r2.x * v4.y;
    float stage52_y = r2.y * v4.y;
    float stage52_z = r2.z * v4.y;
    r2.x = stage52_x;
    r2.y = stage52_y;
    r2.z = stage52_z;
    // mad r0.xyz, r2.xyzx, r1.xyzx, r0.xyzx
    float stage53_x = r2.x * r1.x + r0.x;
    float stage53_y = r2.y * r1.y + r0.y;
    float stage53_z = r2.z * r1.z + r0.z;
    r0.x = stage53_x;
    r0.y = stage53_y;
    r0.z = stage53_z;
    // mad r0.xyz, r0.xyzx, v3.xyzx, cb0[1].xyzx
    float stage54_x = r0.x * v3.x + cb0[1].x;
    float stage54_y = r0.y * v3.y + cb0[1].y;
    float stage54_z = r0.z * v3.z + cb0[1].z;
    r0.x = stage54_x;
    r0.y = stage54_y;
    r0.z = stage54_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage55_x = r0.x * v5.w + v5.x;
    float stage55_y = r0.y * v5.w + v5.y;
    float stage55_z = r0.z * v5.w + v5.z;
    o0.x = stage55_x;
    o0.y = stage55_y;
    o0.z = stage55_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage56_x = r0.x * v1.x;
    float stage56_y = r0.x * v1.y;
    float stage56_z = r0.x * v1.z;
    r0.x = stage56_x;
    r0.y = stage56_y;
    r0.z = stage56_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage57_x = r0.w * v0.z;
    float stage57_y = r0.w * v0.x;
    float stage57_z = r0.w * v0.y;
    r1.x = stage57_x;
    r1.y = stage57_y;
    r1.z = stage57_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage58_x = r0.x * r1.x;
    float stage58_y = r0.x * r1.y;
    float stage58_z = r0.x * r1.z;
    r0.x = stage58_x;
    r0.y = stage58_y;
    r0.z = stage58_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage59_x = r0.x / r0.w;
    float stage59_y = r0.y / r0.w;
    r0.x = stage59_x;
    r0.y = stage59_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage60_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage60_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage60_x;
    r1.y = stage60_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage61_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage61_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage61_x;
    r1.y = stage61_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage62_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage62_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage62_x;
    r1.y = stage62_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage63_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage63_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage63_x;
    r0.y = stage63_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage64_x = r0.x * 0.5f + 0.5f;
    float stage64_y = r0.y * 0.5f + 0.5f;
    o2.x = stage64_x;
    o2.y = stage64_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage65_z = 1.0f;
    float stage65_w = asfloat(0u);
    o2.z = stage65_z;
    o2.w = stage65_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage66_x = cb2[3].x;
    float stage66_y = cb2[3].y;
    float stage66_z = cb2[3].z;
    o3.x = stage66_x;
    o3.y = stage66_y;
    o3.z = stage66_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage67_x = asfloat(0u);
    float stage67_y = asfloat(0u);
    float stage67_z = asfloat(0u);
    float stage67_w = asfloat(0u);
    o4.x = stage67_x;
    o4.y = stage67_y;
    o4.z = stage67_z;
    o4.w = stage67_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage68_x = asfloat(0u);
    float stage68_y = asfloat(0u);
    float stage68_z = asfloat(0u);
    float stage68_w = asfloat(0u);
    o5.x = stage68_x;
    o5.y = stage68_y;
    o5.z = stage68_z;
    o5.w = stage68_w;

    Shade_Ue3_fx_w_pa_area_01_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
