// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_j_pa_rotturbulance_01_ad_Constants0 : register(b0)
{
    float4 cb0[10];
};
cbuffer Shade_Ue3_fx_j_pa_rotturbulance_01_ad_Constants2 : register(b2)
{
    float4 cb2[2];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
SamplerState s5 : register(s5);
SamplerState s6 : register(s6);
SamplerState s7 : register(s7);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);
Texture2D t5 : register(t5);
Texture2D t6 : register(t6);
Texture2D t7 : register(t7);

struct Shade_Ue3_fx_j_pa_rotturbulance_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_j_pa_rotturbulance_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_j_pa_rotturbulance_01_ad_OUTPUT Shade_Ue3_fx_j_pa_rotturbulance_01_ad(Shade_Ue3_fx_j_pa_rotturbulance_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 r5 = (float4)0;
    float4 o0 = (float4)0;

    // mul r0.x, v2.x, cb0[7].w
    r0.x = v2.x * cb0[7].w;
    // mul r0.y, v2.y, cb0[8].x
    r0.y = v2.y * cb0[8].x;
    // add r0.xy, r0.xyxx, cb0[8].yzyy
    float stage1_x = r0.x + cb0[8].y;
    float stage1_y = r0.y + cb0[8].z;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // add r0.xy, r0.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage2_x = r0.x + -0.5f;
    float stage2_y = r0.y + -0.5f;
    r0.x = stage2_x;
    r0.y = stage2_y;
    // mul r0.zw, v4.xxxx, l(0.000000, 0.000000, 0.250000, -0.100000)
    float stage3_z = v4.x * 0.25f;
    float stage3_w = v4.x * -0.1f;
    r0.z = stage3_z;
    r0.w = stage3_w;
    // sincos r1.x, r2.x, r0.w
    float stage4_x = r0.w;
    r1.x = sin(stage4_x);
    r2.x = cos(stage4_x);
    // sincos r3.x, r4.x, r0.z
    float stage5_x = r0.z;
    r3.x = sin(stage5_x);
    r4.x = cos(stage5_x);
    // mov r5.x, -r1.x
    r5.x = -r1.x;
    // mov r5.y, r2.x
    r5.y = r2.x;
    // mov r5.z, r1.x
    r5.z = r1.x;
    // dp2 r1.y, r5.zyzz, r0.xyxx
    r1.y = dot(r5.zy, r0.xy);
    // dp2 r1.x, r5.yxyy, r0.xyxx
    r1.x = dot(r5.yx, r0.xy);
    // add r0.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage6_x = r1.x + 0.5f;
    float stage6_y = r1.y + 0.5f;
    r0.x = stage6_x;
    r0.y = stage6_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t6.xyzw, s5, l(0.000000)
    float4 fetch7 = t6.SampleBias(s5, r0.xy, 0.0f);
    r0.x = fetch7.x;
    // mul r0.x, r0.x, cb0[8].w
    r0.x = r0.x * cb0[8].w;
    // mul r0.y, v2.y, cb0[6].w
    r0.y = v2.y * cb0[6].w;
    // mad r1.y, cb0[7].y, v4.y, r0.y
    r1.y = cb0[7].y * v4.y + r0.y;
    // mad r1.x, v2.x, cb0[6].z, cb0[7].x
    r1.x = v2.x * cb0[6].z + cb0[7].x;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r1.xyxx, t5.yxzw, s4, l(0.000000)
    float4 fetch8 = t5.SampleBias(s4, r1.xy, 0.0f);
    r0.y = fetch8.x;
    // mad r0.x, r0.y, cb0[7].z, r0.x
    r0.x = r0.y * cb0[7].z + r0.x;
    // add r0.xy, r0.xxxx, v2.xyxx
    float stage9_x = r0.x + v2.x;
    float stage9_y = r0.x + v2.y;
    r0.x = stage9_x;
    r0.y = stage9_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t7.xyzw, s6, l(0.000000)
    float4 fetch10 = t7.SampleBias(s6, r0.xy, 0.0f);
    r0.x = fetch10.x;
    // mul r0.x, r0.x, cb0[9].x
    r0.x = r0.x * cb0[9].x;
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // lt r0.x, |r0.x|, l(0.000001)
    r0.x = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[9].y
    r0.y = r0.y * cb0[9].y;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // mov r1.x, -r3.x
    r1.x = -r3.x;
    // mad r0.yz, v2.xxyx, cb0[5].xxyx, cb0[5].zzwz
    float stage11_y = v2.x * cb0[5].x + cb0[5].z;
    float stage11_z = v2.y * cb0[5].y + cb0[5].w;
    r0.y = stage11_y;
    r0.z = stage11_z;
    // add r0.yz, r0.yyzy, l(0.000000, -0.500000, -0.500000, 0.000000)
    float stage12_y = r0.y + -0.5f;
    float stage12_z = r0.z + -0.5f;
    r0.y = stage12_y;
    r0.z = stage12_z;
    // mov r1.y, r4.x
    r1.y = r4.x;
    // mov r1.z, r3.x
    r1.z = r3.x;
    // dp2 r2.y, r1.zyzz, r0.yzyy
    r2.y = dot(r1.zy, r0.yz);
    // dp2 r2.x, r1.yxyy, r0.yzyy
    r2.x = dot(r1.yx, r0.yz);
    // add r0.yz, r2.xxyx, l(0.000000, 0.500000, 0.500000, 0.000000)
    float stage13_y = r2.x + 0.5f;
    float stage13_z = r2.y + 0.5f;
    r0.y = stage13_y;
    r0.z = stage13_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t4.yxzw, s3, l(0.000000)
    float4 fetch14 = t4.SampleBias(s3, r0.yz, 0.0f);
    r0.y = fetch14.x;
    // mul r0.y, r0.y, cb0[6].x
    r0.y = r0.y * cb0[6].x;
    // lt r0.z, |r0.y|, l(0.000001)
    r0.z = asfloat((abs(r0.y) < 1e-06f) ? 0xffffffffu : 0u);
    // log r0.y, |r0.y|
    r0.y = log2(abs(r0.y));
    // mul r0.y, r0.y, cb0[6].y
    r0.y = r0.y * cb0[6].y;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.y, r0.z, l(0), r0.y
    r0.y = asuint(r0.z) != 0u ? asfloat(0u) : r0.y;
    // mul r0.z, r0.x, r0.y
    r0.z = r0.x * r0.y;
    // mul r1.xy, v2.xyxx, cb0[2].zwzz
    float stage15_x = v2.x * cb0[2].z;
    float stage15_y = v2.y * cb0[2].w;
    r1.x = stage15_x;
    r1.y = stage15_y;
    // mad r2.x, cb0[2].y, cb0[2].x, r1.x
    r2.x = cb0[2].y * cb0[2].x + r1.x;
    // mad r2.y, cb0[2].y, cb0[3].x, r1.y
    r2.y = cb0[2].y * cb0[3].x + r1.y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.w, r2.xyxx, t2.yzwx, s1, l(0.000000)
    float4 fetch16 = t2.SampleBias(s1, r2.xy, 0.0f);
    r0.w = fetch16.x;
    // mad r1.xy, r0.wwww, cb0[3].yyyy, v2.xyxx
    float stage17_x = r0.w * cb0[3].y + v2.x;
    float stage17_y = r0.w * cb0[3].y + v2.y;
    r1.x = stage17_x;
    r1.y = stage17_y;
    // mad r1.xy, r1.xyxx, cb0[3].zwzz, cb0[4].xyxx
    float stage18_x = r1.x * cb0[3].z + cb0[4].x;
    float stage18_y = r1.y * cb0[3].w + cb0[4].y;
    r1.x = stage18_x;
    r1.y = stage18_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t3.yzwx, s2, l(0.000000)
    float4 fetch19 = t3.SampleBias(s2, r1.xy, 0.0f);
    r0.w = fetch19.x;
    // mul r0.w, r0.w, r0.w
    r0.w = r0.w * r0.w;
    // log r1.x, r0.w
    r1.x = log2(r0.w);
    // lt r0.w, r0.w, l(0.000001)
    r0.w = asfloat((r0.w < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.x, r1.x, cb0[4].z
    r1.x = r1.x * cb0[4].z;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // mul r1.y, v4.z, cb0[4].w
    r1.y = v4.z * cb0[4].w;
    // mul r1.x, r1.y, r1.x
    r1.x = r1.y * r1.x;
    // movc r0.w, r0.w, l(0), r1.x
    r0.w = asuint(r0.w) != 0u ? asfloat(0u) : r1.x;
    // mul r0.w, r0.w, r0.w
    r0.w = r0.w * r0.w;
    // mul r1.x, r0.z, r0.w
    r1.x = r0.z * r0.w;
    // dp3 r1.y, r1.xxxx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.y = dot(r1.xxx, float3(0.3f, 0.59f, 0.11f));
    // mad r0.z, -r0.w, r0.z, r1.y
    r0.z = -r0.w * r0.z + r1.y;
    // mad r0.z, cb0[9].z, r0.z, r1.x
    r0.z = cb0[9].z * r0.z + r1.x;
    // mad r0.x, r0.y, r0.x, r0.z
    r0.x = r0.y * r0.x + r0.z;
    // mad r0.xyz, v3.xyzx, r0.xxxx, cb0[1].xyzx
    float stage20_x = v3.x * r0.x + cb0[1].x;
    float stage20_y = v3.y * r0.x + cb0[1].y;
    float stage20_z = v3.z * r0.x + cb0[1].z;
    r0.x = stage20_x;
    r0.y = stage20_y;
    r0.z = stage20_z;
    // mul r0.xyz, r0.xyzx, v5.wwww
    float stage21_x = r0.x * v5.w;
    float stage21_y = r0.y * v5.w;
    float stage21_z = r0.z * v5.w;
    r0.x = stage21_x;
    r0.y = stage21_y;
    r0.z = stage21_z;
    // div r1.xy, v7.xyxx, v7.wwww
    float stage22_x = v7.x / v7.w;
    float stage22_y = v7.y / v7.w;
    r1.x = stage22_x;
    r1.y = stage22_y;
    // mad r1.xy, r1.xyxx, cb2[0].xyxx, cb2[0].wzww
    float stage23_x = r1.x * cb2[0].x + cb2[0].w;
    float stage23_y = r1.y * cb2[0].y + cb2[0].z;
    r1.x = stage23_x;
    r1.y = stage23_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t1.yzwx, s0, l(0.000000)
    float4 fetch24 = t1.SampleLevel(s0, r1.xy, 0.0f);
    r0.w = fetch24.x;
    // min r0.w, r0.w, l(0.999000)
    r0.w = min(r0.w, 0.999f);
    // mad r1.x, r0.w, cb2[1].z, -cb2[1].w
    r1.x = r0.w * cb2[1].z + -cb2[1].w;
    // mad r0.w, r0.w, cb2[1].x, cb2[1].y
    r0.w = r0.w * cb2[1].x + cb2[1].y;
    // div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
    r1.x = 1.0f / r1.x;
    // add r0.w, r0.w, r1.x
    r0.w = r0.w + r1.x;
    // add r0.w, r0.w, -v7.w
    r0.w = r0.w + -v7.w;
    // add r1.x, -cb0[9].w, l(1.000000)
    r1.x = -cb0[9].w + 1.0f;
    // mul r1.x, r1.x, l(100.000000)
    r1.x = r1.x * 100.0f;
    // max r1.x, r1.x, l(0.001000)
    r1.x = max(r1.x, 0.001f);
    // div_sat r0.w, r0.w, r1.x
    r0.w = saturate(r0.w / r1.x);
    // sample_b_indexable(texture2d)(float,float,float,float) r1.x, v2.xyxx, t0.xyzw, s7, l(0.000000)
    float4 fetch25 = t0.SampleBias(s7, v2.xy, 0.0f);
    r1.x = fetch25.x;
    // sqrt r1.x, r1.x
    r1.x = sqrt(r1.x);
    // mul r1.x, r1.x, v3.w
    r1.x = r1.x * v3.w;
    // mul r0.w, r0.w, r1.x
    r0.w = r0.w * r1.x;
    // mul r0.w, r0.w, cb0[0].x
    r0.w = r0.w * cb0[0].x;
    // mul o0.xyz, r0.wwww, r0.xyzx
    float stage26_x = r0.w * r0.x;
    float stage26_y = r0.w * r0.y;
    float stage26_z = r0.w * r0.z;
    o0.x = stage26_x;
    o0.y = stage26_y;
    o0.z = stage26_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_j_pa_rotturbulance_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
