// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_m_pa_worldoffset_01_tr_Constants0 : register(b0)
{
    float4 cb0[16];
};
cbuffer Shade_Ue3_fx_m_pa_worldoffset_01_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);

struct Shade_Ue3_fx_m_pa_worldoffset_01_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_m_pa_worldoffset_01_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_m_pa_worldoffset_01_tr_OUTPUT Shade_Ue3_fx_m_pa_worldoffset_01_tr(Shade_Ue3_fx_m_pa_worldoffset_01_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // add r0.xyzw, v2.xyxy, l(-0.020000, -0.030000, -0.500000, -0.500000)
    float stage1_x = v2.x + -0.02f;
    float stage1_y = v2.y + -0.03f;
    float stage1_z = v2.x + -0.5f;
    float stage1_w = v2.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    r0.z = stage1_z;
    r0.w = stage1_w;
    // max r1.x, |r0.w|, |r0.z|
    r1.x = max(abs(r0.w), abs(r0.z));
    // div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
    r1.x = 1.0f / r1.x;
    // min r1.y, |r0.w|, |r0.z|
    r1.y = min(abs(r0.w), abs(r0.z));
    // mul r1.x, r1.x, r1.y
    r1.x = r1.x * r1.y;
    // mul r1.y, r1.x, r1.x
    r1.y = r1.x * r1.x;
    // mad r1.z, r1.y, l(0.020835), l(-0.085133)
    r1.z = r1.y * 0.020835f + -0.085133f;
    // mad r1.z, r1.y, r1.z, l(0.180141)
    r1.z = r1.y * r1.z + 0.180141f;
    // mad r1.z, r1.y, r1.z, l(-0.330299)
    r1.z = r1.y * r1.z + -0.330299f;
    // mad r1.y, r1.y, r1.z, l(0.999866)
    r1.y = r1.y * r1.z + 0.999866f;
    // mul r1.z, r1.y, r1.x
    r1.z = r1.y * r1.x;
    // mad r1.z, r1.z, l(-2.000000), l(1.570796)
    r1.z = r1.z * -2.0f + 1.570796f;
    // lt r1.w, |r0.w|, |r0.z|
    r1.w = asfloat((abs(r0.w) < abs(r0.z)) ? 0xffffffffu : 0u);
    // and r1.z, r1.w, r1.z
    r1.z = asfloat(asuint(r1.w) & asuint(r1.z));
    // mad r1.x, r1.x, r1.y, r1.z
    r1.x = r1.x * r1.y + r1.z;
    // lt r1.y, r0.w, -r0.w
    r1.y = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // and r1.y, r1.y, l(0xc0490fdb)
    r1.y = asfloat(asuint(r1.y) & asuint(-3.1415927410125732f));
    // add r1.x, r1.y, r1.x
    r1.x = r1.y + r1.x;
    // min r1.y, r0.w, r0.z
    r1.y = min(r0.w, r0.z);
    // lt r1.y, r1.y, -r1.y
    r1.y = asfloat((r1.y < -r1.y) ? 0xffffffffu : 0u);
    // max r1.z, r0.w, r0.z
    r1.z = max(r0.w, r0.z);
    // ge r1.z, r1.z, -r1.z
    r1.z = asfloat((r1.z >= -r1.z) ? 0xffffffffu : 0u);
    // and r1.y, r1.z, r1.y
    r1.y = asfloat(asuint(r1.z) & asuint(r1.y));
    // movc r1.x, r1.y, -r1.x, r1.x
    r1.x = asuint(r1.y) != 0u ? -r1.x : r1.x;
    // mad r1.x, r1.x, l(0.159155), l(0.500000)
    r1.x = r1.x * 0.159155f + 0.5f;
    // mul r1.x, r1.x, cb0[10].y
    r1.x = r1.x * cb0[10].y;
    // dp2 r0.z, r0.zwzz, r0.zwzz
    r0.z = dot(r0.zw, r0.zw);
    // sqrt r0.z, r0.z
    r0.z = sqrt(r0.z);
    // mul r0.z, r0.z, l(1.500000)
    r0.z = r0.z * 1.5f;
    // min r0.z, r0.z, l(1.000000)
    r0.z = min(r0.z, 1.0f);
    // mul r1.y, r0.z, cb0[10].z
    r1.y = r0.z * cb0[10].z;
    // add r0.zw, r1.xxxy, cb0[5].xxxy
    float stage2_z = r1.x + cb0[5].x;
    float stage2_w = r1.y + cb0[5].y;
    r0.z = stage2_z;
    r0.w = stage2_w;
    // dp3 r1.x, v1.xyzx, v1.xyzx
    r1.x = dot(v1.xyz, v1.xyz);
    // rsq r1.x, r1.x
    r1.x = rsqrt(r1.x);
    // mul r1.xyz, r1.xxxx, v1.zxyz
    float stage3_x = r1.x * v1.z;
    float stage3_y = r1.x * v1.x;
    float stage3_z = r1.x * v1.y;
    r1.x = stage3_x;
    r1.y = stage3_y;
    r1.z = stage3_z;
    // dp3 r1.w, v0.xyzx, v0.xyzx
    r1.w = dot(v0.xyz, v0.xyz);
    // rsq r1.w, r1.w
    r1.w = rsqrt(r1.w);
    // mul r2.xyz, r1.wwww, v0.yzxy
    float stage4_x = r1.w * v0.y;
    float stage4_y = r1.w * v0.z;
    float stage4_z = r1.w * v0.x;
    r2.x = stage4_x;
    r2.y = stage4_y;
    r2.z = stage4_z;
    // mul r3.xyz, r1.xyzx, r2.xyzx
    float stage5_x = r1.x * r2.x;
    float stage5_y = r1.y * r2.y;
    float stage5_z = r1.z * r2.z;
    r3.x = stage5_x;
    r3.y = stage5_y;
    r3.z = stage5_z;
    // mad r3.xyz, r1.zxyz, r2.yzxy, -r3.xyzx
    float stage6_x = r1.z * r2.y + -r3.x;
    float stage6_y = r1.x * r2.z + -r3.y;
    float stage6_z = r1.y * r2.x + -r3.z;
    r3.x = stage6_x;
    r3.y = stage6_y;
    r3.z = stage6_z;
    // mul r3.xyz, r3.xzyx, v1.wwww
    float stage7_x = r3.x * v1.w;
    float stage7_y = r3.z * v1.w;
    float stage7_z = r3.y * v1.w;
    r3.x = stage7_x;
    r3.y = stage7_y;
    r3.z = stage7_z;
    // add r4.xyz, v7.xyzx, cb0[0].xyzx
    float stage8_x = v7.x + cb0[0].x;
    float stage8_y = v7.y + cb0[0].y;
    float stage8_z = v7.z + cb0[0].z;
    r4.x = stage8_x;
    r4.y = stage8_y;
    r4.z = stage8_z;
    // mul r4.yw, r3.xxxz, r4.yyyy
    float stage9_y = r3.x * r4.y;
    float stage9_w = r3.z * r4.y;
    r4.y = stage9_y;
    r4.w = stage9_w;
    // mad r2.xz, r4.xxxx, r2.zzxz, r4.yywy
    float stage10_x = r4.x * r2.z + r4.y;
    float stage10_z = r4.x * r2.x + r4.w;
    r2.x = stage10_x;
    r2.z = stage10_z;
    // mov r3.x, r2.y
    r3.x = r2.y;
    // mad r1.yz, r4.zzzz, r1.yyzy, r2.xxzx
    float stage11_y = r4.z * r1.y + r2.x;
    float stage11_z = r4.z * r1.z + r2.z;
    r1.y = stage11_y;
    r1.z = stage11_z;
    // mov r3.z, r1.x
    r3.z = r1.x;
    // mad r1.xw, cb0[6].xxxx, r1.yyyz, cb0[3].xxxy
    float stage12_x = cb0[6].x * r1.y + cb0[3].x;
    float stage12_w = cb0[6].x * r1.z + cb0[3].y;
    r1.x = stage12_x;
    r1.w = stage12_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xw, r1.xwxx, t0.xzwy, s0, l(0.000000)
    float4 fetch13 = t0.SampleBias(s0, r1.xw, 0.0f);
    r1.x = fetch13.x;
    r1.w = fetch13.y;
    // mad r2.xy, cb0[7].zzzz, r1.yzyy, cb0[4].xyxx
    float stage14_x = cb0[7].z * r1.y + cb0[4].x;
    float stage14_y = cb0[7].z * r1.z + cb0[4].y;
    r2.x = stage14_x;
    r2.y = stage14_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xy, r2.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch15 = t0.SampleBias(s0, r2.xy, 0.0f);
    r2.x = fetch15.x;
    r2.y = fetch15.y;
    // mul r1.xw, r1.xxxw, r2.xxxy
    float stage16_x = r1.x * r2.x;
    float stage16_w = r1.w * r2.y;
    r1.x = stage16_x;
    r1.w = stage16_w;
    // mad r0.zw, cb0[9].xxxx, r1.xxxw, r0.zzzw
    float stage17_z = cb0[9].x * r1.x + r0.z;
    float stage17_w = cb0[9].x * r1.w + r0.w;
    r0.z = stage17_z;
    r0.w = stage17_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t1.yzxw, s1, l(0.000000)
    float4 fetch18 = t1.SampleBias(s1, r0.zw, 0.0f);
    r0.z = fetch18.x;
    // mul r0.w, r0.z, cb0[11].y
    r0.w = r0.z * cb0[11].y;
    // mad r2.yz, cb0[8].wwww, r1.yyzy, r0.wwww
    float stage19_y = cb0[8].w * r1.y + r0.w;
    float stage19_z = cb0[8].w * r1.z + r0.w;
    r2.y = stage19_y;
    r2.z = stage19_z;
    // mul r1.yz, r1.yyzy, cb0[14].xxxx
    float stage20_y = r1.y * cb0[14].x;
    float stage20_z = r1.z * cb0[14].x;
    r1.y = stage20_y;
    r1.z = stage20_z;
    // mad r1.yz, r1.xxwx, l(0.000000, 0.200000, 0.200000, 0.000000), r1.yyzy
    float stage21_y = r1.x * 0.2f + r1.y;
    float stage21_z = r1.w * 0.2f + r1.z;
    r1.y = stage21_y;
    r1.z = stage21_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r4.xyz, r1.yzyy, t3.xyzw, s3, l(0.000000)
    float4 fetch22 = t3.SampleBias(s3, r1.yz, 0.0f);
    r4.x = fetch22.x;
    r4.y = fetch22.y;
    r4.z = fetch22.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.yz, r2.yzyy, t2.zxyw, s2, l(0.000000)
    float4 fetch23 = t2.SampleBias(s2, r2.yz, 0.0f);
    r1.y = fetch23.x;
    r1.z = fetch23.y;
    // mad r1.yz, r1.yyzy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
    float stage24_y = r1.y * 2.0f + -1.0f;
    float stage24_z = r1.z * 2.0f + -1.0f;
    r1.y = stage24_y;
    r1.z = stage24_z;
    // mul r1.yz, r1.yyzy, cb0[11].zzzz
    float stage25_y = r1.y * cb0[11].z;
    float stage25_z = r1.z * cb0[11].z;
    r1.y = stage25_y;
    r1.z = stage25_z;
    // mad r1.xy, cb0[8].yyyy, r1.xwxx, r1.yzyy
    float stage26_x = cb0[8].y * r1.x + r1.y;
    float stage26_y = cb0[8].y * r1.w + r1.z;
    r1.x = stage26_x;
    r1.y = stage26_y;
    // add r0.xy, r0.xyxx, r1.xyxx
    float stage27_x = r0.x + r1.x;
    float stage27_y = r0.y + r1.y;
    r0.x = stage27_x;
    r0.y = stage27_y;
    // add r0.xy, r0.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage28_x = r0.x + -0.5f;
    float stage28_y = r0.y + -0.5f;
    r0.x = stage28_x;
    r0.y = stage28_y;
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // mad r0.x, -r0.x, cb0[12].y, l(1.000000)
    r0.x = -r0.x * cb0[12].y + 1.0f;
    // mul_sat r0.x, r0.x, cb0[13].z
    r0.x = saturate(r0.x * cb0[13].z);
    // log r0.y, |r2.x|
    r0.y = log2(abs(r2.x));
    // lt r0.w, |r2.x|, l(0.000001)
    r0.w = asfloat((abs(r2.x) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[15].x
    r0.y = r0.y * cb0[15].x;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul r0.y, r0.y, r0.x
    r0.y = r0.y * r0.x;
    // mul r0.y, r0.y, l(40.000000)
    r0.y = r0.y * 40.0f;
    // movc r0.y, r0.w, l(0), r0.y
    r0.y = asuint(r0.w) != 0u ? asfloat(0u) : r0.y;
    // mul r1.xy, r0.xxxx, l(30.000000, 28.000000, 0.000000, 0.000000)
    float stage29_x = r0.x * 30.0f;
    float stage29_y = r0.x * 28.0f;
    r1.x = stage29_x;
    r1.y = stage29_y;
    // min r1.xy, r1.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
    float stage30_x = min(r1.x, 1.0f);
    float stage30_y = min(r1.y, 1.0f);
    r1.x = stage30_x;
    r1.y = stage30_y;
    // add r0.w, -r1.y, r1.x
    r0.w = -r1.y + r1.x;
    // max r0.w, r0.w, l(0.000000)
    r0.w = max(r0.w, 0.0f);
    // mad r0.y, r0.w, cb0[14].w, r0.y
    r0.y = r0.w * cb0[14].w + r0.y;
    // mul_sat r0.y, r0.y, v3.w
    r0.y = saturate(r0.y * v3.w);
    // add r0.w, v4.x, l(-1.000000)
    r0.w = v4.x + -1.0f;
    // add r0.w, -r0.w, r4.x
    r0.w = -r0.w + r4.x;
    // mul_sat r0.w, r0.w, l(30.000000)
    r0.w = saturate(r0.w * 30.0f);
    // mul r0.y, r0.w, r0.y
    r0.y = r0.w * r0.y;
    // mul o0.w, r0.y, cb0[0].w
    o0.w = r0.y * cb0[0].w;
    // log r0.y, |r0.z|
    r0.y = log2(abs(r0.z));
    // lt r0.z, |r0.z|, l(0.000001)
    r0.z = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[14].y
    r0.y = r0.y * cb0[14].y;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul r0.y, r0.y, cb0[14].z
    r0.y = r0.y * cb0[14].z;
    // movc r0.y, r0.z, l(0), r0.y
    r0.y = asuint(r0.z) != 0u ? asfloat(0u) : r0.y;
    // mul r0.z, r0.x, r0.x
    r0.z = r0.x * r0.x;
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, r0.z
    r0.z = r0.z * r0.z;
    // mul r1.xyz, r0.zzzz, cb0[2].xyzx
    float stage31_x = r0.z * cb0[2].x;
    float stage31_y = r0.z * cb0[2].y;
    float stage31_z = r0.z * cb0[2].z;
    r1.x = stage31_x;
    r1.y = stage31_y;
    r1.z = stage31_z;
    // movc r0.xzw, r0.xxxx, l(0,0,0,0), r1.xxyz
    float stage32_x = asuint(r0.x) != 0u ? asfloat(0u) : r1.x;
    float stage32_z = asuint(r0.x) != 0u ? asfloat(0u) : r1.y;
    float stage32_w = asuint(r0.x) != 0u ? asfloat(0u) : r1.z;
    r0.x = stage32_x;
    r0.z = stage32_z;
    r0.w = stage32_w;
    // mad r0.xzw, r4.xxyz, l(0.500000, 0.000000, 0.500000, 0.500000), r0.xxzw
    float stage33_x = r4.x * 0.5f + r0.x;
    float stage33_z = r4.y * 0.5f + r0.z;
    float stage33_w = r4.z * 0.5f + r0.w;
    r0.x = stage33_x;
    r0.z = stage33_z;
    r0.w = stage33_w;
    // mad r0.xyz, r0.yyyy, r0.xzwx, r0.xzwx
    float stage34_x = r0.y * r0.x + r0.x;
    float stage34_y = r0.y * r0.z + r0.z;
    float stage34_z = r0.y * r0.w + r0.w;
    r0.x = stage34_x;
    r0.y = stage34_y;
    r0.z = stage34_z;
    // mad r0.xyz, r0.xyzx, v3.xyzx, cb0[1].xyzx
    float stage35_x = r0.x * v3.x + cb0[1].x;
    float stage35_y = r0.y * v3.y + cb0[1].y;
    float stage35_z = r0.z * v3.z + cb0[1].z;
    r0.x = stage35_x;
    r0.y = stage35_y;
    r0.z = stage35_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage36_x = r0.x * v5.w + v5.x;
    float stage36_y = r0.y * v5.w + v5.y;
    float stage36_z = r0.z * v5.w + v5.z;
    o0.x = stage36_x;
    o0.y = stage36_y;
    o0.z = stage36_z;
    // dp3 r0.x, r3.xyzx, r3.xyzx
    r0.x = dot(r3.xyz, r3.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r3.xyzx
    float stage37_x = r0.x * r3.x;
    float stage37_y = r0.x * r3.y;
    float stage37_z = r0.x * r3.z;
    r0.x = stage37_x;
    r0.y = stage37_y;
    r0.z = stage37_z;
    // ge r0.w, l(0.000000), r0.z
    r0.w = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // dp3 r0.z, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.z = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.zzzz
    float stage38_x = r0.x / r0.z;
    float stage38_y = r0.y / r0.z;
    r0.x = stage38_x;
    r0.y = stage38_y;
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage39_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage39_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage39_x;
    r1.y = stage39_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage40_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage40_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage40_x;
    r1.y = stage40_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage41_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage41_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage41_x;
    r1.y = stage41_y;
    // movc r0.xy, r0.wwww, r1.xyxx, r0.xyxx
    float stage42_x = asuint(r0.w) != 0u ? r1.x : r0.x;
    float stage42_y = asuint(r0.w) != 0u ? r1.y : r0.y;
    r0.x = stage42_x;
    r0.y = stage42_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage43_x = r0.x * 0.5f + 0.5f;
    float stage43_y = r0.y * 0.5f + 0.5f;
    o2.x = stage43_x;
    o2.y = stage43_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage44_z = 1.0f;
    float stage44_w = asfloat(0u);
    o2.z = stage44_z;
    o2.w = stage44_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage45_x = cb2[3].x;
    float stage45_y = cb2[3].y;
    float stage45_z = cb2[3].z;
    o3.x = stage45_x;
    o3.y = stage45_y;
    o3.z = stage45_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage46_x = asfloat(0u);
    float stage46_y = asfloat(0u);
    float stage46_z = asfloat(0u);
    float stage46_w = asfloat(0u);
    o4.x = stage46_x;
    o4.y = stage46_y;
    o4.z = stage46_z;
    o4.w = stage46_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage47_x = asfloat(0u);
    float stage47_y = asfloat(0u);
    float stage47_z = asfloat(0u);
    float stage47_w = asfloat(0u);
    o5.x = stage47_x;
    o5.y = stage47_y;
    o5.z = stage47_z;
    o5.w = stage47_w;

    Shade_Ue3_fx_m_pa_worldoffset_01_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
