// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_mm_hole_06_tr_Constants0 : register(b0)
{
    float4 cb0[12];
};
cbuffer Shade_Ue3_fx_mm_hole_06_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);

struct Shade_Ue3_fx_mm_hole_06_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v6;
};

struct Shade_Ue3_fx_mm_hole_06_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_mm_hole_06_tr_OUTPUT Shade_Ue3_fx_mm_hole_06_tr(Shade_Ue3_fx_mm_hole_06_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v6 = stage.v6;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // dp3 r0.x, v6.xyzx, v6.xyzx
    r0.x = dot(v6.xyz, v6.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xy, r0.xxxx, v6.xyxx
    float stage1_x = r0.x * v6.x;
    float stage1_y = r0.x * v6.y;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // add r0.zw, v2.xxxy, cb0[2].xxxy
    float stage2_z = v2.x + cb0[2].x;
    float stage2_w = v2.y + cb0[2].y;
    r0.z = stage2_z;
    r0.w = stage2_w;
    // mul r1.x, v4.x, cb0[6].z
    r1.x = v4.x * cb0[6].z;
    // mad r1.y, r1.x, l(0.050000), l(-0.025000)
    r1.y = r1.x * 0.05f + -0.025f;
    // mul r1.x, r1.x, l(0.040000)
    r1.x = r1.x * 0.04f;
    // add r1.x, |r1.x|, cb0[7].y
    r1.x = abs(r1.x) + cb0[7].y;
    // add r1.x, r1.x, l(0.500000)
    r1.x = r1.x + 0.5f;
    // max r1.x, r1.x, l(0.000010)
    r1.x = max(r1.x, 1e-05f);
    // div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
    r1.x = 1.0f / r1.x;
    // mad r0.xy, r1.yyyy, r0.xyxx, r0.zwzz
    float stage3_x = r1.y * r0.x + r0.z;
    float stage3_y = r1.y * r0.y + r0.w;
    r0.x = stage3_x;
    r0.y = stage3_y;
    // add r0.xy, r0.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage4_x = r0.x + -0.5f;
    float stage4_y = r0.y + -0.5f;
    r0.x = stage4_x;
    r0.y = stage4_y;
    // max r0.z, |r0.y|, |r0.x|
    r0.z = max(abs(r0.y), abs(r0.x));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.y|, |r0.x|
    r0.w = min(abs(r0.y), abs(r0.x));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.y, r0.w, l(0.020835), l(-0.085133)
    r1.y = r0.w * 0.020835f + -0.085133f;
    // mad r1.y, r0.w, r1.y, l(0.180141)
    r1.y = r0.w * r1.y + 0.180141f;
    // mad r1.y, r0.w, r1.y, l(-0.330299)
    r1.y = r0.w * r1.y + -0.330299f;
    // mad r0.w, r0.w, r1.y, l(0.999866)
    r0.w = r0.w * r1.y + 0.999866f;
    // mul r1.y, r0.w, r0.z
    r1.y = r0.w * r0.z;
    // mad r1.y, r1.y, l(-2.000000), l(1.570796)
    r1.y = r1.y * -2.0f + 1.570796f;
    // lt r1.z, |r0.y|, |r0.x|
    r1.z = asfloat((abs(r0.y) < abs(r0.x)) ? 0xffffffffu : 0u);
    // and r1.y, r1.z, r1.y
    r1.y = asfloat(asuint(r1.z) & asuint(r1.y));
    // mad r0.z, r0.z, r0.w, r1.y
    r0.z = r0.z * r0.w + r1.y;
    // lt r0.w, r0.y, -r0.y
    r0.w = asfloat((r0.y < -r0.y) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.y, r0.x
    r0.w = min(r0.y, r0.x);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.y, r0.y, r0.x
    r1.y = max(r0.y, r0.x);
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // ge r0.y, r1.y, -r1.y
    r0.y = asfloat((r1.y >= -r1.y) ? 0xffffffffu : 0u);
    // and r0.y, r0.y, r0.w
    r0.y = asfloat(asuint(r0.y) & asuint(r0.w));
    // movc r0.y, r0.y, -r0.z, r0.z
    r0.y = asuint(r0.y) != 0u ? -r0.z : r0.z;
    // mad r0.y, r0.y, l(0.318310), l(1.000000)
    r0.y = r0.y * 0.31831f + 1.0f;
    // add r0.z, -r0.x, cb0[6].w
    r0.z = -r0.x + cb0[6].w;
    // mad r0.x, -r0.x, r1.x, l(1.000000)
    r0.x = -r0.x * r1.x + 1.0f;
    // max r0.x, r0.x, l(0.000000)
    r0.x = max(r0.x, 0.0f);
    // add r0.x, -r0.x, l(1.000000)
    r0.x = -r0.x + 1.0f;
    // div r0.z, r0.z, cb0[6].w
    r0.z = r0.z / cb0[6].w;
    // mul r0.w, v4.w, cb0[7].x
    r0.w = v4.w * cb0[7].x;
    // mul r0.z, r0.w, r0.z
    r0.z = r0.w * r0.z;
    // mad r1.x, r0.y, l(0.500000), r0.z
    r1.x = r0.y * 0.5f + r0.z;
    // log r0.y, r0.x
    r0.y = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.y, cb0[7].z
    r0.z = r0.y * cb0[7].z;
    // mul r0.y, r0.y, cb0[9].w
    r0.y = r0.y * cb0[9].w;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul_sat r0.y, r0.y, cb0[10].x
    r0.y = saturate(r0.y * cb0[10].x);
    // movc r0.y, r0.x, l(0), r0.y
    r0.y = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // min r0.z, r0.z, l(1.000000)
    r0.z = min(r0.z, 1.0f);
    // movc r0.x, r0.x, l(0), r0.z
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.z;
    // add r1.y, r0.x, r1.x
    r1.y = r0.x + r1.x;
    // mul r0.xz, r1.xxyx, cb0[5].zzwz
    float stage5_x = r1.x * cb0[5].z;
    float stage5_z = r1.y * cb0[5].w;
    r0.x = stage5_x;
    r0.z = stage5_z;
    // mul r1.xy, r1.xyxx, cb0[8].yzyy
    float stage6_x = r1.x * cb0[8].y;
    float stage6_y = r1.y * cb0[8].z;
    r1.x = stage6_x;
    r1.y = stage6_y;
    // mad r1.xy, cb0[5].yyyy, cb0[8].xwxx, r1.xyxx
    float stage7_x = cb0[5].y * cb0[8].x + r1.x;
    float stage7_y = cb0[5].y * cb0[8].w + r1.y;
    r1.x = stage7_x;
    r1.y = stage7_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t1.xyzw, s1, l(0.000000)
    float4 fetch8 = t1.SampleLevel(s1, r1.xy, 0.0f);
    r1.x = fetch8.x;
    r1.y = fetch8.y;
    r1.z = fetch8.z;
    // mad r2.x, cb0[5].y, cb0[5].x, r0.x
    r2.x = cb0[5].y * cb0[5].x + r0.x;
    // mad r2.y, cb0[5].y, cb0[7].w, r0.z
    r2.y = cb0[5].y * cb0[7].w + r0.z;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.xzw, r2.xyxx, t0.xwyz, s0, l(0.000000)
    float4 fetch9 = t0.SampleLevel(s0, r2.xy, 0.0f);
    r0.x = fetch9.x;
    r0.z = fetch9.y;
    r0.w = fetch9.z;
    // mul r2.xyzw, r1.xxyz, r0.xxzw
    float stage10_x = r1.x * r0.x;
    float stage10_y = r1.x * r0.x;
    float stage10_z = r1.y * r0.z;
    float stage10_w = r1.z * r0.w;
    r2.x = stage10_x;
    r2.y = stage10_y;
    r2.z = stage10_z;
    r2.w = stage10_w;
    // dp3 r1.w, r2.yzwy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.w = dot(r2.yzw, float3(0.3f, 0.59f, 0.11f));
    // mad r0.xzw, -r0.xxzw, r1.xxyz, r1.wwww
    float stage11_x = -r0.x * r1.x + r1.w;
    float stage11_z = -r0.z * r1.y + r1.w;
    float stage11_w = -r0.w * r1.z + r1.w;
    r0.x = stage11_x;
    r0.z = stage11_z;
    r0.w = stage11_w;
    // mad r0.xzw, cb0[9].xxxx, r0.xxzw, r2.yyzw
    float stage12_x = cb0[9].x * r0.x + r2.y;
    float stage12_z = cb0[9].x * r0.z + r2.z;
    float stage12_w = cb0[9].x * r0.w + r2.w;
    r0.x = stage12_x;
    r0.z = stage12_z;
    r0.w = stage12_w;
    // mul_sat r1.x, r2.x, cb0[11].z
    r1.x = saturate(r2.x * cb0[11].z);
    // max r1.x, r1.x, l(0.000001)
    r1.x = max(r1.x, 1e-06f);
    // log r1.x, r1.x
    r1.x = log2(r1.x);
    // mul r1.x, r1.x, cb0[11].w
    r1.x = r1.x * cb0[11].w;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // max r0.xzw, |r0.xxzw|, l(0.000001, 0.000000, 0.000001, 0.000001)
    float stage13_x = max(abs(r0.x), 1e-06f);
    float stage13_z = max(abs(r0.z), 1e-06f);
    float stage13_w = max(abs(r0.w), 1e-06f);
    r0.x = stage13_x;
    r0.z = stage13_z;
    r0.w = stage13_w;
    // log r0.xzw, r0.xxzw
    float stage14_x = log2(r0.x);
    float stage14_z = log2(r0.z);
    float stage14_w = log2(r0.w);
    r0.x = stage14_x;
    r0.z = stage14_z;
    r0.w = stage14_w;
    // mul r0.xzw, r0.xxzw, cb0[9].yyyy
    float stage15_x = r0.x * cb0[9].y;
    float stage15_z = r0.z * cb0[9].y;
    float stage15_w = r0.w * cb0[9].y;
    r0.x = stage15_x;
    r0.z = stage15_z;
    r0.w = stage15_w;
    // exp r0.xzw, r0.xxzw
    float stage16_x = exp2(r0.x);
    float stage16_z = exp2(r0.z);
    float stage16_w = exp2(r0.w);
    r0.x = stage16_x;
    r0.z = stage16_z;
    r0.w = stage16_w;
    // mul r0.xzw, r0.xxzw, cb0[9].zzzz
    float stage17_x = r0.x * cb0[9].z;
    float stage17_z = r0.z * cb0[9].z;
    float stage17_w = r0.w * cb0[9].z;
    r0.x = stage17_x;
    r0.z = stage17_z;
    r0.w = stage17_w;
    // mul r0.xyz, r0.xzwx, r0.yyyy
    float stage18_x = r0.x * r0.y;
    float stage18_y = r0.z * r0.y;
    float stage18_z = r0.w * r0.y;
    r0.x = stage18_x;
    r0.y = stage18_y;
    r0.z = stage18_z;
    // mul r1.yzw, cb0[3].xxyz, cb0[3].wwww
    float stage19_y = cb0[3].x * cb0[3].w;
    float stage19_z = cb0[3].y * cb0[3].w;
    float stage19_w = cb0[3].z * cb0[3].w;
    r1.y = stage19_y;
    r1.z = stage19_z;
    r1.w = stage19_w;
    // mul r2.xyz, cb0[4].xyzx, cb0[4].wwww
    float stage20_x = cb0[4].x * cb0[4].w;
    float stage20_y = cb0[4].y * cb0[4].w;
    float stage20_z = cb0[4].z * cb0[4].w;
    r2.x = stage20_x;
    r2.y = stage20_y;
    r2.z = stage20_z;
    // mad r0.xyz, r0.xyzx, r1.yzwy, r2.xyzx
    float stage21_x = r0.x * r1.y + r2.x;
    float stage21_y = r0.y * r1.z + r2.y;
    float stage21_z = r0.z * r1.w + r2.z;
    r0.x = stage21_x;
    r0.y = stage21_y;
    r0.z = stage21_z;
    // mad r0.xyz, v3.xyzx, r0.xyzx, cb0[1].xyzx
    float stage22_x = v3.x * r0.x + cb0[1].x;
    float stage22_y = v3.y * r0.y + cb0[1].y;
    float stage22_z = v3.z * r0.z + cb0[1].z;
    r0.x = stage22_x;
    r0.y = stage22_y;
    r0.z = stage22_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage23_x = r0.x * v5.w + v5.x;
    float stage23_y = r0.y * v5.w + v5.y;
    float stage23_z = r0.z * v5.w + v5.z;
    o0.x = stage23_x;
    o0.y = stage23_y;
    o0.z = stage23_z;
    // add r0.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage24_x = v2.x + -0.5f;
    float stage24_y = v2.y + -0.5f;
    r0.x = stage24_x;
    r0.y = stage24_y;
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // mul r0.y, v4.y, cb0[10].y
    r0.y = v4.y * cb0[10].y;
    // max r0.y, r0.y, l(0.000010)
    r0.y = max(r0.y, 1e-05f);
    // div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
    r0.y = 1.0f / r0.y;
    // mad r0.x, -r0.x, r0.y, l(1.000000)
    r0.x = -r0.x * r0.y + 1.0f;
    // mul_sat r0.x, r0.x, cb0[11].y
    r0.x = saturate(r0.x * cb0[11].y);
    // add r0.y, r1.x, r0.x
    r0.y = r1.x + r0.x;
    // mul r0.x, r0.y, r0.x
    r0.x = r0.y * r0.x;
    // min r0.x, r0.x, l(1.000000)
    r0.x = min(r0.x, 1.0f);
    // mul_sat r0.x, r0.x, v3.w
    r0.x = saturate(r0.x * v3.w);
    // mul o0.w, r0.x, cb0[0].x
    o0.w = r0.x * cb0[0].x;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage25_x = r0.x * v1.x;
    float stage25_y = r0.x * v1.y;
    float stage25_z = r0.x * v1.z;
    r0.x = stage25_x;
    r0.y = stage25_y;
    r0.z = stage25_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage26_x = r0.w * v0.z;
    float stage26_y = r0.w * v0.x;
    float stage26_z = r0.w * v0.y;
    r1.x = stage26_x;
    r1.y = stage26_y;
    r1.z = stage26_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage27_x = r0.x * r1.x;
    float stage27_y = r0.x * r1.y;
    float stage27_z = r0.x * r1.z;
    r0.x = stage27_x;
    r0.y = stage27_y;
    r0.z = stage27_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage28_x = r0.x / r0.w;
    float stage28_y = r0.y / r0.w;
    r0.x = stage28_x;
    r0.y = stage28_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage29_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage29_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage29_x;
    r1.y = stage29_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage30_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage30_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage30_x;
    r1.y = stage30_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage31_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage31_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage31_x;
    r1.y = stage31_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage32_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage32_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage32_x;
    r0.y = stage32_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage33_x = r0.x * 0.5f + 0.5f;
    float stage33_y = r0.y * 0.5f + 0.5f;
    o2.x = stage33_x;
    o2.y = stage33_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage34_z = 1.0f;
    float stage34_w = asfloat(0u);
    o2.z = stage34_z;
    o2.w = stage34_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage35_x = cb2[3].x;
    float stage35_y = cb2[3].y;
    float stage35_z = cb2[3].z;
    o3.x = stage35_x;
    o3.y = stage35_y;
    o3.z = stage35_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage36_x = asfloat(0u);
    float stage36_y = asfloat(0u);
    float stage36_z = asfloat(0u);
    float stage36_w = asfloat(0u);
    o4.x = stage36_x;
    o4.y = stage36_y;
    o4.z = stage36_z;
    o4.w = stage36_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage37_x = asfloat(0u);
    float stage37_y = asfloat(0u);
    float stage37_z = asfloat(0u);
    float stage37_w = asfloat(0u);
    o5.x = stage37_x;
    o5.y = stage37_y;
    o5.z = stage37_z;
    o5.w = stage37_w;

    Shade_Ue3_fx_mm_hole_06_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
