// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_master_01_ad_Constants0 : register(b0)
{
    float4 cb0[11];
};
cbuffer Shade_Ue3_fx_d_pa_master_01_ad_Constants2 : register(b2)
{
    float4 cb2[2];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);

struct Shade_Ue3_fx_d_pa_master_01_ad_INPUT
{
    float4 v2;
    float4 v4;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_d_pa_master_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_d_pa_master_01_ad_OUTPUT Shade_Ue3_fx_d_pa_master_01_ad(Shade_Ue3_fx_d_pa_master_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 r5 = (float4)0;
    float4 o0 = (float4)0;

    // div r0.xy, v7.xyxx, v7.wwww
    float stage1_x = v7.x / v7.w;
    float stage1_y = v7.y / v7.w;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // mad r0.xy, r0.xyxx, cb2[0].xyxx, cb2[0].wzww
    float stage2_x = r0.x * cb2[0].x + cb2[0].w;
    float stage2_y = r0.y * cb2[0].y + cb2[0].z;
    r0.x = stage2_x;
    r0.y = stage2_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t3.xyzw, s0, l(0.000000)
    float4 fetch3 = t3.SampleLevel(s0, r0.xy, 0.0f);
    r0.x = fetch3.x;
    // min r0.x, r0.x, l(0.999000)
    r0.x = min(r0.x, 0.999f);
    // mad r0.y, r0.x, cb2[1].z, -cb2[1].w
    r0.y = r0.x * cb2[1].z + -cb2[1].w;
    // mad r0.x, r0.x, cb2[1].x, cb2[1].y
    r0.x = r0.x * cb2[1].x + cb2[1].y;
    // div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
    r0.y = 1.0f / r0.y;
    // add r0.x, r0.y, r0.x
    r0.x = r0.y + r0.x;
    // add r0.x, r0.x, -v7.w
    r0.x = r0.x + -v7.w;
    // add r0.y, -cb0[10].y, l(1.000000)
    r0.y = -cb0[10].y + 1.0f;
    // max r0.y, -r0.y, l(0.001000)
    r0.y = max(-r0.y, 0.001f);
    // div_sat r0.x, r0.x, r0.y
    r0.x = saturate(r0.x / r0.y);
    // mul r0.yz, v4.xxyx, cb0[5].zzwz
    float stage4_y = v4.x * cb0[5].z;
    float stage4_z = v4.y * cb0[5].w;
    r0.y = stage4_y;
    r0.z = stage4_z;
    // mul r0.w, cb0[4].x, cb0[4].y
    r0.w = cb0[4].x * cb0[4].y;
    // mad r1.x, r0.w, cb0[5].y, r0.y
    r1.x = r0.w * cb0[5].y + r0.y;
    // mad r1.y, r0.w, cb0[6].x, r0.z
    r1.y = r0.w * cb0[6].x + r0.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.yz, r1.xyxx, t0.zxyw, s1, l(0.000000)
    float4 fetch5 = t0.SampleBias(s1, r1.xy, 0.0f);
    r0.y = fetch5.x;
    r0.z = fetch5.y;
    // mad r0.yz, cb0[6].zzzz, r0.yyzy, v4.xxyx
    float stage6_y = cb0[6].z * r0.y + v4.x;
    float stage6_z = cb0[6].z * r0.z + v4.y;
    r0.y = stage6_y;
    r0.z = stage6_z;
    // mul r1.x, r0.y, cb0[7].w
    r1.x = r0.y * cb0[7].w;
    // mad r1.x, r0.w, cb0[7].z, r1.x
    r1.x = r0.w * cb0[7].z + r1.x;
    // mul r1.z, r0.z, cb0[8].x
    r1.z = r0.z * cb0[8].x;
    // mad r1.y, r0.w, cb0[8].y, r1.z
    r1.y = r0.w * cb0[8].y + r1.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t1.xyzw, s3, l(0.000000)
    float4 fetch7 = t1.SampleBias(s3, r1.xy, 0.0f);
    r1.x = fetch7.x;
    r1.y = fetch7.y;
    r1.z = fetch7.z;
    // add r2.xy, r0.yzyy, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage8_x = r0.y + -0.5f;
    float stage8_y = r0.z + -0.5f;
    r2.x = stage8_x;
    r2.y = stage8_y;
    // mad r1.w, cb0[4].y, cb0[8].w, cb0[9].x
    r1.w = cb0[4].y * cb0[8].w + cb0[9].x;
    // sincos r3.x, r4.x, r1.w
    float stage9_x = r1.w;
    r3.x = sin(stage9_x);
    r4.x = cos(stage9_x);
    // mov r5.x, -r3.x
    r5.x = -r3.x;
    // mov r5.y, r4.x
    r5.y = r4.x;
    // mov r5.z, r3.x
    r5.z = r3.x;
    // dp2 r3.y, r5.zyzz, r2.xyxx
    r3.y = dot(r5.zy, r2.xy);
    // dp2 r3.x, r5.yxyy, r2.xyxx
    r3.x = dot(r5.yx, r2.xy);
    // mad r2.xy, r3.xyxx, cb0[3].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage10_x = r3.x * cb0[3].x + 0.5f;
    float stage10_y = r3.y * cb0[3].y + 0.5f;
    r2.x = stage10_x;
    r2.y = stage10_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xyxx, t2.xyzw, s4, l(0.000000)
    float4 fetch11 = t2.SampleBias(s4, r2.xy, 0.0f);
    r2.x = fetch11.x;
    r2.y = fetch11.y;
    r2.z = fetch11.z;
    // mul r1.xy, r1.xyxx, r2.xyxx
    float stage12_x = r1.x * r2.x;
    float stage12_y = r1.y * r2.y;
    r1.x = stage12_x;
    r1.y = stage12_y;
    // add r1.x, r1.y, r1.x
    r1.x = r1.y + r1.x;
    // mad r1.x, r1.z, r2.z, r1.x
    r1.x = r1.z * r2.z + r1.x;
    // mul r1.x, r1.x, cb0[9].w
    r1.x = r1.x * cb0[9].w;
    // mul_sat r1.x, r1.x, l(0.333330)
    r1.x = saturate(r1.x * 0.33333f);
    // log r1.y, r1.x
    r1.y = log2(r1.x);
    // lt r1.x, r1.x, l(0.000001)
    r1.x = asfloat((r1.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.y, r1.y, cb0[10].x
    r1.y = r1.y * cb0[10].x;
    // exp r1.y, r1.y
    r1.y = exp2(r1.y);
    // mul r0.x, r0.x, r1.y
    r0.x = r0.x * r1.y;
    // mul_sat r0.x, r0.x, v2.w
    r0.x = saturate(r0.x * v2.w);
    // mul r0.x, r0.x, cb0[0].x
    r0.x = r0.x * cb0[0].x;
    // movc r0.x, r1.x, l(0), r0.x
    r0.x = asuint(r1.x) != 0u ? asfloat(0u) : r0.x;
    // mul r0.y, r0.y, cb0[4].w
    r0.y = r0.y * cb0[4].w;
    // mad r1.x, r0.w, cb0[4].z, r0.y
    r1.x = r0.w * cb0[4].z + r0.y;
    // mul r0.y, r0.w, cb0[6].w
    r0.y = r0.w * cb0[6].w;
    // mad r1.y, cb0[5].x, r0.z, r0.y
    r1.y = cb0[5].x * r0.z + r0.y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.yzw, r1.xyxx, t4.wxyz, s2, l(0.000000)
    float4 fetch13 = t4.SampleBias(s2, r1.xy, 0.0f);
    r0.y = fetch13.x;
    r0.z = fetch13.y;
    r0.w = fetch13.z;
    // dp3 r1.x, r0.yzwy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.x = dot(r0.yzw, float3(0.3f, 0.59f, 0.11f));
    // add r1.xyz, -r0.yzwy, r1.xxxx
    float stage14_x = -r0.y + r1.x;
    float stage14_y = -r0.z + r1.x;
    float stage14_z = -r0.w + r1.x;
    r1.x = stage14_x;
    r1.y = stage14_y;
    r1.z = stage14_z;
    // mad r0.yzw, cb0[7].xxxx, r1.xxyz, r0.yyzw
    float stage15_y = cb0[7].x * r1.x + r0.y;
    float stage15_z = cb0[7].x * r1.y + r0.z;
    float stage15_w = cb0[7].x * r1.z + r0.w;
    r0.y = stage15_y;
    r0.z = stage15_z;
    r0.w = stage15_w;
    // max r0.yzw, |r0.yyzw|, l(0.000000, 0.000001, 0.000001, 0.000001)
    float stage16_y = max(abs(r0.y), 1e-06f);
    float stage16_z = max(abs(r0.z), 1e-06f);
    float stage16_w = max(abs(r0.w), 1e-06f);
    r0.y = stage16_y;
    r0.z = stage16_z;
    r0.w = stage16_w;
    // log r0.yzw, r0.yyzw
    float stage17_y = log2(r0.y);
    float stage17_z = log2(r0.z);
    float stage17_w = log2(r0.w);
    r0.y = stage17_y;
    r0.z = stage17_z;
    r0.w = stage17_w;
    // mul r0.yzw, r0.yyzw, cb0[7].yyyy
    float stage18_y = r0.y * cb0[7].y;
    float stage18_z = r0.z * cb0[7].y;
    float stage18_w = r0.w * cb0[7].y;
    r0.y = stage18_y;
    r0.z = stage18_z;
    r0.w = stage18_w;
    // exp r0.yzw, r0.yyzw
    float stage19_y = exp2(r0.y);
    float stage19_z = exp2(r0.z);
    float stage19_w = exp2(r0.w);
    r0.y = stage19_y;
    r0.z = stage19_z;
    r0.w = stage19_w;
    // mul r1.xyz, cb0[2].xyzx, cb0[2].wwww
    float stage20_x = cb0[2].x * cb0[2].w;
    float stage20_y = cb0[2].y * cb0[2].w;
    float stage20_z = cb0[2].z * cb0[2].w;
    r1.x = stage20_x;
    r1.y = stage20_y;
    r1.z = stage20_z;
    // mul r0.yzw, r0.yyzw, r1.xxyz
    float stage21_y = r0.y * r1.x;
    float stage21_z = r0.z * r1.y;
    float stage21_w = r0.w * r1.z;
    r0.y = stage21_y;
    r0.z = stage21_z;
    r0.w = stage21_w;
    // mad r0.yzw, r0.yyzw, v2.xxyz, cb0[1].xxyz
    float stage22_y = r0.y * v2.x + cb0[1].x;
    float stage22_z = r0.z * v2.y + cb0[1].y;
    float stage22_w = r0.w * v2.z + cb0[1].z;
    r0.y = stage22_y;
    r0.z = stage22_z;
    r0.w = stage22_w;
    // mul r0.yzw, r0.yyzw, v5.wwww
    float stage23_y = r0.y * v5.w;
    float stage23_z = r0.z * v5.w;
    float stage23_w = r0.w * v5.w;
    r0.y = stage23_y;
    r0.z = stage23_z;
    r0.w = stage23_w;
    // mul o0.xyz, r0.xxxx, r0.yzwy
    float stage24_x = r0.x * r0.y;
    float stage24_y = r0.x * r0.z;
    float stage24_z = r0.x * r0.w;
    o0.x = stage24_x;
    o0.y = stage24_y;
    o0.z = stage24_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_d_pa_master_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
