// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_m_pa_spritewave_01_tr_e7ad15135c47af4d78ffceae8617c2561fdbe443dc2065ad782e1cbefa039b86_Constants0 : register(b0)
{
    float4 cb0[20];
};
cbuffer Shade_Ue3_fx_m_pa_spritewave_01_tr_e7ad15135c47af4d78ffceae8617c2561fdbe443dc2065ad782e1cbefa039b86_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);

struct Shade_Ue3_fx_m_pa_spritewave_01_tr_e7ad15135c47af4d78ffceae8617c2561fdbe443dc2065ad782e1cbefa039b86_INPUT
{
    float4 v0;
    float4 v1;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_m_pa_spritewave_01_tr_e7ad15135c47af4d78ffceae8617c2561fdbe443dc2065ad782e1cbefa039b86_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_m_pa_spritewave_01_tr_e7ad15135c47af4d78ffceae8617c2561fdbe443dc2065ad782e1cbefa039b86_OUTPUT Shade_Ue3_fx_m_pa_spritewave_01_tr_e7ad15135c47af4d78ffceae8617c2561fdbe443dc2065ad782e1cbefa039b86(Shade_Ue3_fx_m_pa_spritewave_01_tr_e7ad15135c47af4d78ffceae8617c2561fdbe443dc2065ad782e1cbefa039b86_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // add r0.xy, v4.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v4.x + -0.5f;
    float stage1_y = v4.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.y|, |r0.x|
    r0.z = max(abs(r0.y), abs(r0.x));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.y|, |r0.x|
    r0.w = min(abs(r0.y), abs(r0.x));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.y|, |r0.x|
    r1.y = asfloat((abs(r0.y) < abs(r0.x)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.y, -r0.y
    r0.w = asfloat((r0.y < -r0.y) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.y, r0.x
    r0.w = min(r0.y, r0.x);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.y, r0.x
    r1.x = max(r0.y, r0.x);
    // ge r1.x, r1.x, -r1.x
    r1.x = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, r1.x
    r0.w = asfloat(asuint(r0.w) & asuint(r1.x));
    // movc r0.z, r0.w, -r0.z, r0.z
    r0.z = asuint(r0.w) != 0u ? -r0.z : r0.z;
    // mad r1.x, r0.z, l(0.159155), l(0.500000)
    r1.x = r0.z * 0.159155f + 0.5f;
    // dp2 r0.z, r0.xyxx, r0.xyxx
    r0.z = dot(r0.xy, r0.xy);
    // sqrt r0.z, r0.z
    r0.z = sqrt(r0.z);
    // log r0.w, r0.z
    r0.w = log2(r0.z);
    // mul r0.w, r0.w, cb0[3].w
    r0.w = r0.w * cb0[3].w;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // lt r1.z, r0.z, l(0.000001)
    r1.z = asfloat((r0.z < 1e-06f) ? 0xffffffffu : 0u);
    // mad r0.z, -r0.z, l(2.000000), l(1.000000)
    r0.z = -r0.z * 2.0f + 1.0f;
    // max r0.z, r0.z, l(0.000000)
    r0.z = max(r0.z, 0.0f);
    // mul r0.z, r0.z, cb0[18].z
    r0.z = r0.z * cb0[18].z;
    // max r0.z, r0.z, cb0[19].x
    r0.z = max(r0.z, cb0[19].x);
    // min r0.z, r0.z, cb0[18].w
    r0.z = min(r0.z, cb0[18].w);
    // movc r1.y, r1.z, l(0), r0.w
    r1.y = asuint(r1.z) != 0u ? asfloat(0u) : r0.w;
    // mul r1.xy, r1.xyxx, cb0[12].xyxx
    float stage2_x = r1.x * cb0[12].x;
    float stage2_y = r1.y * cb0[12].y;
    r1.x = stage2_x;
    r1.y = stage2_y;
    // mad r2.x, cb0[11].w, cb0[11].z, r1.x
    r2.x = cb0[11].w * cb0[11].z + r1.x;
    // mad r2.y, cb0[11].w, cb0[12].z, r1.y
    r2.y = cb0[11].w * cb0[12].z + r1.y;
    // mul r1.x, cb0[3].x, cb0[12].w
    r1.x = cb0[3].x * cb0[12].w;
    // mul r1.y, cb0[3].x, cb0[13].x
    r1.y = cb0[3].x * cb0[13].x;
    // mad r1.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), r1.xyxx
    float stage3_x = r2.x * 2.0f + r1.x;
    float stage3_y = r2.y * 2.0f + r1.y;
    r1.x = stage3_x;
    r1.y = stage3_y;
    // mul r1.zw, v4.xxxy, cb0[13].zzzw
    float stage4_z = v4.x * cb0[13].z;
    float stage4_w = v4.y * cb0[13].w;
    r1.z = stage4_z;
    r1.w = stage4_w;
    // mad r2.x, cb0[11].w, cb0[13].y, r1.z
    r2.x = cb0[11].w * cb0[13].y + r1.z;
    // mad r2.y, cb0[11].w, cb0[14].x, r1.w
    r2.y = cb0[11].w * cb0[14].x + r1.w;
    // add r1.zw, r2.xxxy, cb0[4].xxxy
    float stage5_z = r2.x + cb0[4].x;
    float stage5_w = r2.y + cb0[4].y;
    r1.z = stage5_z;
    r1.w = stage5_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.w, r1.zwzz, t0.yzwx, s1, l(0.000000)
    float4 fetch6 = t0.SampleBias(s1, r1.zw, 0.0f);
    r0.w = fetch6.x;
    // add r1.z, cb0[3].z, cb0[14].w
    r1.z = cb0[3].z + cb0[14].w;
    // mad r1.zw, r0.wwww, r1.zzzz, cb0[5].xxxy
    float stage7_z = r0.w * r1.z + cb0[5].x;
    float stage7_w = r0.w * r1.z + cb0[5].y;
    r1.z = stage7_z;
    r1.w = stage7_w;
    // add r1.xy, r1.zwzz, r1.xyxx
    float stage8_x = r1.z + r1.x;
    float stage8_y = r1.w + r1.y;
    r1.x = stage8_x;
    r1.y = stage8_y;
    // add r1.xy, r1.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage9_x = r1.x + -0.5f;
    float stage9_y = r1.y + -0.5f;
    r1.x = stage9_x;
    r1.y = stage9_y;
    // dp2 r2.x, cb0[6].xyxx, r1.xyxx
    r2.x = dot(cb0[6].xy, r1.xy);
    // dp2 r2.y, cb0[7].xyxx, r1.xyxx
    r2.y = dot(cb0[7].xy, r1.xy);
    // add r1.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage10_x = r2.x + 0.5f;
    float stage10_y = r2.y + 0.5f;
    r1.x = stage10_x;
    r1.y = stage10_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.w, r1.xyxx, t1.yzwx, s0, l(-1.000000)
    float4 fetch11 = t1.SampleLevel(s0, r1.xy, -1.0f);
    r0.w = fetch11.x;
    // log r1.x, |r0.w|
    r1.x = log2(abs(r0.w));
    // mul r1.x, r1.x, cb0[15].z
    r1.x = r1.x * cb0[15].z;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // mul r1.x, r1.x, cb0[15].w
    r1.x = r1.x * cb0[15].w;
    // lt r1.y, |r0.w|, l(0.000001)
    r1.y = asfloat((abs(r0.w) < 1e-06f) ? 0xffffffffu : 0u);
    // movc r1.x, r1.y, l(0), r1.x
    r1.x = asuint(r1.y) != 0u ? asfloat(0u) : r1.x;
    // mad r1.x, r0.w, cb0[16].x, r1.x
    r1.x = r0.w * cb0[16].x + r1.x;
    // dp2 r2.x, cb0[8].xyxx, r0.xyxx
    r2.x = dot(cb0[8].xy, r0.xy);
    // dp2 r2.y, cb0[9].xyxx, r0.xyxx
    r2.y = dot(cb0[9].xy, r0.xy);
    // add r0.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage12_x = r2.x + 0.5f;
    float stage12_y = r2.y + 0.5f;
    r0.x = stage12_x;
    r0.y = stage12_y;
    // mul r0.xy, r0.xyxx, cb0[16].zwzz
    float stage13_x = r0.x * cb0[16].z;
    float stage13_y = r0.y * cb0[16].w;
    r0.x = stage13_x;
    r0.y = stage13_y;
    // mad r2.x, cb0[11].w, cb0[16].y, r0.x
    r2.x = cb0[11].w * cb0[16].y + r0.x;
    // mad r2.y, cb0[11].w, cb0[17].y, r0.y
    r2.y = cb0[11].w * cb0[17].y + r0.y;
    // add r0.xy, r2.xyxx, cb0[17].zwzz
    float stage14_x = r2.x + cb0[17].z;
    float stage14_y = r2.y + cb0[17].w;
    r0.x = stage14_x;
    r0.y = stage14_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t2.xyzw, s2, l(0.000000)
    float4 fetch15 = t2.SampleBias(s2, r0.xy, 0.0f);
    r0.x = fetch15.x;
    // add r0.x, r0.x, l(0.100000)
    r0.x = r0.x + 0.1f;
    // add r0.y, cb0[3].y, l(-1.000000)
    r0.y = cb0[3].y + -1.0f;
    // add_sat r0.x, -r0.y, r0.x
    r0.x = saturate(-r0.y + r0.x);
    // log r0.y, r0.x
    r0.y = log2(r0.x);
    // mul r0.y, r0.y, cb0[18].y
    r0.y = r0.y * cb0[18].y;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul_sat r0.y, r0.y, cb0[18].x
    r0.y = saturate(r0.y * cb0[18].x);
    // lt r1.y, r0.x, l(0.000001)
    r1.y = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.x, r0.x, cb0[18].x
    r0.x = r0.x * cb0[18].x;
    // movc r0.y, r1.y, l(-0.000000), -r0.y
    r0.y = asuint(r1.y) != 0u ? -0.0f : -r0.y;
    // mov_sat r1.y, r0.x
    r1.y = saturate(r0.x);
    // mul r0.x, r0.x, r0.w
    r0.x = r0.x * r0.w;
    // mul r0.x, r0.x, cb0[19].y
    r0.x = r0.x * cb0[19].y;
    // mul_sat r0.x, r0.x, cb0[1].w
    r0.x = saturate(r0.x * cb0[1].w);
    // mul r0.x, r0.x, r0.z
    r0.x = r0.x * r0.z;
    // mul o0.w, r0.x, cb0[0].x
    o0.w = r0.x * cb0[0].x;
    // add r0.x, r0.y, r1.y
    r0.x = r0.y + r1.y;
    // max r0.x, r0.x, l(0.000000)
    r0.x = max(r0.x, 0.0f);
    // mad r0.xyz, r0.xxxx, cb0[10].xyzx, r1.xxxx
    float stage16_x = r0.x * cb0[10].x + r1.x;
    float stage16_y = r0.x * cb0[10].y + r1.x;
    float stage16_z = r0.x * cb0[10].z + r1.x;
    r0.x = stage16_x;
    r0.y = stage16_y;
    r0.z = stage16_z;
    // mad r0.xyz, r0.xyzx, cb0[1].xyzx, cb0[2].xyzx
    float stage17_x = r0.x * cb0[1].x + cb0[2].x;
    float stage17_y = r0.y * cb0[1].y + cb0[2].y;
    float stage17_z = r0.z * cb0[1].z + cb0[2].z;
    r0.x = stage17_x;
    r0.y = stage17_y;
    r0.z = stage17_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage18_x = r0.x * v5.w + v5.x;
    float stage18_y = r0.y * v5.w + v5.y;
    float stage18_z = r0.z * v5.w + v5.z;
    o0.x = stage18_x;
    o0.y = stage18_y;
    o0.z = stage18_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage19_x = r0.x * v1.x;
    float stage19_y = r0.x * v1.y;
    float stage19_z = r0.x * v1.z;
    r0.x = stage19_x;
    r0.y = stage19_y;
    r0.z = stage19_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage20_x = r0.w * v0.z;
    float stage20_y = r0.w * v0.x;
    float stage20_z = r0.w * v0.y;
    r1.x = stage20_x;
    r1.y = stage20_y;
    r1.z = stage20_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage21_x = r0.x * r1.x;
    float stage21_y = r0.x * r1.y;
    float stage21_z = r0.x * r1.z;
    r0.x = stage21_x;
    r0.y = stage21_y;
    r0.z = stage21_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage22_x = r0.x / r0.w;
    float stage22_y = r0.y / r0.w;
    r0.x = stage22_x;
    r0.y = stage22_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage23_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage23_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage23_x;
    r1.y = stage23_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage24_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage24_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage24_x;
    r1.y = stage24_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage25_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage25_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage25_x;
    r1.y = stage25_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage26_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage26_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage26_x;
    r0.y = stage26_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage27_x = r0.x * 0.5f + 0.5f;
    float stage27_y = r0.y * 0.5f + 0.5f;
    o2.x = stage27_x;
    o2.y = stage27_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage28_z = 1.0f;
    float stage28_w = asfloat(0u);
    o2.z = stage28_z;
    o2.w = stage28_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage29_x = cb2[3].x;
    float stage29_y = cb2[3].y;
    float stage29_z = cb2[3].z;
    o3.x = stage29_x;
    o3.y = stage29_y;
    o3.z = stage29_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage30_x = asfloat(0u);
    float stage30_y = asfloat(0u);
    float stage30_z = asfloat(0u);
    float stage30_w = asfloat(0u);
    o4.x = stage30_x;
    o4.y = stage30_y;
    o4.z = stage30_z;
    o4.w = stage30_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage31_x = asfloat(0u);
    float stage31_y = asfloat(0u);
    float stage31_z = asfloat(0u);
    float stage31_w = asfloat(0u);
    o5.x = stage31_x;
    o5.y = stage31_y;
    o5.z = stage31_z;
    o5.w = stage31_w;

    Shade_Ue3_fx_m_pa_spritewave_01_tr_e7ad15135c47af4d78ffceae8617c2561fdbe443dc2065ad782e1cbefa039b86_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
