// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_j_pa_circledisort_01_ad_Constants0 : register(b0)
{
    float4 cb0[2];
};

struct Shade_Ue3_fx_j_pa_circledisort_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_j_pa_circledisort_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_j_pa_circledisort_01_ad_OUTPUT Shade_Ue3_fx_j_pa_circledisort_01_ad(Shade_Ue3_fx_j_pa_circledisort_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 o0 = (float4)0;

    // mad r0.x, -v4.y, l(0.500000), l(1.000000)
    r0.x = -v4.y * 0.5f + 1.0f;
    // max r0.x, r0.x, l(0.000010)
    r0.x = max(r0.x, 1e-05f);
    // div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
    r0.x = 1.0f / r0.x;
    // add r0.yz, v2.xxyx, l(0.000000, -0.500000, -0.500000, 0.000000)
    float stage1_y = v2.x + -0.5f;
    float stage1_z = v2.y + -0.5f;
    r0.y = stage1_y;
    r0.z = stage1_z;
    // dp2 r0.y, r0.yzyy, r0.yzyy
    r0.y = dot(r0.yz, r0.yz);
    // sqrt r0.y, r0.y
    r0.y = sqrt(r0.y);
    // add r0.z, -r0.y, l(1.000000)
    r0.z = -r0.y + 1.0f;
    // mul_sat r0.x, r0.x, r0.z
    r0.x = saturate(r0.x * r0.z);
    // mad r0.z, -r0.y, l(2.000000), l(1.000000)
    r0.z = -r0.y * 2.0f + 1.0f;
    // mad r0.y, -r0.y, l(1.923077), l(1.000000)
    r0.y = -r0.y * 1.923077f + 1.0f;
    // mul_sat r0.yz, r0.yyzy, l(0.000000, 9.999998, 100.000099, 0.000000)
    float stage2_y = saturate(r0.y * 9.999998f);
    float stage2_z = saturate(r0.z * 100.000099f);
    r0.y = stage2_y;
    r0.z = stage2_z;
    // add r0.xy, -r0.xyxx, r0.zzzz
    float stage3_x = -r0.x + r0.z;
    float stage3_y = -r0.y + r0.z;
    r0.x = stage3_x;
    r0.y = stage3_y;
    // max r0.x, r0.x, l(0.000000)
    r0.x = max(r0.x, 0.0f);
    // log r0.z, r0.x
    r0.z = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, l(1.500000)
    r0.z = r0.z * 1.5f;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // movc r0.x, r0.x, l(0), r0.z
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.z;
    // mad_sat r0.x, r0.y, l(0.300000), r0.x
    r0.x = saturate(r0.y * 0.3f + r0.x);
    // mad r0.xyz, r0.xxxx, v3.xyzx, cb0[1].xyzx
    float stage4_x = r0.x * v3.x + cb0[1].x;
    float stage4_y = r0.x * v3.y + cb0[1].y;
    float stage4_z = r0.x * v3.z + cb0[1].z;
    r0.x = stage4_x;
    r0.y = stage4_y;
    r0.z = stage4_z;
    // mul r0.xyz, r0.xyzx, v5.wwww
    float stage5_x = r0.x * v5.w;
    float stage5_y = r0.y * v5.w;
    float stage5_z = r0.z * v5.w;
    r0.x = stage5_x;
    r0.y = stage5_y;
    r0.z = stage5_z;
    // mul r0.w, v3.w, cb0[0].x
    r0.w = v3.w * cb0[0].x;
    // mul o0.xyz, r0.wwww, r0.xyzx
    float stage6_x = r0.w * r0.x;
    float stage6_y = r0.w * r0.y;
    float stage6_z = r0.w * r0.z;
    o0.x = stage6_x;
    o0.y = stage6_y;
    o0.z = stage6_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_j_pa_circledisort_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
