// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_j_pa_linearwave_02_tr_Constants0 : register(b0)
{
    float4 cb0[33];
};
cbuffer Shade_Ue3_fx_j_pa_linearwave_02_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
SamplerState s5 : register(s5);
SamplerState s6 : register(s6);
SamplerState s7 : register(s7);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);
Texture2D t5 : register(t5);
Texture2D t6 : register(t6);
Texture2D t7 : register(t7);

struct Shade_Ue3_fx_j_pa_linearwave_02_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_j_pa_linearwave_02_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_j_pa_linearwave_02_tr_OUTPUT Shade_Ue3_fx_j_pa_linearwave_02_tr(Shade_Ue3_fx_j_pa_linearwave_02_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mul r0.x, v4.w, cb0[27].w
    r0.x = v4.w * cb0[27].w;
    // add r0.y, v4.y, cb0[26].z
    r0.y = v4.y + cb0[26].z;
    // add r0.zw, v2.xxxy, l(0.000000, 0.000000, -0.500000, -0.500000)
    float stage1_z = v2.x + -0.5f;
    float stage1_w = v2.y + -0.5f;
    r0.z = stage1_z;
    r0.w = stage1_w;
    // mad r1.xy, cb0[25].zzzz, r0.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage2_x = cb0[25].z * r0.z + 0.5f;
    float stage2_y = cb0[25].z * r0.w + 0.5f;
    r1.x = stage2_x;
    r1.y = stage2_y;
    // mad r2.y, r1.y, cb0[26].x, r0.y
    r2.y = r1.y * cb0[26].x + r0.y;
    // mad r2.x, r1.x, cb0[25].w, cb0[26].y
    r2.x = r1.x * cb0[25].w + cb0[26].y;
    // add r1.xy, r2.xyxx, l(-0.500000, -1.500000, 0.000000, 0.000000)
    float stage3_x = r2.x + -0.5f;
    float stage3_y = r2.y + -1.5f;
    r1.x = stage3_x;
    r1.y = stage3_y;
    // dp2 r2.x, cb0[8].xyxx, r1.xyxx
    r2.x = dot(cb0[8].xy, r1.xy);
    // dp2 r2.y, cb0[9].xyxx, r1.xyxx
    r2.y = dot(cb0[9].xy, r1.xy);
    // add r1.xy, r2.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage4_x = r2.x + 0.5f;
    float stage4_y = r2.y + 0.5f;
    r1.x = stage4_x;
    r1.y = stage4_y;
    // dp2 r2.x, cb0[10].xyxx, r0.zwzz
    r2.x = dot(cb0[10].xy, r0.zw);
    // dp2 r2.y, cb0[11].xyxx, r0.zwzz
    r2.y = dot(cb0[11].xy, r0.zw);
    // add r1.zw, r2.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
    float stage5_z = r2.x + 0.5f;
    float stage5_w = r2.y + 0.5f;
    r1.z = stage5_z;
    r1.w = stage5_w;
    // mul r1.zw, r1.zzzw, cb0[27].yyyz
    float stage6_z = r1.z * cb0[27].y;
    float stage6_w = r1.w * cb0[27].z;
    r1.z = stage6_z;
    r1.w = stage6_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.zw, r1.zwzz, t3.zwxy, s6, l(0.000000)
    float4 fetch7 = t3.SampleBias(s6, r1.zw, 0.0f);
    r1.z = fetch7.x;
    r1.w = fetch7.y;
    // mad r0.xy, r0.xxxx, r1.zwzz, r1.xyxx
    float stage8_x = r0.x * r1.z + r1.x;
    float stage8_y = r0.x * r1.w + r1.y;
    r0.x = stage8_x;
    r0.y = stage8_y;
    // dp2 r1.x, cb0[12].xyxx, r0.zwzz
    r1.x = dot(cb0[12].xy, r0.zw);
    // dp2 r1.y, cb0[13].xyxx, r0.zwzz
    r1.y = dot(cb0[13].xy, r0.zw);
    // add r1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage9_x = r1.x + 0.5f;
    float stage9_y = r1.y + 0.5f;
    r1.x = stage9_x;
    r1.y = stage9_y;
    // mul r1.xy, r1.xyxx, cb0[28].zwzz
    float stage10_x = r1.x * cb0[28].z;
    float stage10_y = r1.y * cb0[28].w;
    r1.x = stage10_x;
    r1.y = stage10_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t4.xyzw, s7, l(0.000000)
    float4 fetch11 = t4.SampleBias(s7, r1.xy, 0.0f);
    r1.x = fetch11.x;
    r1.y = fetch11.y;
    // mad r0.xy, cb0[29].xxxx, r1.xyxx, r0.xyxx
    float stage12_x = cb0[29].x * r1.x + r0.x;
    float stage12_y = cb0[29].x * r1.y + r0.y;
    r0.x = stage12_x;
    r0.y = stage12_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t5.xyzw, s5, cb0[24].x
    float4 fetch13 = t5.SampleLevel(s5, r0.xy, cb0[24].x);
    r0.x = fetch13.x;
    // mad r0.x, cb0[29].z, -r0.x, r0.x
    r0.x = cb0[29].z * -r0.x + r0.x;
    // mul r0.x, r0.x, cb0[29].w
    r0.x = r0.x * cb0[29].w;
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // lt r0.x, |r0.x|, l(0.000001)
    r0.x = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.y, r0.y, cb0[30].x
    r0.y = r0.y * cb0[30].x;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // dp2 r1.x, cb0[4].xyxx, r0.zwzz
    r1.x = dot(cb0[4].xy, r0.zw);
    // dp2 r1.y, cb0[5].xyxx, r0.zwzz
    r1.y = dot(cb0[5].xy, r0.zw);
    // add r1.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage14_x = r1.x + 0.5f;
    float stage14_y = r1.y + 0.5f;
    r1.x = stage14_x;
    r1.y = stage14_y;
    // mul r2.x, r1.x, cb0[20].w
    r2.x = r1.x * cb0[20].w;
    // mul r2.y, r1.y, cb0[21].x
    r2.y = r1.y * cb0[21].x;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xy, r2.xyxx, t0.xyzw, s3, l(0.000000)
    float4 fetch15 = t0.SampleBias(s3, r2.xy, 0.0f);
    r1.x = fetch15.x;
    r1.y = fetch15.y;
    // add r0.y, v4.x, cb0[19].x
    r0.y = v4.x + cb0[19].x;
    // mad r1.zw, cb0[18].xxxx, r0.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
    float stage16_z = cb0[18].x * r0.z + 0.5f;
    float stage16_w = cb0[18].x * r0.w + 0.5f;
    r1.z = stage16_z;
    r1.w = stage16_w;
    // mad r2.y, r1.w, cb0[18].z, r0.y
    r2.y = r1.w * cb0[18].z + r0.y;
    // mad r2.x, r1.z, cb0[18].y, cb0[18].w
    r2.x = r1.z * cb0[18].y + cb0[18].w;
    // add r1.zw, r2.xxxy, l(0.000000, 0.000000, -0.500000, -1.500000)
    float stage17_z = r2.x + -0.5f;
    float stage17_w = r2.y + -1.5f;
    r1.z = stage17_z;
    r1.w = stage17_w;
    // dp2 r2.x, cb0[2].xyxx, r1.zwzz
    r2.x = dot(cb0[2].xy, r1.zw);
    // dp2 r2.y, cb0[3].xyxx, r1.zwzz
    r2.y = dot(cb0[3].xy, r1.zw);
    // add r1.zw, r2.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
    float stage18_z = r2.x + 0.5f;
    float stage18_w = r2.y + 0.5f;
    r1.z = stage18_z;
    r1.w = stage18_w;
    // mul r0.y, v4.w, cb0[21].y
    r0.y = v4.w * cb0[21].y;
    // mad r1.xy, r0.yyyy, r1.xyxx, r1.zwzz
    float stage19_x = r0.y * r1.x + r1.z;
    float stage19_y = r0.y * r1.y + r1.w;
    r1.x = stage19_x;
    r1.y = stage19_y;
    // dp2 r2.x, cb0[6].xyxx, r0.zwzz
    r2.x = dot(cb0[6].xy, r0.zw);
    // dp2 r2.y, cb0[7].xyxx, r0.zwzz
    r2.y = dot(cb0[7].xy, r0.zw);
    // dp2 r0.y, r0.zwzz, r0.zwzz
    r0.y = dot(r0.zw, r0.zw);
    // add r0.y, -r0.y, l(1.000000)
    r0.y = -r0.y + 1.0f;
    // add r0.zw, r2.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
    float stage20_z = r2.x + 0.5f;
    float stage20_w = r2.y + 0.5f;
    r0.z = stage20_z;
    r0.w = stage20_w;
    // mul r0.zw, r0.zzzw, cb0[22].xxxy
    float stage21_z = r0.z * cb0[22].x;
    float stage21_w = r0.w * cb0[22].y;
    r0.z = stage21_z;
    r0.w = stage21_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.zw, r0.zwzz, t1.zwxy, s4, l(0.000000)
    float4 fetch22 = t1.SampleBias(s4, r0.zw, 0.0f);
    r0.z = fetch22.x;
    r0.w = fetch22.y;
    // mad r0.zw, cb0[22].zzzz, r0.zzzw, r1.xxxy
    float stage23_z = cb0[22].z * r0.z + r1.x;
    float stage23_w = cb0[22].z * r0.w + r1.y;
    r0.z = stage23_z;
    r0.w = stage23_w;
    // mul r1.x, v4.z, cb0[17].z
    r1.x = v4.z * cb0[17].z;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t2.yzxw, s2, r1.x
    float4 fetch24 = t2.SampleLevel(s2, r0.zw, r1.x);
    r0.z = fetch24.x;
    // mad r0.z, cb0[23].x, -r0.z, r0.z
    r0.z = cb0[23].x * -r0.z + r0.z;
    // mul r0.z, r0.z, cb0[23].y
    r0.z = r0.z * cb0[23].y;
    // lt r0.w, |r0.z|, l(0.000001)
    r0.w = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // log r0.z, |r0.z|
    r0.z = log2(abs(r0.z));
    // mul r0.z, r0.z, cb0[23].z
    r0.z = r0.z * cb0[23].z;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // movc r0.z, r0.w, l(0), r0.z
    r0.z = asuint(r0.w) != 0u ? asfloat(0u) : r0.z;
    // add r0.x, -r0.z, r0.x
    r0.x = -r0.z + r0.x;
    // mad r0.x, cb0[30].y, r0.x, r0.z
    r0.x = cb0[30].y * r0.x + r0.z;
    // log r0.z, |r0.x|
    r0.z = log2(abs(r0.x));
    // mul r0.z, r0.z, cb0[31].x
    r0.z = r0.z * cb0[31].x;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // mul r0.z, r0.z, cb0[31].y
    r0.z = r0.z * cb0[31].y;
    // lt r0.w, |r0.x|, l(0.000001)
    r0.w = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // movc r0.z, r0.w, l(0), r0.z
    r0.z = asuint(r0.w) != 0u ? asfloat(0u) : r0.z;
    // log r0.w, |r0.y|
    r0.w = log2(abs(r0.y));
    // lt r0.y, |r0.y|, l(0.000001)
    r0.y = asfloat((abs(r0.y) < 1e-06f) ? 0xffffffffu : 0u);
    // mad r1.x, cb0[31].z, l(10.000000), l(10.000000)
    r1.x = cb0[31].z * 10.0f + 10.0f;
    // mul r0.w, r0.w, r1.x
    r0.w = r0.w * r1.x;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // mul r0.w, r0.w, cb0[31].w
    r0.w = r0.w * cb0[31].w;
    // movc r0.y, r0.y, l(0), r0.w
    r0.y = asuint(r0.y) != 0u ? asfloat(0u) : r0.w;
    // mul r0.y, r0.z, r0.y
    r0.y = r0.z * r0.y;
    // div r0.zw, v7.xxxy, v7.wwww
    float stage25_z = v7.x / v7.w;
    float stage25_w = v7.y / v7.w;
    r0.z = stage25_z;
    r0.w = stage25_w;
    // mad r0.zw, r0.zzzw, cb2[0].xxxy, cb2[0].wwwz
    float stage26_z = r0.z * cb2[0].x + cb2[0].w;
    float stage26_w = r0.w * cb2[0].y + cb2[0].z;
    r0.z = stage26_z;
    r0.w = stage26_w;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t6.yzxw, s0, l(0.000000)
    float4 fetch27 = t6.SampleLevel(s0, r0.zw, 0.0f);
    r0.z = fetch27.x;
    // min r0.z, r0.z, l(0.999000)
    r0.z = min(r0.z, 0.999f);
    // mad r0.w, r0.z, cb2[1].z, -cb2[1].w
    r0.w = r0.z * cb2[1].z + -cb2[1].w;
    // mad r0.z, r0.z, cb2[1].x, cb2[1].y
    r0.z = r0.z * cb2[1].x + cb2[1].y;
    // div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
    r0.w = 1.0f / r0.w;
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // add r0.z, r0.z, -v7.w
    r0.z = r0.z + -v7.w;
    // add r0.w, -cb0[32].x, l(1.000000)
    r0.w = -cb0[32].x + 1.0f;
    // mul r0.w, r0.w, l(100.000000)
    r0.w = r0.w * 100.0f;
    // max r0.w, r0.w, l(0.001000)
    r0.w = max(r0.w, 0.001f);
    // div_sat r0.z, r0.z, r0.w
    r0.z = saturate(r0.z / r0.w);
    // mul r0.y, r0.z, r0.y
    r0.y = r0.z * r0.y;
    // mul_sat r0.y, r0.y, v3.w
    r0.y = saturate(r0.y * v3.w);
    // mul o0.w, r0.y, cb0[0].x
    o0.w = r0.y * cb0[0].x;
    // mad r1.x, v2.x, cb0[15].x, cb0[16].y
    r1.x = v2.x * cb0[15].x + cb0[16].y;
    // mad r1.y, v2.y, cb0[15].y, cb0[17].x
    r1.y = v2.y * cb0[15].y + cb0[17].x;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.yzw, r1.xyxx, t7.wxyz, s1, l(-1.000000)
    float4 fetch28 = t7.SampleLevel(s1, r1.xy, -1.0f);
    r0.y = fetch28.x;
    r0.z = fetch28.y;
    r0.w = fetch28.z;
    // dp3 r1.x, r0.yzwy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.x = dot(r0.yzw, float3(0.3f, 0.59f, 0.11f));
    // add r1.xyz, -r0.yzwy, r1.xxxx
    float stage29_x = -r0.y + r1.x;
    float stage29_y = -r0.z + r1.x;
    float stage29_z = -r0.w + r1.x;
    r1.x = stage29_x;
    r1.y = stage29_y;
    r1.z = stage29_z;
    // mad r0.yzw, cb0[17].yyyy, r1.xxyz, r0.yyzw
    float stage30_y = cb0[17].y * r1.x + r0.y;
    float stage30_z = cb0[17].y * r1.y + r0.z;
    float stage30_w = cb0[17].y * r1.z + r0.w;
    r0.y = stage30_y;
    r0.z = stage30_z;
    r0.w = stage30_w;
    // mul r0.xyz, r0.yzwy, r0.xxxx
    float stage31_x = r0.y * r0.x;
    float stage31_y = r0.z * r0.x;
    float stage31_z = r0.w * r0.x;
    r0.x = stage31_x;
    r0.y = stage31_y;
    r0.z = stage31_z;
    // mul r0.xyz, r0.xyzx, cb0[30].zzzz
    float stage32_x = r0.x * cb0[30].z;
    float stage32_y = r0.y * cb0[30].z;
    float stage32_z = r0.z * cb0[30].z;
    r0.x = stage32_x;
    r0.y = stage32_y;
    r0.z = stage32_z;
    // max r0.xyz, |r0.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage33_x = max(abs(r0.x), 1e-06f);
    float stage33_y = max(abs(r0.y), 1e-06f);
    float stage33_z = max(abs(r0.z), 1e-06f);
    r0.x = stage33_x;
    r0.y = stage33_y;
    r0.z = stage33_z;
    // log r0.xyz, r0.xyzx
    float stage34_x = log2(r0.x);
    float stage34_y = log2(r0.y);
    float stage34_z = log2(r0.z);
    r0.x = stage34_x;
    r0.y = stage34_y;
    r0.z = stage34_z;
    // mul r0.xyz, r0.xyzx, cb0[30].wwww
    float stage35_x = r0.x * cb0[30].w;
    float stage35_y = r0.y * cb0[30].w;
    float stage35_z = r0.z * cb0[30].w;
    r0.x = stage35_x;
    r0.y = stage35_y;
    r0.z = stage35_z;
    // exp r0.xyz, r0.xyzx
    float stage36_x = exp2(r0.x);
    float stage36_y = exp2(r0.y);
    float stage36_z = exp2(r0.z);
    r0.x = stage36_x;
    r0.y = stage36_y;
    r0.z = stage36_z;
    // mul_sat r0.xyz, r0.xyzx, cb0[14].xyzx
    float stage37_x = saturate(r0.x * cb0[14].x);
    float stage37_y = saturate(r0.y * cb0[14].y);
    float stage37_z = saturate(r0.z * cb0[14].z);
    r0.x = stage37_x;
    r0.y = stage37_y;
    r0.z = stage37_z;
    // mad r0.xyz, r0.xyzx, v3.xyzx, cb0[1].xyzx
    float stage38_x = r0.x * v3.x + cb0[1].x;
    float stage38_y = r0.y * v3.y + cb0[1].y;
    float stage38_z = r0.z * v3.z + cb0[1].z;
    r0.x = stage38_x;
    r0.y = stage38_y;
    r0.z = stage38_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage39_x = r0.x * v5.w + v5.x;
    float stage39_y = r0.y * v5.w + v5.y;
    float stage39_z = r0.z * v5.w + v5.z;
    o0.x = stage39_x;
    o0.y = stage39_y;
    o0.z = stage39_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage40_x = r0.x * v1.x;
    float stage40_y = r0.x * v1.y;
    float stage40_z = r0.x * v1.z;
    r0.x = stage40_x;
    r0.y = stage40_y;
    r0.z = stage40_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage41_x = r0.w * v0.z;
    float stage41_y = r0.w * v0.x;
    float stage41_z = r0.w * v0.y;
    r1.x = stage41_x;
    r1.y = stage41_y;
    r1.z = stage41_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage42_x = r0.x * r1.x;
    float stage42_y = r0.x * r1.y;
    float stage42_z = r0.x * r1.z;
    r0.x = stage42_x;
    r0.y = stage42_y;
    r0.z = stage42_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage43_x = r0.x / r0.w;
    float stage43_y = r0.y / r0.w;
    r0.x = stage43_x;
    r0.y = stage43_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage44_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage44_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage44_x;
    r1.y = stage44_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage45_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage45_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage45_x;
    r1.y = stage45_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage46_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage46_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage46_x;
    r1.y = stage46_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage47_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage47_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage47_x;
    r0.y = stage47_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage48_x = r0.x * 0.5f + 0.5f;
    float stage48_y = r0.y * 0.5f + 0.5f;
    o2.x = stage48_x;
    o2.y = stage48_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage49_z = 1.0f;
    float stage49_w = asfloat(0u);
    o2.z = stage49_z;
    o2.w = stage49_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage50_x = cb2[3].x;
    float stage50_y = cb2[3].y;
    float stage50_z = cb2[3].z;
    o3.x = stage50_x;
    o3.y = stage50_y;
    o3.z = stage50_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage51_x = asfloat(0u);
    float stage51_y = asfloat(0u);
    float stage51_z = asfloat(0u);
    float stage51_w = asfloat(0u);
    o4.x = stage51_x;
    o4.y = stage51_y;
    o4.z = stage51_z;
    o4.w = stage51_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage52_x = asfloat(0u);
    float stage52_y = asfloat(0u);
    float stage52_z = asfloat(0u);
    float stage52_w = asfloat(0u);
    o5.x = stage52_x;
    o5.y = stage52_y;
    o5.z = stage52_z;
    o5.w = stage52_w;

    Shade_Ue3_fx_j_pa_linearwave_02_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
