// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_k_crackholev2_01_Constants0 : register(b0)
{
    float4 cb0[19];
};
cbuffer Shade_Ue3_fx_k_crackholev2_01_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
SamplerState s5 : register(s5);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);
Texture2D t5 : register(t5);

struct Shade_Ue3_fx_k_crackholev2_01_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
    float4 v6;
};

struct Shade_Ue3_fx_k_crackholev2_01_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_k_crackholev2_01_OUTPUT Shade_Ue3_fx_k_crackholev2_01(Shade_Ue3_fx_k_crackholev2_01_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v6 = stage.v6;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // dp3 r0.x, v6.xyzx, v6.xyzx
    r0.x = dot(v6.xyz, v6.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xy, r0.xxxx, v6.xyxx
    float stage1_x = r0.x * v6.x;
    float stage1_y = r0.x * v6.y;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // add r0.zw, v2.xxxy, cb0[6].xxxy
    float stage2_z = v2.x + cb0[6].x;
    float stage2_w = v2.y + cb0[6].y;
    r0.z = stage2_z;
    r0.w = stage2_w;
    // mul r1.x, v4.x, cb0[14].x
    r1.x = v4.x * cb0[14].x;
    // mad r1.y, r1.x, l(0.050000), l(-0.025000)
    r1.y = r1.x * 0.05f + -0.025f;
    // mul r1.x, r1.x, l(0.040000)
    r1.x = r1.x * 0.04f;
    // add r1.x, |r1.x|, cb0[14].y
    r1.x = abs(r1.x) + cb0[14].y;
    // add r1.x, r1.x, l(0.500000)
    r1.x = r1.x + 0.5f;
    // max r1.x, r1.x, l(0.000010)
    r1.x = max(r1.x, 1e-05f);
    // div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
    r1.x = 1.0f / r1.x;
    // mad r0.zw, r1.yyyy, r0.xxxy, r0.zzzw
    float stage3_z = r1.y * r0.x + r0.z;
    float stage3_w = r1.y * r0.y + r0.w;
    r0.z = stage3_z;
    r0.w = stage3_w;
    // add r0.zw, r0.zzzw, l(0.000000, 0.000000, -0.500000, -0.500000)
    float stage4_z = r0.z + -0.5f;
    float stage4_w = r0.w + -0.5f;
    r0.z = stage4_z;
    r0.w = stage4_w;
    // max r1.y, |r0.w|, |r0.z|
    r1.y = max(abs(r0.w), abs(r0.z));
    // div r1.y, l(1.000000, 1.000000, 1.000000, 1.000000), r1.y
    r1.y = 1.0f / r1.y;
    // min r1.z, |r0.w|, |r0.z|
    r1.z = min(abs(r0.w), abs(r0.z));
    // mul r1.y, r1.y, r1.z
    r1.y = r1.y * r1.z;
    // mul r1.z, r1.y, r1.y
    r1.z = r1.y * r1.y;
    // mad r1.w, r1.z, l(0.020835), l(-0.085133)
    r1.w = r1.z * 0.020835f + -0.085133f;
    // mad r1.w, r1.z, r1.w, l(0.180141)
    r1.w = r1.z * r1.w + 0.180141f;
    // mad r1.w, r1.z, r1.w, l(-0.330299)
    r1.w = r1.z * r1.w + -0.330299f;
    // mad r1.z, r1.z, r1.w, l(0.999866)
    r1.z = r1.z * r1.w + 0.999866f;
    // mul r1.w, r1.z, r1.y
    r1.w = r1.z * r1.y;
    // mad r1.w, r1.w, l(-2.000000), l(1.570796)
    r1.w = r1.w * -2.0f + 1.570796f;
    // lt r2.x, |r0.w|, |r0.z|
    r2.x = asfloat((abs(r0.w) < abs(r0.z)) ? 0xffffffffu : 0u);
    // and r1.w, r1.w, r2.x
    r1.w = asfloat(asuint(r1.w) & asuint(r2.x));
    // mad r1.y, r1.y, r1.z, r1.w
    r1.y = r1.y * r1.z + r1.w;
    // lt r1.z, r0.w, -r0.w
    r1.z = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // and r1.z, r1.z, l(0xc0490fdb)
    r1.z = asfloat(asuint(r1.z) & asuint(-3.1415927410125732f));
    // add r1.y, r1.z, r1.y
    r1.y = r1.z + r1.y;
    // min r1.z, r0.w, r0.z
    r1.z = min(r0.w, r0.z);
    // lt r1.z, r1.z, -r1.z
    r1.z = asfloat((r1.z < -r1.z) ? 0xffffffffu : 0u);
    // max r1.w, r0.w, r0.z
    r1.w = max(r0.w, r0.z);
    // dp2 r0.z, r0.zwzz, r0.zwzz
    r0.z = dot(r0.zw, r0.zw);
    // sqrt r0.z, r0.z
    r0.z = sqrt(r0.z);
    // mad r0.z, -r0.z, r1.x, l(1.000000)
    r0.z = -r0.z * r1.x + 1.0f;
    // max r0.z, r0.z, l(0.000000)
    r0.z = max(r0.z, 0.0f);
    // add r0.z, -r0.z, l(1.000000)
    r0.z = -r0.z + 1.0f;
    // ge r0.w, r1.w, -r1.w
    r0.w = asfloat((r1.w >= -r1.w) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, r1.z
    r0.w = asfloat(asuint(r0.w) & asuint(r1.z));
    // movc r0.w, r0.w, -r1.y, r1.y
    r0.w = asuint(r0.w) != 0u ? -r1.y : r1.y;
    // mad r0.w, r0.w, l(0.318310), l(1.000000)
    r0.w = r0.w * 0.31831f + 1.0f;
    // mul r1.x, r0.w, l(0.500000)
    r1.x = r0.w * 0.5f;
    // log r0.w, r0.z
    r0.w = log2(r0.z);
    // lt r0.z, r0.z, l(0.000001)
    r0.z = asfloat((r0.z < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.z, r0.w, cb0[14].z
    r1.z = r0.w * cb0[14].z;
    // mul r0.w, r0.w, cb0[17].z
    r0.w = r0.w * cb0[17].z;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // mul_sat r0.w, r0.w, cb0[17].w
    r0.w = saturate(r0.w * cb0[17].w);
    // movc r0.w, r0.z, l(0), r0.w
    r0.w = asuint(r0.z) != 0u ? asfloat(0u) : r0.w;
    // exp r1.z, r1.z
    r1.z = exp2(r1.z);
    // min r1.z, r1.z, l(1.000000)
    r1.z = min(r1.z, 1.0f);
    // movc r1.y, r0.z, l(0), r1.z
    r1.y = asuint(r0.z) != 0u ? asfloat(0u) : r1.z;
    // mul r1.zw, r1.xxxy, cb0[13].xxxy
    float stage5_z = r1.x * cb0[13].x;
    float stage5_w = r1.y * cb0[13].y;
    r1.z = stage5_z;
    r1.w = stage5_w;
    // mad r2.x, cb0[9].z, cb0[12].w, r1.z
    r2.x = cb0[9].z * cb0[12].w + r1.z;
    // mad r2.y, cb0[9].z, cb0[14].w, r1.w
    r2.y = cb0[9].z * cb0[14].w + r1.w;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.z, r2.xyxx, t3.yzxw, s4, l(0.000000)
    float4 fetch6 = t3.SampleLevel(s4, r2.xy, 0.0f);
    r0.z = fetch6.x;
    // mul r1.z, v4.z, cb0[15].x
    r1.z = v4.z * cb0[15].x;
    // mad r1.xy, r0.zzzz, r1.zzzz, r1.xyxx
    float stage7_x = r0.z * r1.z + r1.x;
    float stage7_y = r0.z * r1.z + r1.y;
    r1.x = stage7_x;
    r1.y = stage7_y;
    // mul r0.z, cb0[9].z, cb0[15].z
    r0.z = cb0[9].z * cb0[15].z;
    // mad r2.x, cb0[15].w, r1.x, r0.z
    r2.x = cb0[15].w * r1.x + r0.z;
    // mul r0.z, r1.y, cb0[16].x
    r0.z = r1.y * cb0[16].x;
    // mul r1.xy, r1.xyxx, cb0[12].yzyy
    float stage8_x = r1.x * cb0[12].y;
    float stage8_y = r1.y * cb0[12].z;
    r1.x = stage8_x;
    r1.y = stage8_y;
    // mad r2.y, cb0[9].z, cb0[16].y, r0.z
    r2.y = cb0[9].z * cb0[16].y + r0.z;
    // sample_l_indexable(texture2d)(float,float,float,float) r2.xyz, r2.xyxx, t5.xyzw, s5, l(0.000000)
    float4 fetch9 = t5.SampleLevel(s5, r2.xy, 0.0f);
    r2.x = fetch9.x;
    r2.y = fetch9.y;
    r2.z = fetch9.z;
    // mad r3.x, cb0[9].z, cb0[12].x, r1.x
    r3.x = cb0[9].z * cb0[12].x + r1.x;
    // mad r3.y, cb0[9].z, cb0[15].y, r1.y
    r3.y = cb0[9].z * cb0[15].y + r1.y;
    // sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, r3.xyxx, t4.xyzw, s3, l(0.000000)
    float4 fetch10 = t4.SampleLevel(s3, r3.xy, 0.0f);
    r1.x = fetch10.x;
    r1.y = fetch10.y;
    r1.z = fetch10.z;
    // mul r3.xyz, r2.xyzx, r1.xyzx
    float stage11_x = r2.x * r1.x;
    float stage11_y = r2.y * r1.y;
    float stage11_z = r2.z * r1.z;
    r3.x = stage11_x;
    r3.y = stage11_y;
    r3.z = stage11_z;
    // dp3 r0.z, r3.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.z = dot(r3.xyz, float3(0.3f, 0.59f, 0.11f));
    // mad r1.xyz, -r1.xyzx, r2.xyzx, r0.zzzz
    float stage12_x = -r1.x * r2.x + r0.z;
    float stage12_y = -r1.y * r2.y + r0.z;
    float stage12_z = -r1.z * r2.z + r0.z;
    r1.x = stage12_x;
    r1.y = stage12_y;
    r1.z = stage12_z;
    // mad r1.xyz, cb0[16].zzzz, r1.xyzx, r3.xyzx
    float stage13_x = cb0[16].z * r1.x + r3.x;
    float stage13_y = cb0[16].z * r1.y + r3.y;
    float stage13_z = cb0[16].z * r1.z + r3.z;
    r1.x = stage13_x;
    r1.y = stage13_y;
    r1.z = stage13_z;
    // max r2.xyz, |r1.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage14_x = max(abs(r1.x), 1e-06f);
    float stage14_y = max(abs(r1.y), 1e-06f);
    float stage14_z = max(abs(r1.z), 1e-06f);
    r2.x = stage14_x;
    r2.y = stage14_y;
    r2.z = stage14_z;
    // mul_sat r1.xyz, r1.xyzx, cb0[16].wwww
    float stage15_x = saturate(r1.x * cb0[16].w);
    float stage15_y = saturate(r1.y * cb0[16].w);
    float stage15_z = saturate(r1.z * cb0[16].w);
    r1.x = stage15_x;
    r1.y = stage15_y;
    r1.z = stage15_z;
    // log r2.xyz, r2.xyzx
    float stage16_x = log2(r2.x);
    float stage16_y = log2(r2.y);
    float stage16_z = log2(r2.z);
    r2.x = stage16_x;
    r2.y = stage16_y;
    r2.z = stage16_z;
    // mul r2.xyz, r2.xyzx, cb0[17].xxxx
    float stage17_x = r2.x * cb0[17].x;
    float stage17_y = r2.y * cb0[17].x;
    float stage17_z = r2.z * cb0[17].x;
    r2.x = stage17_x;
    r2.y = stage17_y;
    r2.z = stage17_z;
    // exp r2.xyz, r2.xyzx
    float stage18_x = exp2(r2.x);
    float stage18_y = exp2(r2.y);
    float stage18_z = exp2(r2.z);
    r2.x = stage18_x;
    r2.y = stage18_y;
    r2.z = stage18_z;
    // mul r2.xyz, r2.xyzx, cb0[17].yyyy
    float stage19_x = r2.x * cb0[17].y;
    float stage19_y = r2.y * cb0[17].y;
    float stage19_z = r2.z * cb0[17].y;
    r2.x = stage19_x;
    r2.y = stage19_y;
    r2.z = stage19_z;
    // mul r2.xyz, r0.wwww, r2.xyzx
    float stage20_x = r0.w * r2.x;
    float stage20_y = r0.w * r2.y;
    float stage20_z = r0.w * r2.z;
    r2.x = stage20_x;
    r2.y = stage20_y;
    r2.z = stage20_z;
    // mul r3.xyz, cb0[7].xyzx, cb0[7].wwww
    float stage21_x = cb0[7].x * cb0[7].w;
    float stage21_y = cb0[7].y * cb0[7].w;
    float stage21_z = cb0[7].z * cb0[7].w;
    r3.x = stage21_x;
    r3.y = stage21_y;
    r3.z = stage21_z;
    // mul r4.xyz, cb0[8].xyzx, cb0[8].wwww
    float stage22_x = cb0[8].x * cb0[8].w;
    float stage22_y = cb0[8].y * cb0[8].w;
    float stage22_z = cb0[8].z * cb0[8].w;
    r4.x = stage22_x;
    r4.y = stage22_y;
    r4.z = stage22_z;
    // mad r2.xyz, r2.xyzx, r3.xyzx, r4.xyzx
    float stage23_x = r2.x * r3.x + r4.x;
    float stage23_y = r2.y * r3.y + r4.y;
    float stage23_z = r2.z * r3.z + r4.z;
    r2.x = stage23_x;
    r2.y = stage23_y;
    r2.z = stage23_z;
    // mul r2.xyz, r2.xyzx, v3.xyzx
    float stage24_x = r2.x * v3.x;
    float stage24_y = r2.y * v3.y;
    float stage24_z = r2.z * v3.z;
    r2.x = stage24_x;
    r2.y = stage24_y;
    r2.z = stage24_z;
    // mad r0.z, cb0[18].y, l(0.050000), l(-0.050000)
    r0.z = cb0[18].y * 0.05f + -0.05f;
    // mad r0.xy, r0.zzzz, r0.xyxx, v2.xyxx
    float stage25_x = r0.z * r0.x + v2.x;
    float stage25_y = r0.z * r0.y + v2.y;
    r0.x = stage25_x;
    r0.y = stage25_y;
    // mad r0.zw, v2.xxxy, cb0[3].xxxy, cb0[5].xxxy
    float stage26_z = v2.x * cb0[3].x + cb0[5].x;
    float stage26_w = v2.y * cb0[3].y + cb0[5].y;
    r0.z = stage26_z;
    r0.w = stage26_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t0.yzxw, s0, l(0.000000)
    float4 fetch27 = t0.SampleBias(s0, r0.zw, 0.0f);
    r0.z = fetch27.x;
    // mul r0.z, r0.z, cb0[10].z
    r0.z = r0.z * cb0[10].z;
    // mad r3.xy, v2.xyxx, cb0[3].xyxx, cb0[4].xyxx
    float stage28_x = v2.x * cb0[3].x + cb0[4].x;
    float stage28_y = v2.y * cb0[3].y + cb0[4].y;
    r3.x = stage28_x;
    r3.y = stage28_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.w, r3.xyxx, t0.yzwx, s0, l(0.000000)
    float4 fetch29 = t0.SampleBias(s0, r3.xy, 0.0f);
    r0.w = fetch29.x;
    // mad r0.z, r0.w, cb0[10].z, r0.z
    r0.z = r0.w * cb0[10].z + r0.z;
    // mad r0.zw, r0.zzzz, l(0.000000, 0.000000, 0.100000, -0.100000), cb0[11].wwww
    float stage30_z = r0.z * 0.1f + cb0[11].w;
    float stage30_w = r0.z * -0.1f + cb0[11].w;
    r0.z = stage30_z;
    r0.w = stage30_w;
    // add r0.xy, r0.zwzz, r0.xyxx
    float stage31_x = r0.z + r0.x;
    float stage31_y = r0.w + r0.y;
    r0.x = stage31_x;
    r0.y = stage31_y;
    // add r0.zw, r0.zzzw, v2.xxxy
    float stage32_z = r0.z + v2.x;
    float stage32_w = r0.w + v2.y;
    r0.z = stage32_z;
    r0.w = stage32_w;
    // add r1.w, v4.y, cb0[18].x
    r1.w = v4.y + cb0[18].x;
    // mul r3.xy, r1.wwww, l(0.200000, -0.200000, 0.000000, 0.000000)
    float stage33_x = r1.w * 0.2f;
    float stage33_y = r1.w * -0.2f;
    r3.x = stage33_x;
    r3.y = stage33_y;
    // mov r3.z, l(0)
    r3.z = asfloat(0u);
    // add r3.xyzw, r0.xyxy, r3.xzyz
    float stage34_x = r0.x + r3.x;
    float stage34_y = r0.y + r3.z;
    float stage34_z = r0.x + r3.y;
    float stage34_w = r0.y + r3.z;
    r3.x = stage34_x;
    r3.y = stage34_y;
    r3.z = stage34_z;
    r3.w = stage34_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r3.xyxx, t1.xyzw, s1, l(0.000000)
    float4 fetch35 = t1.SampleBias(s1, r3.xy, 0.0f);
    r0.x = fetch35.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r3.zwzz, t2.yxzw, s2, l(0.000000)
    float4 fetch36 = t2.SampleBias(s2, r3.zw, 0.0f);
    r0.y = fetch36.x;
    // mul r0.x, r0.y, r0.x
    r0.x = r0.y * r0.x;
    // mad r3.xz, v4.yyyy, l(0.200000, 0.000000, -0.200000, 0.000000), l(-0.080000, 0.000000, 0.080000, 0.000000)
    float stage37_x = v4.y * 0.2f + -0.08f;
    float stage37_z = v4.y * -0.2f + 0.08f;
    r3.x = stage37_x;
    r3.z = stage37_z;
    // mov r3.yw, l(0,0,0,0)
    float stage38_y = asfloat(0u);
    float stage38_w = asfloat(0u);
    r3.y = stage38_y;
    r3.w = stage38_w;
    // add r3.xyzw, r0.zwzw, r3.xyzw
    float stage39_x = r0.z + r3.x;
    float stage39_y = r0.w + r3.y;
    float stage39_z = r0.z + r3.z;
    float stage39_w = r0.w + r3.w;
    r3.x = stage39_x;
    r3.y = stage39_y;
    r3.z = stage39_z;
    r3.w = stage39_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r3.xyxx, t1.yxzw, s1, l(0.000000)
    float4 fetch40 = t1.SampleBias(s1, r3.xy, 0.0f);
    r0.y = fetch40.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.w, r3.zwzz, t2.yzwx, s2, l(0.000000)
    float4 fetch41 = t2.SampleBias(s2, r3.zw, 0.0f);
    r1.w = fetch41.x;
    // mul r0.y, r0.y, r1.w
    r0.y = r0.y * r1.w;
    // mul_sat r1.w, r0.y, v3.w
    r1.w = saturate(r0.y * v3.w);
    // mul r0.x, r0.x, r1.w
    r0.x = r0.x * r1.w;
    // mul o0.w, r1.w, cb0[0].x
    o0.w = r1.w * cb0[0].x;
    // mul r2.xyz, r0.xxxx, r2.xyzx
    float stage42_x = r0.x * r2.x;
    float stage42_y = r0.x * r2.y;
    float stage42_z = r0.x * r2.z;
    r2.x = stage42_x;
    r2.y = stage42_y;
    r2.z = stage42_z;
    // add r0.x, v4.y, -cb0[9].x
    r0.x = v4.y + -cb0[9].x;
    // add r0.x, r0.x, l(-0.400000)
    r0.x = r0.x + -0.4f;
    // mul r3.xy, r0.xxxx, l(0.200000, -0.200000, 0.000000, 0.000000)
    float stage43_x = r0.x * 0.2f;
    float stage43_y = r0.x * -0.2f;
    r3.x = stage43_x;
    r3.y = stage43_y;
    // mov r3.z, l(0)
    r3.z = asfloat(0u);
    // add r3.xyzw, r0.zwzw, r3.xzyz
    float stage44_x = r0.z + r3.x;
    float stage44_y = r0.w + r3.z;
    float stage44_z = r0.z + r3.y;
    float stage44_w = r0.w + r3.z;
    r3.x = stage44_x;
    r3.y = stage44_y;
    r3.z = stage44_z;
    r3.w = stage44_w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.x, r3.xyxx, t1.xyzw, s1, l(0.000000)
    float4 fetch45 = t1.SampleBias(s1, r3.xy, 0.0f);
    r0.x = fetch45.x;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r3.zwzz, t2.yzxw, s2, l(0.000000)
    float4 fetch46 = t2.SampleBias(s2, r3.zw, 0.0f);
    r0.z = fetch46.x;
    // mad r0.x, -r0.x, r0.z, l(1.000000)
    r0.x = -r0.x * r0.z + 1.0f;
    // mul r0.x, r0.y, r0.x
    r0.x = r0.y * r0.x;
    // mul r0.xyz, r1.xyzx, r0.xxxx
    float stage47_x = r1.x * r0.x;
    float stage47_y = r1.y * r0.x;
    float stage47_z = r1.z * r0.x;
    r0.x = stage47_x;
    r0.y = stage47_y;
    r0.z = stage47_z;
    // mad r0.xyz, cb0[2].xyzx, r0.xyzx, r2.xyzx
    float stage48_x = cb0[2].x * r0.x + r2.x;
    float stage48_y = cb0[2].y * r0.y + r2.y;
    float stage48_z = cb0[2].z * r0.z + r2.z;
    r0.x = stage48_x;
    r0.y = stage48_y;
    r0.z = stage48_z;
    // add r0.xyz, r0.xyzx, cb0[1].xyzx
    float stage49_x = r0.x + cb0[1].x;
    float stage49_y = r0.y + cb0[1].y;
    float stage49_z = r0.z + cb0[1].z;
    r0.x = stage49_x;
    r0.y = stage49_y;
    r0.z = stage49_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage50_x = r0.x * v5.w + v5.x;
    float stage50_y = r0.y * v5.w + v5.y;
    float stage50_z = r0.z * v5.w + v5.z;
    o0.x = stage50_x;
    o0.y = stage50_y;
    o0.z = stage50_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage51_x = r0.x * v1.x;
    float stage51_y = r0.x * v1.y;
    float stage51_z = r0.x * v1.z;
    r0.x = stage51_x;
    r0.y = stage51_y;
    r0.z = stage51_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage52_x = r0.w * v0.z;
    float stage52_y = r0.w * v0.x;
    float stage52_z = r0.w * v0.y;
    r1.x = stage52_x;
    r1.y = stage52_y;
    r1.z = stage52_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage53_x = r0.x * r1.x;
    float stage53_y = r0.x * r1.y;
    float stage53_z = r0.x * r1.z;
    r0.x = stage53_x;
    r0.y = stage53_y;
    r0.z = stage53_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage54_x = r0.x / r0.w;
    float stage54_y = r0.y / r0.w;
    r0.x = stage54_x;
    r0.y = stage54_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage55_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage55_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage55_x;
    r1.y = stage55_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage56_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage56_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage56_x;
    r1.y = stage56_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage57_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage57_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage57_x;
    r1.y = stage57_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage58_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage58_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage58_x;
    r0.y = stage58_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage59_x = r0.x * 0.5f + 0.5f;
    float stage59_y = r0.y * 0.5f + 0.5f;
    o2.x = stage59_x;
    o2.y = stage59_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage60_z = 1.0f;
    float stage60_w = asfloat(0u);
    o2.z = stage60_z;
    o2.w = stage60_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage61_x = cb2[3].x;
    float stage61_y = cb2[3].y;
    float stage61_z = cb2[3].z;
    o3.x = stage61_x;
    o3.y = stage61_y;
    o3.z = stage61_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage62_x = asfloat(0u);
    float stage62_y = asfloat(0u);
    float stage62_z = asfloat(0u);
    float stage62_w = asfloat(0u);
    o4.x = stage62_x;
    o4.y = stage62_y;
    o4.z = stage62_z;
    o4.w = stage62_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage63_x = asfloat(0u);
    float stage63_y = asfloat(0u);
    float stage63_z = asfloat(0u);
    float stage63_w = asfloat(0u);
    o5.x = stage63_x;
    o5.y = stage63_y;
    o5.z = stage63_z;
    o5.w = stage63_w;

    Shade_Ue3_fx_k_crackholev2_01_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
