// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_a_me_panning_01_ts_ad_Constants0 : register(b0)
{
    float4 cb0[4];
};
cbuffer Shade_Ue3_fx_a_me_panning_01_ts_ad_Constants2 : register(b2)
{
    float4 cb2[2];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);

struct Shade_Ue3_fx_a_me_panning_01_ts_ad_INPUT
{
    float4 v4;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_a_me_panning_01_ts_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_a_me_panning_01_ts_ad_OUTPUT Shade_Ue3_fx_a_me_panning_01_ts_ad(Shade_Ue3_fx_a_me_panning_01_ts_ad_INPUT stage)
{
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;

    // div r0.xy, v7.xyxx, v7.wwww
    float stage1_x = v7.x / v7.w;
    float stage1_y = v7.y / v7.w;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // mad r0.xy, r0.xyxx, cb2[0].xyxx, cb2[0].wzww
    float stage2_x = r0.x * cb2[0].x + cb2[0].w;
    float stage2_y = r0.y * cb2[0].y + cb2[0].z;
    r0.x = stage2_x;
    r0.y = stage2_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t2.xyzw, s0, l(0.000000)
    float4 fetch3 = t2.SampleLevel(s0, r0.xy, 0.0f);
    r0.x = fetch3.x;
    // min r0.x, r0.x, l(0.999000)
    r0.x = min(r0.x, 0.999f);
    // mad r0.y, r0.x, cb2[1].z, -cb2[1].w
    r0.y = r0.x * cb2[1].z + -cb2[1].w;
    // mad r0.x, r0.x, cb2[1].x, cb2[1].y
    r0.x = r0.x * cb2[1].x + cb2[1].y;
    // div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
    r0.y = 1.0f / r0.y;
    // add r0.x, r0.y, r0.x
    r0.x = r0.y + r0.x;
    // add r0.x, r0.x, -v7.w
    r0.x = r0.x + -v7.w;
    // mul_sat r0.x, r0.x, l(0.034483)
    r0.x = saturate(r0.x * 0.034483f);
    // mov r0.y, v4.y
    r0.y = v4.y;
    // add r1.y, r0.y, cb0[3].x
    r1.y = r0.y + cb0[3].x;
    // mul r1.x, v4.x, cb0[3].y
    r1.x = v4.x * cb0[3].y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r1.xyxx, t0.yxzw, s1, l(0.000000)
    float4 fetch4 = t0.SampleBias(s1, r1.xy, 0.0f);
    r0.y = fetch4.x;
    // mul r0.y, r0.y, cb0[1].w
    r0.y = r0.y * cb0[1].w;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, v4.xyxx, t1.yzxw, s2, l(0.000000)
    float4 fetch5 = t1.SampleBias(s2, v4.xy, 0.0f);
    r0.z = fetch5.x;
    // mul_sat r0.y, r0.z, r0.y
    r0.y = saturate(r0.z * r0.y);
    // mul r0.x, r0.x, r0.y
    r0.x = r0.x * r0.y;
    // mul r0.x, r0.x, cb0[0].x
    r0.x = r0.x * cb0[0].x;
    // add r0.yzw, cb0[1].xxyz, cb0[2].xxyz
    float stage6_y = cb0[1].x + cb0[2].x;
    float stage6_z = cb0[1].y + cb0[2].y;
    float stage6_w = cb0[1].z + cb0[2].z;
    r0.y = stage6_y;
    r0.z = stage6_z;
    r0.w = stage6_w;
    // mul r0.yzw, r0.yyzw, v5.wwww
    float stage7_y = r0.y * v5.w;
    float stage7_z = r0.z * v5.w;
    float stage7_w = r0.w * v5.w;
    r0.y = stage7_y;
    r0.z = stage7_z;
    r0.w = stage7_w;
    // mul o0.xyz, r0.xxxx, r0.yzwy
    float stage8_x = r0.x * r0.y;
    float stage8_y = r0.x * r0.z;
    float stage8_z = r0.x * r0.w;
    o0.x = stage8_x;
    o0.y = stage8_y;
    o0.z = stage8_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_a_me_panning_01_ts_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
