// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_n_pa_ring_07_ad_Constants0 : register(b0)
{
    float4 cb0[6];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);

struct Shade_Ue3_fx_n_pa_ring_07_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_n_pa_ring_07_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_n_pa_ring_07_ad_OUTPUT Shade_Ue3_fx_n_pa_ring_07_ad(Shade_Ue3_fx_n_pa_ring_07_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;

    // add r0.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.x + -0.5f;
    float stage1_y = v2.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.y|, |r0.x|
    r0.z = max(abs(r0.y), abs(r0.x));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.y|, |r0.x|
    r0.w = min(abs(r0.y), abs(r0.x));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.y|, |r0.x|
    r1.y = asfloat((abs(r0.y) < abs(r0.x)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.y, -r0.y
    r0.w = asfloat((r0.y < -r0.y) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.y, r0.x
    r0.w = min(r0.y, r0.x);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.y, r0.x
    r1.x = max(r0.y, r0.x);
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // add r0.x, r0.x, r0.x
    r0.x = r0.x + r0.x;
    // min r0.x, r0.x, l(1.000000)
    r0.x = min(r0.x, 1.0f);
    // ge r0.y, r1.x, -r1.x
    r0.y = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.y, r0.y, r0.w
    r0.y = asfloat(asuint(r0.y) & asuint(r0.w));
    // movc r0.y, r0.y, -r0.z, r0.z
    r0.y = asuint(r0.y) != 0u ? -r0.z : r0.z;
    // mad r0.y, r0.y, l(0.159155), l(0.500000)
    r0.y = r0.y * 0.159155f + 0.5f;
    // mul r0.y, r0.y, cb0[2].w
    r0.y = r0.y * cb0[2].w;
    // mad r1.x, cb0[2].z, cb0[2].y, r0.y
    r1.x = cb0[2].z * cb0[2].y + r0.y;
    // mul r0.y, v2.y, cb0[4].x
    r0.y = v2.y * cb0[4].x;
    // mad r2.y, cb0[2].z, cb0[4].y, r0.y
    r2.y = cb0[2].z * cb0[4].y + r0.y;
    // mul r0.yz, cb0[2].zzzz, cb0[3].yyzy
    float stage2_y = cb0[2].z * cb0[3].y;
    float stage2_z = cb0[2].z * cb0[3].z;
    r0.y = stage2_y;
    r0.z = stage2_z;
    // mad r2.x, cb0[3].w, v2.x, r0.z
    r2.x = cb0[3].w * v2.x + r0.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.z, r2.xyxx, t0.yzxw, s1, l(0.000000)
    float4 fetch3 = t0.SampleBias(s1, r2.xy, 0.0f);
    r0.z = fetch3.x;
    // log r0.w, r0.x
    r0.w = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.w, r0.w, v4.z
    r0.w = r0.w * v4.z;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // movc r0.x, r0.x, l(0), r0.w
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.w;
    // mad r1.y, cb0[3].x, r0.x, r0.y
    r1.y = cb0[3].x * r0.x + r0.y;
    // mul r0.x, v4.x, cb0[4].z
    r0.x = v4.x * cb0[4].z;
    // mad r0.yw, r0.zzzz, r0.xxxx, r1.xxxy
    float stage4_y = r0.z * r0.x + r1.x;
    float stage4_w = r0.z * r0.x + r1.y;
    r0.y = stage4_y;
    r0.w = stage4_w;
    // mad r0.xz, r0.zzzz, r0.xxxx, v2.xxyx
    float stage5_x = r0.z * r0.x + v2.x;
    float stage5_z = r0.z * r0.x + v2.y;
    r0.x = stage5_x;
    r0.z = stage5_z;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xzxx, t2.xyzw, s2, cb0[2].x
    float4 fetch6 = t2.SampleLevel(s2, r0.xz, cb0[2].x);
    r0.x = fetch6.x;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.yzw, r0.ywyy, t1.wxyz, s0, cb0[2].x
    float4 fetch7 = t1.SampleLevel(s0, r0.yw, cb0[2].x);
    r0.y = fetch7.x;
    r0.z = fetch7.y;
    r0.w = fetch7.z;
    // mul_sat r1.x, r0.y, cb0[5].x
    r1.x = saturate(r0.y * cb0[5].x);
    // mov_sat r1.y, v4.y
    r1.y = saturate(v4.y);
    // add r1.y, -r1.y, l(1.000000)
    r1.y = -r1.y + 1.0f;
    // add r1.x, -r1.y, r1.x
    r1.x = -r1.y + r1.x;
    // max r1.x, r1.x, l(0.000000)
    r1.x = max(r1.x, 0.0f);
    // mul_sat r0.x, r0.x, r1.x
    r0.x = saturate(r0.x * r1.x);
    // log r1.x, r0.x
    r1.x = log2(r0.x);
    // lt r0.x, r0.x, l(0.000001)
    r0.x = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.x, r1.x, cb0[5].y
    r1.x = r1.x * cb0[5].y;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // mul_sat r1.x, r1.x, v3.w
    r1.x = saturate(r1.x * v3.w);
    // mul r1.x, r1.x, cb0[0].x
    r1.x = r1.x * cb0[0].x;
    // movc r0.x, r0.x, l(0), r1.x
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r1.x;
    // dp3 r1.x, r0.yzwy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.x = dot(r0.yzw, float3(0.3f, 0.59f, 0.11f));
    // add r1.xyz, -r0.yzwy, r1.xxxx
    float stage8_x = -r0.y + r1.x;
    float stage8_y = -r0.z + r1.x;
    float stage8_z = -r0.w + r1.x;
    r1.x = stage8_x;
    r1.y = stage8_y;
    r1.z = stage8_z;
    // mad r0.yzw, cb0[4].wwww, r1.xxyz, r0.yyzw
    float stage9_y = cb0[4].w * r1.x + r0.y;
    float stage9_z = cb0[4].w * r1.y + r0.z;
    float stage9_w = cb0[4].w * r1.z + r0.w;
    r0.y = stage9_y;
    r0.z = stage9_z;
    r0.w = stage9_w;
    // mad r0.yzw, r0.yyzw, v3.xxyz, cb0[1].xxyz
    float stage10_y = r0.y * v3.x + cb0[1].x;
    float stage10_z = r0.z * v3.y + cb0[1].y;
    float stage10_w = r0.w * v3.z + cb0[1].z;
    r0.y = stage10_y;
    r0.z = stage10_z;
    r0.w = stage10_w;
    // mul r0.yzw, r0.yyzw, v5.wwww
    float stage11_y = r0.y * v5.w;
    float stage11_z = r0.z * v5.w;
    float stage11_w = r0.w * v5.w;
    r0.y = stage11_y;
    r0.z = stage11_z;
    r0.w = stage11_w;
    // mul o0.xyz, r0.xxxx, r0.yzwy
    float stage12_x = r0.x * r0.y;
    float stage12_y = r0.x * r0.z;
    float stage12_z = r0.x * r0.w;
    o0.x = stage12_x;
    o0.y = stage12_y;
    o0.z = stage12_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_n_pa_ring_07_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
