// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_n_pa_db_01_01_ad_Constants0 : register(b0)
{
    float4 cb0[4];
};
SamplerState s0 : register(s0);
Texture2D t0 : register(t0);

struct Shade_Ue3_fx_n_pa_db_01_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_n_pa_db_01_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_n_pa_db_01_01_ad_OUTPUT Shade_Ue3_fx_n_pa_db_01_01_ad(Shade_Ue3_fx_n_pa_db_01_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;

    // add r0.x, v2.x, l(-0.500000)
    r0.x = v2.x + -0.5f;
    // mad r0.x, r0.x, cb0[2].x, l(0.500000)
    r0.x = r0.x * cb0[2].x + 0.5f;
    // mul r0.z, v2.y, cb0[2].z
    r0.z = v2.y * cb0[2].z;
    // mul r0.z, r0.z, l(6.283185)
    r0.z = r0.z * 6.283185f;
    // sincos r0.z, null, r0.z
    float stage1_z = r0.z;
    r0.z = sin(stage1_z);
    // mul r1.xy, v4.yzyy, cb0[2].ywyy
    float stage2_x = v4.y * cb0[2].y;
    float stage2_y = v4.z * cb0[2].w;
    r1.x = stage2_x;
    r1.y = stage2_y;
    // mul r0.z, r0.z, r1.y
    r0.z = r0.z * r1.y;
    // add r0.w, v2.y, -v4.x
    r0.w = v2.y + -v4.x;
    // add r0.w, r0.w, l(0.500000)
    r0.w = r0.w + 0.5f;
    // mad r0.y, r0.w, r1.x, l(0.500000)
    r0.y = r0.w * r1.x + 0.5f;
    // mad r0.w, -cb0[2].z, v2.y, l(1.000000)
    r0.w = -cb0[2].z * v2.y + 1.0f;
    // mad r0.xy, r0.wwww, r0.zzzz, r0.xyxx
    float stage3_x = r0.w * r0.z + r0.x;
    float stage3_y = r0.w * r0.z + r0.y;
    r0.x = stage3_x;
    r0.y = stage3_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch4 = t0.SampleBias(s0, r0.xy, 0.0f);
    r0.x = fetch4.x;
    r0.y = fetch4.y;
    r0.z = fetch4.z;
    // dp3 r0.w, r0.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.w = dot(r0.xyz, float3(0.3f, 0.59f, 0.11f));
    // add r1.xyz, -r0.xyzx, r0.wwww
    float stage5_x = -r0.x + r0.w;
    float stage5_y = -r0.y + r0.w;
    float stage5_z = -r0.z + r0.w;
    r1.x = stage5_x;
    r1.y = stage5_y;
    r1.z = stage5_z;
    // mad r0.xyz, cb0[3].xxxx, r1.xyzx, r0.xyzx
    float stage6_x = cb0[3].x * r1.x + r0.x;
    float stage6_y = cb0[3].x * r1.y + r0.y;
    float stage6_z = cb0[3].x * r1.z + r0.z;
    r0.x = stage6_x;
    r0.y = stage6_y;
    r0.z = stage6_z;
    // max r0.xyz, |r0.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage7_x = max(abs(r0.x), 1e-06f);
    float stage7_y = max(abs(r0.y), 1e-06f);
    float stage7_z = max(abs(r0.z), 1e-06f);
    r0.x = stage7_x;
    r0.y = stage7_y;
    r0.z = stage7_z;
    // log r0.xyz, r0.xyzx
    float stage8_x = log2(r0.x);
    float stage8_y = log2(r0.y);
    float stage8_z = log2(r0.z);
    r0.x = stage8_x;
    r0.y = stage8_y;
    r0.z = stage8_z;
    // mul r0.xyz, r0.xyzx, cb0[3].yyyy
    float stage9_x = r0.x * cb0[3].y;
    float stage9_y = r0.y * cb0[3].y;
    float stage9_z = r0.z * cb0[3].y;
    r0.x = stage9_x;
    r0.y = stage9_y;
    r0.z = stage9_z;
    // exp r0.xyz, r0.xyzx
    float stage10_x = exp2(r0.x);
    float stage10_y = exp2(r0.y);
    float stage10_z = exp2(r0.z);
    r0.x = stage10_x;
    r0.y = stage10_y;
    r0.z = stage10_z;
    // mad r0.xyz, r0.xyzx, v3.xyzx, cb0[1].xyzx
    float stage11_x = r0.x * v3.x + cb0[1].x;
    float stage11_y = r0.y * v3.y + cb0[1].y;
    float stage11_z = r0.z * v3.z + cb0[1].z;
    r0.x = stage11_x;
    r0.y = stage11_y;
    r0.z = stage11_z;
    // mul r0.xyz, r0.xyzx, v5.wwww
    float stage12_x = r0.x * v5.w;
    float stage12_y = r0.y * v5.w;
    float stage12_z = r0.z * v5.w;
    r0.x = stage12_x;
    r0.y = stage12_y;
    r0.z = stage12_z;
    // add r0.w, -v2.y, l(1.000000)
    r0.w = -v2.y + 1.0f;
    // mul r0.w, r0.w, v2.y
    r0.w = r0.w * v2.y;
    // mul r1.x, |r0.w|, |r0.w|
    r1.x = abs(r0.w) * abs(r0.w);
    // lt r0.w, |r0.w|, l(0.000001)
    r0.w = asfloat((abs(r0.w) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.x, r1.x, l(100.000000)
    r1.x = r1.x * 100.0f;
    // min r1.x, r1.x, l(1.000000)
    r1.x = min(r1.x, 1.0f);
    // mul r1.x, r1.x, v3.w
    r1.x = r1.x * v3.w;
    // mul r1.x, r1.x, cb0[0].x
    r1.x = r1.x * cb0[0].x;
    // movc r0.w, r0.w, l(0), r1.x
    r0.w = asuint(r0.w) != 0u ? asfloat(0u) : r1.x;
    // mul o0.xyz, r0.wwww, r0.xyzx
    float stage13_x = r0.w * r0.x;
    float stage13_y = r0.w * r0.y;
    float stage13_z = r0.w * r0.z;
    o0.x = stage13_x;
    o0.y = stage13_y;
    o0.z = stage13_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_n_pa_db_01_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
