// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_flare_01_ad_Constants0 : register(b0)
{
    float4 cb0[6];
};
cbuffer Shade_Ue3_fx_d_pa_flare_01_ad_Constants2 : register(b2)
{
    float4 cb2[2];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);

struct Shade_Ue3_fx_d_pa_flare_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v5;
    float4 v7;
};

struct Shade_Ue3_fx_d_pa_flare_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_d_pa_flare_01_ad_OUTPUT Shade_Ue3_fx_d_pa_flare_01_ad(Shade_Ue3_fx_d_pa_flare_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v5 = stage.v5;
    float4 v7 = stage.v7;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 o0 = (float4)0;

    // div r0.xy, v7.xyxx, v7.wwww
    float stage1_x = v7.x / v7.w;
    float stage1_y = v7.y / v7.w;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // mad r0.xy, r0.xyxx, cb2[0].xyxx, cb2[0].wzww
    float stage2_x = r0.x * cb2[0].x + cb2[0].w;
    float stage2_y = r0.y * cb2[0].y + cb2[0].z;
    r0.x = stage2_x;
    r0.y = stage2_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t1.xyzw, s0, l(0.000000)
    float4 fetch3 = t1.SampleLevel(s0, r0.xy, 0.0f);
    r0.x = fetch3.x;
    // min r0.x, r0.x, l(0.999000)
    r0.x = min(r0.x, 0.999f);
    // mad r0.y, r0.x, cb2[1].z, -cb2[1].w
    r0.y = r0.x * cb2[1].z + -cb2[1].w;
    // mad r0.x, r0.x, cb2[1].x, cb2[1].y
    r0.x = r0.x * cb2[1].x + cb2[1].y;
    // div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
    r0.y = 1.0f / r0.y;
    // add r0.x, r0.y, r0.x
    r0.x = r0.y + r0.x;
    // add r0.x, r0.x, -v7.w
    r0.x = r0.x + -v7.w;
    // add r0.y, -cb0[5].z, l(1.000000)
    r0.y = -cb0[5].z + 1.0f;
    // max r0.y, -r0.y, l(0.001000)
    r0.y = max(-r0.y, 0.001f);
    // div_sat r0.x, r0.x, r0.y
    r0.x = saturate(r0.x / r0.y);
    // add r0.yz, v2.xxyx, l(0.000000, -0.500000, -0.500000, 0.000000)
    float stage4_y = v2.x + -0.5f;
    float stage4_z = v2.y + -0.5f;
    r0.y = stage4_y;
    r0.z = stage4_z;
    // max r0.w, |r0.z|, |r0.y|
    r0.w = max(abs(r0.z), abs(r0.y));
    // div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
    r0.w = 1.0f / r0.w;
    // min r1.x, |r0.z|, |r0.y|
    r1.x = min(abs(r0.z), abs(r0.y));
    // mul r0.w, r0.w, r1.x
    r0.w = r0.w * r1.x;
    // mul r1.x, r0.w, r0.w
    r1.x = r0.w * r0.w;
    // mad r1.y, r1.x, l(0.020835), l(-0.085133)
    r1.y = r1.x * 0.020835f + -0.085133f;
    // mad r1.y, r1.x, r1.y, l(0.180141)
    r1.y = r1.x * r1.y + 0.180141f;
    // mad r1.y, r1.x, r1.y, l(-0.330299)
    r1.y = r1.x * r1.y + -0.330299f;
    // mad r1.x, r1.x, r1.y, l(0.999866)
    r1.x = r1.x * r1.y + 0.999866f;
    // mul r1.y, r0.w, r1.x
    r1.y = r0.w * r1.x;
    // mad r1.y, r1.y, l(-2.000000), l(1.570796)
    r1.y = r1.y * -2.0f + 1.570796f;
    // lt r1.z, |r0.z|, |r0.y|
    r1.z = asfloat((abs(r0.z) < abs(r0.y)) ? 0xffffffffu : 0u);
    // and r1.y, r1.z, r1.y
    r1.y = asfloat(asuint(r1.z) & asuint(r1.y));
    // mad r0.w, r0.w, r1.x, r1.y
    r0.w = r0.w * r1.x + r1.y;
    // lt r1.x, r0.z, -r0.z
    r1.x = asfloat((r0.z < -r0.z) ? 0xffffffffu : 0u);
    // and r1.x, r1.x, l(0xc0490fdb)
    r1.x = asfloat(asuint(r1.x) & asuint(-3.1415927410125732f));
    // add r0.w, r0.w, r1.x
    r0.w = r0.w + r1.x;
    // min r1.x, r0.z, r0.y
    r1.x = min(r0.z, r0.y);
    // lt r1.x, r1.x, -r1.x
    r1.x = asfloat((r1.x < -r1.x) ? 0xffffffffu : 0u);
    // max r1.y, r0.z, r0.y
    r1.y = max(r0.z, r0.y);
    // dp2 r0.y, r0.yzyy, r0.yzyy
    r0.y = dot(r0.yz, r0.yz);
    // sqrt r0.y, r0.y
    r0.y = sqrt(r0.y);
    // mad r0.y, -r0.y, l(2.000000), l(1.000000)
    r0.y = -r0.y * 2.0f + 1.0f;
    // max r0.y, r0.y, l(0.000000)
    r0.y = max(r0.y, 0.0f);
    // ge r0.z, r1.y, -r1.y
    r0.z = asfloat((r1.y >= -r1.y) ? 0xffffffffu : 0u);
    // and r0.z, r0.z, r1.x
    r0.z = asfloat(asuint(r0.z) & asuint(r1.x));
    // movc r0.z, r0.z, -r0.w, r0.w
    r0.z = asuint(r0.z) != 0u ? -r0.w : r0.w;
    // mad r0.z, r0.z, l(0.159155), l(0.500000)
    r0.z = r0.z * 0.159155f + 0.5f;
    // add r1.xy, r0.zzzz, cb0[2].xyxx
    float stage5_x = r0.z + cb0[2].x;
    float stage5_y = r0.z + cb0[2].y;
    r1.x = stage5_x;
    r1.y = stage5_y;
    // add r0.zw, r0.zzzz, cb0[3].xxxy
    float stage6_z = r0.z + cb0[3].x;
    float stage6_w = r0.z + cb0[3].y;
    r0.z = stage6_z;
    r0.w = stage6_w;
    // sample_l_indexable(texture2d)(float,float,float,float) r2.xyz, r0.zwzz, t0.xyzw, s1, l(-1.000000)
    float4 fetch7 = t0.SampleLevel(s1, r0.zw, -1.0f);
    r2.x = fetch7.x;
    r2.y = fetch7.y;
    r2.z = fetch7.z;
    // sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t0.xyzw, s1, l(-1.000000)
    float4 fetch8 = t0.SampleLevel(s1, r1.xy, -1.0f);
    r1.x = fetch8.x;
    r1.y = fetch8.y;
    r1.z = fetch8.z;
    // add r1.xyz, r2.xyzx, r1.xyzx
    float stage9_x = r2.x + r1.x;
    float stage9_y = r2.y + r1.y;
    float stage9_z = r2.z + r1.z;
    r1.x = stage9_x;
    r1.y = stage9_y;
    r1.z = stage9_z;
    // dp2 r0.z, r1.xyxx, r1.yzyy
    r0.z = dot(r1.xy, r1.yz);
    // log r0.w, |r0.z|
    r0.w = log2(abs(r0.z));
    // lt r0.z, |r0.z|, l(0.000001)
    r0.z = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.w, r0.w, cb0[5].x
    r0.w = r0.w * cb0[5].x;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // mul r0.w, r0.w, cb0[5].y
    r0.w = r0.w * cb0[5].y;
    // mul r1.w, r0.y, r0.y
    r1.w = r0.y * r0.y;
    // mul r0.y, r0.y, r1.w
    r0.y = r0.y * r1.w;
    // mul r0.y, r0.w, r0.y
    r0.y = r0.w * r0.y;
    // mul r0.x, r0.x, r0.y
    r0.x = r0.x * r0.y;
    // mul_sat r0.x, r0.x, v3.w
    r0.x = saturate(r0.x * v3.w);
    // mul r0.x, r0.x, cb0[0].x
    r0.x = r0.x * cb0[0].x;
    // movc r0.x, r0.z, l(0), r0.x
    r0.x = asuint(r0.z) != 0u ? asfloat(0u) : r0.x;
    // dp3 r0.y, r1.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.y = dot(r1.xyz, float3(0.3f, 0.59f, 0.11f));
    // add r0.yzw, -r1.xxyz, r0.yyyy
    float stage10_y = -r1.x + r0.y;
    float stage10_z = -r1.y + r0.y;
    float stage10_w = -r1.z + r0.y;
    r0.y = stage10_y;
    r0.z = stage10_z;
    r0.w = stage10_w;
    // mad r0.yzw, cb0[4].yyyy, r0.yyzw, r1.xxyz
    float stage11_y = cb0[4].y * r0.y + r1.x;
    float stage11_z = cb0[4].y * r0.z + r1.y;
    float stage11_w = cb0[4].y * r0.w + r1.z;
    r0.y = stage11_y;
    r0.z = stage11_z;
    r0.w = stage11_w;
    // mul r0.yzw, r0.yyzw, cb0[4].zzzz
    float stage12_y = r0.y * cb0[4].z;
    float stage12_z = r0.z * cb0[4].z;
    float stage12_w = r0.w * cb0[4].z;
    r0.y = stage12_y;
    r0.z = stage12_z;
    r0.w = stage12_w;
    // max r0.yzw, |r0.yyzw|, l(0.000000, 0.000001, 0.000001, 0.000001)
    float stage13_y = max(abs(r0.y), 1e-06f);
    float stage13_z = max(abs(r0.z), 1e-06f);
    float stage13_w = max(abs(r0.w), 1e-06f);
    r0.y = stage13_y;
    r0.z = stage13_z;
    r0.w = stage13_w;
    // log r0.yzw, r0.yyzw
    float stage14_y = log2(r0.y);
    float stage14_z = log2(r0.z);
    float stage14_w = log2(r0.w);
    r0.y = stage14_y;
    r0.z = stage14_z;
    r0.w = stage14_w;
    // mul r0.yzw, r0.yyzw, cb0[4].wwww
    float stage15_y = r0.y * cb0[4].w;
    float stage15_z = r0.z * cb0[4].w;
    float stage15_w = r0.w * cb0[4].w;
    r0.y = stage15_y;
    r0.z = stage15_z;
    r0.w = stage15_w;
    // exp r0.yzw, r0.yyzw
    float stage16_y = exp2(r0.y);
    float stage16_z = exp2(r0.z);
    float stage16_w = exp2(r0.w);
    r0.y = stage16_y;
    r0.z = stage16_z;
    r0.w = stage16_w;
    // mad r0.yzw, r0.yyzw, v3.xxyz, cb0[1].xxyz
    float stage17_y = r0.y * v3.x + cb0[1].x;
    float stage17_z = r0.z * v3.y + cb0[1].y;
    float stage17_w = r0.w * v3.z + cb0[1].z;
    r0.y = stage17_y;
    r0.z = stage17_z;
    r0.w = stage17_w;
    // mul r0.yzw, r0.yyzw, v5.wwww
    float stage18_y = r0.y * v5.w;
    float stage18_z = r0.z * v5.w;
    float stage18_w = r0.w * v5.w;
    r0.y = stage18_y;
    r0.z = stage18_z;
    r0.w = stage18_w;
    // mul o0.xyz, r0.xxxx, r0.yzwy
    float stage19_x = r0.x * r0.y;
    float stage19_y = r0.x * r0.z;
    float stage19_z = r0.x * r0.w;
    o0.x = stage19_x;
    o0.y = stage19_y;
    o0.z = stage19_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_d_pa_flare_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
