// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_e_me_rock_01_ma_Constants0 : register(b0)
{
    float4 cb0[9];
};
cbuffer Shade_Ue3_fx_e_me_rock_01_ma_Constants2 : register(b2)
{
    float4 cb2[5];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);

struct Shade_Ue3_fx_e_me_rock_01_ma_INPUT
{
    float4 v0;
    float4 v1;
    float4 v4;
    float4 v5;
    float4 v6;
    uint4 vCoverage;
};

struct Shade_Ue3_fx_e_me_rock_01_ma_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
    uint oMask;
};

Shade_Ue3_fx_e_me_rock_01_ma_OUTPUT Shade_Ue3_fx_e_me_rock_01_ma(Shade_Ue3_fx_e_me_rock_01_ma_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v6 = stage.v6;
    uint4 vCoverage = stage.vCoverage;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 r5 = (float4)0;
    float4 r6 = (float4)0;
    float4 r7 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;
    uint oMask = 0xffffffffu;

    // mov_sat r0.x, cb0[0].w
    r0.x = saturate(cb0[0].w);
    // add r0.x, r0.x, l(-0.333300)
    r0.x = r0.x + -0.3333f;
    // lt r0.x, r0.x, l(0.000000)
    r0.x = asfloat((r0.x < 0.0f) ? 0xffffffffu : 0u);
    // discard_nz r0.x
    if (asuint(r0.x) != 0u) discard;
    // mov oMask, vCoverage.x
    oMask = asuint(vCoverage.x);
    // dp3 r0.x, v5.xyzx, v5.xyzx
    r0.x = dot(v5.xyz, v5.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v5.xyzx
    float stage1_x = r0.x * v5.x;
    float stage1_y = r0.x * v5.y;
    float stage1_z = r0.x * v5.z;
    r0.x = stage1_x;
    r0.y = stage1_y;
    r0.z = stage1_z;
    // mul r1.xy, v4.xyxx, cb0[4].xxxx
    float stage2_x = v4.x * cb0[4].x;
    float stage2_y = v4.y * cb0[4].x;
    r1.x = stage2_x;
    r1.y = stage2_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.zw, r1.xyxx, t0.zwxy, s0, l(0.000000)
    float4 fetch3 = t0.SampleBias(s0, r1.xy, 0.0f);
    r1.z = fetch3.x;
    r1.w = fetch3.y;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyxx, t1.xyzw, s1, l(0.000000)
    float4 fetch4 = t1.SampleBias(s1, r1.xy, 0.0f);
    r2.x = fetch4.x;
    r2.y = fetch4.y;
    r2.z = fetch4.z;
    r2.w = fetch4.w;
    // mad r1.xy, r1.zwzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
    float stage5_x = r1.z * 2.0f + -1.0f;
    float stage5_y = r1.w * 2.0f + -1.0f;
    r1.x = stage5_x;
    r1.y = stage5_y;
    // dp2 r0.w, r1.xyxx, r1.xyxx
    r0.w = dot(r1.xy, r1.xy);
    // add r0.w, -r0.w, l(1.000000)
    r0.w = -r0.w + 1.0f;
    // max r0.w, r0.w, l(0.000000)
    r0.w = max(r0.w, 0.0f);
    // sqrt r0.w, r0.w
    r0.w = sqrt(r0.w);
    // add r1.z, r0.w, l(0.000010)
    r1.z = r0.w + 1e-05f;
    // dp3 r0.w, r1.xyzx, r1.xyzx
    r0.w = dot(r1.xyz, r1.xyz);
    // rsq r1.w, r0.w
    r1.w = rsqrt(r0.w);
    // sqrt r0.w, r0.w
    r0.w = sqrt(r0.w);
    // div r3.xyz, r1.xyzx, r0.wwww
    float stage6_x = r1.x / r0.w;
    float stage6_y = r1.y / r0.w;
    float stage6_z = r1.z / r0.w;
    r3.x = stage6_x;
    r3.y = stage6_y;
    r3.z = stage6_z;
    // mul r1.xyz, r1.wwww, r1.xyzx
    float stage7_x = r1.w * r1.x;
    float stage7_y = r1.w * r1.y;
    float stage7_z = r1.w * r1.z;
    r1.x = stage7_x;
    r1.y = stage7_y;
    r1.z = stage7_z;
    // dp3 r0.w, r1.xyzx, r0.xyzx
    r0.w = dot(r1.xyz, r0.xyz);
    // mul r4.xyz, r0.wwww, r1.xyzx
    float stage8_x = r0.w * r1.x;
    float stage8_y = r0.w * r1.y;
    float stage8_z = r0.w * r1.z;
    r4.x = stage8_x;
    r4.y = stage8_y;
    r4.z = stage8_z;
    // mad r0.xyz, r4.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), -r0.xyzx
    float stage9_x = r4.x * 2.0f + -r0.x;
    float stage9_y = r4.y * 2.0f + -r0.y;
    float stage9_z = r4.z * 2.0f + -r0.z;
    r0.x = stage9_x;
    r0.y = stage9_y;
    r0.z = stage9_z;
    // dp3 r0.w, v1.xyzx, v1.xyzx
    r0.w = dot(v1.xyz, v1.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r4.xyz, r0.wwww, v1.xyzx
    float stage10_x = r0.w * v1.x;
    float stage10_y = r0.w * v1.y;
    float stage10_z = r0.w * v1.z;
    r4.x = stage10_x;
    r4.y = stage10_y;
    r4.z = stage10_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r5.xyz, r0.wwww, v0.xyzx
    float stage11_x = r0.w * v0.x;
    float stage11_y = r0.w * v0.y;
    float stage11_z = r0.w * v0.z;
    r5.x = stage11_x;
    r5.y = stage11_y;
    r5.z = stage11_z;
    // mul r6.xyz, r4.zxyz, r5.yzxy
    float stage12_x = r4.z * r5.y;
    float stage12_y = r4.x * r5.z;
    float stage12_z = r4.y * r5.x;
    r6.x = stage12_x;
    r6.y = stage12_y;
    r6.z = stage12_z;
    // mad r6.xyz, r4.yzxy, r5.zxyz, -r6.xyzx
    float stage13_x = r4.y * r5.z + -r6.x;
    float stage13_y = r4.z * r5.x + -r6.y;
    float stage13_z = r4.x * r5.y + -r6.z;
    r6.x = stage13_x;
    r6.y = stage13_y;
    r6.z = stage13_z;
    // mul r6.xyz, r6.xzyx, v1.wwww
    float stage14_x = r6.x * v1.w;
    float stage14_y = r6.z * v1.w;
    float stage14_z = r6.y * v1.w;
    r6.x = stage14_x;
    r6.y = stage14_y;
    r6.z = stage14_z;
    // dp3 r7.y, r6.xzyx, r0.xyzx
    r7.y = dot(r6.xzy, r0.xyz);
    // dp3 r7.x, r5.xyzx, r0.xyzx
    r7.x = dot(r5.xyz, r0.xyz);
    // dp3 r7.z, r4.xyzx, r0.xyzx
    r7.z = dot(r4.xyz, r0.xyz);
    // dp3 r0.y, r6.xzyx, r1.xyzx
    r0.y = dot(r6.xzy, r1.xyz);
    // mov r6.x, r5.z
    r6.x = r5.z;
    // dp3 r0.x, r5.xyzx, r1.xyzx
    r0.x = dot(r5.xyz, r1.xyz);
    // mov r6.z, r4.z
    r6.z = r4.z;
    // dp3 r0.z, r4.xyzx, r1.xyzx
    r0.z = dot(r4.xyz, r1.xyz);
    // dp3_sat r0.w, r7.xyzx, r6.xyzx
    r0.w = saturate(dot(r7.xyz, r6.xyz));
    // dp3_sat r1.w, r3.xyzx, r6.xyzx
    r1.w = saturate(dot(r3.xyz, r6.xyz));
    // mul r3.x, r1.w, l(10.000000)
    r3.x = r1.w * 10.0f;
    // mul r3.yzw, r1.wwww, cb0[3].xxyz
    float stage15_y = r1.w * cb0[3].x;
    float stage15_z = r1.w * cb0[3].y;
    float stage15_w = r1.w * cb0[3].z;
    r3.y = stage15_y;
    r3.z = stage15_z;
    r3.w = stage15_w;
    // min r1.w, r3.x, l(1.000000)
    r1.w = min(r3.x, 1.0f);
    // mul r0.w, r0.w, r1.w
    r0.w = r0.w * r1.w;
    // log r1.w, r0.w
    r1.w = log2(r0.w);
    // lt r0.w, r0.w, l(0.000001)
    r0.w = asfloat((r0.w < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.w, r1.w, cb0[4].y
    r1.w = r1.w * cb0[4].y;
    // exp r1.w, r1.w
    r1.w = exp2(r1.w);
    // mul r1.w, r1.w, cb0[4].z
    r1.w = r1.w * cb0[4].z;
    // movc r0.w, r0.w, l(0), r1.w
    r0.w = asuint(r0.w) != 0u ? asfloat(0u) : r1.w;
    // mul r2.xyz, r2.xyzx, cb0[0].xyzx
    float stage16_x = r2.x * cb0[0].x;
    float stage16_y = r2.y * cb0[0].y;
    float stage16_z = r2.z * cb0[0].z;
    r2.x = stage16_x;
    r2.y = stage16_y;
    r2.z = stage16_z;
    // mul r3.xyz, r3.yzwy, r2.xyzx
    float stage17_x = r3.y * r2.x;
    float stage17_y = r3.z * r2.y;
    float stage17_z = r3.w * r2.z;
    r3.x = stage17_x;
    r3.y = stage17_y;
    r3.z = stage17_z;
    // mul r4.xyz, cb0[2].xyzx, cb0[2].wwww
    float stage18_x = cb0[2].x * cb0[2].w;
    float stage18_y = cb0[2].y * cb0[2].w;
    float stage18_z = cb0[2].z * cb0[2].w;
    r4.x = stage18_x;
    r4.y = stage18_y;
    r4.z = stage18_z;
    // mad r2.xyz, r4.xyzx, r2.xyzx, r3.xyzx
    float stage19_x = r4.x * r2.x + r3.x;
    float stage19_y = r4.y * r2.y + r3.y;
    float stage19_z = r4.z * r2.z + r3.z;
    r2.x = stage19_x;
    r2.y = stage19_y;
    r2.z = stage19_z;
    // mad r2.xyz, r2.wwww, r0.wwww, r2.xyzx
    float stage20_x = r2.w * r0.w + r2.x;
    float stage20_y = r2.w * r0.w + r2.y;
    float stage20_z = r2.w * r0.w + r2.z;
    r2.x = stage20_x;
    r2.y = stage20_y;
    r2.z = stage20_z;
    // add r3.xyz, -cb0[1].xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
    float stage21_x = -cb0[1].x + 1.0f;
    float stage21_y = -cb0[1].y + 1.0f;
    float stage21_z = -cb0[1].z + 1.0f;
    r3.x = stage21_x;
    r3.y = stage21_y;
    r3.z = stage21_z;
    // mul r2.xyz, r2.xyzx, r3.xyzx
    float stage22_x = r2.x * r3.x;
    float stage22_y = r2.y * r3.y;
    float stage22_z = r2.z * r3.z;
    r2.x = stage22_x;
    r2.y = stage22_y;
    r2.z = stage22_z;
    // mad r2.xyz, r2.xyzx, cb2[3].wwww, cb2[3].xyzx
    float stage23_x = r2.x * cb2[3].w + cb2[3].x;
    float stage23_y = r2.y * cb2[3].w + cb2[3].y;
    float stage23_z = r2.z * cb2[3].w + cb2[3].z;
    r2.x = stage23_x;
    r2.y = stage23_y;
    r2.z = stage23_z;
    // dp3 r0.w, v6.xyzx, v6.xyzx
    r0.w = dot(v6.xyz, v6.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r3.xyz, r0.wwww, v6.xyzx
    float stage24_x = r0.w * v6.x;
    float stage24_y = r0.w * v6.y;
    float stage24_z = r0.w * v6.z;
    r3.x = stage24_x;
    r3.y = stage24_y;
    r3.z = stage24_z;
    // dp3 r0.w, r3.xyzx, r1.xyzx
    r0.w = dot(r3.xyz, r1.xyz);
    // mad r1.xy, r0.wwww, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage25_x = r0.w * 0.5f + 0.5f;
    float stage25_y = r0.w * -0.5f + 0.5f;
    r1.x = stage25_x;
    r1.y = stage25_y;
    // mul r1.xy, r1.xyxx, r1.xyxx
    float stage26_x = r1.x * r1.x;
    float stage26_y = r1.y * r1.y;
    r1.x = stage26_x;
    r1.y = stage26_y;
    // mul r1.yzw, r1.yyyy, cb0[7].xxyz
    float stage27_y = r1.y * cb0[7].x;
    float stage27_z = r1.y * cb0[7].y;
    float stage27_w = r1.y * cb0[7].z;
    r1.y = stage27_y;
    r1.z = stage27_z;
    r1.w = stage27_w;
    // mad r1.xyz, r1.xxxx, cb0[6].xyzx, r1.yzwy
    float stage28_x = r1.x * cb0[6].x + r1.y;
    float stage28_y = r1.x * cb0[6].y + r1.z;
    float stage28_z = r1.x * cb0[6].z + r1.w;
    r1.x = stage28_x;
    r1.y = stage28_y;
    r1.z = stage28_z;
    // mul r1.xyz, r1.xyzx, cb0[8].wwww
    float stage29_x = r1.x * cb0[8].w;
    float stage29_y = r1.y * cb0[8].w;
    float stage29_z = r1.z * cb0[8].w;
    r1.x = stage29_x;
    r1.y = stage29_y;
    r1.z = stage29_z;
    // mad r3.xyz, r1.xyzx, r2.xyzx, cb0[1].xyzx
    float stage30_x = r1.x * r2.x + cb0[1].x;
    float stage30_y = r1.y * r2.y + cb0[1].y;
    float stage30_z = r1.z * r2.z + cb0[1].z;
    r3.x = stage30_x;
    r3.y = stage30_y;
    r3.z = stage30_z;
    // mul r1.xyz, r2.xyzx, r1.xyzx
    float stage31_x = r2.x * r1.x;
    float stage31_y = r2.y * r1.y;
    float stage31_z = r2.z * r1.z;
    r1.x = stage31_x;
    r1.y = stage31_y;
    r1.z = stage31_z;
    // dp3 o4.y, r1.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    o4.y = dot(r1.xyz, float3(0.3f, 0.59f, 0.11f));
    // mad o0.xyz, r2.xyzx, cb0[8].xyzx, r3.xyzx
    float stage32_x = r2.x * cb0[8].x + r3.x;
    float stage32_y = r2.y * cb0[8].y + r3.y;
    float stage32_z = r2.z * cb0[8].z + r3.z;
    o0.x = stage32_x;
    o0.y = stage32_y;
    o0.z = stage32_z;
    // mov o3.xyz, r2.xyzx
    float stage33_x = r2.x;
    float stage33_y = r2.y;
    float stage33_z = r2.z;
    o3.x = stage33_x;
    o3.y = stage33_y;
    o3.z = stage33_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);
    // dp3 r0.w, r0.xyzx, r0.xyzx
    r0.w = dot(r0.xyz, r0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r0.xyz, r0.wwww, r0.xyzx
    float stage34_x = r0.w * r0.x;
    float stage34_y = r0.w * r0.y;
    float stage34_z = r0.w * r0.z;
    r0.x = stage34_x;
    r0.y = stage34_y;
    r0.z = stage34_z;
    // ge r0.w, l(0.000000), r0.z
    r0.w = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // dp3 r0.z, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.z = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.zzzz
    float stage35_x = r0.x / r0.z;
    float stage35_y = r0.y / r0.z;
    r0.x = stage35_x;
    r0.y = stage35_y;
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage36_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage36_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage36_x;
    r1.y = stage36_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage37_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage37_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage37_x;
    r1.y = stage37_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage38_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage38_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage38_x;
    r1.y = stage38_y;
    // movc r0.xy, r0.wwww, r1.xyxx, r0.xyxx
    float stage39_x = asuint(r0.w) != 0u ? r1.x : r0.x;
    float stage39_y = asuint(r0.w) != 0u ? r1.y : r0.y;
    r0.x = stage39_x;
    r0.y = stage39_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage40_x = r0.x * 0.5f + 0.5f;
    float stage40_y = r0.y * 0.5f + 0.5f;
    o2.x = stage40_x;
    o2.y = stage40_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage41_z = 1.0f;
    float stage41_w = asfloat(0u);
    o2.z = stage41_z;
    o2.w = stage41_w;
    // mov o3.w, l(0.030000)
    o3.w = 0.03f;
    // mov o4.xzw, l(0,0,0,0)
    float stage42_x = asfloat(0u);
    float stage42_z = asfloat(0u);
    float stage42_w = asfloat(0u);
    o4.x = stage42_x;
    o4.z = stage42_z;
    o4.w = stage42_w;
    // ftou r0.x, cb0[5].z
    r0.x = asfloat((uint)(cb0[5].z));
    // bfi r0.x, l(5), l(0), r0.x, l(32)
    r0.x = asfloat((((asuint(r0.x) << (asuint(asfloat(0u)) & 31u)) & ((((1u << (asuint(asfloat(5u)) & 31u)) - 1u) << (asuint(asfloat(0u)) & 31u)))) | (asuint(asfloat(32u)) & ~((((1u << (asuint(asfloat(5u)) & 31u)) - 1u) << (asuint(asfloat(0u)) & 31u))))));
    // utof r0.x, r0.x
    r0.x = (float)asuint(r0.x);
    // mul o5.w, r0.x, l(0.003922)
    o5.w = r0.x * 0.003922f;
    // mul_sat r0.xyz, cb2[4].xyzx, l(0.100000, 0.100000, 0.100000, 0.000000)
    float stage43_x = saturate(cb2[4].x * 0.1f);
    float stage43_y = saturate(cb2[4].y * 0.1f);
    float stage43_z = saturate(cb2[4].z * 0.1f);
    r0.x = stage43_x;
    r0.y = stage43_y;
    r0.z = stage43_z;
    // sqrt o5.xyz, r0.xyzx
    float stage44_x = sqrt(r0.x);
    float stage44_y = sqrt(r0.y);
    float stage44_z = sqrt(r0.z);
    o5.x = stage44_x;
    o5.y = stage44_y;
    o5.z = stage44_z;

    Shade_Ue3_fx_e_me_rock_01_ma_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    result.oMask = oMask;
    return result;
}
