// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_mm_light_01_ad_Constants0 : register(b0)
{
    float4 cb0[2];
};
SamplerState s0 : register(s0);
Texture2D t0 : register(t0);

struct Shade_Ue3_fx_mm_light_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v5;
};

struct Shade_Ue3_fx_mm_light_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_fx_mm_light_01_ad_OUTPUT Shade_Ue3_fx_mm_light_01_ad(Shade_Ue3_fx_mm_light_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 o0 = (float4)0;

    // sample_b_indexable(texture2d)(float,float,float,float) r0.xyzw, v2.xyxx, t0.xyzw, s0, l(0.000000)
    float4 fetch1 = t0.SampleBias(s0, v2.xy, 0.0f);
    r0.x = fetch1.x;
    r0.y = fetch1.y;
    r0.z = fetch1.z;
    r0.w = fetch1.w;
    // mul r0.w, r0.w, v3.w
    r0.w = r0.w * v3.w;
    // mad r0.xyz, r0.xyzx, v3.xyzx, cb0[1].xyzx
    float stage2_x = r0.x * v3.x + cb0[1].x;
    float stage2_y = r0.y * v3.y + cb0[1].y;
    float stage2_z = r0.z * v3.z + cb0[1].z;
    r0.x = stage2_x;
    r0.y = stage2_y;
    r0.z = stage2_z;
    // mul r0.xyz, r0.xyzx, v5.wwww
    float stage3_x = r0.x * v5.w;
    float stage3_y = r0.y * v5.w;
    float stage3_z = r0.z * v5.w;
    r0.x = stage3_x;
    r0.y = stage3_y;
    r0.z = stage3_z;
    // mov_sat r0.w, r0.w
    r0.w = saturate(r0.w);
    // mul r0.w, r0.w, cb0[0].x
    r0.w = r0.w * cb0[0].x;
    // mul o0.xyz, r0.wwww, r0.xyzx
    float stage4_x = r0.w * r0.x;
    float stage4_y = r0.w * r0.y;
    float stage4_z = r0.w * r0.z;
    o0.x = stage4_x;
    o0.y = stage4_y;
    o0.z = stage4_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_fx_mm_light_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
