// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_d_pa_field_02_tr_Constants0 : register(b0)
{
    float4 cb0[18];
};
cbuffer Shade_Ue3_fx_d_pa_field_02_tr_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);

struct Shade_Ue3_fx_d_pa_field_02_tr_INPUT
{
    float4 v0;
    float4 v1;
    float4 v4;
    float4 v5;
    float4 v6;
};

struct Shade_Ue3_fx_d_pa_field_02_tr_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_d_pa_field_02_tr_OUTPUT Shade_Ue3_fx_d_pa_field_02_tr(Shade_Ue3_fx_d_pa_field_02_tr_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 v6 = stage.v6;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 r4 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mov_sat r0.x, cb0[4].x
    r0.x = saturate(cb0[4].x);
    // add r0.x, -r0.x, l(1.000000)
    r0.x = -r0.x + 1.0f;
    // mul r0.yz, v4.xxyx, cb0[10].yyzy
    float stage1_y = v4.x * cb0[10].y;
    float stage1_z = v4.y * cb0[10].z;
    r0.y = stage1_y;
    r0.z = stage1_z;
    // mad r0.yz, cb0[9].yyyy, cb0[10].xxwx, r0.yyzy
    float stage2_y = cb0[9].y * cb0[10].x + r0.y;
    float stage2_z = cb0[9].y * cb0[10].w + r0.z;
    r0.y = stage2_y;
    r0.z = stage2_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t0.yxzw, s0, l(0.000000)
    float4 fetch3 = t0.SampleBias(s0, r0.yz, 0.0f);
    r0.y = fetch3.x;
    // mad r0.yz, r0.yyyy, cb0[11].xxxx, v4.xxyx
    float stage4_y = r0.y * cb0[11].x + v4.x;
    float stage4_z = r0.y * cb0[11].x + v4.y;
    r0.y = stage4_y;
    r0.z = stage4_z;
    // mul r0.w, r0.z, cb0[13].x
    r0.w = r0.z * cb0[13].x;
    // mad r1.w, cb0[9].y, cb0[13].y, r0.w
    r1.w = cb0[9].y * cb0[13].y + r0.w;
    // mul r2.xy, r0.zyzz, cb0[12].xwxx
    float stage5_x = r0.z * cb0[12].x;
    float stage5_y = r0.y * cb0[12].w;
    r2.x = stage5_x;
    r2.y = stage5_y;
    // mad r1.yz, cb0[9].yyyy, cb0[12].yyzy, r2.xxyx
    float stage6_y = cb0[9].y * cb0[12].y + r2.x;
    float stage6_z = cb0[9].y * cb0[12].z + r2.y;
    r1.y = stage6_y;
    r1.z = stage6_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r2.xyz, r1.zwzz, t3.xyzw, s3, l(0.000000)
    float4 fetch7 = t3.SampleBias(s3, r1.zw, 0.0f);
    r2.x = fetch7.x;
    r2.y = fetch7.y;
    r2.z = fetch7.z;
    // mul r0.w, cb0[9].y, cb0[11].z
    r0.w = cb0[9].y * cb0[11].z;
    // mad r1.x, cb0[11].w, r0.y, r0.w
    r1.x = cb0[11].w * r0.y + r0.w;
    // mul r0.yz, r0.yyzy, cb0[9].zzwz
    float stage8_y = r0.y * cb0[9].z;
    float stage8_z = r0.z * cb0[9].w;
    r0.y = stage8_y;
    r0.z = stage8_z;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t2.xyzw, s2, l(0.000000)
    float4 fetch9 = t2.SampleBias(s2, r1.xy, 0.0f);
    r1.x = fetch9.x;
    r1.y = fetch9.y;
    r1.z = fetch9.z;
    // mad r3.x, cb0[9].y, cb0[9].x, r0.y
    r3.x = cb0[9].y * cb0[9].x + r0.y;
    // mad r3.y, cb0[9].y, cb0[11].y, r0.z
    r3.y = cb0[9].y * cb0[11].y + r0.z;
    // sample_b_indexable(texture2d)(float,float,float,float) r0.yzw, r3.xyxx, t1.wxyz, s1, l(0.000000)
    float4 fetch10 = t1.SampleBias(s1, r3.xy, 0.0f);
    r0.y = fetch10.x;
    r0.z = fetch10.y;
    r0.w = fetch10.z;
    // mad r3.xy, r0.yyyy, r1.xxxx, r2.xxxx
    float stage11_x = r0.y * r1.x + r2.x;
    float stage11_y = r0.y * r1.x + r2.x;
    r3.x = stage11_x;
    r3.y = stage11_y;
    // add r4.xyzw, v4.xyxy, l(-0.500000, -0.500000, -0.500000, -0.500000)
    float stage12_x = v4.x + -0.5f;
    float stage12_y = v4.y + -0.5f;
    float stage12_z = v4.x + -0.5f;
    float stage12_w = v4.y + -0.5f;
    r4.x = stage12_x;
    r4.y = stage12_y;
    r4.z = stage12_z;
    r4.w = stage12_w;
    // dp4 r1.w, cb0[5].xxyy, r4.zzww
    r1.w = dot(cb0[5].xxyy, r4.zzww);
    // dp4 r2.w, cb0[8].xyxy, r4.xyzw
    r2.w = dot(cb0[8].xyxy, r4.xyzw);
    // add r1.w, |r1.w|, l(0.100000)
    r1.w = abs(r1.w) + 0.1f;
    // mad r3.yz, r3.xxyx, cb0[13].zzzz, r1.wwww
    float stage13_y = r3.x * cb0[13].z + r1.w;
    float stage13_z = r3.y * cb0[13].z + r1.w;
    r3.y = stage13_y;
    r3.z = stage13_z;
    // add r3.yz, -r0.xxxx, r3.yyzy
    float stage14_y = -r0.x + r3.y;
    float stage14_z = -r0.x + r3.z;
    r3.y = stage14_y;
    r3.z = stage14_z;
    // mul r0.x, cb0[4].z, cb0[14].y
    r0.x = cb0[4].z * cb0[14].y;
    // mul_sat r3.yz, r0.xxxx, r3.yyzy
    float stage15_y = saturate(r0.x * r3.y);
    float stage15_z = saturate(r0.x * r3.z);
    r3.y = stage15_y;
    r3.z = stage15_z;
    // log r4.xy, r3.yzyy
    float stage16_x = log2(r3.y);
    float stage16_y = log2(r3.z);
    r4.x = stage16_x;
    r4.y = stage16_y;
    // lt r3.yz, r3.yyzy, l(0.000000, 0.000001, 0.000001, 0.000000)
    float stage17_y = asfloat((r3.y < 1e-06f) ? 0xffffffffu : 0u);
    float stage17_z = asfloat((r3.z < 1e-06f) ? 0xffffffffu : 0u);
    r3.y = stage17_y;
    r3.z = stage17_z;
    // mul r4.xy, r4.xyxx, cb0[14].zzzz
    float stage18_x = r4.x * cb0[14].z;
    float stage18_y = r4.y * cb0[14].z;
    r4.x = stage18_x;
    r4.y = stage18_y;
    // exp r4.xy, r4.xyxx
    float stage19_x = exp2(r4.x);
    float stage19_y = exp2(r4.y);
    r4.x = stage19_x;
    r4.y = stage19_y;
    // movc r3.yz, r3.yyzy, l(0,0,0,0), r4.xxyx
    float stage20_y = asuint(r3.y) != 0u ? asfloat(0u) : r4.x;
    float stage20_z = asuint(r3.z) != 0u ? asfloat(0u) : r4.y;
    r3.y = stage20_y;
    r3.z = stage20_z;
    // add r0.x, -r3.z, l(1.000000)
    r0.x = -r3.z + 1.0f;
    // mad r2.xyz, r3.zzzz, r0.xxxx, r2.xyzx
    float stage21_x = r3.z * r0.x + r2.x;
    float stage21_y = r3.z * r0.x + r2.y;
    float stage21_z = r3.z * r0.x + r2.z;
    r2.x = stage21_x;
    r2.y = stage21_y;
    r2.z = stage21_z;
    // mul r0.x, r0.x, r3.z
    r0.x = r0.x * r3.z;
    // mul r2.xyz, r2.xyzx, r0.xxxx
    float stage22_x = r2.x * r0.x;
    float stage22_y = r2.y * r0.x;
    float stage22_z = r2.z * r0.x;
    r2.x = stage22_x;
    r2.y = stage22_y;
    r2.z = stage22_z;
    // mul r2.xyz, r2.xyzx, cb0[14].wwww
    float stage23_x = r2.x * cb0[14].w;
    float stage23_y = r2.y * cb0[14].w;
    float stage23_z = r2.z * cb0[14].w;
    r2.x = stage23_x;
    r2.y = stage23_y;
    r2.z = stage23_z;
    // mul_sat r2.xyz, r2.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)
    float stage24_x = saturate(r2.x * 4.0f);
    float stage24_y = saturate(r2.y * 4.0f);
    float stage24_z = saturate(r2.z * 4.0f);
    r2.x = stage24_x;
    r2.y = stage24_y;
    r2.z = stage24_z;
    // max r2.xyz, r2.xyzx, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage25_x = max(r2.x, 1e-06f);
    float stage25_y = max(r2.y, 1e-06f);
    float stage25_z = max(r2.z, 1e-06f);
    r2.x = stage25_x;
    r2.y = stage25_y;
    r2.z = stage25_z;
    // log r2.xyz, r2.xyzx
    float stage26_x = log2(r2.x);
    float stage26_y = log2(r2.y);
    float stage26_z = log2(r2.z);
    r2.x = stage26_x;
    r2.y = stage26_y;
    r2.z = stage26_z;
    // mul r2.xyz, r2.xyzx, cb0[15].xxxx
    float stage27_x = r2.x * cb0[15].x;
    float stage27_y = r2.y * cb0[15].x;
    float stage27_z = r2.z * cb0[15].x;
    r2.x = stage27_x;
    r2.y = stage27_y;
    r2.z = stage27_z;
    // exp r2.xyz, r2.xyzx
    float stage28_x = exp2(r2.x);
    float stage28_y = exp2(r2.y);
    float stage28_z = exp2(r2.z);
    r2.x = stage28_x;
    r2.y = stage28_y;
    r2.z = stage28_z;
    // mul r4.xyz, r1.xyzx, r0.yzwy
    float stage29_x = r1.x * r0.y;
    float stage29_y = r1.y * r0.z;
    float stage29_z = r1.z * r0.w;
    r4.x = stage29_x;
    r4.y = stage29_y;
    r4.z = stage29_z;
    // dp3 r0.x, r4.xyzx, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.x = dot(r4.xyz, float3(0.3f, 0.59f, 0.11f));
    // mad r0.xyz, -r0.yzwy, r1.xyzx, r0.xxxx
    float stage30_x = -r0.y * r1.x + r0.x;
    float stage30_y = -r0.z * r1.y + r0.x;
    float stage30_z = -r0.w * r1.z + r0.x;
    r0.x = stage30_x;
    r0.y = stage30_y;
    r0.z = stage30_z;
    // mad r0.xyz, cb0[15].yyyy, r0.xyzx, r4.xyzx
    float stage31_x = cb0[15].y * r0.x + r4.x;
    float stage31_y = cb0[15].y * r0.y + r4.y;
    float stage31_z = cb0[15].y * r0.z + r4.z;
    r0.x = stage31_x;
    r0.y = stage31_y;
    r0.z = stage31_z;
    // max r0.xyz, |r0.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage32_x = max(abs(r0.x), 1e-06f);
    float stage32_y = max(abs(r0.y), 1e-06f);
    float stage32_z = max(abs(r0.z), 1e-06f);
    r0.x = stage32_x;
    r0.y = stage32_y;
    r0.z = stage32_z;
    // log r0.xyz, r0.xyzx
    float stage33_x = log2(r0.x);
    float stage33_y = log2(r0.y);
    float stage33_z = log2(r0.z);
    r0.x = stage33_x;
    r0.y = stage33_y;
    r0.z = stage33_z;
    // mul r0.xyz, r0.xyzx, cb0[15].zzzz
    float stage34_x = r0.x * cb0[15].z;
    float stage34_y = r0.y * cb0[15].z;
    float stage34_z = r0.z * cb0[15].z;
    r0.x = stage34_x;
    r0.y = stage34_y;
    r0.z = stage34_z;
    // exp r0.xyz, r0.xyzx
    float stage35_x = exp2(r0.x);
    float stage35_y = exp2(r0.y);
    float stage35_z = exp2(r0.z);
    r0.x = stage35_x;
    r0.y = stage35_y;
    r0.z = stage35_z;
    // mul_sat r0.xyz, r0.xyzx, cb0[15].wwww
    float stage36_x = saturate(r0.x * cb0[15].w);
    float stage36_y = saturate(r0.y * cb0[15].w);
    float stage36_z = saturate(r0.z * cb0[15].w);
    r0.x = stage36_x;
    r0.y = stage36_y;
    r0.z = stage36_z;
    // mul r1.xyz, cb0[6].xyzx, cb0[6].wwww
    float stage37_x = cb0[6].x * cb0[6].w;
    float stage37_y = cb0[6].y * cb0[6].w;
    float stage37_z = cb0[6].z * cb0[6].w;
    r1.x = stage37_x;
    r1.y = stage37_y;
    r1.z = stage37_z;
    // mad r4.xyz, cb0[7].wwww, cb0[7].xyzx, -r1.xyzx
    float stage38_x = cb0[7].w * cb0[7].x + -r1.x;
    float stage38_y = cb0[7].w * cb0[7].y + -r1.y;
    float stage38_z = cb0[7].w * cb0[7].z + -r1.z;
    r4.x = stage38_x;
    r4.y = stage38_y;
    r4.z = stage38_z;
    // mad r0.xyz, r0.xyzx, r4.xyzx, r1.xyzx
    float stage39_x = r0.x * r4.x + r1.x;
    float stage39_y = r0.y * r4.y + r1.y;
    float stage39_z = r0.z * r4.z + r1.z;
    r0.x = stage39_x;
    r0.y = stage39_y;
    r0.z = stage39_z;
    // mul r1.xyz, cb0[3].xyzx, cb0[3].wwww
    float stage40_x = cb0[3].x * cb0[3].w;
    float stage40_y = cb0[3].y * cb0[3].w;
    float stage40_z = cb0[3].z * cb0[3].w;
    r1.x = stage40_x;
    r1.y = stage40_y;
    r1.z = stage40_z;
    // mul r1.xyz, r1.xyzx, cb0[4].yyyy
    float stage41_x = r1.x * cb0[4].y;
    float stage41_y = r1.y * cb0[4].y;
    float stage41_z = r1.z * cb0[4].y;
    r1.x = stage41_x;
    r1.y = stage41_y;
    r1.z = stage41_z;
    // mad r0.xyz, r1.xyzx, r2.xyzx, r0.xyzx
    float stage42_x = r1.x * r2.x + r0.x;
    float stage42_y = r1.y * r2.y + r0.y;
    float stage42_z = r1.z * r2.z + r0.z;
    r0.x = stage42_x;
    r0.y = stage42_y;
    r0.z = stage42_z;
    // mad r0.xyz, r0.xyzx, cb0[1].xyzx, cb0[2].xyzx
    float stage43_x = r0.x * cb0[1].x + cb0[2].x;
    float stage43_y = r0.y * cb0[1].y + cb0[2].y;
    float stage43_z = r0.z * cb0[1].z + cb0[2].z;
    r0.x = stage43_x;
    r0.y = stage43_y;
    r0.z = stage43_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage44_x = r0.x * v5.w + v5.x;
    float stage44_y = r0.y * v5.w + v5.y;
    float stage44_z = r0.z * v5.w + v5.z;
    o0.x = stage44_x;
    o0.y = stage44_y;
    o0.z = stage44_z;
    // mul r0.x, |r2.w|, |r2.w|
    r0.x = abs(r2.w) * abs(r2.w);
    // mad r0.x, -|r2.w|, r0.x, l(1.000000)
    r0.x = -(abs(r2.w)) * r0.x + 1.0f;
    // lt r0.y, |r2.w|, l(0.000001)
    r0.y = asfloat((abs(r2.w) < 1e-06f) ? 0xffffffffu : 0u);
    // movc r0.x, r0.y, l(1.000000), r0.x
    r0.x = asuint(r0.y) != 0u ? 1.0f : r0.x;
    // add r0.y, r0.x, r3.x
    r0.y = r0.x + r3.x;
    // mul_sat r0.x, r0.x, r0.y
    r0.x = saturate(r0.x * r0.y);
    // lt r0.y, r0.x, l(0.000001)
    r0.y = asfloat((r0.x < 1e-06f) ? 0xffffffffu : 0u);
    // log r0.x, r0.x
    r0.x = log2(r0.x);
    // mul r0.x, r0.x, cb0[16].z
    r0.x = r0.x * cb0[16].z;
    // exp r0.x, r0.x
    r0.x = exp2(r0.x);
    // mul_sat r0.x, r0.x, cb0[16].w
    r0.x = saturate(r0.x * cb0[16].w);
    // dp3 r0.z, v6.xyzx, v6.xyzx
    r0.z = dot(v6.xyz, v6.xyz);
    // rsq r0.z, r0.z
    r0.z = rsqrt(r0.z);
    // mul r0.z, r0.z, v6.z
    r0.z = r0.z * v6.z;
    // lt r0.w, |r0.z|, l(0.000001)
    r0.w = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // log r0.z, |r0.z|
    r0.z = log2(abs(r0.z));
    // mul r0.z, r0.z, cb0[17].x
    r0.z = r0.z * cb0[17].x;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // mul_sat r0.z, r0.z, cb0[17].y
    r0.z = saturate(r0.z * cb0[17].y);
    // mul r0.x, r0.z, r0.x
    r0.x = r0.z * r0.x;
    // or r0.y, r0.y, r0.w
    r0.y = asfloat(asuint(r0.y) | asuint(r0.w));
    // movc r0.x, r0.y, l(0), r0.x
    r0.x = asuint(r0.y) != 0u ? asfloat(0u) : r0.x;
    // mul r0.x, r0.x, r3.y
    r0.x = r0.x * r3.y;
    // min r0.x, r0.x, l(1.000000)
    r0.x = min(r0.x, 1.0f);
    // mul_sat r0.x, r0.x, cb0[1].w
    r0.x = saturate(r0.x * cb0[1].w);
    // mul o0.w, r0.x, cb0[0].x
    o0.w = r0.x * cb0[0].x;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage45_x = r0.x * v1.x;
    float stage45_y = r0.x * v1.y;
    float stage45_z = r0.x * v1.z;
    r0.x = stage45_x;
    r0.y = stage45_y;
    r0.z = stage45_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage46_x = r0.w * v0.z;
    float stage46_y = r0.w * v0.x;
    float stage46_z = r0.w * v0.y;
    r1.x = stage46_x;
    r1.y = stage46_y;
    r1.z = stage46_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage47_x = r0.x * r1.x;
    float stage47_y = r0.x * r1.y;
    float stage47_z = r0.x * r1.z;
    r0.x = stage47_x;
    r0.y = stage47_y;
    r0.z = stage47_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage48_x = r0.x / r0.w;
    float stage48_y = r0.y / r0.w;
    r0.x = stage48_x;
    r0.y = stage48_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage49_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage49_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage49_x;
    r1.y = stage49_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage50_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage50_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage50_x;
    r1.y = stage50_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage51_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage51_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage51_x;
    r1.y = stage51_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage52_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage52_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage52_x;
    r0.y = stage52_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage53_x = r0.x * 0.5f + 0.5f;
    float stage53_y = r0.y * 0.5f + 0.5f;
    o2.x = stage53_x;
    o2.y = stage53_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage54_z = 1.0f;
    float stage54_w = asfloat(0u);
    o2.z = stage54_z;
    o2.w = stage54_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage55_x = cb2[3].x;
    float stage55_y = cb2[3].y;
    float stage55_z = cb2[3].z;
    o3.x = stage55_x;
    o3.y = stage55_y;
    o3.z = stage55_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage56_x = asfloat(0u);
    float stage56_y = asfloat(0u);
    float stage56_z = asfloat(0u);
    float stage56_w = asfloat(0u);
    o4.x = stage56_x;
    o4.y = stage56_y;
    o4.z = stage56_z;
    o4.w = stage56_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage57_x = asfloat(0u);
    float stage57_y = asfloat(0u);
    float stage57_z = asfloat(0u);
    float stage57_w = asfloat(0u);
    o5.x = stage57_x;
    o5.y = stage57_y;
    o5.z = stage57_z;
    o5.w = stage57_w;

    Shade_Ue3_fx_d_pa_field_02_tr_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
