// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_fx_j_pa_linearwave_01_tr_c35c1cfe9f2f1aeae3ffc577e2586926aff612027a8d2680be4706fd5f7b4fd1_Constants0 : register(b0)
{
    float4 cb0[21];
};
cbuffer Shade_Ue3_fx_j_pa_linearwave_01_tr_c35c1cfe9f2f1aeae3ffc577e2586926aff612027a8d2680be4706fd5f7b4fd1_Constants2 : register(b2)
{
    float4 cb2[4];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
SamplerState s3 : register(s3);
SamplerState s4 : register(s4);
SamplerState s5 : register(s5);
SamplerState s6 : register(s6);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);
Texture2D t3 : register(t3);
Texture2D t4 : register(t4);
Texture2D t5 : register(t5);
Texture2D t6 : register(t6);

struct Shade_Ue3_fx_j_pa_linearwave_01_tr_c35c1cfe9f2f1aeae3ffc577e2586926aff612027a8d2680be4706fd5f7b4fd1_INPUT
{
    float4 v0;
    float4 v1;
    float4 v2;
    float4 v3;
    float4 v4;
    float4 v5;
};

struct Shade_Ue3_fx_j_pa_linearwave_01_tr_c35c1cfe9f2f1aeae3ffc577e2586926aff612027a8d2680be4706fd5f7b4fd1_OUTPUT
{
    float4 o0;
    float4 o2;
    float4 o3;
    float4 o4;
    float4 o5;
};

Shade_Ue3_fx_j_pa_linearwave_01_tr_c35c1cfe9f2f1aeae3ffc577e2586926aff612027a8d2680be4706fd5f7b4fd1_OUTPUT Shade_Ue3_fx_j_pa_linearwave_01_tr_c35c1cfe9f2f1aeae3ffc577e2586926aff612027a8d2680be4706fd5f7b4fd1(Shade_Ue3_fx_j_pa_linearwave_01_tr_c35c1cfe9f2f1aeae3ffc577e2586926aff612027a8d2680be4706fd5f7b4fd1_INPUT stage)
{
    float4 v0 = stage.v0;
    float4 v1 = stage.v1;
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v4 = stage.v4;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 o0 = (float4)0;
    float4 o2 = (float4)0;
    float4 o3 = (float4)0;
    float4 o4 = (float4)0;
    float4 o5 = (float4)0;

    // mad r0.xy, v2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
    float stage1_x = v2.x * 2.0f + -1.0f;
    float stage1_y = v2.y * 2.0f + -1.0f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // max r0.z, |r0.x|, |r0.y|
    r0.z = max(abs(r0.x), abs(r0.y));
    // div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
    r0.z = 1.0f / r0.z;
    // min r0.w, |r0.x|, |r0.y|
    r0.w = min(abs(r0.x), abs(r0.y));
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.w, r0.z, r0.z
    r0.w = r0.z * r0.z;
    // mad r1.x, r0.w, l(0.020835), l(-0.085133)
    r1.x = r0.w * 0.020835f + -0.085133f;
    // mad r1.x, r0.w, r1.x, l(0.180141)
    r1.x = r0.w * r1.x + 0.180141f;
    // mad r1.x, r0.w, r1.x, l(-0.330299)
    r1.x = r0.w * r1.x + -0.330299f;
    // mad r0.w, r0.w, r1.x, l(0.999866)
    r0.w = r0.w * r1.x + 0.999866f;
    // mul r1.x, r0.w, r0.z
    r1.x = r0.w * r0.z;
    // mad r1.x, r1.x, l(-2.000000), l(1.570796)
    r1.x = r1.x * -2.0f + 1.570796f;
    // lt r1.y, |r0.x|, |r0.y|
    r1.y = asfloat((abs(r0.x) < abs(r0.y)) ? 0xffffffffu : 0u);
    // and r1.x, r1.y, r1.x
    r1.x = asfloat(asuint(r1.y) & asuint(r1.x));
    // mad r0.z, r0.z, r0.w, r1.x
    r0.z = r0.z * r0.w + r1.x;
    // lt r0.w, r0.x, -r0.x
    r0.w = asfloat((r0.x < -r0.x) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, l(0xc0490fdb)
    r0.w = asfloat(asuint(r0.w) & asuint(-3.1415927410125732f));
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // min r0.w, r0.x, r0.y
    r0.w = min(r0.x, r0.y);
    // lt r0.w, r0.w, -r0.w
    r0.w = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // max r1.x, r0.x, r0.y
    r1.x = max(r0.x, r0.y);
    // mul r0.xy, r0.xyxx, r0.xyxx
    float stage2_x = r0.x * r0.x;
    float stage2_y = r0.y * r0.y;
    r0.x = stage2_x;
    r0.y = stage2_y;
    // add r0.x, r0.y, r0.x
    r0.x = r0.y + r0.x;
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // mov r0.y, -r0.x
    r0.y = -r0.x;
    // ge r1.x, r1.x, -r1.x
    r1.x = asfloat((r1.x >= -r1.x) ? 0xffffffffu : 0u);
    // and r0.w, r0.w, r1.x
    r0.w = asfloat(asuint(r0.w) & asuint(r1.x));
    // movc r0.z, r0.w, -r0.z, r0.z
    r0.z = asuint(r0.w) != 0u ? -r0.z : r0.z;
    // mul r0.z, r0.z, l(0.159155)
    r0.z = r0.z * 0.159155f;
    // frc r0.x, r0.z
    r0.x = frac(r0.z);
    // add r0.xy, r0.xyxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
    float stage3_x = r0.x + -0.5f;
    float stage3_y = r0.y + 0.5f;
    r0.x = stage3_x;
    r0.y = stage3_y;
    // mad r0.zw, cb0[9].wwww, r0.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
    float stage4_z = cb0[9].w * r0.x + 0.5f;
    float stage4_w = cb0[9].w * r0.y + 0.5f;
    r0.z = stage4_z;
    r0.w = stage4_w;
    // mad r0.xy, cb0[14].yyyy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage5_x = cb0[14].y * r0.x + 0.5f;
    float stage5_y = cb0[14].y * r0.y + 0.5f;
    r0.x = stage5_x;
    r0.y = stage5_y;
    // mad r0.xy, r0.xyxx, cb0[14].zwzz, cb0[15].xwxx
    float stage6_x = r0.x * cb0[14].z + cb0[15].x;
    float stage6_y = r0.y * cb0[14].w + cb0[15].w;
    r0.x = stage6_x;
    r0.y = stage6_y;
    // add r0.xy, r0.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage7_x = r0.x + -0.5f;
    float stage7_y = r0.y + -0.5f;
    r0.x = stage7_x;
    r0.y = stage7_y;
    // mul r0.w, r0.w, cb0[10].y
    r0.w = r0.w * cb0[10].y;
    // mad r1.x, r0.z, cb0[10].x, cb0[10].z
    r1.x = r0.z * cb0[10].x + cb0[10].z;
    // mad r1.y, cb0[10].w, v4.x, r0.w
    r1.y = cb0[10].w * v4.x + r0.w;
    // add r0.zw, r1.xxxy, l(0.000000, 0.000000, -0.500000, -0.500000)
    float stage8_z = r1.x + -0.5f;
    float stage8_w = r1.y + -0.5f;
    r0.z = stage8_z;
    r0.w = stage8_w;
    // dp2 r1.x, cb0[2].xyxx, r0.zwzz
    r1.x = dot(cb0[2].xy, r0.zw);
    // dp2 r1.y, cb0[3].xyxx, r0.zwzz
    r1.y = dot(cb0[3].xy, r0.zw);
    // add r0.zw, r1.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
    float stage9_z = r1.x + 0.5f;
    float stage9_w = r1.y + 0.5f;
    r0.z = stage9_z;
    r0.w = stage9_w;
    // mad r1.xy, v2.xyxx, cb0[11].xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
    float stage10_x = v2.x * cb0[11].x + 1.0f;
    float stage10_y = v2.y * cb0[11].y + 1.0f;
    r1.x = stage10_x;
    r1.y = stage10_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t0.xyzw, s2, l(0.000000)
    float4 fetch11 = t0.SampleBias(s2, r1.xy, 0.0f);
    r1.x = fetch11.x;
    r1.y = fetch11.y;
    // mul r1.z, v4.w, cb0[11].z
    r1.z = v4.w * cb0[11].z;
    // mad r0.zw, r1.zzzz, r1.xxxy, r0.zzzw
    float stage12_z = r1.z * r1.x + r0.z;
    float stage12_w = r1.z * r1.y + r0.w;
    r0.z = stage12_z;
    r0.w = stage12_w;
    // mul r1.z, v2.x, cb0[11].w
    r1.z = v2.x * cb0[11].w;
    // mul r1.w, v2.y, cb0[12].x
    r1.w = v2.y * cb0[12].x;
    // add r1.xy, r1.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
    float stage13_x = r1.z + 1.0f;
    float stage13_y = r1.w + 1.0f;
    r1.x = stage13_x;
    r1.y = stage13_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t1.xyzw, s3, l(0.000000)
    float4 fetch14 = t1.SampleBias(s3, r1.xy, 0.0f);
    r1.x = fetch14.x;
    r1.y = fetch14.y;
    // mad r0.zw, cb0[12].yyyy, r1.xxxy, r0.zzzw
    float stage15_z = cb0[12].y * r1.x + r0.z;
    float stage15_w = cb0[12].y * r1.y + r0.w;
    r0.z = stage15_z;
    r0.w = stage15_w;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t2.yzxw, s1, cb0[8].y
    float4 fetch16 = t2.SampleLevel(s1, r0.zw, cb0[8].y);
    r0.z = fetch16.x;
    // mad r0.z, cb0[12].w, -r0.z, r0.z
    r0.z = cb0[12].w * -r0.z + r0.z;
    // mul r0.z, r0.z, cb0[13].x
    r0.z = r0.z * cb0[13].x;
    // log r0.w, |r0.z|
    r0.w = log2(abs(r0.z));
    // lt r0.z, |r0.z|, l(0.000001)
    r0.z = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.w, r0.w, cb0[13].y
    r0.w = r0.w * cb0[13].y;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // movc r0.z, r0.z, l(0), r0.w
    r0.z = asuint(r0.z) != 0u ? asfloat(0u) : r0.w;
    // dp2 r1.x, cb0[4].xyxx, r0.xyxx
    r1.x = dot(cb0[4].xy, r0.xy);
    // dp2 r1.y, cb0[5].xyxx, r0.xyxx
    r1.y = dot(cb0[5].xy, r0.xy);
    // add r0.xy, r1.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage17_x = r1.x + 0.5f;
    float stage17_y = r1.y + 0.5f;
    r0.x = stage17_x;
    r0.y = stage17_y;
    // mad r1.xy, v2.xyxx, cb0[16].xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
    float stage18_x = v2.x * cb0[16].x + 1.0f;
    float stage18_y = v2.y * cb0[16].y + 1.0f;
    r1.x = stage18_x;
    r1.y = stage18_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t3.xyzw, s5, l(0.000000)
    float4 fetch19 = t3.SampleBias(s5, r1.xy, 0.0f);
    r1.x = fetch19.x;
    r1.y = fetch19.y;
    // mul r0.w, v4.w, cb0[16].z
    r0.w = v4.w * cb0[16].z;
    // mad r0.xy, r0.wwww, r1.xyxx, r0.xyxx
    float stage20_x = r0.w * r1.x + r0.x;
    float stage20_y = r0.w * r1.y + r0.y;
    r0.x = stage20_x;
    r0.y = stage20_y;
    // mul r1.z, v2.x, cb0[16].w
    r1.z = v2.x * cb0[16].w;
    // mul r1.w, v2.y, cb0[17].x
    r1.w = v2.y * cb0[17].x;
    // add r1.xy, r1.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
    float stage21_x = r1.z + 1.0f;
    float stage21_y = r1.w + 1.0f;
    r1.x = stage21_x;
    r1.y = stage21_y;
    // sample_b_indexable(texture2d)(float,float,float,float) r1.xy, r1.xyxx, t4.xyzw, s6, l(0.000000)
    float4 fetch22 = t4.SampleBias(s6, r1.xy, 0.0f);
    r1.x = fetch22.x;
    r1.y = fetch22.y;
    // mad r0.xy, cb0[17].yyyy, r1.xyxx, r0.xyxx
    float stage23_x = cb0[17].y * r1.x + r0.x;
    float stage23_y = cb0[17].y * r1.y + r0.y;
    r0.x = stage23_x;
    r0.y = stage23_y;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t5.xyzw, s4, cb0[13].w
    float4 fetch24 = t5.SampleLevel(s4, r0.xy, cb0[13].w);
    r0.x = fetch24.x;
    // mad r0.x, cb0[17].w, -r0.x, r0.x
    r0.x = cb0[17].w * -r0.x + r0.x;
    // mul r0.x, r0.x, cb0[18].x
    r0.x = r0.x * cb0[18].x;
    // lt r0.y, |r0.x|, l(0.000001)
    r0.y = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // log r0.x, |r0.x|
    r0.x = log2(abs(r0.x));
    // mul r0.x, r0.x, cb0[18].y
    r0.x = r0.x * cb0[18].y;
    // exp r0.x, r0.x
    r0.x = exp2(r0.x);
    // movc r0.x, r0.y, l(0), r0.x
    r0.x = asuint(r0.y) != 0u ? asfloat(0u) : r0.x;
    // mul r0.x, r0.x, r0.z
    r0.x = r0.x * r0.z;
    // mul r0.x, r0.x, cb0[18].z
    r0.x = r0.x * cb0[18].z;
    // log r0.y, |r0.x|
    r0.y = log2(abs(r0.x));
    // mul r0.y, r0.y, cb0[19].y
    r0.y = r0.y * cb0[19].y;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul r0.y, r0.y, cb0[19].z
    r0.y = r0.y * cb0[19].z;
    // lt r0.z, |r0.x|, l(0.000001)
    r0.z = asfloat((abs(r0.x) < 1e-06f) ? 0xffffffffu : 0u);
    // movc r0.y, r0.z, l(0), r0.y
    r0.y = asuint(r0.z) != 0u ? asfloat(0u) : r0.y;
    // add r0.zw, v2.xxxy, l(0.000000, 0.000000, -0.500000, -0.500000)
    float stage25_z = v2.x + -0.5f;
    float stage25_w = v2.y + -0.5f;
    r0.z = stage25_z;
    r0.w = stage25_w;
    // mul r0.zw, r0.zzzw, r0.zzzw
    float stage26_z = r0.z * r0.z;
    float stage26_w = r0.w * r0.w;
    r0.z = stage26_z;
    r0.w = stage26_w;
    // add r0.z, r0.w, r0.z
    r0.z = r0.w + r0.z;
    // add r0.z, -r0.z, l(1.000000)
    r0.z = -r0.z + 1.0f;
    // log r0.w, |r0.z|
    r0.w = log2(abs(r0.z));
    // lt r0.z, |r0.z|, l(0.000001)
    r0.z = asfloat((abs(r0.z) < 1e-06f) ? 0xffffffffu : 0u);
    // mad r1.x, cb0[19].w, l(10.000000), l(10.000000)
    r1.x = cb0[19].w * 10.0f + 10.0f;
    // mul r0.w, r0.w, r1.x
    r0.w = r0.w * r1.x;
    // exp r0.w, r0.w
    r0.w = exp2(r0.w);
    // movc r0.z, r0.z, l(0), r0.w
    r0.z = asuint(r0.z) != 0u ? asfloat(0u) : r0.w;
    // add r0.w, -r0.z, l(1.000000)
    r0.w = -r0.z + 1.0f;
    // mul r0.z, r0.z, cb0[20].x
    r0.z = r0.z * cb0[20].x;
    // mul r0.w, r0.w, r0.w
    r0.w = r0.w * r0.w;
    // mul r0.z, r0.z, r0.w
    r0.z = r0.z * r0.w;
    // mul r0.z, r0.z, cb0[20].y
    r0.z = r0.z * cb0[20].y;
    // mul r0.y, r0.y, r0.z
    r0.y = r0.y * r0.z;
    // mul_sat r0.y, r0.y, v3.w
    r0.y = saturate(r0.y * v3.w);
    // mul o0.w, r0.y, cb0[0].x
    o0.w = r0.y * cb0[0].x;
    // mad r0.yz, v2.xxyx, cb0[7].yyzy, l(0.000000, 1.000000, 1.000000, 0.000000)
    float stage27_y = v2.x * cb0[7].y + 1.0f;
    float stage27_z = v2.y * cb0[7].z + 1.0f;
    r0.y = stage27_y;
    r0.z = stage27_z;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.yzw, r0.yzyy, t6.wxyz, s0, cb0[7].x
    float4 fetch28 = t6.SampleLevel(s0, r0.yz, cb0[7].x);
    r0.y = fetch28.x;
    r0.z = fetch28.y;
    r0.w = fetch28.z;
    // dp3 r1.x, r0.yzwy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r1.x = dot(r0.yzw, float3(0.3f, 0.59f, 0.11f));
    // add r1.xyz, -r0.yzwy, r1.xxxx
    float stage29_x = -r0.y + r1.x;
    float stage29_y = -r0.z + r1.x;
    float stage29_z = -r0.w + r1.x;
    r1.x = stage29_x;
    r1.y = stage29_y;
    r1.z = stage29_z;
    // mad r0.yzw, cb0[7].wwww, r1.xxyz, r0.yyzw
    float stage30_y = cb0[7].w * r1.x + r0.y;
    float stage30_z = cb0[7].w * r1.y + r0.z;
    float stage30_w = cb0[7].w * r1.z + r0.w;
    r0.y = stage30_y;
    r0.z = stage30_z;
    r0.w = stage30_w;
    // mul r0.xyz, r0.yzwy, r0.xxxx
    float stage31_x = r0.y * r0.x;
    float stage31_y = r0.z * r0.x;
    float stage31_z = r0.w * r0.x;
    r0.x = stage31_x;
    r0.y = stage31_y;
    r0.z = stage31_z;
    // mul r0.xyz, r0.xyzx, cb0[18].wwww
    float stage32_x = r0.x * cb0[18].w;
    float stage32_y = r0.y * cb0[18].w;
    float stage32_z = r0.z * cb0[18].w;
    r0.x = stage32_x;
    r0.y = stage32_y;
    r0.z = stage32_z;
    // max r0.xyz, |r0.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage33_x = max(abs(r0.x), 1e-06f);
    float stage33_y = max(abs(r0.y), 1e-06f);
    float stage33_z = max(abs(r0.z), 1e-06f);
    r0.x = stage33_x;
    r0.y = stage33_y;
    r0.z = stage33_z;
    // log r0.xyz, r0.xyzx
    float stage34_x = log2(r0.x);
    float stage34_y = log2(r0.y);
    float stage34_z = log2(r0.z);
    r0.x = stage34_x;
    r0.y = stage34_y;
    r0.z = stage34_z;
    // mul r0.xyz, r0.xyzx, cb0[19].xxxx
    float stage35_x = r0.x * cb0[19].x;
    float stage35_y = r0.y * cb0[19].x;
    float stage35_z = r0.z * cb0[19].x;
    r0.x = stage35_x;
    r0.y = stage35_y;
    r0.z = stage35_z;
    // exp r0.xyz, r0.xyzx
    float stage36_x = exp2(r0.x);
    float stage36_y = exp2(r0.y);
    float stage36_z = exp2(r0.z);
    r0.x = stage36_x;
    r0.y = stage36_y;
    r0.z = stage36_z;
    // mul_sat r0.xyz, r0.xyzx, cb0[6].xyzx
    float stage37_x = saturate(r0.x * cb0[6].x);
    float stage37_y = saturate(r0.y * cb0[6].y);
    float stage37_z = saturate(r0.z * cb0[6].z);
    r0.x = stage37_x;
    r0.y = stage37_y;
    r0.z = stage37_z;
    // mad r0.xyz, r0.xyzx, v3.xyzx, cb0[1].xyzx
    float stage38_x = r0.x * v3.x + cb0[1].x;
    float stage38_y = r0.y * v3.y + cb0[1].y;
    float stage38_z = r0.z * v3.z + cb0[1].z;
    r0.x = stage38_x;
    r0.y = stage38_y;
    r0.z = stage38_z;
    // mad o0.xyz, r0.xyzx, v5.wwww, v5.xyzx
    float stage39_x = r0.x * v5.w + v5.x;
    float stage39_y = r0.y * v5.w + v5.y;
    float stage39_z = r0.z * v5.w + v5.z;
    o0.x = stage39_x;
    o0.y = stage39_y;
    o0.z = stage39_z;
    // dp3 r0.x, v1.xyzx, v1.xyzx
    r0.x = dot(v1.xyz, v1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, v1.xyzx
    float stage40_x = r0.x * v1.x;
    float stage40_y = r0.x * v1.y;
    float stage40_z = r0.x * v1.z;
    r0.x = stage40_x;
    r0.y = stage40_y;
    r0.z = stage40_z;
    // dp3 r0.w, v0.xyzx, v0.xyzx
    r0.w = dot(v0.xyz, v0.xyz);
    // rsq r0.w, r0.w
    r0.w = rsqrt(r0.w);
    // mul r1.xyz, r0.wwww, v0.zxyz
    float stage41_x = r0.w * v0.z;
    float stage41_y = r0.w * v0.x;
    float stage41_z = r0.w * v0.y;
    r1.x = stage41_x;
    r1.y = stage41_y;
    r1.z = stage41_z;
    // mul r0.y, r0.y, r1.y
    r0.y = r0.y * r1.y;
    // mad r0.x, r0.x, r1.z, -r0.y
    r0.x = r0.x * r1.z + -r0.y;
    // mov r1.z, r0.z
    r1.z = r0.z;
    // mul r1.y, r0.x, v1.w
    r1.y = r0.x * v1.w;
    // dp3 r0.x, r1.xyzx, r1.xyzx
    r0.x = dot(r1.xyz, r1.xyz);
    // rsq r0.x, r0.x
    r0.x = rsqrt(r0.x);
    // mul r0.xyz, r0.xxxx, r1.xyzx
    float stage42_x = r0.x * r1.x;
    float stage42_y = r0.x * r1.y;
    float stage42_z = r0.x * r1.z;
    r0.x = stage42_x;
    r0.y = stage42_y;
    r0.z = stage42_z;
    // dp3 r0.w, l(1.000000, 1.000000, 1.000000, 0.000000), |r0.xyzx|
    r0.w = dot(float3(1.0f, 1.0f, 1.0f), abs(r0.xyz));
    // div r0.xy, r0.xyxx, r0.wwww
    float stage43_x = r0.x / r0.w;
    float stage43_y = r0.y / r0.w;
    r0.x = stage43_x;
    r0.y = stage43_y;
    // ge r0.z, l(0.000000), r0.z
    r0.z = asfloat((0.0f >= r0.z) ? 0xffffffffu : 0u);
    // ge r1.xy, r0.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
    float stage44_x = asfloat((r0.x >= 0.0f) ? 0xffffffffu : 0u);
    float stage44_y = asfloat((r0.y >= 0.0f) ? 0xffffffffu : 0u);
    r1.x = stage44_x;
    r1.y = stage44_y;
    // movc r1.xy, r1.xyxx, l(1.000000,1.000000,0,0), l(-1.000000,-1.000000,0,0)
    float stage45_x = asuint(r1.x) != 0u ? 1.0f : -1.0f;
    float stage45_y = asuint(r1.y) != 0u ? 1.0f : -1.0f;
    r1.x = stage45_x;
    r1.y = stage45_y;
    // mad r1.xy, -|r0.yxyy|, r1.xyxx, r1.xyxx
    float stage46_x = -(abs(r0.y)) * r1.x + r1.x;
    float stage46_y = -(abs(r0.x)) * r1.y + r1.y;
    r1.x = stage46_x;
    r1.y = stage46_y;
    // movc r0.xy, r0.zzzz, r1.xyxx, r0.xyxx
    float stage47_x = asuint(r0.z) != 0u ? r1.x : r0.x;
    float stage47_y = asuint(r0.z) != 0u ? r1.y : r0.y;
    r0.x = stage47_x;
    r0.y = stage47_y;
    // mad o2.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    float stage48_x = r0.x * 0.5f + 0.5f;
    float stage48_y = r0.y * 0.5f + 0.5f;
    o2.x = stage48_x;
    o2.y = stage48_y;
    // mov o2.zw, l(0,0,1.000000,0)
    float stage49_z = 1.0f;
    float stage49_w = asfloat(0u);
    o2.z = stage49_z;
    o2.w = stage49_w;
    // mov o3.xyz, cb2[3].xyzx
    float stage50_x = cb2[3].x;
    float stage50_y = cb2[3].y;
    float stage50_z = cb2[3].z;
    o3.x = stage50_x;
    o3.y = stage50_y;
    o3.z = stage50_z;
    // mov o3.w, l(0)
    o3.w = asfloat(0u);
    // mov o4.xyzw, l(0,0,0,0)
    float stage51_x = asfloat(0u);
    float stage51_y = asfloat(0u);
    float stage51_z = asfloat(0u);
    float stage51_w = asfloat(0u);
    o4.x = stage51_x;
    o4.y = stage51_y;
    o4.z = stage51_z;
    o4.w = stage51_w;
    // mov o5.xyzw, l(0,0,0,0)
    float stage52_x = asfloat(0u);
    float stage52_y = asfloat(0u);
    float stage52_z = asfloat(0u);
    float stage52_w = asfloat(0u);
    o5.x = stage52_x;
    o5.y = stage52_y;
    o5.z = stage52_z;
    o5.w = stage52_w;

    Shade_Ue3_fx_j_pa_linearwave_01_tr_c35c1cfe9f2f1aeae3ffc577e2586926aff612027a8d2680be4706fd5f7b4fd1_OUTPUT result;
    result.o0 = o0;
    result.o2 = o2;
    result.o3 = o3;
    result.o4 = o4;
    result.o5 = o5;
    return result;
}
