// Generated by Tools/EffectPipeline/translate_ue3_dxbc_to_hlsl.py.
// One statement per cooked DXBC instruction.  Do not hand-edit: regenerate.

cbuffer Shade_Ue3_bfx_i_pa_wave_01_ad_Constants0 : register(b0)
{
    float4 cb0[9];
};
SamplerState s0 : register(s0);
SamplerState s1 : register(s1);
SamplerState s2 : register(s2);
Texture2D t0 : register(t0);
Texture2D t1 : register(t1);
Texture2D t2 : register(t2);

struct Shade_Ue3_bfx_i_pa_wave_01_ad_INPUT
{
    float4 v2;
    float4 v3;
    float4 v5;
};

struct Shade_Ue3_bfx_i_pa_wave_01_ad_OUTPUT
{
    float4 o0;
};

Shade_Ue3_bfx_i_pa_wave_01_ad_OUTPUT Shade_Ue3_bfx_i_pa_wave_01_ad(Shade_Ue3_bfx_i_pa_wave_01_ad_INPUT stage)
{
    float4 v2 = stage.v2;
    float4 v3 = stage.v3;
    float4 v5 = stage.v5;
    float4 r0 = (float4)0;
    float4 r1 = (float4)0;
    float4 r2 = (float4)0;
    float4 r3 = (float4)0;
    float4 o0 = (float4)0;

    // add r0.xy, v2.xyxx, l(-0.500000, -0.500000, 0.000000, 0.000000)
    float stage1_x = v2.x + -0.5f;
    float stage1_y = v2.y + -0.5f;
    r0.x = stage1_x;
    r0.y = stage1_y;
    // add r0.zw, r0.yyyx, r0.yyyx
    float stage2_z = r0.y + r0.y;
    float stage2_w = r0.x + r0.x;
    r0.z = stage2_z;
    r0.w = stage2_w;
    // dp2 r0.x, r0.xyxx, r0.xyxx
    r0.x = dot(r0.xy, r0.xy);
    // sqrt r0.x, r0.x
    r0.x = sqrt(r0.x);
    // max r0.y, |r0.w|, |r0.z|
    r0.y = max(abs(r0.w), abs(r0.z));
    // div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
    r0.y = 1.0f / r0.y;
    // min r1.x, |r0.w|, |r0.z|
    r1.x = min(abs(r0.w), abs(r0.z));
    // mul r0.y, r0.y, r1.x
    r0.y = r0.y * r1.x;
    // mul r1.x, r0.y, r0.y
    r1.x = r0.y * r0.y;
    // mad r1.y, r1.x, l(0.020835), l(-0.085133)
    r1.y = r1.x * 0.020835f + -0.085133f;
    // mad r1.y, r1.x, r1.y, l(0.180141)
    r1.y = r1.x * r1.y + 0.180141f;
    // mad r1.y, r1.x, r1.y, l(-0.330299)
    r1.y = r1.x * r1.y + -0.330299f;
    // mad r1.x, r1.x, r1.y, l(0.999866)
    r1.x = r1.x * r1.y + 0.999866f;
    // mul r1.y, r0.y, r1.x
    r1.y = r0.y * r1.x;
    // mad r1.y, r1.y, l(-2.000000), l(1.570796)
    r1.y = r1.y * -2.0f + 1.570796f;
    // lt r1.z, |r0.w|, |r0.z|
    r1.z = asfloat((abs(r0.w) < abs(r0.z)) ? 0xffffffffu : 0u);
    // and r1.y, r1.z, r1.y
    r1.y = asfloat(asuint(r1.z) & asuint(r1.y));
    // mad r0.y, r0.y, r1.x, r1.y
    r0.y = r0.y * r1.x + r1.y;
    // lt r1.x, r0.w, -r0.w
    r1.x = asfloat((r0.w < -r0.w) ? 0xffffffffu : 0u);
    // and r1.x, r1.x, l(0xc0490fdb)
    r1.x = asfloat(asuint(r1.x) & asuint(-3.1415927410125732f));
    // add r0.y, r0.y, r1.x
    r0.y = r0.y + r1.x;
    // min r1.x, r0.w, r0.z
    r1.x = min(r0.w, r0.z);
    // max r0.z, r0.w, r0.z
    r0.z = max(r0.w, r0.z);
    // ge r0.z, r0.z, -r0.z
    r0.z = asfloat((r0.z >= -r0.z) ? 0xffffffffu : 0u);
    // lt r0.w, r1.x, -r1.x
    r0.w = asfloat((r1.x < -r1.x) ? 0xffffffffu : 0u);
    // and r0.z, r0.z, r0.w
    r0.z = asfloat(asuint(r0.z) & asuint(r0.w));
    // movc r0.y, r0.z, -r0.y, r0.y
    r0.y = asuint(r0.z) != 0u ? -r0.y : r0.y;
    // mul r0.y, r0.y, cb0[3].x
    r0.y = r0.y * cb0[3].x;
    // add r0.z, -r0.x, l(0.500000)
    r0.z = -r0.x + 0.5f;
    // dp2 r0.z, r0.zzzz, cb0[3].yyyy
    r0.z = dot(r0.zz, cb0[3].yy);
    // mad r1.x, r0.y, l(0.318310), r0.z
    r1.x = r0.y * 0.31831f + r0.z;
    // mul r2.x, r1.x, cb0[4].w
    r2.x = r1.x * cb0[4].w;
    // mul r3.x, r2.x, cb0[5].w
    r3.x = r2.x * cb0[5].w;
    // add r0.y, r0.x, r0.x
    r0.y = r0.x + r0.x;
    // lt r0.x, r0.x, l(0.000000)
    r0.x = asfloat((r0.x < 0.0f) ? 0xffffffffu : 0u);
    // log r0.y, r0.y
    r0.y = log2(r0.y);
    // mul r0.y, r0.y, cb0[3].z
    r0.y = r0.y * cb0[3].z;
    // exp r0.y, r0.y
    r0.y = exp2(r0.y);
    // mul r0.y, r0.y, cb0[3].w
    r0.y = r0.y * cb0[3].w;
    // movc r0.x, r0.x, l(0), r0.y
    r0.x = asuint(r0.x) != 0u ? asfloat(0u) : r0.y;
    // add r1.y, r0.x, cb0[4].z
    r1.y = r0.x + cb0[4].z;
    // mad r2.y, r1.y, cb0[5].x, cb0[5].z
    r2.y = r1.y * cb0[5].x + cb0[5].z;
    // mad r3.y, r2.y, cb0[6].x, cb0[6].z
    r3.y = r2.y * cb0[6].x + cb0[6].z;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r3.xyxx, t0.xyzw, s1, l(0.000000)
    float4 fetch3 = t0.SampleLevel(s1, r3.xy, 0.0f);
    r0.x = fetch3.x;
    // mad r0.yz, cb0[6].wwww, r0.xxxx, r2.xxyx
    float stage4_y = cb0[6].w * r0.x + r2.x;
    float stage4_z = cb0[6].w * r0.x + r2.y;
    r0.y = stage4_y;
    r0.z = stage4_z;
    // mad r0.xw, cb0[6].wwww, r0.xxxx, r1.xxxy
    float stage5_x = cb0[6].w * r0.x + r1.x;
    float stage5_w = cb0[6].w * r0.x + r1.y;
    r0.x = stage5_x;
    r0.w = stage5_w;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.x, r0.xwxx, t1.xyzw, s0, l(0.000000)
    float4 fetch6 = t1.SampleLevel(s0, r0.xw, 0.0f);
    r0.x = fetch6.x;
    // sample_l_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t2.yxzw, s2, l(0.000000)
    float4 fetch7 = t2.SampleLevel(s2, r0.yz, 0.0f);
    r0.y = fetch7.x;
    // log r0.z, |r0.y|
    r0.z = log2(abs(r0.y));
    // lt r0.y, |r0.y|, l(0.000001)
    r0.y = asfloat((abs(r0.y) < 1e-06f) ? 0xffffffffu : 0u);
    // mul r0.z, r0.z, cb0[7].x
    r0.z = r0.z * cb0[7].x;
    // exp r0.z, r0.z
    r0.z = exp2(r0.z);
    // mul r0.z, r0.z, cb0[7].y
    r0.z = r0.z * cb0[7].y;
    // movc r0.y, r0.y, l(0), r0.z
    r0.y = asuint(r0.y) != 0u ? asfloat(0u) : r0.z;
    // dp3 r0.z, r0.yyyy, l(0.300000, 0.590000, 0.110000, 0.000000)
    r0.z = dot(r0.yyy, float3(0.3f, 0.59f, 0.11f));
    // add r0.z, -r0.y, r0.z
    r0.z = -r0.y + r0.z;
    // mad r0.y, cb0[7].z, r0.z, r0.y
    r0.y = cb0[7].z * r0.z + r0.y;
    // mul r0.yzw, r0.yyyy, cb0[2].xxyz
    float stage8_y = r0.y * cb0[2].x;
    float stage8_z = r0.y * cb0[2].y;
    float stage8_w = r0.y * cb0[2].z;
    r0.y = stage8_y;
    r0.z = stage8_z;
    r0.w = stage8_w;
    // mul r0.xyz, r0.yzwy, r0.xxxx
    float stage9_x = r0.y * r0.x;
    float stage9_y = r0.z * r0.x;
    float stage9_z = r0.w * r0.x;
    r0.x = stage9_x;
    r0.y = stage9_y;
    r0.z = stage9_z;
    // max r0.xyz, |r0.xyzx|, l(0.000001, 0.000001, 0.000001, 0.000000)
    float stage10_x = max(abs(r0.x), 1e-06f);
    float stage10_y = max(abs(r0.y), 1e-06f);
    float stage10_z = max(abs(r0.z), 1e-06f);
    r0.x = stage10_x;
    r0.y = stage10_y;
    r0.z = stage10_z;
    // log r0.xyz, r0.xyzx
    float stage11_x = log2(r0.x);
    float stage11_y = log2(r0.y);
    float stage11_z = log2(r0.z);
    r0.x = stage11_x;
    r0.y = stage11_y;
    r0.z = stage11_z;
    // mul r0.xyz, r0.xyzx, cb0[7].wwww
    float stage12_x = r0.x * cb0[7].w;
    float stage12_y = r0.y * cb0[7].w;
    float stage12_z = r0.z * cb0[7].w;
    r0.x = stage12_x;
    r0.y = stage12_y;
    r0.z = stage12_z;
    // exp r0.xyz, r0.xyzx
    float stage13_x = exp2(r0.x);
    float stage13_y = exp2(r0.y);
    float stage13_z = exp2(r0.z);
    r0.x = stage13_x;
    r0.y = stage13_y;
    r0.z = stage13_z;
    // mul r0.xyz, r0.xyzx, v3.xyzx
    float stage14_x = r0.x * v3.x;
    float stage14_y = r0.y * v3.y;
    float stage14_z = r0.z * v3.z;
    r0.x = stage14_x;
    r0.y = stage14_y;
    r0.z = stage14_z;
    // mad r0.xyz, r0.xyzx, l(1.500000, 1.500000, 1.500000, 0.000000), cb0[1].xyzx
    float stage15_x = r0.x * 1.5f + cb0[1].x;
    float stage15_y = r0.y * 1.5f + cb0[1].y;
    float stage15_z = r0.z * 1.5f + cb0[1].z;
    r0.x = stage15_x;
    r0.y = stage15_y;
    r0.z = stage15_z;
    // mul r0.xyz, r0.xyzx, v5.wwww
    float stage16_x = r0.x * v5.w;
    float stage16_y = r0.y * v5.w;
    float stage16_z = r0.z * v5.w;
    r0.x = stage16_x;
    r0.y = stage16_y;
    r0.z = stage16_z;
    // mad r1.xy, v2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
    float stage17_x = v2.x * 2.0f + -1.0f;
    float stage17_y = v2.y * 2.0f + -1.0f;
    r1.x = stage17_x;
    r1.y = stage17_y;
    // dp2 r0.w, r1.xyxx, r1.xyxx
    r0.w = dot(r1.xy, r1.xy);
    // min r0.w, r0.w, l(1.000000)
    r0.w = min(r0.w, 1.0f);
    // log r1.x, r0.w
    r1.x = log2(r0.w);
    // mul r1.x, r1.x, cb0[8].y
    r1.x = r1.x * cb0[8].y;
    // exp r1.x, r1.x
    r1.x = exp2(r1.x);
    // mul r1.x, r1.x, cb0[8].z
    r1.x = r1.x * cb0[8].z;
    // lt r1.y, r0.w, l(0.000001)
    r1.y = asfloat((r0.w < 1e-06f) ? 0xffffffffu : 0u);
    // add r0.w, -r0.w, l(1.000000)
    r0.w = -r0.w + 1.0f;
    // movc r1.x, r1.y, l(0), r1.x
    r1.x = asuint(r1.y) != 0u ? asfloat(0u) : r1.x;
    // log r1.y, r0.w
    r1.y = log2(r0.w);
    // lt r0.w, r0.w, l(0.000001)
    r0.w = asfloat((r0.w < 1e-06f) ? 0xffffffffu : 0u);
    // mul r1.y, r1.y, cb0[8].x
    r1.y = r1.y * cb0[8].x;
    // exp r1.y, r1.y
    r1.y = exp2(r1.y);
    // movc r0.w, r0.w, l(0), r1.y
    r0.w = asuint(r0.w) != 0u ? asfloat(0u) : r1.y;
    // mul r0.w, r1.x, r0.w
    r0.w = r1.x * r0.w;
    // mul r0.w, r0.w, cb0[8].w
    r0.w = r0.w * cb0[8].w;
    // mul r0.w, r0.w, v3.w
    r0.w = r0.w * v3.w;
    // mul r0.w, r0.w, cb0[0].x
    r0.w = r0.w * cb0[0].x;
    // mul o0.xyz, r0.wwww, r0.xyzx
    float stage18_x = r0.w * r0.x;
    float stage18_y = r0.w * r0.y;
    float stage18_z = r0.w * r0.z;
    o0.x = stage18_x;
    o0.y = stage18_y;
    o0.z = stage18_z;
    // mov o0.w, l(0)
    o0.w = asfloat(0u);

    Shade_Ue3_bfx_i_pa_wave_01_ad_OUTPUT result;
    result.o0 = o0;
    return result;
}
