#pragma once

#include <cstdint>
#include <string_view>

namespace LostArk::Shared
{
	/* Log-schema values, not wire values. Keep append-only so JSONL captures
	   from different builds remain comparable without changing the network
	   protocol. */
	enum class SESSION_DIAGNOSTIC_REASON : std::uint16_t
	{
		NONE = 0,

		CLIENT_CONNECT_FAILED,
		CLIENT_ENTER_SEND_FAILED,
		CLIENT_APPROVAL_TIMEOUT,
		CLIENT_CONNECTION_LOST,
		CLIENT_PEER_CLOSED,
		CLIENT_RECEIVE_ERROR,
		CLIENT_SEND_ERROR,
		CLIENT_PARSER_OVERFLOW,
		CLIENT_INVALID_FRAME,
		CLIENT_RAW_QUEUE_OVERFLOW,
		CLIENT_EVENT_QUEUE_OVERFLOW,
		CLIENT_MESSAGE_DECODE_FAILED,
		CLIENT_ENTRY_PRESENTATION_BASELINE_FAILED,
		CLIENT_ENTRY_PRESENTATION_REVISION_FAILED,
		CLIENT_INVALID_SERVER_RESPONSE,
		CLIENT_EXPECTED_ROOM_FULL,
		CLIENT_REPLICATION_FAILED,
		CLIENT_LOAD_FAILED,
		CLIENT_LOADING_START_FAILED,
		CLIENT_ACTIVATION_PROFILE_MISSING,
		CLIENT_ACTIVATION_LEVEL_CREATE_FAILED,
		CLIENT_ACTIVATION_PROFILE_FAILED,
		CLIENT_ACTIVATION_CHANGE_LEVEL_FAILED,
		CLIENT_IDENTITY_COMMIT_FAILED,
		CLIENT_WORLD_TRANSFER_FAILED,

		SERVER_PEER_CLOSED,
		SERVER_RECEIVE_ERROR,
		SERVER_INVALID_FRAME,
		SERVER_PARSER_OVERFLOW,
		SERVER_SEND_ERROR_OR_TIMEOUT,
		SERVER_RELIABLE_OUTBOUND_OVERFLOW,
		SERVER_CLIENT_MESSAGE_DECODE_FAILED,
		SERVER_UNKNOWN_PACKET,
		SERVER_SESSION_START_FAILED,
		SERVER_SESSION_BIND_FAILED,
		SERVER_ROOM_INGRESS_OVERFLOW,
		SERVER_CLIENT_COMMAND_VALIDATION_FAILED,
		SERVER_JOIN_VALIDATION_FAILED,
		SERVER_SPAWN_EXHAUSTED,
		SERVER_PROFILE_MISSING,
		SERVER_NAVIGATION_FAILED,
		SERVER_JOIN_PREFLIGHT_FAILED,
		SERVER_INITIAL_SYNC_ENQUEUE_FAILED,
		SERVER_EXPECTED_ROOM_FULL,
		SERVER_APPLICATION_CLOSE,
		SERVER_SHUTDOWN,
		SERVER_ROOM_RUNTIME_FAILED,

		END
	};

	[[nodiscard]]
	constexpr bool Is_Known_SessionDiagnosticReason(
		const SESSION_DIAGNOSTIC_REASON reason) noexcept
	{
		return SESSION_DIAGNOSTIC_REASON::NONE < reason &&
			reason < SESSION_DIAGNOSTIC_REASON::END;
	}

	[[nodiscard]]
	constexpr std::string_view To_SessionDiagnosticReasonName(
		const SESSION_DIAGNOSTIC_REASON reason) noexcept
	{
		switch (reason)
		{
		case SESSION_DIAGNOSTIC_REASON::NONE:
			return "NONE";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_CONNECT_FAILED:
			return "CLIENT_CONNECT_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_ENTER_SEND_FAILED:
			return "CLIENT_ENTER_SEND_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_APPROVAL_TIMEOUT:
			return "CLIENT_APPROVAL_TIMEOUT";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_CONNECTION_LOST:
			return "CLIENT_CONNECTION_LOST";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_PEER_CLOSED:
			return "CLIENT_PEER_CLOSED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_RECEIVE_ERROR:
			return "CLIENT_RECEIVE_ERROR";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_SEND_ERROR:
			return "CLIENT_SEND_ERROR";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_PARSER_OVERFLOW:
			return "CLIENT_PARSER_OVERFLOW";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_INVALID_FRAME:
			return "CLIENT_INVALID_FRAME";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_RAW_QUEUE_OVERFLOW:
			return "CLIENT_RAW_QUEUE_OVERFLOW";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_EVENT_QUEUE_OVERFLOW:
			return "CLIENT_EVENT_QUEUE_OVERFLOW";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_MESSAGE_DECODE_FAILED:
			return "CLIENT_MESSAGE_DECODE_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_ENTRY_PRESENTATION_BASELINE_FAILED:
			return "CLIENT_ENTRY_PRESENTATION_BASELINE_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_ENTRY_PRESENTATION_REVISION_FAILED:
			return "CLIENT_ENTRY_PRESENTATION_REVISION_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_INVALID_SERVER_RESPONSE:
			return "CLIENT_INVALID_SERVER_RESPONSE";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_EXPECTED_ROOM_FULL:
			return "CLIENT_EXPECTED_ROOM_FULL";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_REPLICATION_FAILED:
			return "CLIENT_REPLICATION_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_LOAD_FAILED:
			return "CLIENT_LOAD_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_LOADING_START_FAILED:
			return "CLIENT_LOADING_START_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_ACTIVATION_PROFILE_MISSING:
			return "CLIENT_ACTIVATION_PROFILE_MISSING";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_ACTIVATION_LEVEL_CREATE_FAILED:
			return "CLIENT_ACTIVATION_LEVEL_CREATE_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_ACTIVATION_PROFILE_FAILED:
			return "CLIENT_ACTIVATION_PROFILE_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_ACTIVATION_CHANGE_LEVEL_FAILED:
			return "CLIENT_ACTIVATION_CHANGE_LEVEL_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_IDENTITY_COMMIT_FAILED:
			return "CLIENT_IDENTITY_COMMIT_FAILED";
		case SESSION_DIAGNOSTIC_REASON::CLIENT_WORLD_TRANSFER_FAILED:
			return "CLIENT_WORLD_TRANSFER_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_PEER_CLOSED:
			return "SERVER_PEER_CLOSED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_RECEIVE_ERROR:
			return "SERVER_RECEIVE_ERROR";
		case SESSION_DIAGNOSTIC_REASON::SERVER_INVALID_FRAME:
			return "SERVER_INVALID_FRAME";
		case SESSION_DIAGNOSTIC_REASON::SERVER_PARSER_OVERFLOW:
			return "SERVER_PARSER_OVERFLOW";
		case SESSION_DIAGNOSTIC_REASON::SERVER_SEND_ERROR_OR_TIMEOUT:
			return "SERVER_SEND_ERROR_OR_TIMEOUT";
		case SESSION_DIAGNOSTIC_REASON::SERVER_RELIABLE_OUTBOUND_OVERFLOW:
			return "SERVER_RELIABLE_OUTBOUND_OVERFLOW";
		case SESSION_DIAGNOSTIC_REASON::SERVER_CLIENT_MESSAGE_DECODE_FAILED:
			return "SERVER_CLIENT_MESSAGE_DECODE_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_UNKNOWN_PACKET:
			return "SERVER_UNKNOWN_PACKET";
		case SESSION_DIAGNOSTIC_REASON::SERVER_SESSION_START_FAILED:
			return "SERVER_SESSION_START_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_SESSION_BIND_FAILED:
			return "SERVER_SESSION_BIND_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_ROOM_INGRESS_OVERFLOW:
			return "SERVER_ROOM_INGRESS_OVERFLOW";
		case SESSION_DIAGNOSTIC_REASON::SERVER_CLIENT_COMMAND_VALIDATION_FAILED:
			return "SERVER_CLIENT_COMMAND_VALIDATION_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_JOIN_VALIDATION_FAILED:
			return "SERVER_JOIN_VALIDATION_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_SPAWN_EXHAUSTED:
			return "SERVER_SPAWN_EXHAUSTED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_PROFILE_MISSING:
			return "SERVER_PROFILE_MISSING";
		case SESSION_DIAGNOSTIC_REASON::SERVER_NAVIGATION_FAILED:
			return "SERVER_NAVIGATION_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_JOIN_PREFLIGHT_FAILED:
			return "SERVER_JOIN_PREFLIGHT_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_INITIAL_SYNC_ENQUEUE_FAILED:
			return "SERVER_INITIAL_SYNC_ENQUEUE_FAILED";
		case SESSION_DIAGNOSTIC_REASON::SERVER_EXPECTED_ROOM_FULL:
			return "SERVER_EXPECTED_ROOM_FULL";
		case SESSION_DIAGNOSTIC_REASON::SERVER_APPLICATION_CLOSE:
			return "SERVER_APPLICATION_CLOSE";
		case SESSION_DIAGNOSTIC_REASON::SERVER_SHUTDOWN:
			return "SERVER_SHUTDOWN";
		case SESSION_DIAGNOSTIC_REASON::SERVER_ROOM_RUNTIME_FAILED:
			return "SERVER_ROOM_RUNTIME_FAILED";
		default:
			return "UNKNOWN_SESSION_DIAGNOSTIC_REASON";
		}
	}
}
