#pragma once

#include "Client_Defines.h"
#include "Engine_Defines.h"

#include <string>
#include <unordered_map>
#include <vector>

NS_BEGIN(Client)

/* Data/UI/Customizing/CustomizingIcons.json, generated by
Tools/LpkPipeline/build_customizing_icons.py from EFTable_CharacterCustomizing and
IconInfo.loa. It says which Resources-relative image each left-column cell and each
face preset cell shows, per class, in the order the retail table sorts them.

The document only names images; the screen still owns where they go. A class that
is missing, or a list that is empty, leaves those cells as bare frames rather than
failing the screen. */
class CCustomizingIconDocument final
{
public:
	struct CLASS_ICONS
	{
		/* Two different lists that happen to have the same row count per class, which is why
		they look interchangeable and are not. The base tab's 프리셋 is a curated set of whole
		appearances (table category 0, scattered icon indices); the face tab's 기본 얼굴 is the
		systematic face-shape set (category 1, a consecutive run). */
		std::vector<std::string> Presets;
		std::vector<std::string> FaceShapes;
		/* The left column's costume row: five per class, the same five the retail table
		carries with Object_Unit 0..4 as the costume each cell stands for. */
		std::vector<std::string> Costumes;
		std::vector<std::string> Actions;
		std::vector<std::string> Backgrounds;
		/* The secondary tabs' own lists, by the table category each comes from: hair shapes
		(4), eye irises (9), and the adorn pages the movie gives a list to -- eye make (10),
		cheek touch (11) and lip (12). The adorn eyebrow page carries only a slider and a
		colour chip, so it has no list here either. */
		std::vector<std::string> HairShapes;
		std::vector<std::string> EyeIrises;
		std::vector<std::string> AdornEyeLine;
		std::vector<std::string> AdornTouch;
		std::vector<std::string> AdornLip;
	};

public:
	/* Reads and validates the whole document. On failure the previous contents are
	kept and Get_Status explains why, the same parse -> validate -> stage -> commit
	the other runtime documents use. */
	bool_t Load();
	const CLASS_ICONS* Find(const std::string& strAssetId) const;
	const std::string& Get_Status() const { return m_strStatus; }

private:
	std::unordered_map<std::string, CLASS_ICONS> m_Classes;
	std::string m_strStatus = "Customizing icon document is not loaded";
};

NS_END
