#pragma once

#include "Client_Defines.h"
#include "Engine_Defines.h"

#include <array>
#include <string>
#include <vector>

NS_BEGIN(Client)

/* One additive pose key of a face slider: bone-local position delta in
centimetres and the rotation delta as the source quaternion. Key 1 is the
neutral pose (identity); keys 0 and 2 are the two slider extremes. */
struct FACE_SLIDER_KEY
{
	float3_t vPosition{ 0.f, 0.f, 0.f };
	float4_t vRotation{ 0.f, 0.f, 0.f, 1.f };
};

constexpr size_t FACE_SLIDER_KEY_COUNT = 3;
constexpr size_t FACE_SLIDER_NEUTRAL_KEY = 1;

struct FACE_SLIDER_BONE
{
	std::string strBoneName;
	std::array<FACE_SLIDER_KEY, FACE_SLIDER_KEY_COUNT> Keys{};
};

struct FACE_SLIDER
{
	/* Stable slider ID, e.g. "eye_scaleh". */
	std::string strId;
	/* Retail additive sequence the keys came from, e.g. "add_eye_scaleh_ui". */
	std::string strSequence;
	std::vector<FACE_SLIDER_BONE> Bones;
};

/* Data/Customizing/FaceSliders/<race>.facesliders.json, generated by
Tools/CharacterCustomizing/build_face_sliders.py from the retail face AnimSet.
Load is parse -> validate -> commit: a failure leaves the document untouched. */
struct FACE_SLIDER_DOCUMENT
{
	std::string strRace;
	std::vector<FACE_SLIDER> Sliders;

	bool_t Load(const char_t* pRace, std::string& outError);
};

NS_END
