#pragma once

#include "Client_Defines.h"
#include "Engine_Defines.h"
#include "MvpResultView.h"

#include <string>
#include <vector>

NS_BEGIN(Client)

/* How a contribution's title is decided. EFTable_MvpTitle carries three tiers
for every contribution but no cutoff, so the rule lives in the document. */
enum class MVP_TITLE_RULE
{
	/* Tier comes from the player's share of the party total. */
	SHARE,
	/* One title, awarded for being alive at the clear -- EFTable_MvpTitle's
	   three rows for this contribution are the same string. */
	SURVIVE,
	END
};

/* One contribution the raid tracks: EFTable_Mvp joined to its three
EFTable_MvpTitle rows, with the strings already resolved through
EFTable_GameMsg. */
struct MVP_AWARD_STAT final
{
	int32_t			iPrimaryKey = 0;
	int32_t			iStatType = 0;
	/* EFTable_Mvp.CalcType -- 0 draws the raw amount, 1 draws a percentage. */
	int32_t			iCalcType = 0;
	wstring_t		strName;
	/* Tier 1, 2, 3 in order. Tier 3 is the highest. */
	wstring_t		strTitles[3];
	MVP_TITLE_RULE	eTitleRule = MVP_TITLE_RULE::SHARE;
	/* How strongly the contribution moves the total that picks the MVP: 1 is the
	   strongest, 0 means it is not part of the total. The reference states an
	   ordering and not coefficients, so this is never multiplied by anything --
	   it only breaks a tie between two equal scores. */
	int32_t			iWeightTier = 0;
	/* "core" carries the total, "support" only nudges it, "none" is outside it. */
	string			strScoreRole;
	/* Lower bound of each tier, per party size. Absent for a contribution whose
	   cutoffs have not been supplied; that contribution resolves no title. */
	bool_t			bHasThresholds4 = false;
	bool_t			bHasThresholds8 = false;
	f32_t			fThresholds4[3] = {};
	f32_t			fThresholds8[3] = {};
};

/* One medal the raid can award. Unlike the titles, the condition really is in
the client data -- EFTable_MvpMedalGroup.Param1..3. The columns are named
Param1..3 and nothing states their unit, so they are carried through as-is. */
struct MVP_AWARD_MEDAL final
{
	int32_t		iMedalIndex = 0;
	int32_t		iIconIndex = 0;
	wstring_t	strName;
	int32_t		iParam1 = 0;
	int32_t		iParam2 = 0;
	int32_t		iParam3 = 0;
};

/* What one player did in one contribution category.

fScore is the server's own number for this contribution -- the catalogue never
computes it, because the coefficients behind it are not in the client data. The
page only needs it to rank rows against each other. */
struct MVP_AWARD_CONTRIBUTION final
{
	int32_t		iStatType = 0;
	f32_t		fScore = 0.f;
	f32_t		fSharePercent = 0.f;
	/* The amount as the page should print it. EFTable_Mvp.CalcType says whether
	   retail formats it as a raw amount or a percentage; the caller owns the
	   formatting because it owns the units. */
	wstring_t	strValue;
};

/* One raid member as the page's input. */
struct MVP_AWARD_PARTICIPANT final
{
	wstring_t						strCharacterName;
	wstring_t						strGuildName;
	/* Sum of the contribution scores, server-owned. Highest becomes the MVP. */
	f32_t							fTotalScore = 0.f;
	vector<MVP_AWARD_CONTRIBUTION>	Contributions;
	vector<int32_t>					Medals;
};

/* The award definitions for one raid's MVP group, read once from
Data/UI/MVP/MvpAwards.json (generated by Tools/LpkPipeline/build_mvp_awards.py
from EFTable_Mvp / MvpTitle / MvpMedalGroup / MvpMedalDescription).

This is a lookup, not a judge. It never decides who earned what: a caller hands
it a contribution share and it answers with the title retail would print. */
class CMvpAwardCatalog final
{
public:
	static CMvpAwardCatalog& Get();

	/* Parses on first use and keeps the result. A document that fails to parse
	   leaves the catalog empty rather than half-filled. */
	bool_t Is_Loaded() const { return m_bLoaded; }
	int32_t Get_MvpGroupId() const { return m_iMvpGroupId; }

	const MVP_AWARD_STAT* Find_Stat(int32_t iStatType) const;
	const vector<MVP_AWARD_STAT>& Get_Stats() const { return m_Stats; }

	/* The title for this share, or nullptr when the contribution earns none --
	   the share is under tier 1, the cutoffs are missing, or the contribution
	   is not decided by share at all. iPartySize is 4 or 8. */
	const wchar_t* Resolve_ShareTitle(
		int32_t iStatType, int32_t iPartySize, f32_t fSharePercent) const;

	/* The single title of a SURVIVE contribution, or nullptr. */
	const wchar_t* Resolve_SurvivalTitle(int32_t iStatType) const;

	const MVP_AWARD_MEDAL* Find_Medal(int32_t iMedalIndex) const;
	const vector<MVP_AWARD_MEDAL>& Get_Medals() const { return m_Medals; }

	/* A contribution at most one of the three party columns may show. The MVP
	   is exempt: it is a separate card, not one of the three. */
	bool_t Is_ColumnExclusive(int32_t iStatType) const;

	/* The headline above the MVP, as coloured runs.

	   iRaidGroupId is EFTable_ZoneEpicGate.GroupId -- 101 is Valtan, 103 is
	   KoukuSaydon -- so the raid name changes with the raid rather than being
	   fixed to one. iGate is 1-based. szDifficultyId is a sys.mvp.difficulty_*
	   suffix ("normal", "hard", "special_madness"...).

	   A piece that does not resolve is left out instead of guessed, so an
	   unknown gate or difficulty costs that piece and not the line. */
	vector<MVP_TEXT_RUN> Build_ContentName(
		int32_t iRaidGroupId, int32_t iGate, const char* szDifficultyId) const;

	/* Lays the whole page out from the raid's contributions.

	   Highest total score becomes the MVP and the rest fill the three columns in
	   descending score. Each card lists its own highest-scoring contributions
	   that earned a title, and a column-exclusive contribution is skipped on
	   every column after the first that used it, so a second dealer shows their
	   next contribution instead of a second damage title. Medals the raid's
	   group cannot award are dropped.

	   iPartySize picks the cutoff set (4 or 8). */
	MVP_RESULT_DATA Compose_Page(
		const vector<MVP_TEXT_RUN>& ContentName,
		const vector<MVP_AWARD_PARTICIPANT>& Participants,
		int32_t iPartySize) const;

private:
	/* One piece of the headline: its text and, when GameMsg gave the piece its
	   own <FONT COLOR>, that colour. Without one the piece takes the field's
	   white, which is what the raid name and the normal difficulty do. */
	struct CONTENT_NAME_PIECE
	{
		string		strId;
		int32_t		iKey = 0;
		wstring_t	strText;
		bool_t		bHasColor = false;
		float4_t	vColor = float4_t(1.f, 1.f, 1.f, 1.f);
	};

private:
	CMvpAwardCatalog();
	void Load_ContentNames();

	/* One card's rows, in the order the page prints them. Contributions already
	   used up by an earlier column are passed in and added to. */
	vector<MVP_RESULT_STAT> Select_Rows(
		const MVP_AWARD_PARTICIPANT& Participant,
		int32_t iPartySize,
		bool_t bIsMvpCard,
		vector<int32_t>& ExclusiveStatTypesTaken) const;

private:
	vector<MVP_AWARD_STAT>	m_Stats;
	vector<MVP_AWARD_MEDAL>	m_Medals;
	vector<int32_t>			m_ColumnExclusiveStatTypes;
	/* Headline lookups, from the separate MvpContentNames document. Keyed by
	   difficulty id, gate number and EFTable_ZoneEpicGate.GroupId. */
	vector<CONTENT_NAME_PIECE>	m_Difficulties;
	vector<CONTENT_NAME_PIECE>	m_Gates;
	vector<CONTENT_NAME_PIECE>	m_Raids;
	int32_t					m_iMvpGroupId = 0;
	bool_t					m_bLoaded = false;
};

NS_END
