#pragma once

#include "CameraShakeService.h"
#include "Client_Defines.h"
#include "Engine_Defines.h"

#include <cstdint>
#include <filesystem>
#include <string>
#include <string_view>
#include <vector>

NS_BEGIN(Client)

class CEncounterPatternReference;
struct BOSS_PATTERN_ANIMATION_BINDING_DOCUMENT;
struct VALTAN_STAGE_VIEW;

enum class VALTAN_PATTERN_SHAKE_REPEAT_POLICY : uint8_t
{
	ONCE,
	EACH_LOOP,
};

struct VALTAN_PATTERN_SHAKE_CUE final
{
	std::string strBindingId;
	std::string strOccurrenceId;
	std::string strPatternId;
	std::string strStageId;
	std::string strActionId;
	std::string strClipOccurrenceId;
	/* Source CEFCameraViewShake block, parsed once by CCameraShakeService. */
	CAMERA_SHAKE_SPEC Spec;
	std::string strPayload; // Original source payload is preserved during copy/save.
	VALTAN_PATTERN_SHAKE_REPEAT_POLICY eRepeatPolicy =
		VALTAN_PATTERN_SHAKE_REPEAT_POLICY::ONCE;
	/* Clip-local millisecond offset, same meaning as
	VALTAN_PATTERN_EFFECT_CUE::iStartMs -- validated against the clip's own
	iSourceStartMs/iPlayMs segment window and the encounter stage's duration. */
	uint32_t iStartMs = 0u;
	uint32_t iStageDurationMs = 0u;
	/* Resolved once at Parse_Text time (index of strStageId within the pattern's
	own stages array) so CValtan::Spawn_DuePatternShakeCues can match the live
	server stage by a cheap numeric compare against m_iServerPatternStageIndex,
	the same real invariant VALTAN_PATTERN_EFFECT_CUE::iStageIndex relies on. */
	uint32_t iStageIndex = 0u;
};

struct VALTAN_PATTERN_SHAKE_CUE_DOCUMENT final
{
	uint32_t iFormatVersion = 1u;
	std::string strOwnerArchetypeId;
	std::vector<VALTAN_PATTERN_SHAKE_CUE> Cues;
	// Runtime-filtered rows remain part of the source transaction, never lost on save.
	std::vector<VALTAN_PATTERN_SHAKE_CUE> PreservedCues;
	std::string strSourceBytes;
	uint64_t iDraftGeneration = 0u;
	bool_t bDraftDirty = false;
};

/* Action- and clip-occurrence-qualified boss camera-shake cues for Valtan,
generated by Tools/ValtanPipeline/build_valtan_pattern_shake_cues.py from the
raw extracted Valtan.animevents SHAKE rows (source CEFCameraViewShake specs)
joined against Valtan.patternbindings.json and ValtanEncounter.json. Same
load-time re-validation as the Sound cue document; the payload itself is
parsed by CCameraShakeService::Parse_PayloadSpec. Draft edits are staged in memory;
Prepare_Save joins the existing Composition Save transaction and never writes files. */
class CValtanPatternShakeCueDocument final
{
public:
	static std::filesystem::path Resolve_Path();
	static bool_t Parse_Text(
		std::string_view Text,
		const CEncounterPatternReference& Encounter,
		const BOSS_PATTERN_ANIMATION_BINDING_DOCUMENT& AnimationBindings,
		VALTAN_PATTERN_SHAKE_CUE_DOCUMENT& InOutDocument,
		std::string& strOutStatus);
	static bool_t Remove_StageDraft(VALTAN_PATTERN_SHAKE_CUE_DOCUMENT& Document,
		const std::string& patternId, const std::string& stageId, std::string& status);
	static bool_t Remove_ClipDraft(VALTAN_PATTERN_SHAKE_CUE_DOCUMENT& Document,
		const std::string& patternId, const std::string& stageId, const std::string& clipId, std::string& status);
	static bool_t Append_StageCopyDraft(VALTAN_PATTERN_SHAKE_CUE_DOCUMENT& Document,
		const std::vector<VALTAN_PATTERN_SHAKE_CUE>& copied, const VALTAN_STAGE_VIEW& source,
		const VALTAN_STAGE_VIEW& target, const std::string& patternId, uint32_t stageIndex, std::string& status);
	static bool_t Prepare_Save(const VALTAN_PATTERN_SHAKE_CUE_DOCUMENT& Document,
		std::string& baseline, std::string& candidate, uint64_t& generation, std::string& status);
	static bool_t Accept_Save(VALTAN_PATTERN_SHAKE_CUE_DOCUMENT& Document,
		uint64_t generation, const std::string& candidate, std::string& status);
	static bool_t Load_Source(
		VALTAN_PATTERN_SHAKE_CUE_DOCUMENT& InOutDocument,
		std::string& strOutStatus);
};

NS_END
