#pragma once

#include "Client_Defines.h"
#include "Engine_Defines.h"

#include <cstdint>
#include <filesystem>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

NS_BEGIN(Client)

class CEncounterPatternReference;
struct BOSS_PATTERN_ANIMATION_BINDING_DOCUMENT;

enum class VALTAN_PATTERN_SOUND_REPEAT_POLICY : uint8_t
{
	ONCE,
	EACH_LOOP,
};

struct VALTAN_PATTERN_SOUND_CUE final
{
	std::string strBindingId;
	std::string strOccurrenceId;
	std::string strPatternId;
	std::string strStageId;
	std::string strActionId;
	std::string strClipOccurrenceId;
	std::string strSoundBank;
	std::string strSoundEvent;
	VALTAN_PATTERN_SOUND_REPEAT_POLICY eRepeatPolicy =
		VALTAN_PATTERN_SOUND_REPEAT_POLICY::ONCE;
	/* Clip-local millisecond offset, same meaning as
	VALTAN_PATTERN_EFFECT_CUE::iStartMs -- validated against the clip's own
	iSourceStartMs/iPlayMs segment window and the encounter stage's duration. */
	uint32_t iStartMs = 0u;
	uint32_t iStageDurationMs = 0u;
	/* Resolved once at Parse_Text time (index of strStageId within the pattern's
	own stages array) so CValtan::Spawn_DuePatternSoundCues can match the live
	server stage by a cheap numeric compare against m_iServerPatternStageIndex,
	the same real invariant VALTAN_PATTERN_EFFECT_CUE::iStageIndex relies on. */
	uint32_t iStageIndex = 0u;

	bool operator==(const VALTAN_PATTERN_SOUND_CUE&) const = default;
};

struct VALTAN_PATTERN_SOUND_CUE_DOCUMENT final
{
	uint32_t iFormatVersion = 1u;
	std::string strOwnerArchetypeId;
	std::vector<VALTAN_PATTERN_SOUND_CUE> Cues;

	bool operator==(
		const VALTAN_PATTERN_SOUND_CUE_DOCUMENT&) const = default;
};

struct VALTAN_PATTERN_SOUND_CUE_ADD_ROW final
{
	std::string strPatternId;
	std::string strStageId;
	std::string strActionId;
	std::string strClipOccurrenceId;
	std::string strSoundBank;
	std::string strSoundEvent;
	VALTAN_PATTERN_SOUND_REPEAT_POLICY eRepeatPolicy =
		VALTAN_PATTERN_SOUND_REPEAT_POLICY::ONCE;
	uint32_t iStartMs = 0u;
};

struct VALTAN_PATTERN_SOUND_CUE_ROW_ID final
{
	std::string strBindingId;
	std::string strOccurrenceId;

	bool operator==(const VALTAN_PATTERN_SOUND_CUE_ROW_ID&) const = default;
};

/* Action- and clip-occurrence-qualified boss voice/impact sound cues for
Valtan, generated by Tools/ValtanPipeline/build_valtan_pattern_sound_cues.py
from the raw extracted Valtan.animevents SOUND rows joined against
Valtan.patternbindings.json and ValtanEncounter.json (see
.md/TJ/08-25/2026-08-25_VALTAN_PATTERN_SOUND_CUE_PLAN.md section 1 for the
measured join). This class only re-validates that join at load time (clip
occurrence still exists, start time still falls inside the clip segment and
the encounter stage's own duration) -- it deliberately does not carry
CValtanPatternEffectCueDocument's Product Effect-catalog admission, Material
V1 alias, anchor-bone, or transform validation, none of which apply to a
sound cue (no spatial attachment, no GPU-prepared asset to admit ahead of
spawn -- CSoundCueCatalog::Find_Variants is already a synchronous, always-
loaded lookup). Every public load stages into a temporary document and only
replaces the caller's output after the entire contract has validated. */
class CValtanPatternSoundCueDocument final
{
public:
	static std::filesystem::path Resolve_Path();
	static bool_t Parse_Text(
		std::string_view Text,
		const CEncounterPatternReference& Encounter,
		const BOSS_PATTERN_ANIMATION_BINDING_DOCUMENT& AnimationBindings,
		VALTAN_PATTERN_SOUND_CUE_DOCUMENT& InOutDocument,
		std::string& strOutStatus);
	static bool_t Load_Source(
		VALTAN_PATTERN_SOUND_CUE_DOCUMENT& InOutDocument,
		std::string& strOutStatus);
	/* Workbench owner load. Unlike the presentation-tolerant runtime Parse_Text
	   path, every source row must still join the current encounter, animation
	   occurrence, and Data/Sound Valtan event/asset catalog. */
	static bool_t Load_AuthoringSource(
		VALTAN_PATTERN_SOUND_CUE_DOCUMENT& InOutDocument,
		std::string& strOutStatus);
	/* Workbench CAS load. The document and exact source bytes are staged as one
	   snapshot; neither output changes when load/validation fails. */
	static bool_t Load_ForAuthoring(
		VALTAN_PATTERN_SOUND_CUE_DOCUMENT& InOutDocument,
		std::string& InOutBaselineSourceBytes,
		std::string& strOutStatus);
	/* Strong save admission. The caller must provide the current CModel source
	   duration in seconds for every clip used by the current pattern binding.
	   The complete ordered action chain is resolved through
	   CActionPresentationTimeline before any cue may reach disk. */
	static bool_t Validate_Joined(
		const VALTAN_PATTERN_SOUND_CUE_DOCUMENT& Document,
		const CEncounterPatternReference& Encounter,
		const BOSS_PATTERN_ANIMATION_BINDING_DOCUMENT& AnimationBindings,
		const std::unordered_map<std::string, f32_t>&
			ClipSourceDurationSecondsByName,
		std::string& strOutStatus);
	/* Adds one strongly joined row to a staged Workbench document. IDs are
	   generated from the action-qualified clip occurrence plus the lowest free
	   deterministic authoring ordinal; callers cannot supply vector indices,
	   pointers, or arbitrary persisted IDs. Both outputs are unchanged on
	   failure. */
	static bool_t Add_AuthoringRow(
		VALTAN_PATTERN_SOUND_CUE_DOCUMENT& InOutDocument,
		const VALTAN_PATTERN_SOUND_CUE_ADD_ROW& Row,
		const std::unordered_map<std::string, f32_t>&
			ClipSourceDurationSecondsByName,
		VALTAN_PATTERN_SOUND_CUE_ROW_ID& InOutCreatedRowId,
		std::string& strOutStatus);
	/* Removes exactly one selected stable row. A partial/mismatched
	   bindingId+occurrenceId pair never falls back to index or first match. */
	static bool_t Remove_AuthoringRow(
		VALTAN_PATTERN_SOUND_CUE_DOCUMENT& InOutDocument,
		const VALTAN_PATTERN_SOUND_CUE_ROW_ID& RowId,
		std::string& strOutStatus);
	/* Existing rows only expose soundBank, soundEvent, repeatPolicy, and startMs.
	   Inventory changes must come from Add_AuthoringRow/Remove_AuthoringRow;
	   common stable rows cannot change identity. The exact baseline returned by
	   Load_ForAuthoring must still match before staging and immediately before
	   atomic replacement; success advances it to the committed bytes and every
	   failure preserves it. There is deliberately no duration-free or CAS-free
	   save overload. An unchanged legacy row that runtime already isolates is
	   preserved field-for-field, but editing that row subjects it to the same
	   strong model timeline admission as every new edit. */
	static bool_t Save_Atomic(
		const VALTAN_PATTERN_SOUND_CUE_DOCUMENT& Document,
		const std::unordered_map<std::string, f32_t>&
			ClipSourceDurationSecondsByName,
		std::string& InOutBaselineSourceBytes,
		std::string& strOutStatus);
};

NS_END
