"""Generate the recovered stand leaf VS displacement, without guessing wind.

Only program 1531 consumes this helper. Existing scene wind uniform retains its
documented UE3 no-wind default; LostArk's live global wind value is not inferred.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT/'Tools/EffectPipeline'))
from translate_ue3_dxbc_to_hlsl import translate_body


def generate(evidence):
    document = json.loads((evidence/'stand-vertex-evidence.json').read_text())
    program = document['programs']['86a842b8c698dc4c911f97cc554ba7b8']['disassembly']
    instructions = program['instructions']
    if len(instructions) != 132 or instructions[111] != 'mad r3.xyz, v3.zzzz, r3.xyzx, r7.xyzx':
        raise ValueError('Source VS instruction slice changed')
    material = json.loads((evidence/'native-static/itr_02453.mat.itr_02453_04_mi.json').read_text())
    scalar = material['scalars']
    values = [scalar[n] for n in ('foliage_wind_speed', 'foliage_wind_frequency',
              'foliage_wind_intensity', 'wind_noise_intensity', 'wind_noise_speed', 'wind_noise_frequency')]
    s = [format(x, '.17g')+'f' if '.' in format(x, '.17g') else format(x, '.17g')+'.f' for x in values]
    start = '''// Generated by generate_maharaka_stand_vertex_shader.py from LocalVertexFactory VS.
// Shader 86a842b8c698dc4c911f97cc554ba7b8, instructions 28..111, original MIC scalars.
// Source bounds: ITR_02453 StaticMesh Bounds; CModel pretransform is baked into vertices.
// World wind is the existing explicit UE3 fallback, NOT a recovered live LostArk value.
#ifndef SOURCE_MAHARAKA_STAND_WIND_INCLUDED
#define SOURCE_MAHARAKA_STAND_WIND_INCLUDED
float3 SourceMaharakaStandWorldOffset(float3 worldPosition, float4 vertexColor,
    float4x4 world, float time, float4 windDirectionSpeed)
{
    float4 cb0[10]; float4 cb1[6];
    [unroll] for(uint i=0;i<10;++i) cb0[i]=0;
    [unroll] for(uint j=0;j<6;++j) cb1[j]=0;
    cb0[0]=float4(1,0,0,0); cb0[1]=float4(0,1,0,0);
    cb0[2]=float4(0,0,1,0); cb0[3]=float4(0,0,0,1);
    cb0[4]=float4(float3(world[3].x,-world[3].z,world[3].y)*100.f,1.f);
    float maxScale=max(length(world[0].xyz),max(length(world[1].xyz),length(world[2].xyz)));
    float3 extent=abs(world[0].xyz)*2.54331f+abs(world[1].xyz)*3.24602f+abs(world[2].xyz)*5.22249f;
    cb0[5].w=594.612f*maxScale;
    cb0[6].xyz=float3(extent.x,extent.z,extent.y)*100.f;
    cb0[7]=windDirectionSpeed;
'''
    start += f'    cb0[8]=float4({s[0]},time,{s[1]},{s[2]});\n'
    start += f'    cb0[9]=float4({s[3]},{s[4]},{s[5]},0.f);\n'
    start += '''    float4 v0=float4(float3(worldPosition.x,-worldPosition.z,worldPosition.y)*100.f,1.f);
    float4 v3=vertexColor.bgra;
    float4 r0=0,r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0,r11=0;
'''
    end = '''
    float3 delta=(r3.xyz-r7.xyz)*.01f;
    return float3(delta.x,delta.z,-delta.y);
}
#endif
'''
    return start+'\n'.join(translate_body(instructions[28:112], '    '))+end


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--evidence', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    after = generate(args.evidence).replace('\n', '\r\n').encode('utf-8')
    path = ROOT/'Client/Bin/ShaderFiles/Shader_SourceMaharakaStandWind.hlsli'
    if args.check:
        if path.read_bytes() != after:
            raise ValueError('Installed stand VS differs from recovered instructions')
    else:
        path.write_bytes(after)
    print('stand leaf VS literal translation:', hashlib.sha256(after).hexdigest())


if __name__ == '__main__':
    main()
